const e10iv_data = [
    { id: "5_iv_1", eng: "build, built, built", phon: "[bɪld], [bɪlt]", ger: "bauen", ctx: "-" },
    { id: "5_iv_2", eng: "win, won, won", phon: "[wɪn], [wʌn]", ger: "gewinnen", ctx: "-" },
    { id: "5_iv_3", eng: "stand, stood, stood", phon: "[stænd], [stʊd]", ger: "stehen; sich hinstellen", ctx: "-" },
    { id: "5_iv_4", eng: "get, got, got", phon: "[ɡet], [ɡɒt]", ger: "bekommen, holen, gelangen", ctx: "-" },
    { id: "5_iv_5", eng: "forget, forgot, forgotten", phon: "[fə'ɡet], [fə'ɡɒt], [fə'ɡɒtn]", ger: "vergessen", ctx: "-" },
    { id: "5_iv_6", eng: "feed, fed, fed", phon: "[fi:d], [fed]", ger: "füttern", ctx: "-" },
    { id: "5_iv_7", eng: "lend, lent, lent", phon: "[lend], [lent]", ger: "leihen, verleihen", ctx: "-" },
    { id: "5_iv_8", eng: "mean, meant, meant", phon: "[mi:n], [ment]", ger: "bedeuten, meinen", ctx: "-" },
    { id: "5_iv_9", eng: "cry, cried, cried", phon: "[kraɪ], [kraɪd]", ger: "weinen", ctx: "-" },
    { id: "5_iv_10", eng: "take off, took, taken", phon: "[teɪk ɒf], [tʊk], ['teɪkən]", ger: "ausziehen, ablegen", ctx: "-" },
    { id: "5_iv_11", eng: "burn, burnt, burnt", phon: "[bɜ:n], [bɜ:nt]", ger: "brennen, verbrennen", ctx: "-" },
    { id: "5_iv_12", eng: "hold out, held, held", phon: "[həʊld aʊt], [held]", ger: "hinhalten", ctx: "-" },
    { id: "5_iv_13", eng: "shake, shook, shaken", phon: "[ʃeɪk], [ʃʊk], ['ʃeɪkən]", ger: "schütteln", ctx: "-" },
    { id: "5_iv_14", eng: "be, was/were, been", phon: "[bi:], [wɒz]/[wɜ:], [bi:n]", ger: "sein", ctx: "-" },
    { id: "5_iv_15", eng: "come, came, come", phon: "[kʌm], [keɪm], [kʌm]", ger: "kommen", ctx: "-" },
    { id: "5_iv_16", eng: "do, did, done", phon: "[du:], [dɪd], [dʌn]", ger: "tun, machen", ctx: "-" },
    { id: "5_iv_17", eng: "drink, drank, drunk", phon: "[drɪŋk], [dræŋk], [drʌŋk]", ger: "trinken", ctx: "-" },
    { id: "5_iv_18", eng: "eat, ate, eaten", phon: "[i:t], [et], ['i:tn]", ger: "essen", ctx: "-" },
    { id: "5_iv_19", eng: "find, found, found", phon: "[faɪnd], [faʊnd]", ger: "finden", ctx: "-" },
    { id: "5_iv_20", eng: "give, gave, given", phon: "[ɡɪv], [ɡeɪv], ['ɡɪvn]", ger: "geben", ctx: "-" },
    { id: "5_iv_21", eng: "go, went, gone", phon: "[ɡəʊ], [went], [ɡɒn]", ger: "gehen", ctx: "-" },
    { id: "5_iv_22", eng: "have, had, had", phon: "[hæv], [hæd]", ger: "haben", ctx: "-" },
    { id: "5_iv_23", eng: "leave, left, left", phon: "[li:v], [left]", ger: "(ver)lassen", ctx: "-" },
    { id: "5_iv_24", eng: "make, made, made", phon: "[meɪk], [meɪd]", ger: "machen", ctx: "-" },
    { id: "5_iv_25", eng: "meet, met, met", phon: "[mi:t], [met]", ger: "treffen", ctx: "-" },
    { id: "5_iv_26", eng: "put, put, put", phon: "[pʊt]", ger: "setzen, stellen, legen", ctx: "-" },
    { id: "5_iv_27", eng: "ride, rode, ridden", phon: "[raɪd], [rəʊd], ['rɪdn]", ger: "reiten, fahren", ctx: "-" },
    { id: "5_iv_28", eng: "swim, swam, swum", phon: "[swɪm], [swæm], [swʌm]", ger: "schwimmen", ctx: "-" },
    { id: "5_iv_29", eng: "take, took, taken", phon: "[teɪk], [tʊk], ['teɪkən]", ger: "nehmen", ctx: "-" },
    { id: "5_iv_30", eng: "tell, told, told", phon: "[tel], [təʊld]", ger: "erzählen", ctx: "-" },
    { id: "5_iv_31", eng: "lose, lost, lost", phon: "[lu:z], [lɒst]", ger: "verlieren", ctx: "-" },
    { id: "5_iv_32", eng: "beat, beat, beaten", phon: "[bi:t], ['bi:tn]", ger: "schlagen, besiegen", ctx: "-" },
    { id: "5_iv_33", eng: "teach, taught, taught", phon: "[ti:tʃ], [tɔ:t]", ger: "lehren, unterrichten", ctx: "-" }
];