const e10u4_data = [
    { id: "10_4_1", eng: "(to) examine", phon: "[ɪɡ'zæmɪn]", ger: "untersuchen", ctx: "noun: examination = Prüfung, Untersuchung" },
    { id: "10_4_2", eng: "individual", phon: "[ˌɪndɪ'vɪdʒuəl]", ger: "Einzelne/r, Individuum; Person", ctx: "adjective: individual = individuell, Individual-" },
    { id: "10_4_3", eng: "(to) participate (in)", phon: "[pɑː'tɪsɪpeɪt]", ger: "teilnehmen (an), sich beteiligen (an)", ctx: "synonym: (to) take part (in); nouns: participant = Teilnehmer/in; participation (in) = Teilnahme" },
    { id: "10_4_4", eng: "donation", phon: "[dəʊ'neɪʃn]", ger: "Spende", ctx: "verb: (to) donate = spenden; phrase: make a donation (to sb.)" },
    { id: "10_4_5", eng: "(to) cycle", phon: "['saɪkl]", ger: "Rad fahren", ctx: "synonym: (to) ride a/your bike" },
    { id: "10_4_6", eng: "consumerism", phon: "[kən'sjuːmərɪzəm]", ger: "Konsumismus, konsumorientiertes Verhalten", ctx: "We buy many more goods than we need. This consumerism is bad." },
    { id: "10_4_7", eng: "extinction", phon: "[ɪk'stɪŋkʃn]", ger: "Ausrottung, Aussterben", ctx: "adjective: extinct = ausgestorben" },
    { id: "10_4_8", eng: "activism", phon: "['æktɪvɪzəm]", ger: "Aktivismus", ctx: "💡 Betonung auf der 1. Silbe! person: activist = Aktivist/in" },
    { id: "10_4_9", eng: "front line", phon: "[frʌnt 'laɪn]", ger: "Front (militärisch)", ctx: "phrase: in/on the front line = an vorderster Front" },
    { id: "10_4_10", eng: "elderly", phon: "['eldəli]", ger: "ältere(r, s)", ctx: "meaning: a more polite word for 'old'" },
    { id: "10_4_11", eng: "(to) marginalize", phon: "['mɑːdʒɪnəlaɪz]", ger: "ins Abseits drängen, an den Rand drängen", ctx: "noun: margin (Rand); adjective: marginal (geringfügig); adverb: marginally" },
    { id: "10_4_12", eng: "(to) witness sth.", phon: "['wɪtnəs]", ger: "etwas (mit)erleben, Zeuge/Zeugin werden von etwas", ctx: "Did you witness the accident? / noun: witness = Zeuge/Zeugin" },
    { id: "10_4_13", eng: "first-hand", phon: "[fɜːst 'hænd]", ger: "aus erster Hand", ctx: "first-hand experience = Erfahrung aus erster Hand" },
    { id: "10_4_14", eng: "damage (to)", phon: "['dæmɪdʒ]", ger: "Schaden, Schäden (an)", ctx: "💡 Im Englischen KEIN Plural (no pl.)! There was no damage to the house. / verb: (to) damage" },
    { id: "10_4_15", eng: "intense", phon: "[ɪn'tens]", ger: "intensiv, enorm", ctx: "noun: intensity [ɪn'tensəti] = Intensität" },
    { id: "10_4_16", eng: "landslide", phon: "['lændslaɪd]", ger: "Erdrutsch", ctx: "noun" },
    { id: "10_4_17", eng: "(to) end up", phon: "[end ʌp]", ger: "(schließlich) enden, landen, gelangen", ctx: "💡 Structure: end up + -ing / end up in prison / end up doing sth. (am Ende etwas tun)" },
    { id: "10_4_18", eng: "painful", phon: "['peɪnfl]", ger: "schmerzafter", ctx: "meaning: causing pain" },
    { id: "10_4_19", eng: "impact", phon: "['ɪmpækt]", ger: "Einfluss, Auswirkung", ctx: "What impact does behaviour have on the environment? (= What effect...)" },
    { id: "10_4_20", eng: "major", phon: "['meɪdʒə]", ger: "groß, bedeutend; Haupt-", ctx: "synonyms: very large, very important; major problems / major roads" },
    { id: "10_4_21", eng: "frequent", phon: "['friːkwənt]", ger: "häufig", ctx: "adverb: frequently = häufig/oft; noun: frequency ['friːkwənsi] = Häufigkeit" },
    { id: "10_4_22", eng: "no longer", phon: "[nəʊ 'lɒŋɡə]", ger: "nicht mehr", ctx: "synonym: not... any more (Jo is no longer my friend.)" },
    { id: "10_4_23", eng: "habitable", phon: "['hæbɪtəbl]", ger: "bewohnbar", ctx: "💡 opposite: uninhabitable = unbewohnbar; verb: (to) inhabit (a region)" },
    { id: "10_4_24", eng: "crisis (pl. crises)", phon: "['kraɪsɪs], ['kraɪsiːz]", ger: "Krise", ctx: "an economic / a financial / a political crisis" },
    { id: "10_4_25", eng: "(to) unite sb./sth. (with)", phon: "[ju'naɪt]", ger: "jn./etwas vereinigen, verbinden (mit)", ctx: "the United Nations (pl.) = die Vereinten Nationen (UN)" },
    { id: "10_4_26", eng: "harmony", phon: "['hɑːməni]", ger: "Harmonie, Einklang", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_4_27", eng: "toxic", phon: "['tɒksɪk]", ger: "toxisch, giftig", ctx: "toxic waste = Giftmüll, toxischer Müll" },
    { id: "10_4_28", eng: "dump", phon: "[dʌmp]", ger: "(Müll-)Abladeplatz, Deponie", ctx: "verb: (to) dump = (Müll, Schutt) abladen, zurücklassen" },
    { id: "10_4_29", eng: "inseparable", phon: "[ɪn'seprəbl]", ger: "untrennbar (miteinander verbunden); unzertrennlich", ctx: "They're inseparable." },
    { id: "10_4_30", eng: "counterpart", phon: "['kaʊntəpɑːt]", ger: "Pendant, Gegenstück; Gegenüber", ctx: "The US president met his French counterpart." },
    { id: "10_4_31", eng: "unjust", phon: "[ʌn'dʒʌst]", ger: "ungerecht", ctx: "opposite: just = gerecht; nouns: justice vs. injustice" },
    { id: "10_4_32", eng: "(to) target sb.", phon: "['tɑːɡɪt]", ger: "auf jn. zielen (jn. als Zielgruppe haben/wählen), jn. ins Visier nehmen", ctx: "noun: target" },
    { id: "10_4_33", eng: "risk", phon: "[rɪsk]", ger: "Risiko", ctx: "phrase: take that risk; adjective: risky; phrases: at risk = in Gefahr / at the risk of = auf die Gefahr hin" },
    { id: "10_4_34", eng: "solidarity", phon: "[ˌsɒlɪ'dærəti]", ger: "Solidarität", ctx: "phrase: express/show solidarity with sb. = sich mit jm. solidarisch erklären" },
    { id: "10_4_35", eng: "related (to)", phon: "[rɪ'leɪtɪd]", ger: "zugehörig, verbunden, verwandt (mit)", ctx: "💡 e.g., climate-related, job-related, weather-related; also: related to each other" },
    { id: "10_4_36", eng: "floodwater (or floodwaters pl.)", phon: "['flʌdwɔːtə]", ger: "Flutwasser, Hochwasser", ctx: "noun" },
    { id: "10_4_37", eng: "(to) tackle", phon: "['tækl]", ger: "(Problem) angehen, in Angriff nehmen; bewältigen", ctx: "💡 tackle = 1. Problem angehen/bewältigen; 2. fassen/angreifen (Sport)" },
    { id: "10_4_38", eng: "(to) exaggerate", phon: "[ɪɡ'zædʒəreɪt]", ger: "übertreiben", ctx: "I'm not exaggerating. / noun: exaggeration [ɪɡˌzædʒə'reɪʃn] = Übertreibung" },
    { id: "10_4_39", eng: "committee", phon: "[kə'mɪti]", ger: "Ausschuss, Kommission, Komitee", ctx: "We have a committee meeting this evening." },
    { id: "10_4_40", eng: "intercultural", phon: "[ˌɪntə'kʌltʃərəl]", ger: "interkulturell", ctx: "meaning: between different cultures" },
    { id: "10_4_41", eng: "cutlery", phon: "['kʌtləri]", ger: "Besteck", ctx: "e.g., wooden cutlery" },
    { id: "10_4_42", eng: "container", phon: "[kən'teɪnə]", ger: "Behälter; Container", ctx: "verb: (to) contain = beinhalten; noun: content = Inhalt" },
    { id: "10_4_43", eng: "capable (of)", phon: "['keɪpəbl]", ger: "fähig (zu), imstande (zu)", ctx: "She wanted to show what she was capable of." },
    { id: "10_4_44", eng: "(to) adapt", phon: "[ə'dæpt]", ger: "adaptieren, (sich) anpassen; (Text) bearbeiten", ctx: "noun: adaptation [ˌædæp'teɪʃn]; adjective: adaptable = anpassungsfähig" },
    { id: "10_4_45", eng: "innovation", phon: "[ˌɪnə'veɪʃn]", ger: "Innovation, Neuerung", ctx: "person: innovator; adjective: innovative ['ɪnəvətɪv]; verb: (to) innovate" },
    { id: "10_4_46", eng: "biodegradable", phon: "[ˌbaɪəʊdɪ'ɡreɪdəbl]", ger: "biologisch abbaubar", ctx: "Biodegradable forks will not harm the environment." },
    { id: "10_4_47", eng: "reusable", phon: "[ˌriː'juːzəbl]", ger: "wiederverwendbar", ctx: "verb: (to) reuse [ˌriː'juːz] (wiederverwenden) – noun: reuse [ˌriː'juːs]" },
    { id: "10_4_48", eng: "(to) bring sth. up", phon: "[brɪŋ]", ger: "etwas erwähnen, zur Sprache bringen", ctx: "I don't know why you keep bringing it up again." },
    { id: "10_4_49", eng: "commitment (to sb./sth.)", phon: "[kə'mɪtmənt]", ger: "Bekenntnis (zu jm./etwas); Engagement, Einsatz (für etwas)", ctx: "phrase: be committed to sth. = sich engagieren / engagiert sein für etwas" },
    { id: "10_4_50", eng: "average", phon: "['ævərɪdʒ]", ger: "durchschnittlich; Durchschnitt", ctx: "phrase: on average = im Durchschnitt, durchschnittlich" },
    { id: "10_4_51", eng: "(to) enable sb. to do sth.", phon: "[ɪ'neɪbl]", ger: "es jm. ermöglichen / jn. befähigen, etwas zu tun", ctx: "meaning: to make sth. possible for sb." },
    { id: "10_4_52", eng: "general assembly", phon: "[ˌdʒenrəl ə'sembli]", ger: "Vollversammlung, Generalversammlung", ctx: "All members of the UN are members of the General Assembly." },
    { id: "10_4_53", eng: "(to) approve", phon: "[ə'pruːv]", ger: "genehmigen, anerkennen; gutfinden, einverstanden sein", ctx: "💡 (to) approve sth. / (to) approve of sb./sth.; noun: approval [ə'pruːvl]" },
    { id: "10_4_54", eng: "till", phon: "[tɪl]", ger: "bis", ctx: "synonym: until" },
    { id: "10_4_55", eng: "intention", phon: "[ɪn'tenʃn]", ger: "Absicht, Vorsatz", ctx: "verb: (to) intend (to do sth.); adjective: intentional = absichtlich; adverb: intentionally" },
    { id: "10_4_56", eng: "measure", phon: "['meʒə]", ger: "Maß(nahme)", ctx: "💡 measure = 1. Maßnahme (take measures); 2. verb: (to) measure = messen" },
    { id: "10_4_57", eng: "(to) transform", phon: "[træns'fɔːm]", ger: "(sich) verwandeln; umwandeln", ctx: "meaning: to change sth. completely; noun: transformation [ˌtrænsfə'meɪʃn]" },
    { id: "10_4_58", eng: "planet", phon: "['plænɪt]", ger: "Planet", ctx: "💡 Betonung auf der 1. Silbe! our planet" },
    { id: "10_4_59", eng: "amount", phon: "[ə'maʊnt]", ger: "Menge; Betrag (Geld)", ctx: "💡 Für Nicht-Zählbares: a large amount of money/water. Für Zählbares: a large number of cars." },
    { id: "10_4_60", eng: "carbon dioxide (CO2)", phon: "[ˌkɑːbən daɪ'ɒksaɪd]", ger: "Kohlendioxid", ctx: "carbon = Kohlenstoff" },
    { id: "10_4_61", eng: "open-minded (about)", phon: "[ˌəʊpən 'maɪndɪd]", ger: "offen, aufgeschlossen (gegenüber)", ctx: "opposite: narrow-minded = engstirnig" },
    { id: "10_4_62", eng: "leadership", phon: "['liːdəʃɪp]", ger: "Führung", ctx: "leadership skills (pl.) = Führungsqualitäten; leader = Führer/in; verb: (to) lead, led, led" },
    { id: "10_4_63", eng: "comparison", phon: "[kəm'pærɪsn]", ger: "Vergleich; Steigerung (von Adjektiven)", ctx: "💡 comparison = 1. Vergleich; 2. Steigerung; verb: (to) compare; adj: comparable (to/with)" },
    { id: "10_4_64", eng: "eco-friendly", phon: "[ˌiːkəʊ 'frendli]", ger: "umweltfreundlich", ctx: "synonyms: environment-friendly / environmentally friendly" },
    { id: "10_4_65", eng: "presenter", phon: "[prɪ'zentə]", ger: "Moderator/in; Referent/in", ctx: "a radio presenter talking to a guest" },
    { id: "10_4_66", eng: "garment", phon: "['ɡɑːmənt]", ger: "Kleidungsstück", ctx: "synonym: a piece of clothing" },
    { id: "10_4_67", eng: "(to) uncover", phon: "[ʌn'kʌvə]", ger: "aufdecken; freilegen, öffnen (z. B. Topfdeckel)", ctx: "The journalists uncovered some highly interesting facts." },
    { id: "10_4_68", eng: "(to) manufacture", phon: "[ˌmænju'fæktʃə]", ger: "herstellen, produzieren, fertigen", ctx: "noun: manufacture; person: manufacturer = Hersteller/in, Produzent/in" },
    { id: "10_4_69", eng: "(to) investigate", phon: "[ɪn'vestɪɡeɪt]", ger: "untersuchen; ermitteln", ctx: "Police are investigating the murder. noun: investigation = Untersuchung, Ermittlung" },
    { id: "10_4_70", eng: "letter to the editor (pl. letters to the editor)", phon: "['edɪtə]", ger: "Leserbrief", ctx: "💡 editor = Herausgeber/in, Redakteur/in" },
    { id: "10_4_71", eng: "(to) praise", phon: "[preɪz]", ger: "loben, rühmen", ctx: "noun: praise (Lob); a hymn a song of praise" },
    { id: "10_4_72", eng: "(to) expose", phon: "[ɪk'spəʊz]", ger: "aufdecken, entlarven; freilegen", ctx: "noun: exposure [ɪk'spəʊʒə] = Aufdeckung, Entlarvung" },
    { id: "10_4_73", eng: "criminal", phon: "['krɪmɪnl]", ger: "kriminell", ctx: "noun: criminal = Verbrecher/in; bad thing that someone does = crime" },
    { id: "10_4_74", eng: "(to) balance", phon: "['bæləns]", ger: "ausgleichen, ins Gleichgewicht bringen", ctx: "💡 Betonung auf 1. Silbe! balanced = ausgewogen; opposite: one-sided = einseitig; noun: balance" },
    { id: "10_4_75", eng: "journalism", phon: "['dʒɜːnəlɪzəm]", ger: "Journalismus", ctx: "💡 Betonung auf der 1. Silbe! person: journalist ['dʒɜːnəlɪst] = Journalist/in" },
    { id: "10_4_76", eng: "evidence (no pl.)", phon: "['evɪdəns]", ger: "Nachweis(e), Beweis(e)", ctx: "💡 Im Englischen KEIN Plural! There was no evidence that he was the criminal." },
    { id: "10_4_77", eng: "What's more, ...", phon: "[wɒts mɔː]", ger: "Darüber hinaus ..., Außerdem ...", ctx: "There's too much sugar in this lemonade, and what's more, it's in a plastic bottle!" },
    { id: "10_4_78", eng: "representative", phon: "[ˌreprɪ'zentətɪv]", ger: "Repräsentant/in, Vertreter/in; Abgeordnete(r)", ctx: "verb: (to) represent = vertreten, repräsentieren" },
    { id: "10_4_79", eng: "rather", phon: "['rɑːðə]", ger: "ziemlich", ctx: "synonym: quite" },
    { id: "10_4_80", eng: "spot on", phon: "[spɒt ɒn]", ger: "haargenau richtig", ctx: "He's spot on. = Er liegt (haar)genau richtig." },
    { id: "10_4_81", eng: "(to) punish", phon: "['pʌnɪʃ]", ger: "bestrafen", ctx: "noun: punishment ['pʌnɪʃmənt] = Strafe, Bestrafung" },
    { id: "10_4_82", eng: "once more", phon: "[wʌns mɔː]", ger: "noch einmal, wieder einmal", ctx: "synonym: one more time" },
    { id: "10_4_83", eng: "colony", phon: "['kɒləni]", ger: "Kolonie", ctx: "💡 Betonung auf 1. Silbe! noun: colonization; person: colonizer; verb: (to) colonize; adj: colonial" },
    { id: "10_4_84", eng: "(to) preserve", phon: "[prɪ'zɜːv]", ger: "bewahren, erhalten", ctx: "preserve food (e.g. meat or fish); noun: preservation = Erhaltung, Bewahrung" },
    { id: "10_4_85", eng: "cryogenic", phon: "[ˌkraɪəʊ'dʒenɪk]", ger: "Tieftemperatur-", ctx: "noun: cryogenics = Tieftemperaturphysik" },
    { id: "10_4_86", eng: "cryonics", phon: "[kraɪ'ɒnɪks]", ger: "Kryotechnik (Kryokonservierung von Lebewesen)", ctx: "informal alternative: cryo; adjective: cryonic" },
    { id: "10_4_87", eng: "laboratory", phon: "[lə'bɒrətri]", ger: "Labor", ctx: "informal short form: lab / a lab(oratory); lab technician = Labortechniker/in" },
    { id: "10_4_88", eng: "technician", phon: "[tek'nɪʃn]", ger: "Techniker/in", ctx: "noun" },
    { id: "10_4_89", eng: "(to) type (in)", phon: "[taɪp]", ger: "(ein)tippen", ctx: "Please type in your name and password." },
    { id: "10_4_90", eng: "(to) approach", phon: "[ə'prəʊtʃ]", ger: "sich nähern, näher kommen", ctx: "As we approached our house... / noun: approach = Ansatz, Herangehensweise" },
    { id: "10_4_91", eng: "(to) seal sth. (up) with sth.", phon: "[siːl]", ger: "etwas mit etwas abdichten, versiegeln", ctx: "noun: seal = Siegel, (Ab-)Dichtung" },
    { id: "10_4_92", eng: "tube", phon: "[tjuːb]", ger: "Schlauch; Tube; Rohr, Röhre", ctx: "noun" },
    { id: "10_4_93", eng: "wire", phon: "['waɪə]", ger: "Draht", ctx: "noun" },
    { id: "10_4_94", eng: "(to) cram", phon: "[kræm]", ger: "(hinein)stopfen, (sich) hineindrängen, hineinzwängen", ctx: "crammed it full of presents / Don't cram so much in your mouth." },
    { id: "10_4_95", eng: "liquid", phon: "['lɪkwɪd]", ger: "Flüssigkeit", ctx: "Water is a clear liquid. / adjective: liquid = flüssig" },
    { id: "10_4_96", eng: "vein", phon: "[veɪn]", ger: "Vene", ctx: "Veins are tubes that carry blood towards your heart." },
    { id: "10_4_97", eng: "grunt", phon: "[ɡrʌnt]", ger: "Grunzen, Grunzlaut; Ächzen", ctx: "verb: (to) grunt = grunzen, ächzen" },
    { id: "10_4_98", eng: "(to) squeeze", phon: "[skwiːz]", ger: "(zusammen)drücken; (sich) zwängen, (sich) quetschen", ctx: "squeeze your eyes shut (Augen zukneifen); noun: squeeze = Drücken, Druck" },
    { id: "10_4_99", eng: "(to) stroke", phon: "[strəʊk]", ger: "streicheln", ctx: "stroking my cat" },
    { id: "10_4_100", eng: "anything but ...", phon: "['enɪθɪŋ bʌt]", ger: "alles andere als ...", ctx: "Houses in this area are anything but cheap (= they are expensive)." },
    { id: "10_4_101", eng: "(to) tug", phon: "[tʌɡ]", ger: "ziehen (z. B. am Ärmel)", ctx: "synonym: (to) pull (She tugged my hair.); noun: tug = das Ziehen" },
    { id: "10_4_102", eng: "tactic", phon: "['tæktɪk]", ger: "Taktik", ctx: "💡 oft im Plural: tactics; synonym: strategy; adj: tactical" },
    { id: "10_4_103", eng: "muscle", phon: "['mʌsl]", ger: "Muskel", ctx: "muscled = muskulös (a muscled chest)" },
    { id: "10_4_104", eng: "chest", phon: "[tʃest]", ger: "Brust, Brustkorb", ctx: "noun" },
    { id: "10_4_105", eng: "hose", phon: "[həʊz]", ger: "Schlauch", ctx: "e.g., a garden hose" },
    { id: "10_4_106", eng: "speckle", phon: "['spekl]", ger: "Tupfen, Sprenkel", ctx: "blue-speckled = blau getupft/gesprenkelt" },
    { id: "10_4_107", eng: "shoebox", phon: "['ʃuːbɒks]", ger: "Schuhkarton", ctx: "shoebox coffin = eine Kryo-Box in Form eines Schuhkartons" },
    { id: "10_4_108", eng: "(to) rush", phon: "[rʌʃ]", ger: "eilen; hetzen; (schnell) fließen", ctx: "noun: rush = Eile; Ansturm; Stoß" },
    { id: "10_4_109", eng: "bubble", phon: "['bʌbl]", ger: "Bläschen, Blase (Denkblase, Sprechblase)", ctx: "verb: (to) bubble = sprudeln, Blasen bilden; soap bubbles" },
    { id: "10_4_110", eng: "(to) lower", phon: "['ləʊə]", ger: "sinken (lassen), (sich) senken, herabsetzen", ctx: "meaning: to let/make sb./sth. go down, to reduce; adjective: low" },
    { id: "10_4_111", eng: "lid", phon: "[lɪd]", ger: "Deckel", ctx: "Put the lid on the pot, please." },
    { id: "10_4_112", eng: "mortuary", phon: "['mɔːtʃuəri]", ger: "Leichenhalle; Leichenschauhaus", ctx: "Dead bodies are kept in a mortuary before they are buried." },
    { id: "10_4_113", eng: "hiss", phon: "[hɪs]", ger: "(das/ein) Zischen, Fauchen", ctx: "verb: (to) hiss = zischen, fauchen" },
    { id: "10_4_114", eng: "steam", phon: "[stiːm]", ger: "Dampf", ctx: "verb: (to) steam = dämpfen/dünsten (lassen)" },
    { id: "10_4_115", eng: "(to) flash freeze", phon: "[flæʃ friːz]", ger: "schockgefrieren", ctx: "meaning: to freeze very quickly" },
    { id: "10_4_116", eng: "(to) back down (on/from sth.)", phon: "[bæk daʊn]", ger: "einen Rückzieher machen", ctx: "informal (meaning: to give in)" },
    { id: "10_4_117", eng: "(to) guilt sb. into sth. / into doing sth.", phon: "[ɡɪlt]", ger: "jn. moralisch zu etwas verpflichten/verpflichten, etwas zu tun", ctx: "noun: guilt (Schuldgefühl); adjective: guilty (of a crime) = schuldbewusst/schuldig" },
    { id: "10_4_118", eng: "trail", phon: "[treɪl]", ger: "Spur; Weg, Pfad; Route", ctx: "trails made by planes / trails for hiking in the hills" },
    { id: "10_4_119", eng: "mission", phon: "['mɪʃn]", ger: "Mission; Auftrag", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_4_120", eng: "the military", phon: "['mɪlətri]", ger: "das Militär", ctx: "adjective: military = militärisch" },
    { id: "10_4_121", eng: "For Pete's sake!", phon: "[seɪk]", ger: "Um Himmels Willen!", ctx: "idiom (Oh, for Pete's sake! We forgot the cake!)" },
    { id: "10_4_122", eng: "battlefield", phon: "['bætlfiːld]", ger: "Schlachtfeld", ctx: "noun" },
    { id: "10_4_123", eng: "analyst", phon: "['ænəlɪst]", ger: "Experte/Expertin; Analyst/in", ctx: "💡 Betonung auf 1. Silbe! noun: analysis; verb: (to) analyze" },
    { id: "10_4_124", eng: "command", phon: "[kə'mɑːnd]", ger: "Anordnung; Befehl", ctx: "commander-in-chief = Oberbefehlshaber; verb: (to) command = befehlen; in command = Befehlshaber sein" },
    { id: "10_4_125", eng: "genetic", phon: "[dʒə'netɪk]", ger: "genetisch", ctx: "adverb: genetically; noun: genetics = Genetik" },
    { id: "10_4_126", eng: "(to) splice", phon: "[splaɪs]", ger: "verkleben; verspleißen (durch Verflechten einzelner Stränge verbinden)", ctx: "genetic splicing = Genspleißen" },
    { id: "10_4_127", eng: "crop", phon: "[krɒp]", ger: "Feldfrucht, Anbaupflanze; Ernte", ctx: "What kinds of crops do you grow on your farm?" },
    { id: "10_4_128", eng: "(to) undress", phon: "[ˌʌn'dres]", ger: "sich ausziehen", ctx: "opposite: (to) dress / (to) get dressed" },
    { id: "10_4_129", eng: "chamber", phon: "['tʃeɪmbə]", ger: "Kammer", ctx: "Scientists found the underground chambers." },
    { id: "10_4_130", eng: "the inside", phon: "[ɪn'saɪd]", ger: "das Innere, die Innenseite", ctx: "💡 plural informal: the insides = die Eingeweide" },
    { id: "10_4_131", eng: "(to) stick, stuck, stuck", phon: "[stɪk], [stʌk]", ger: "kleben; stecken; (haften) bleiben", ctx: "stick in my mind = im Gedächtnis bleiben; stick out = herausstrecken" },
    { id: "10_4_132", eng: "intravenous (= IV)", phon: "[ˌɪntrə'viːnəs]", ger: "intravenös", ctx: "meaning: into a vein" },
    { id: "10_4_133", eng: "needle", phon: "['niːdl]", ger: "Nadel; Kanüle", ctx: "noun" },
    { id: "10_4_134", eng: "spine", phon: "[spaɪn]", ger: "Wirbelsäule, Rückgrat", ctx: "small bones connected together that go down the middle of the back" },
    { id: "10_4_135", eng: "pinky (finger) (AE)", phon: "['pɪŋki]", ger: "kleiner Finger", ctx: "pinky finger sticking out" },
    { id: "10_4_136", eng: "(to) wrap sth. in/with sth.", phon: "[ræp]", ger: "etwas in etwas (ein)wickeln / mit etwas umwickeln", ctx: "wrap sth. around sb. / wrap arms around sb. (umarmen); noun: wrap = Verpackung" },
    { id: "10_4_137", eng: "(to) slam", phon: "[slæm]", ger: "(hin)knallen, zuschlagen (Tür)", ctx: "slamming the door behind me; noun: slam = Knall" },
    { id: "10_4_138", eng: "puff", phon: "[pʌf]", ger: "Stoß, (Luft-)Zug, Wolke", ctx: "a puff of steam; verb: (to) puff = keuchen, schnaufen, entweichen lassen" },
    { id: "10_4_139", eng: "(to) jerk", phon: "[dʒɜːk]", ger: "rucken, mit einem Ruck ziehen/stoßen", ctx: "He jerked the door open. / noun: jerk = Ruck" },
    { id: "10_4_140", eng: "translucent", phon: "[trænz'luːsnt]", ger: "durchscheinend", ctx: "Light can get through it, but you can't look through clearly." },
    { id: "10_4_141", eng: "solid", phon: "['sɒlɪd]", ger: "fest, solide, stabil", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_4_142", eng: "(to) go under", phon: "[ɡəʊ 'ʌndə]", ger: "untergehen (unter Wasser); zu Grunde gehen", ctx: "The dog tried to swim, but he would go under." },
    { id: "10_4_143", eng: "watery", phon: "['wɔːtəri]", ger: "wässrig, Wasser-", ctx: "My eyes were watery (voll Tränen); noun: water" },
    { id: "10_4_144", eng: "(to) drift", phon: "[drɪft]", ger: "treiben, wehen; sich bewegen, driften, (Gedanken) wandern", ctx: "Clouds can drift across the sky. / My thoughts drifted to the beach." },
    { id: "10_4_145", eng: "(to) splutter", phon: "['splʌtə]", ger: "schnauben, prusten", ctx: "I drank too quickly and started coughing and spluttering." },
    { id: "10_4_146", eng: "(to) remove", phon: "[rɪ'muːv]", ger: "entfernen, beseitigen; ausziehen (Kleidung)", ctx: "remove this spot / remove your jacket; noun: removal [rɪ'muːvl]" },
    { id: "10_4_147", eng: "engineering", phon: "[ˌendʒɪ'nɪərɪŋ]", ger: "Ingenieurwesen, Maschinenbau", ctx: "She studied engineering and became an engineer." },
    { id: "10_4_148", eng: "ambitious", phon: "[æm'bɪʃəs]", ger: "ehrgeizig", ctx: "quite an ambitious plan; noun: ambition = Ehrgeiz, Bestreben" },
    { id: "10_4_149", eng: "(to) circulate", phon: "['sɜːkjuleɪt]", ger: "zirkulieren, sich (im Kreis) bewegen", ctx: "adjective: circular = rund; noun: circulation = Zirkulation, Kreislauf" },
    { id: "10_4_150", eng: "percentage", phon: "[pə'sentɪdʒ]", ger: "Anteil, Prozentsatz", ctx: "What percentage of your pocket money do you spend?" },
    { id: "10_4_151", eng: "patch", phon: "[pætʃ]", ger: "Flicken; Fleck, Stelle; Stück (z. B. Stoff)", ctx: "verb: (to) patch sth. (up) = etwas zusammenflicken" },
    { id: "10_4_152", eng: "garbage (AE)", phon: "['ɡɑːbɪdʒ]", ger: "Müll, Abfall", ctx: "British English equivalent: rubbish" },
    { id: "10_4_153", eng: "wave", phon: "[weɪv]", ger: "Welle", ctx: "wave power = Wellenkraft; verb: (to) wave (to sb.) = jm. zuwinken" },
    { id: "10_4_154", eng: "research", phon: "[rɪ'sɜːtʃ]", ger: "erforschen, untersuchen, recherchieren", ctx: "noun: research; person: researcher = Forscher/in" },
    { id: "10_4_155", eng: "(to) invest (in)", phon: "[ɪn'vest]", ger: "investieren (in)", ctx: "noun: investment = Anlage, Investition" },
    { id: "10_4_156", eng: "trial", phon: "['traɪəl]", ger: "Test, Studie; Probe; Gerichtsverfahren", ctx: "💡 trial = 1. Test, Studie, Probe; 2. (Gerichts-)Verfahren, Prozess" },
    { id: "10_4_157", eng: "(to) place", phon: "[pleɪs]", ger: "stellen, legen, setzen, platzieren", ctx: "synonym: (to) put (sth. somewhere); noun: place" },
    { id: "10_4_158", eng: "strategic", phon: "[strə'tiːdʒɪk]", ger: "strategisch", ctx: "adverb: strategically [strə'tiːdʒɪkli]; noun: strategy ['strætədʒi]" },
    { id: "10_4_159", eng: "solar power", phon: "[ˌsəʊlə 'paʊə]", ger: "Sonnenenergie", ctx: "solar = Sonnen-; solar-powered = solarbetrieben; power = Kraft/Energie" },
    { id: "10_4_160", eng: "conveyor (belt)", phon: "[kən'veɪə]", ger: "Transportband, Förderband; Fließband", ctx: "💡 belt = Riemen, Gürtel (seat belt = Sicherheitsgurt)" },
    { id: "10_4_161", eng: "technological", phon: "[ˌteknə'lɒdʒɪkl]", ger: "technologisch", ctx: "adjective; noun: technology" },
    { id: "10_4_162", eng: "order", phon: "['ɔːdə]", ger: "Reihenfolge", ctx: "in the wrong order; verb: (to) order = ordnen, anordnen; bestellen" },
    { id: "10_4_163", eng: "and so on", phon: "[ænd səʊ ɒn]", ger: "und so weiter", ctx: "synonym: etc." },
    { id: "10_4_164", eng: "(to) contribute (to/towards)", phon: "[kən'trɪbjuːt]", ger: "beitragen, beisteuern (zu); spenden (für)", ctx: "nouns: contribution = Beitrag; contributor = Mitwirkende/r; make a contribution" },
    { id: "10_4_165", eng: "systematic", phon: "[ˌsɪstə'mætɪk]", ger: "systematisch", ctx: "adverb: systematically; noun: system" },
    { id: "10_4_166", eng: "(to) expand on sth.", phon: "[ɪk'spænd]", ger: "etwas weiter ausführen; (sich) ausweiten, erweitern", ctx: "noun: expansion [ɪk'spænʃn] = Ausdehnung, Erweiterung" },
    { id: "10_4_167", eng: "so far", phon: "[ˌsəʊ 'fɑː]", ger: "bis jetzt, bis hierher", ctx: "synonym: up to now (So far my holiday has been great.)" },
    { id: "10_4_168", eng: "(to) group", phon: "[ɡruːp]", ger: "gruppieren", ctx: "noun: group" }
];