const e10u2_data = [
    { id: "10_2_1", eng: "insight (into)", phon: "['ɪnsaɪt]", ger: "Einblick (in), Verständnis (von)", ctx: "meaning: an understanding of what something is like" },
    { id: "10_2_2", eng: "format", phon: "['fɔːmæt]", ger: "Format", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_2_3", eng: "sheep (pl. sheep)", phon: "[ʃiːp]", ger: "Schaf; Schafe", ctx: "💡 Einzahl und Mehrzahl sind absolut identisch: one sheep – two sheep." },
    { id: "10_2_4", eng: "marine", phon: "[mə'riːn]", ger: "Meeres-", ctx: "e.g., marine life, marine animals, marine scientists" },
    { id: "10_2_5", eng: "kiwi", phon: "['kiːwi]", ger: "Kiwi", ctx: "💡 kiwi = 1. Kiwi (Vogel); 2. informal: Neuseeländer/in; kiwi fruit = Frucht" },
    { id: "10_2_6", eng: "flightless", phon: "['flaɪtləs]", ger: "flugunfähig", ctx: "A flightless bird is a bird that can't fly." },
    { id: "10_2_7", eng: "icon", phon: "['aɪkɒn]", ger: "Symbol; Ikone", ctx: "style icon (Mode-Ikone) / Wi-Fi icon (Wlan-Symbol)" },
    { id: "10_2_8", eng: "peninsula", phon: "[pə'nɪnsjələ]", ger: "Halbinsel", ctx: "noun" },
    { id: "10_2_9", eng: "cloud", phon: "[klaʊd]", ger: "Wolke", ctx: "adjective: cloudy = wolkig" },
    { id: "10_2_10", eng: "ethnic", phon: "['eθnɪk]", ger: "ethnisch, Volks-", ctx: "adverb: ethnically; noun: ethnicity [eθ'nɪsəti] = Ethnizität" },
    { id: "10_2_11", eng: "Pacific Islands (pl.)", phon: "[pə'sɪfɪk 'aɪləndz]", ger: "Inseln im Pazifischen Ozean", ctx: "person: Pacific Islander; (the) Pacific (Ocean) = der Pazifik" },
    { id: "10_2_12", eng: "census (pl. censuses)", phon: "['sensəs]", ger: "Volkszählung", ctx: "phrase: take/perform a census = eine Volkszählung durchführen" },
    { id: "10_2_13", eng: "Commonwealth", phon: "['kɒmənwelθ]", ger: "Gemeinschaft der Länder des ehemaligen Britischen Weltreichs", ctx: "organization of 54 countries" },
    { id: "10_2_14", eng: "doubtful", phon: "['daʊtfl]", ger: "zweifelhaft, ungewiss, fraglich", ctx: "be doubtful about sth. = Bedenken haben; noun: doubt; verb: (to) doubt" },
    { id: "10_2_15", eng: "(to) tackle", phon: "['tækl]", ger: "fassen (American Football, Rugby); angreifen (Fußball etc.)", ctx: "tackling a player in rugby" },
    { id: "10_2_16", eng: "(to) laugh your head off", phon: "[lɑːf]", ger: "lauthals lachen, sich kaputtlachen", ctx: "informal idiom" },
    { id: "10_2_17", eng: "(to) frame", phon: "[freɪm]", ger: "(ein-/um-)rahmen", ctx: "noun: frame = Rahmen; Gestell, Fahrgestell" },
    { id: "10_2_18", eng: "cup", phon: "[kʌp]", ger: "Pokal (z. B. Sport); Tasse", ctx: "💡 cup = 1. Pokal (World Cup = Weltmeisterschaft); 2. Tasse" },
    { id: "10_2_19", eng: "(to) run deep", phon: "[rʌn diːp]", ger: "tief verwurzelt sein, (Gefühle) tief empfunden werden", ctx: "to be felt in a strong way; to have a long tradition" },
    { id: "10_2_20", eng: "integral (to)", phon: "['ɪntɪɡrəl]", ger: "wesentlich (für)", ctx: "an integral part = ein fester/wesentlicher Bestandteil" },
    { id: "10_2_21", eng: "(a)round the world", phon: "[raʊnd]", ger: "rund um den Globus, überall auf der Welt", ctx: "meaning: all over the world" },
    { id: "10_2_22", eng: "(to) catch on, caught, caught", phon: "[kætʃ]", ger: "sich durchsetzen, populär werden", ctx: "meaning: to become very popular" },
    { id: "10_2_23", eng: "grassroots (pl.)", phon: "[ɡrɑːs'ruːts]", ger: "(gesellschaftliche) Basis", ctx: "at (the) grassroots level = an der gesellschaftlichen Basis" },
    { id: "10_2_24", eng: "opponent", phon: "[ə'pəʊnənt]", ger: "Gegner/in", ctx: "someone you fight or play against (e.g. in a match)" },
    { id: "10_2_25", eng: "nationwide", phon: "[ˌneɪʃn'waɪd]", ger: "landesweit, im ganzen Land", ctx: "meaning: all over the country" },
    { id: "10_2_26", eng: "gear", phon: "[ɡɪə]", ger: "Ausrüstung", ctx: "synonym: equipment (uncountable noun)" },
    { id: "10_2_27", eng: "hub", phon: "[hʌb]", ger: "Mittelpunkt, (Verkehrs-)Knotenpunkt", ctx: "the central point of a place or activity (e.g., airport hub)" },
    { id: "10_2_28", eng: "gathering", phon: "['ɡæðərɪŋ]", ger: "Treffen, Versammlung", ctx: "verb: (to) gather = sammeln; (sich) versammeln" },
    { id: "10_2_29", eng: "tie", phon: "[taɪ]", ger: "(Ver-)Bindung, Beziehung; Krawatte", ctx: "💡 tie = 1. Verbindung; 2. Krawatte; 3. verb: binden, schnüren" },
    { id: "10_2_30", eng: "historian", phon: "[hɪ'stɔːriən]", ger: "Historiker/in", ctx: "somebody who studies history and is an expert in it" },
    { id: "10_2_31", eng: "importance", phon: "[ɪm'pɔːtns]", ger: "Bedeutung, Wichtigkeit", ctx: "adjective: important" },
    { id: "10_2_32", eng: "psyche", phon: "['saɪki]", ger: "Psyche, Seele", ctx: "💡 Achte auf die korrekte englische Aussprache!" },
    { id: "10_2_33", eng: "tough", phon: "[tʌf]", ger: "(knall)hart; zäh, robust", ctx: "Rugby is a tough game, and rugby players are tough people." },
    { id: "10_2_34", eng: "mentality", phon: "[men'tæləti]", ger: "Mentalität", ctx: "💡 Betonung auf der 2. Silbe!" },
    { id: "10_2_35", eng: "ideal", phon: "[aɪ'dɪəl]", ger: "Ideal; ideal", ctx: "💡 Achte auf Betonung und Aussprache im Gegensatz zum Deutschen!" },
    { id: "10_2_36", eng: "original", phon: "[ə'rɪdʒənl]", ger: "original, ursprünglich", ctx: "💡 Betonung auf der 2. Silbe! noun: original" },
    { id: "10_2_37", eng: "isle", phon: "[aɪl]", ger: "Insel, Eiland (kurz für 'island')", ctx: "the British Isles (pl.) = die Britischen Inseln (the 's' is silent!)" },
    { id: "10_2_38", eng: "turning point", phon: "['tɜːnɪŋ pɔɪnt]", ger: "Wendepunkt", ctx: "noun phrase" },
    { id: "10_2_39", eng: "impressive", phon: "[ɪm'presɪv]", ger: "beeindruckend", ctx: "adjective: impressive – noun: impression – verb: (to) impress" },
    { id: "10_2_40", eng: "characteristic (of)", phon: "[ˌkærəktə'rɪstɪk]", ger: "typisch (für), charakteristisch (für)", ctx: "adverb: characteristically; noun: characteristic (Merkmal)" },
    { id: "10_2_41", eng: "(to) shape (sth. into sth.)", phon: "[ʃeɪp]", ger: "(etwas zu etwas) formen", ctx: "noun: shape = Form, Gestalt" },
    { id: "10_2_42", eng: "ritual", phon: "['rɪtʃuəl]", ger: "Ritual", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_2_43", eng: "sidelines (pl.)", phon: "['saɪdlaɪnz]", ger: "Seitenlinie, Spielfeldrand", ctx: "phrase: sitting on the sidelines" },
    { id: "10_2_44", eng: "rival", phon: "['raɪvl]", ger: "Rivale, Rivalin", ctx: "synonym: opponent" },
    { id: "10_2_45", eng: "teammate", phon: "['tiːmmeɪt]", ger: "Mannschaftskamerad/in", ctx: "someone who is in the same team as you" },
    { id: "10_2_46", eng: "union", phon: "['juːniən]", ger: "Union; Vereinigung, Verband", ctx: "teachers' union (Gewerkschaft); Rugby Union = 'Fünfzehner-Rugby'" },
    { id: "10_2_47", eng: "powerful", phon: "['paʊəfl]", ger: "kräftig, stark, mächtig", ctx: "a powerful voice / a powerful storm; noun: power" },
    { id: "10_2_48", eng: "highly", phon: "['haɪli]", ger: "sehr, höchst, äußerst", ctx: "💡 Adverb-Bedeutung unterscheidet sich vom Adjektiv! This is highly dangerous." },
    { id: "10_2_49", eng: "function", phon: "['fʌŋkʃn]", ger: "Funktion", ctx: "verb: (to) function (funktionieren); adjective: functional" },
    { id: "10_2_50", eng: "breath", phon: "[breθ]", ger: "Atem", ctx: "💡 breathtaking = atemberaubend; verb: (to) breathe [briːð] = atmen" },
    { id: "10_2_51", eng: "epic", phon: "['epɪk]", ger: "gewaltig; (Reise) lang und abenteuerlich; monumental; episch", ctx: "adjective or noun" },
    { id: "10_2_52", eng: "(to) camp", phon: "[kæmp]", ger: "campen, zelten", ctx: "noun: camp; camping near a river" },
    { id: "10_2_53", eng: "a bunch of ...", phon: "[bʌntʃ]", ger: "eine Menge ...; eine Gruppe ... (von Menschen)", ctx: "informal (e.g., a bunch of interesting new things / a bunch of losers)" },
    { id: "10_2_54", eng: "incredible", phon: "[ɪn'kredəbl]", ger: "unglaublich", ctx: "adverb: incredibly (incredibly fast/beautiful)" },
    { id: "10_2_55", eng: "Mount (= Mt.)", phon: "[maʊnt]", ger: "Berg (nur in Namen von Bergen)", ctx: "e.g., Mount Everest" },
    { id: "10_2_56", eng: "kea", phon: "['kiːə]", ger: "Kea (Bergpapagei in Neuseeland)", ctx: "noun" },
    { id: "10_2_57", eng: "cheeky", phon: "['tʃiːki]", ger: "frech, dreist", ctx: "meaning: rude, but in a funny or annoying way" },
    { id: "10_2_58", eng: "hilarious", phon: "[hɪ'leəriəs]", ger: "urkomisch, unheimlich witzig", ctx: "meaning: very funny (We all laughed our heads off!)" },
    { id: "10_2_59", eng: "certainty", phon: "['sɜːtnti]", ger: "Gewissheit, Sicherheit (Überzeugung)", ctx: "adjective/adverb: certain(ly)" },
    { id: "10_2_60", eng: "somehow", phon: "['sʌmhaʊ]", ger: "irgendwie", ctx: "Somehow I'll earn enough money." },
    { id: "10_2_61", eng: "(to) head (with prep / with adv)", phon: "[hed]", ger: "Richtung ... gehen, fahren; sich nach ... aufmachen; zusteuern auf ...", ctx: "headed for the door / heading home / a storm was heading for the island" },
    { id: "10_2_62", eng: "straight", phon: "[streɪt]", ger: "direkt, gleich; gerade; glatt (Haare)", ctx: "headed straight home; adverb or adjective" },
    { id: "10_2_63", eng: "universe", phon: "['juːnɪvɜːs]", ger: "Universum", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_2_64", eng: "(to) do turns", phon: "[tɜːnz]", ger: "sich drehen", ctx: "noun: turn = Drehung" },
    { id: "10_2_65", eng: "(to) do spins", phon: "[spɪnz]", ger: "sich drehen, rotieren, trudeln", ctx: "noun: spin = Drehung, Rotation; (das) Trudeln" },
    { id: "10_2_66", eng: "location", phon: "[ləʊ'keɪʃn]", ger: "Ort (Standort; Einsatzort, Drehort)", ctx: "exact location of my bike / film location" },
    { id: "10_2_67", eng: "She had a point.", phon: "[pɔɪnt]", ger: "Da hatte sie recht.", ctx: "Alternative: You have a point (there). = Da hast du recht." },
    { id: "10_2_68", eng: "(to) bump into/against sb./sth.", phon: "[bʌmp]", ger: "jn./etwas (an)stoßen, gegen etwas stoßen; jn. zufällig treffen", ctx: "bumped into a wall / bumped into Lucie in town (zufällig treffen)" },
    { id: "10_2_69", eng: "otherwise", phon: "['ʌðəwaɪz]", ger: "anderenfalls, ansonsten, sonst; anders", ctx: "Hurry up, otherwise we'll miss the train!" },
    { id: "10_2_70", eng: "absolute", phon: "['æbsəluːt]", ger: "absolut", ctx: "💡 Betonung auf 1. Silbe! Aber als alleinstehende Antwort (Absolut!): Absolutely! [æbsə'luːtli] auf der 3. Silbe!" },
    { id: "10_2_71", eng: "(to) get informed (about)", phon: "[ɪn'fɔːmd]", ger: "sich informieren (über)", ctx: "Keep me informed. / (to) keep sb. informed = jn. auf dem Laufenden halten" },
    { id: "10_2_72", eng: "the gist (of sth.) (no pl.)", phon: "[dʒɪst]", ger: "das Wesentliche (an/von etwas)", ctx: "It was hard to get the gist of what he was saying." },
    { id: "10_2_73", eng: "(to) recharge", phon: "[ˌriː'tʃɑːdʒ]", ger: "(wieder) aufladen (Batterie, Handy, ...)", ctx: "synonym: (to) charge (again)" },
    { id: "10_2_74", eng: "campsite", phon: "['kæmpsaɪt]", ger: "Campingplatz", ctx: "AE alternative: campground" },
    { id: "10_2_75", eng: "kayak", phon: "['kaɪæk]", ger: "Kajak", ctx: "kayaking = Kajakfahren; kayaker = Kajakfahrer/in" },
    { id: "10_2_76", eng: "guided tour", phon: "[ˌɡaɪdɪd 'tʊə]", ger: "Führung, geführte Tour", ctx: "guided walking tour / guided walk = geführter Spaziergang" },
    { id: "10_2_77", eng: "commercial", phon: "[kə'mɜːʃl]", ger: "kommerziell (auf Gewinn ausgerichtet)", ctx: "a huge commercial success" },
    { id: "10_2_78", eng: "swing", phon: "[swɪŋ]", ger: "(das) Schwingen, Schwung; Schaukel", ctx: "kids on a swing" },
    { id: "10_2_79", eng: "canyon", phon: "['kænjən]", ger: "Cañon (steilwandiges Tal)", ctx: "There's a river at the bottom of the deep canyon." },
    { id: "10_2_80", eng: "(to) strap sb. (onto/to sth.)", phon: "[stræp]", ger: "jn. (auf/an etwas) festschnallen", ctx: "secure sb. with straps; noun: strap" },
    { id: "10_2_81", eng: "(to) bring sb./sth. along", phon: "[brɪŋ]", ger: "jn./etwas mitbringen", ctx: "Bring along your friends!" },
    { id: "10_2_82", eng: "(to) paddle", phon: "['pædl]", ger: "paddeln", ctx: "noun: paddle = Paddel" },
    { id: "10_2_83", eng: "sunblock", phon: "['sʌnblɒk]", ger: "Sonnenschutz(creme)", ctx: "synonyms: sun cream, sunscreen" },
    { id: "10_2_84", eng: "swimwear", phon: "['swɪmweə]", ger: "Badekleidung", ctx: "noun" },
    { id: "10_2_85", eng: "sandals (pl.)", phon: "['sændlz]", ger: "Sandalen", ctx: "noun" },
    { id: "10_2_86", eng: "(to) signal", phon: "['sɪɡnəl]", ger: "signalisieren", ctx: "meaning: to show, to make clear; noun: signal" },
    { id: "10_2_87", eng: "(to) admit", phon: "[əd'mɪt]", ger: "zugeben, (ein)gestehen", ctx: "He does stupid things, but he would never admit it!" },
    { id: "10_2_88", eng: "lovely", phon: "['lʌvli]", ger: "(wunder)schön, herrlich; (Person:) nett, lieb", ctx: "lovely weather / a lovely old lady" },
    { id: "10_2_89", eng: "spot", phon: "[spɒt]", ger: "Stelle, Fleck, Punkt", ctx: "💡 noun: spot; verb: (to) spot sth. = etwas entdecken (spotted some sea lions)" },
    { id: "10_2_90", eng: "spectacular", phon: "[spek'tækjələ]", ger: "spektakulär", ctx: "💡 Betonung auf der 2. Silbe!" },
    { id: "10_2_91", eng: "unless", phon: "[ən'les]", ger: "es sei denn; außer (wenn)", ctx: "💡 Conjunction of condition: unless you work harder (= if you do *not* work harder)" },
    { id: "10_2_92", eng: "unexpected", phon: "[ˌʌnɪk'spektɪd]", ger: "unerwartet", ctx: "meaning: we didn't expect it at all" },
    { id: "10_2_93", eng: "stylistic", phon: "[staɪ'lɪstɪk]", ger: "stilistisch, Stil-", ctx: "adverb: stylistically; noun: style" },
    { id: "10_2_94", eng: "expressive", phon: "[ɪk'spresɪv]", ger: "ausdrucksvoll, ausdrucksstark; Ausdrucks-", ctx: "noun: expression; verb: (to) express" },
    { id: "10_2_95", eng: "novel", phon: "['nɒvl]", ger: "Roman", ctx: "💡 False Friend! novel = Roman / Roman = Römer/in" },
    { id: "10_2_96", eng: "developer", phon: "[dɪ'veləpə]", ger: "Bauunternehmer/in; Entwickler/in", ctx: "a person or company that buys land to develop it" },
    { id: "10_2_97", eng: "coastal", phon: "['kəʊstl]", ger: "Küsten-", ctx: "Plymouth is a coastal town. (noun: coast)" },
    { id: "10_2_98", eng: "mysterious", phon: "[mɪ'stɪəriəs]", ger: "geheimnisvoll", ctx: "noun: mystery ['mɪstri] = Geheimnis" },
    { id: "10_2_99", eng: "deformed", phon: "[dɪ'fɔːmd]", ger: "missgebildet", ctx: "noun: deformity [dɪ'fɔːməti] = Missbildung" },
    { id: "10_2_100", eng: "be to do sth.", phon: "[biː tuː]", ger: "etwas tun sollen", ctx: "synonyms: should, be supposed to (They told us we were to wait outside.)" },
    { id: "10_2_101", eng: "(to) minimize", phon: "['mɪnɪmaɪz]", ger: "auf ein Minimum beschränken, minimieren", ctx: "to make sth. as small as possible; noun: minimum" },
    { id: "10_2_102", eng: "(to) cooperate (with sb. in/on sth.)", phon: "[kəʊ'ɒpəreɪt]", ger: "kooperieren, zusammenarbeiten (mit jm. bei/an etwas)", ctx: "noun: cooperation [kəʊˌɒpə'reɪʃn]" },
    { id: "10_2_103", eng: "foresight", phon: "['fɔːsaɪt]", ger: "weise Voraussicht, Weitblick", ctx: "the ability to predict what could happen" },
    { id: "10_2_104", eng: "(to) cut down (on sth.)", phon: "[kʌt daʊn]", ger: "(etwas) reduzieren, einsparen; sich (bei etwas) einschränken", ctx: "I really have to cut down on chocolate." },
    { id: "10_2_105", eng: "for the present", phon: "['preznt]", ger: "vorläufig, für den Moment", ctx: "synonym: for the time being" },
    { id: "10_2_106", eng: "one way or another", phon: "[weɪ]", ger: "so oder so, auf die eine oder andere Art", ctx: "synonym: somehow" },
    { id: "10_2_107", eng: "(to) persuade", phon: "[pə'sweɪd]", ger: "überreden, überzeugen", ctx: "noun: persuasion [pə'sweɪʒn] = Überzeugungskunst" },
    { id: "10_2_108", eng: "sharp", phon: "[ʃɑːp]", ger: "scharf (z. B. Messer, Kommentar)", ctx: "💡 Scharfe Messer/Kommentare = sharp / Scharf gewürztes Essen = hot!" },
    { id: "10_2_109", eng: "amenity", phon: "[ə'miːnəti]", ger: "Einrichtung; Annehmlichkeit", ctx: "Our B&B is close to all local amenities (= shops, station, sports centre)." },
    { id: "10_2_110", eng: "(to) please sb.", phon: "[pliːz]", ger: "jn. zufriedenstellen", ctx: "You can't please everybody. / be pleased with sth. = mit etwas zufrieden sein" },
    { id: "10_2_111", eng: "on my/your/their/... own", phon: "[əʊn]", ger: "alleine, ohne Hilfe", ctx: "Can you manage on your own?" },
    { id: "10_2_112", eng: "soul", phon: "[səʊl]", ger: "Seele", ctx: "Do you believe we all have souls?" },
    { id: "10_2_113", eng: "(to) crumble", phon: "['krʌmbl]", ger: "zerfallen, zerbröckeln", ctx: "This wall is crumbling." },
    { id: "10_2_114", eng: "care", phon: "[keə]", ger: "Sorgfalt, Vorsicht", ctx: "I chose my words with care. (mit Bedacht); adjective: careful" },
    { id: "10_2_115", eng: "objection (to)", phon: "[əb'dʒekʃn]", ger: "Einwand (gegen)", ctx: "person: objector = Gegner/in" },
    { id: "10_2_116", eng: "excursion", phon: "[ɪk'skɜːʃn]", ger: "Exkursion, Ausflug", ctx: "a short trip for entertainment or education" },
    { id: "10_2_117", eng: "(to) be involved in", phon: "[ɪn'vɒlvd]", ger: "beteiligt sein an; etwas zu tun haben mit", ctx: "💡 Wortfamilie: noun: involvement (Engagement); verb: (to) involve; phrase: get involved in" },
    { id: "10_2_118", eng: "(to) dress", phon: "[dres]", ger: "sich kleiden, sich anziehen", ctx: "(to) dress up (as) = sich schick anziehen / sich verkleiden (als); noun: dress" },
    { id: "10_2_119", eng: "in favour of sb./sth.", phon: "['feɪvə]", ger: "zugunsten von jm./etwas, für jn./etwas", ctx: "AE spelling: favor (Are you in favour of this plan?)" },
    { id: "10_2_120", eng: "(to) interest sb.", phon: "['ɪntrəst]", ger: "jn. interessieren", ctx: "noun: interest (in); adjectives: interesting / interested in" },
    { id: "10_2_121", eng: "along with", phon: "[ə'lɒŋ wɪð]", ger: "(zusammen) mit, neben", ctx: "synonym: together with" },
    { id: "10_2_122", eng: "(to) line sth. with sth.", phon: "[laɪn]", ger: "etwas säumen; füttern, auskleiden", ctx: "The street was lined with trees." },
    { id: "10_2_123", eng: "(to) rotate", phon: "[rəʊ'teɪt]", ger: "rotieren, sich drehen", ctx: "When a car moves, the wheels rotate." },
    { id: "10_2_124", eng: "craft (pl. craft)", phon: "[krɑːft]", ger: "Boot; Flugzeug; Raumfahrzeug", ctx: "💡 Plural bleibt formgleich! Formal word for boat/ship; e.g., spacecraft" },
    { id: "10_2_125", eng: "means (pl. means)", phon: "[miːnz]", ger: "Mittel, Möglichkeit", ctx: "by means of... = mit Hilfe von...; means of communication / payment / transport" },
    { id: "10_2_126", eng: "seed", phon: "[siːd]", ger: "Samen; Saat", ctx: "putting seeds in the ground" },
    { id: "10_2_127", eng: "flame", phon: "[fleɪm]", ger: "Flamme", ctx: "the flame of a candle" },
    { id: "10_2_128", eng: "dynamite", phon: "['daɪnəmaɪt]", ger: "Dynamit, Sprengstoff", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_2_129", eng: "(to) blast", phon: "[blɑːst]", ger: "sprengen; (mit Wucht) schießen", ctx: "An explosion blasted the old house to bits." },
    { id: "10_2_130", eng: "cost", phon: "[kɒst]", ger: "Kosten; Preis", ctx: "verb: (to) cost, cost, cost" },
    { id: "10_2_131", eng: "central", phon: "['sentrəl]", ger: "zentral", ctx: "💡 central London = London Stadtmitte; noun: centre" },
    { id: "10_2_132", eng: "feel sorry for sb.", phon: "[fɪːl 'sɒri]", ger: "Mitleid haben mit jm.", ctx: "They looked so sad. I really felt sorry for them." },
    { id: "10_2_133", eng: "granny", phon: "['ɡræni]", ger: "Oma", ctx: "informal; synonyms: grandma, grandmother" },
    { id: "10_2_134", eng: "(to) be seated", phon: "['siːtɪd]", ger: "(auf einem Platz) sitzen", ctx: "Please wait to be seated (im Restaurant)." },
    { id: "10_2_135", eng: "furious (with/at sb.)", phon: "['fjʊəriəs]", ger: "wütend", ctx: "He was really furious when I told him. noun: fury ['fjʊəri] (Wut)" },
    { id: "10_2_136", eng: "forehead", phon: "['fɔːhed]", ger: "Stirn", ctx: "noun" },
    { id: "10_2_137", eng: "murmur", phon: "['mɜːmə]", ger: "(das) Murmeln, Gemurmel", ctx: "verb: (to) murmur = murmeln (leise sprechen)" },
    { id: "10_2_138", eng: "hymn", phon: "[hɪm]", ger: "Hymne; Kirchenlied", ctx: "💡 Das 'n' am Ende ist stumm! German Nationalhymne = English national anthem [ˈnæʃnəl ˈænθəm]" },
    { id: "10_2_139", eng: "(to) conclude", phon: "[kən'kluːd]", ger: "(ab)schließen, beenden", ctx: "conclude a meeting / noun: conclusion = Schlussfolgerung (draw the conclusion)" },
    { id: "10_2_140", eng: "(to) bend, bent, bent", phon: "[bend], [bent]", ger: "beugen; sich beugen, sich bücken", ctx: "bend over = sich bücken; bend down = sich hinunterbeugen; noun: bend = Kurve" },
    { id: "10_2_141", eng: "(to) wipe", phon: "[waɪp]", ger: "(ab)wischen", ctx: "wiping the table" },
    { id: "10_2_142", eng: "sorrow", phon: "['sɒrəʊ]", ger: "Kummer, Leid", ctx: "meaning: the feeling of being very sad" },
    { id: "10_2_143", eng: "enslavement", phon: "[ɪn'sleɪvmənt]", ger: "Versklavung", ctx: "the act of enslaving sb.; verb: (to) enslave sb." },
    { id: "10_2_144", eng: "(all) at once", phon: "[æt wʌns]", ger: "sofort; auf einmal (gleichzeitig)", ctx: "leave at once (= immediately) / Don't talk all at once (= at the same time)" },
    { id: "10_2_145", eng: "gentle", phon: "['dʒentl]", ger: "sanft(mütig); behutsam, leicht", ctx: "meaning: calm and kind; adverb: gently" },
    { id: "10_2_146", eng: "domain", phon: "[də'meɪn]", ger: "Domäne, Bereich", ctx: "Space technology is her domain." },
    { id: "10_2_147", eng: "release", phon: "[rɪ'liːs]", ger: "Befreiung; Freilassung; Veröffentlichung", ctx: "verb: (to) release" },
    { id: "10_2_148", eng: "(to) carve", phon: "[kɑːv]", ger: "meißeln, schnitzen; (in Stein) hauen", ctx: "carved hate on the man's face / carved his name into the table" },
    { id: "10_2_149", eng: "anger", phon: "['æŋɡə]", ger: "Zorn, Wut", ctx: "adjective: angry" },
    { id: "10_2_150", eng: "(to) scramble (for)", phon: "['skræmbl]", ger: "drängeln; drängen (an einen Ort); klettern, krabbeln", ctx: "People started scrambling for the exit." },
    { id: "10_2_151", eng: "perspective", phon: "[pə'spektɪv]", ger: "Perspektive", ctx: "💡 Betonung auf der 2. Silbe!" },
    { id: "10_2_152", eng: "(to) rediscover", phon: "[ˌriːdɪ'skʌvə]", ger: "wiederentdecken, wiederfinden", ctx: "💡 re-prefix meaning: being done again or changed back" },
    { id: "10_2_153", eng: "(to) master", phon: "['mɑːstə]", ger: "meistern, beherrschen", ctx: "noun: master (Meister/in)" },
    { id: "10_2_154", eng: "multiple", phon: "['mʌltɪpl]", ger: "mehrere, zahlreiche", ctx: "meaning: many different; e.g., multiple-choice question" },
    { id: "10_2_155", eng: "(to) argue (about)", phon: "['ɑːɡjuː]", ger: "argumentieren; streiten (über/wegen)", ctx: "💡 Wortfamilie: noun: argument = Argument / Streit; adjective: argumentative = streitsüchtig" },
    { id: "10_2_156", eng: "unknown", phon: "[ˌʌn'nəʊn]", ger: "unbekannt", ctx: "meaning: not well-known" },
    { id: "10_2_157", eng: "mania", phon: "['meɪniə]", ger: "Manie, Fimmel", ctx: "e.g., football mania, a mania for computer games" }
];