const e10u1_data = [
    { id: "10_1_1", eng: "diverse", phon: "[daɪ'vɜːs]", ger: "unterschiedlich, vielfältig", ctx: "noun: diversity" },
    { id: "10_1_2", eng: "society", phon: "[sə'saɪəti]", ger: "Gesellschaft", ctx: "adjective: social" },
    { id: "10_1_3", eng: "apartheid", phon: "[ə'pɑːtaɪt]", ger: "Apartheid (früheres System der Trennung zwischen Weißen und Schwarzen in Südafrika)", ctx: "Under apartheid only white people had full political rights." },
    { id: "10_1_4", eng: "relation", phon: "[rɪ'leɪʃn]", ger: "Beziehung, Verhältnis; Bezug", ctx: "in relation to = in Bezug auf; verb: (to) relate to sth. = sich auf etwas beziehen" },
    { id: "10_1_5", eng: "the pros and cons (pl.)", phon: "[prəʊz ənd 'kɒnz]", ger: "das Pro und Kontra; das Für und Wider", ctx: "meaning: the reasons for and against" },
    { id: "10_1_6", eng: "reserve", phon: "[rɪ'zɜːv]", ger: "Schutzgebiet", ctx: "an area which is protected for wildlife" },
    { id: "10_1_7", eng: "facet", phon: "['fæsɪt]", ger: "Facette", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_1_8", eng: "rainbow", phon: "['reɪnbəʊ]", ger: "Regenbogen", ctx: "noun" },
    { id: "10_1_9", eng: "lingua franca", phon: "[ˌlɪŋɡwə 'fræŋkə]", ger: "Lingua Franca (Verkehrssprache)", ctx: "English is a lingua franca in many parts of the world." },
    { id: "10_1_10", eng: "non-", phon: "[nɒn]", ger: "Nicht-; nicht-", ctx: "e.g., non-white(s), a non-stop flight" },
    { id: "10_1_11", eng: "(to) weigh heavily on sb./sb.'s shoulders", phon: "[weɪ]", ger: "schwer lasten auf jm. / auf js. Schultern", ctx: "💡 (to) weigh (the pros and cons) = (das Für und Wider) abwägen" },
    { id: "10_1_12", eng: "optimistic", phon: "[ˌɒptɪ'mɪstɪk]", ger: "optimistisch", ctx: "opposite: pessimistic; nouns: optimism vs. pessimism; person: optimist vs. pessimist" },
    { id: "10_1_13", eng: "beyond", phon: "[bɪ'jɒnd]", ger: "jenseits, außerhalb, weiter als", ctx: "Beyond that I don't know much about him." },
    { id: "10_1_14", eng: "(to) agree (on) sth.", phon: "[ə'ɡriː]", ger: "etwas vereinbaren, absprechen, sich einigen auf etwas; sich einig sein", ctx: "noun: agreement; phrase: reach an agreement = eine Einigung erzielen" },
    { id: "10_1_15", eng: "people of colour", phon: "['kʌlə]", ger: "nicht-weiße Menschen", ctx: "people who are not white" },
    { id: "10_1_16", eng: "phenomenon (pl. phenomena)", phon: "[fə'nɒmɪnən], [fə'nɒmɪnə]", ger: "Phänomen, Erscheinung", ctx: "💡 Betonung auf der 2. Silbe!" },
    { id: "10_1_17", eng: "(to) fix sth.", phon: "[fɪks]", ger: "etwas in Ordnung bringen; reparieren", ctx: "informal (e.g., Fix your hair! / fix a bike)" },
    { id: "10_1_18", eng: "wrong", phon: "[rɒŋ]", ger: "Unrecht", ctx: "difference between right and wrong; adjectives: wrong vs. right" },
    { id: "10_1_19", eng: "reform", phon: "[rɪ'fɔːm]", ger: "Reform", ctx: "verb: (to) reform = reformieren; (sich) ändern" },
    { id: "10_1_20", eng: "youth", phon: "[juːθ]", ger: "Jugend; Jugendlicher", ctx: "1. the time when you're young; 2. a young man" },
    { id: "10_1_21", eng: "growth", phon: "[ɡrəʊθ]", ger: "Wachstum", ctx: "verb: (to) grow, grew, grown" },
    { id: "10_1_22", eng: "educational", phon: "[ˌedʒu'keɪʃənl]", ger: "Erziehungs-, Bildungs-", ctx: "relating to education" },
    { id: "10_1_23", eng: "corruption", phon: "[kə'rʌpʃn]", ger: "Korruption, Bestechlichkeit", ctx: "adjective: corrupt" },
    { id: "10_1_24", eng: "entrepreneur", phon: "[ˌɒntrəprə'nɜː]", ger: "Unternehmer/in", ctx: "synonyms: businessman/businesswoman" },
    { id: "10_1_25", eng: "qualification", phon: "[ˌkwɒlɪfɪ'keɪʃn]", ger: "(Schul-)Abschluss, Qualifikation", ctx: "verb: (to) qualify; qualified cook = ein/e ausgebildete/r Koch/Köchin" },
    { id: "10_1_26", eng: "diploma", phon: "[dɪ'pləʊmə]", ger: "Diplom, Abschlusszeugnis", ctx: "document showing you completed a part of your education" },
    { id: "10_1_27", eng: "(to) struggle", phon: "['strʌɡl]", ger: "kämpfen, sich abmühen", ctx: "I am struggling to understand. / noun: struggle = Kampf, Anstrengung" },
    { id: "10_1_28", eng: "nanny", phon: "['næni]", ger: "Kindermädchen", ctx: "job to look after young children in their home" },
    { id: "10_1_29", eng: "party", phon: "['pɑːti]", ger: "Partei; Gruppe", ctx: "💡 party = 1. Partei/Gruppe (Green Party); 2. Fest, Party" },
    { id: "10_1_30", eng: "(to) fail", phon: "[feɪl]", ger: "scheitern; (es) nicht schaffen", ctx: "fail sb. = jn. enttäuschen; noun: failure = Scheitern, Misserfolg" },
    { id: "10_1_31", eng: "racism", phon: "['reɪsɪzm]", ger: "Rassismus", ctx: "💡 Betonung auf der 1. Silbe! person: racist (Rassist/in); adjective: racist" },
    { id: "10_1_32", eng: "(not) necessarily", phon: "[nesə'serəli]", ger: "zwangsläufig; (nicht) unbedingt", ctx: "An expensive bike isn't necessarily the best one." },
    { id: "10_1_33", eng: "at times", phon: "[æt taɪmz]", ger: "zeitweise, manchmal", ctx: "synonym: sometimes" },
    { id: "10_1_34", eng: "(to) grasp", phon: "[ɡrɑːsp]", ger: "verstehen, begreifen; (er)greifen", ctx: "hard to grasp / He grasped my hand." },
    { id: "10_1_35", eng: "township", phon: "['taʊnʃɪp]", ger: "Township (überwiegend von Schwarzen bewohnte Siedlung in Südafrika)", ctx: "During apartheid, black people had to live in townships." },
    { id: "10_1_36", eng: "largely", phon: "['lɑːdʒli]", ger: "größtenteils, überwiegend, weitgehend", ctx: "💡 adverb; meaning: mostly; adjective: large" },
    { id: "10_1_37", eng: "province", phon: "['provɪns]", ger: "Provinz, Bundesland", ctx: "💡 Betonung auf der 1. Silbe! adjective: provincial" },
    { id: "10_1_38", eng: "(to) socialize (with)", phon: "['səʊʃəlaɪz]", ger: "sich treffen (mit), unter Leute gehen", ctx: "I hardly ever socialize with friends." },
    { id: "10_1_39", eng: "(to) wrestle (with)", phon: "['resl]", ger: "ringen (mit), kämpfen (gegen)", ctx: "noun: wrestling = Ringen (Kampfsport)" },
    { id: "10_1_40", eng: "similarity", phon: "[ˌsɪmə'lærəti]", ger: "Ähnlichkeit, Gemeinsamkeit", ctx: "opposite: difference; adjective: similar (to)" },
    { id: "10_1_41", eng: "revolution", phon: "[ˌrevə'luːʃn]", ger: "Revolution", ctx: "💡 Betonung auf der 3. Silbe!" },
    { id: "10_1_42", eng: "particular", phon: "[pə'tɪkjələ]", ger: "bestimmte(r, s), spezielle(r, s)", ctx: "particularly / in particular = insbesondere" },
    { id: "10_1_43", eng: "transition", phon: "[træn'zɪʃn]", ger: "Übergang", ctx: "the transition from summer to autumn" },
    { id: "10_1_44", eng: "clothing (no pl.)", phon: "['kləʊðɪŋ]", ger: "Kleidung", ctx: "💡 singular structure: a piece of clothing (ein Kleidungsstück). More formal than 'clothes'." },
    { id: "10_1_45", eng: "(to) step", phon: "[step]", ger: "treten (einen Schritt tun)", ctx: "Please step closer! / noun: step" },
    { id: "10_1_46", eng: "inner", phon: "['ɪnə]", ger: "innere(r, s)", ctx: "opposite: outer = äußere(r, s); inner strength = innere Stärke" },
    { id: "10_1_47", eng: "(to) twist", phon: "[twɪst]", ger: "(sich) (ver)biegen, (sich) (ver)drehen", ctx: "twisted branches of a tree" },
    { id: "10_1_48", eng: "(to) shuffle", phon: "['ʃʌfl]", ger: "schlürfen; mit den Füßen scharren", ctx: "She was shuffling her feet nervously." },
    { id: "10_1_49", eng: "(to) stamp", phon: "[stæmp]", ger: "(auf)stampfen", ctx: "(to) stamp your feet = mit den Füßen stampfen" },
    { id: "10_1_50", eng: "rhythmic", phon: "['rɪðmɪk]", ger: "rhythmisch, gleichmäßig", ctx: "adverb: rhythmically; noun: rhythm" },
    { id: "10_1_51", eng: "variation", phon: "[ˌveəri'eɪʃn]", ger: "Variante, Variation; Veränderung, Schwankung", ctx: "variation in temperature" },
    { id: "10_1_52", eng: "limit", phon: "['lɪmɪt]", ger: "Grenze, Begrenzung, Beschränkung", ctx: "verb: (to) limit sth. (to) = etwas beschränken" },
    { id: "10_1_53", eng: "resistance", phon: "[rɪ'zɪstəns]", ger: "Widerstand; Resistenz", ctx: "verb: (to) resist = widerstehen, sich widersetzen" },
    { id: "10_1_54", eng: "(to) shift", phon: "[ʃɪft]", ger: "(sich) verlagern; (sich) verändern; (sich) bewegen", ctx: "noun: shift (in) = Verlagerung, Wandel" },
    { id: "10_1_55", eng: "impulse", phon: "['ɪmpʌls]", ger: "Impuls", ctx: "💡 Betonung auf der 1. Silbe! (noun)" },
    { id: "10_1_56", eng: "(to) respond (to)", phon: "[rɪ'spɒnd]", ger: "reagieren, antworten (auf)", ctx: "noun: response (to) = Reaktion, Antwort" },
    { id: "10_1_57", eng: "gumboot", phon: "['ɡʌmbuːt]", ger: "Gummistiefel", ctx: "noun" },
    { id: "10_1_58", eng: "rural", phon: "['rʊərəl]", ger: "ländlich, Land-", ctx: "meaning: relating to the countryside" },
    { id: "10_1_59", eng: "era", phon: "['ɪərə]", ger: "Ära, Epoche", ctx: "we've been living in an era of peace" },
    { id: "10_1_60", eng: "(to) chain", phon: "[tʃeɪn]", ger: "anketten, fesseln (mit Ketten)", ctx: "(to) chain sb./sth. to sth.; noun: chain = Kette" },
    { id: "10_1_61", eng: "(to) slap", phon: "[slæp]", ger: "schlagen; knallen; klatschen", ctx: "slapped me on the back / slapped the letter on the desk" },
    { id: "10_1_62", eng: "(to) stomp", phon: "[stɒmp]", ger: "stampfen", ctx: "He's stomping his feet." },
    { id: "10_1_63", eng: "(to) combine", phon: "[kəm'baɪn]", ger: "verbinden, kombinieren", ctx: "noun: combination [ˌkɒmbɪ'neɪʃn]" },
    { id: "10_1_64", eng: "hardship", phon: "['hɑːdʃɪp]", ger: "Not, Mühsal, harte Umstände", ctx: "Life was full of hardships. (adjective: hard)" },
    { id: "10_1_65", eng: "celebration", phon: "[ˌselɪ'breɪʃn]", ger: "Feier", ctx: "verb: (to) celebrate" },
    { id: "10_1_66", eng: "choreographer", phon: "[kɒri'ɒɡrəfə]", ger: "Choreograf/in", ctx: "💡 Betonung auf der 3. Silbe!" },
    { id: "10_1_67", eng: "(to) hurry", phon: "['hʌri]", ger: "sich beeilen; eilen", ctx: "Hurry up! (Beeil dich!); phrase: be in a hurry = in Eile sein" },
    { id: "10_1_68", eng: "game", phon: "[ɡeɪm]", ger: "Wild (Tiere, Fleisch)", ctx: "💡 game = 1. Wild; 2. Spiel" },
    { id: "10_1_69", eng: "habitat", phon: "['hæbɪtæt]", ger: "Lebensraum", ctx: "the natural habitat of animals" },
    { id: "10_1_70", eng: "rhino", phon: "['raɪnəʊ]", ger: "Nashorn", ctx: "informal; short for rhinoceros [raɪ'nɒsərəs] (pl. rhinos / rhinoceroses)" },
    { id: "10_1_71", eng: "leopard", phon: "['lepəd]", ger: "Leopard", ctx: "💡 Betonung auf der 1. Silbe! (noun)" },
    { id: "10_1_72", eng: "buffalo (pl. buffalo or buffaloes)", phon: "['bʌfələʊ]", ger: "Büffel; Bison", ctx: "noun" },
    { id: "10_1_73", eng: "variety", phon: "[və'raɪəti]", ger: "Variante, Sorte, Art", ctx: "a large variety of...; variety (of) = Auswahl (an)" },
    { id: "10_1_74", eng: "informative", phon: "[ɪn'fɔːmətɪv]", ger: "informativ", ctx: "💡 Betonung auf der 2. Silbe! verb: (to) inform sb. (about/of sth.)" },
    { id: "10_1_75", eng: "active", phon: "['æktɪv]", ger: "aktiv", ctx: "opposite: passive ['pæsɪv]" },
    { id: "10_1_76", eng: "... as well as ...", phon: "[əz 'wel əz]", ger: "sowohl ... als auch ...", ctx: "I have a bike as well as a car. / as well = auch, ebenso" },
    { id: "10_1_77", eng: "initiative", phon: "[ɪ'nɪʃətɪv]", ger: "Initiative", ctx: "💡 Betonung auf der 2. Silbe!" },
    { id: "10_1_78", eng: "rehabilitation", phon: "[ˌriːəbɪlɪ'teɪʃn]", ger: "Rehabilitation", ctx: "noun" },
    { id: "10_1_79", eng: "(to) nurse", phon: "[nɜːs]", ger: "pflegen; (aus)kurieren", ctx: "noun: nurse = Krankenpfleger/in" },
    { id: "10_1_80", eng: "(to) return", phon: "[rɪ'tɜːn]", ger: "zurückgeben, zurückbringen; zurückkehren", ctx: "💡 return = 1. zurückgeben; 2. zurückkehren; nouns: Rückgabe / Rückkehr" },
    { id: "10_1_81", eng: "in the wild / to the wild", phon: "[waɪld]", ger: "in der Wildnis / in die Wildnis", ctx: "They return the animals to the wild." },
    { id: "10_1_82", eng: "rescue", phon: "['reskjuː]", ger: "Rettung", ctx: "rescue centre = Rettungsstation; verb: (to) rescue = retten" },
    { id: "10_1_83", eng: "circus", phon: "['sɜːkəs]", ger: "Zirkus", ctx: "noun" },
    { id: "10_1_84", eng: "lifelong", phon: "['laɪflɒŋ]", ger: "lebenslang", ctx: "meaning: for as long as you live" },
    { id: "10_1_85", eng: "worldwide", phon: "[ˌwɜːld'waɪd]", ger: "weltweit", ctx: "meaning: all over the world" },
    { id: "10_1_86", eng: "radical", phon: "['rædɪkl]", ger: "radikal", ctx: "adverb: radically (radikal reduziert)" },
    { id: "10_1_87", eng: "(to) poach", phon: "[pəʊtʃ]", ger: "wildern, unerlaubt jagen", ctx: "poaching = Wilderei, (das) Wildern" },
    { id: "10_1_88", eng: "controversial", phon: "[ˌkɒntrə'vɜːʃl]", ger: "kontrovers, umstritten", ctx: "noun: controversy ['kɒntrəvɜːsi] = Kontroverse" },
    { id: "10_1_89", eng: "cub", phon: "[kʌb]", ger: "(Löwen-, Bären-)Junges", ctx: "e.g., a lion cub" },
    { id: "10_1_90", eng: "(to) breed, bred, bred", phon: "[briːd], [bred]", ger: "brüten, Junge bekommen, sich vermehren; züchten; hervorrufen", ctx: "captive breeding = Erhaltungszucht; breed bad feeling = hervorrufen" },
    { id: "10_1_91", eng: "captive", phon: "['kæptɪv]", ger: "gefangen, in Gefangenschaft", ctx: "These animals are captive-bred." },
    { id: "10_1_92", eng: "(to) enclose sth. in/with sth.", phon: "[ɪn'kləʊz]", ger: "etwas (mit etwas) umgeben", ctx: "enclosed = umschlossen, eingezäunt" },
    { id: "10_1_93", eng: "instinct", phon: "['ɪnstɪŋkt]", ger: "Instinkt", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_1_94", eng: "(to) profit (from)", phon: "['prɒfɪt]", ger: "profitieren (von)", ctx: "noun: profit" },
    { id: "10_1_95", eng: "widespread", phon: "['waɪdspred]", ger: "(weit) verbreitet", ctx: "existing in a large area or among lots of people" },
    { id: "10_1_96", eng: "petition", phon: "[pə'tɪʃn]", ger: "Antrag, Petition (Unterschriftenammlung)", ctx: "verb: (to) petition (for/against) = eine Petition starten" },
    { id: "10_1_97", eng: "practice", phon: "['præktɪs]", ger: "Praktik, Vorgehensweise; Praxis", ctx: "💡 practice = 1. Praktik/Vorgehensweise; 2. Übung(en)" },
    { id: "10_1_98", eng: "questionable", phon: "['kwestʃənəbl]", ger: "fragwürdig", ctx: "verb: (to) question = etwas in Frage stellen" },
    { id: "10_1_99", eng: "operator", phon: "['ɒpəreɪtə]", ger: "Betreiber/in", ctx: "a tour operator = Reiseveranstalter" },
    { id: "10_1_100", eng: "brutal", phon: "['bruːtl]", ger: "brutal", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_1_101", eng: "canned hunting", phon: "[kænd 'hʌntɪŋ]", ger: "Jagd auf in Gefangenschaft groß gezogene Tiere in eingezäunten Gebieten", ctx: "noun phrase" },
    { id: "10_1_102", eng: "complaint", phon: "[kəm'pleɪnt]", ger: "Beschwerde", ctx: "make a complaint (about sth.); verb: (to) complain = sich beschweren" },
    { id: "10_1_103", eng: "air conditioning", phon: "['eə kənˌdɪʃnɪŋ]", ger: "Klimatisierung, Klimaanlage", ctx: "💡 air conditioner = das Klimagerät selbst" },
    { id: "10_1_104", eng: "in fact", phon: "[ɪn 'fækt]", ger: "tatsächlich; eigentlich, um genau zu sein", ctx: "My homework wasn't hard. In fact, it only took me 10 minutes." },
    { id: "10_1_105", eng: "little", phon: "['lɪtl]", ger: "wenig", ctx: "💡 Forms: little - less [les] - least [liːst]; also means: klein / a little = ein bisschen" },
    { id: "10_1_106", eng: "circumstances (pl.)", phon: "['sɜːkəmstənsɪz]", ger: "Umstände, Verhältnisse", ctx: "under these circumstances" },
    { id: "10_1_107", eng: "partial", phon: "['pɑːʃl]", ger: "teilweise, Teil-", ctx: "noun: part" },
    { id: "10_1_108", eng: "refund", phon: "['riːfʌnd]", ger: "Rückzahlung, (Kosten-)Erstattung", ctx: "💡 Noun: ['riːfʌnd] – Verb: (to) refund [rɪ'fʌnd]" },
    { id: "10_1_109", eng: "receipt", phon: "[rɪ'siːt]", ger: "(Kauf-)Beleg, Quittung, Kassenzettel", ctx: "💡 False Friend! receipt = Kassenzettel / recipe ['resəpi] = Kochrezept (The 'p' is silent!)" },
    { id: "10_1_110", eng: "consequence", phon: "['kɒnsɪkwəns]", ger: "Folge, Konsequenz", ctx: "As a consequence, I did badly in the exam." },
    { id: "10_1_111", eng: "(to) demand", phon: "[dɪ'mɑːnd]", ger: "fordern, verlangen", ctx: "noun: demand = Forderung, Anforderung" },
    { id: "10_1_112", eng: "(to) elaborate (sth. / on sth.)", phon: "[ɪ'læbəreɪt]", ger: "näher ausführen; ins Detail gehen", ctx: "Can you elaborate on the reasons?" },
    { id: "10_1_113", eng: "prompt", phon: "[prɒmpt]", ger: "Stichwort, Vorgabe", ctx: "adjective: prompt = unverzüglich; verb: (to) prompt = veranlassen, vorsagen" },
    { id: "10_1_114", eng: "formulate", phon: "['fɔːmjuleɪt]", ger: "formulieren", ctx: "noun: formulation [ˌfɔːmju'leɪʃn]" },
    { id: "10_1_115", eng: "comedian", phon: "[kə'miːdiən]", ger: "Komiker/in", ctx: "He's a real comedian." },
    { id: "10_1_116", eng: "political", phon: "[pə'lɪtɪkl]", ger: "politisch", ctx: "💡 nouns: politics ['pɒlətɪks] (Politik ist SINGULAR: Politics *is*...); person: politician" },
    { id: "10_1_117", eng: "commentator", phon: "['kɒmənˌteɪtə]", ger: "Kommentator/in", ctx: "💡 Suffix -or person rule: actor, conductor, operator, survivor, inventor, spectator, visitor" },
    { id: "10_1_118", eng: "host", phon: "[həʊst]", ger: "(Radio-/TV-)Moderator/in", ctx: "💡 host = 1. Moderator/in; 2. Gastgeber/in" },
    { id: "10_1_119", eng: "unique", phon: "[ju'niːk]", ger: "einmalig, einzigartig", ctx: "Our ketchup has a unique taste." },
    { id: "10_1_120", eng: "(light)-skinned", phon: "[skɪnd]", ger: "(hell)-häutig", ctx: "light-skinned vs. dark-skinned" },
    { id: "10_1_121", eng: "take a right/left", phon: "[teɪk]", ger: "(nach) rechts/links abbiegen", ctx: "synonym: turn right/left" },
    { id: "10_1_122", eng: "whenever", phon: "[wen'evə]", ger: "wann (auch) immer", ctx: "You can come and visit us whenever you like." },
    { id: "10_1_123", eng: "(to) yell (at)", phon: "[jel]", ger: "(an)schreien, (an)brüllen", ctx: "meaning: to shout loudly at sb. because you're angry" },
    { id: "10_1_124", eng: "pandemonium", phon: "[ˌpændə'məʊniəm]", ger: "Tumult, Chaos", ctx: "💡 No plural in English: There *was* pandemonium." },
    { id: "10_1_125", eng: "genuine", phon: "['dʒenjuɪn]", ger: "echt, wirklich; aufrichtig", ctx: "adverb: genuinely = wirklich interessierte" },
    { id: "10_1_126", eng: "clue", phon: "[kluː]", ger: "(Lösungs-)Hinweis; Anhaltspunkt", ctx: "looking for clues; I have no clue = Ich habe keine Ahnung." },
    { id: "10_1_127", eng: "face to face", phon: "[feɪs tuː feɪs]", ger: "von Angesicht zu Angesicht", ctx: "I would rather meet her face to face." },
    { id: "10_1_128", eng: "homeland", phon: "['həʊmlænd]", ger: "Heimat(land); (Südafrika:) Homeland", ctx: "Under apartheid, an area where a certain group of Black people lived." },
    { id: "10_1_129", eng: "option", phon: "['ɒpʃn]", ger: "Wahl(möglichkeit), Option", ctx: "I had no option but to pay = Mir blieb nichts anderes übrig, als..." },
    { id: "10_1_130", eng: "(to) give sb. a leg up", phon: "[ɡɪv]", ger: "jm. einen Vorsprung verschaffen", ctx: "informal (These tips can give you a leg up.)" },
    { id: "10_1_131", eng: "comprehension", phon: "[ˌkɒmprɪ'henʃn]", ger: "Verständnis", ctx: "English comprehension = die Fähigkeit, Englisch zu verstehen" },
    { id: "10_1_132", eng: "(to) equate sth. (with)", phon: "[ɪ'kweɪt]", ger: "etwas gleichsetzen (mit)", ctx: "noun: equation [ɪ'kweɪʒn] = Gleichung" },
    { id: "10_1_133", eng: "intelligence", phon: "[ɪn'telɪdʒəns]", ger: "Intelligenz", ctx: "💡 Betonung auf der 2. Silbe! adjective: intelligent" },
    { id: "10_1_134", eng: "dock", phon: "[dɒk]", ger: "Anklagebank", ctx: "phrase: be in the dock = auf der Anklagebank sitzen" },
    { id: "10_1_135", eng: "(to) get away (with) / get off (with)", phon: "[ɡet ə'weɪ]", ger: "davonkommen (mit), durchkommen (mit)", ctx: "get away with murder = sich alles erlauben können" },
    { id: "10_1_136", eng: "fine", phon: "[faɪn]", ger: "Geldstrafe", ctx: "verb: (to) fine = zu einer Geldstrafe verurteilen (You might be fined.)" },
    { id: "10_1_137", eng: "naughty", phon: "['nɔːti]", ger: "ungezogen, frech, unartig (z. B. Kind)", ctx: "a naughty kid" },
    { id: "10_1_138", eng: "(to) be versed in sth.", phon: "[vɜːst]", ger: "versiert in etwas sein, gute Kenntnisse von etwas haben", ctx: "I was well versed in physics." },
    { id: "10_1_139", eng: "(to) pick sth. up", phon: "[pɪk 'ʌp]", ger: "sich etwas aneignen (Sprache/Kenntnisse); etwas aufnehmen (vom Boden)", ctx: "💡 pick up = 1. etwas aufschnappen/aneignen; 2. etwas aufheben" },
    { id: "10_1_140", eng: "upside (the head) (AE)", phon: "[ˌʌp'saɪd]", ger: "auf den Kopf, vor den Kopf", ctx: "informal; meaning: on(to) the head" },
    { id: "10_1_141", eng: "idiot", phon: "['ɪdiət]", ger: "Idiot/in", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_1_142", eng: "passionate", phon: "['pæʃənət]", ger: "leidenschaftlich", ctx: "be passionate about sth.; noun: passion" },
    { id: "10_1_143", eng: "(to) oppress", phon: "[ə'pres]", ger: "unterdrücken", ctx: "nouns: oppression (Unterdrückung); person: oppressor (Unterdrücker/in)" },
    { id: "10_1_144", eng: "boundary", phon: "['baʊndri]", ger: "Grenze", ctx: "Music can cross cultural boundaries." },
    { id: "10_1_145", eng: "(to) handle sth.", phon: "['hændl]", ger: "mit etwas umgehen, etwas handhaben", ctx: "noun: handle = (Hand-)Griff" },
    { id: "10_1_146", eng: "(to) navigate", phon: "['nævɪɡeɪt]", ger: "navigieren, den Weg finden (in/durch)", ctx: "💡 Betonung auf der 1. Silbe! noun: navigation [ˌnævɪ'ɡeɪʃn]" },
    { id: "10_1_147", eng: "shopkeeper", phon: "['ʃɒpˌkiːpə]", ger: "Ladenbesitzer/in", ctx: "noun" },
    { id: "10_1_148", eng: "fluent", phon: "['fluːənt]", ger: "fließend (Sprache)", ctx: "able to speak, read and write well" },
    { id: "10_1_149", eng: "merely", phon: "['mɪəli]", ger: "nur, bloß", ctx: "synonym: only" },
    { id: "10_1_150", eng: "brief", phon: "[briːf]", ger: "kurz, knapp", ctx: "synonym: short" },
    { id: "10_1_151", eng: "confusion", phon: "[kən'fjuːʒn]", ger: "Verwirrung; Durcheinander; Verwechslung", ctx: "verb: (to) confuse = verwirren, verwechseln" },
    { id: "10_1_152", eng: "(to) serve", phon: "[sɜːv]", ger: "servieren (Essen, Getränke); (Kundschaft) bedienen; dienen", ctx: "serve the drinks / serve as an example (dienen als)" },
    { id: "10_1_153", eng: "(to) mug sb.", phon: "[mʌɡ]", ger: "jn. überfallen", ctx: "meaning: to attack sb. in a public place to steal from them; noun: mugging" },
    { id: "10_1_154", eng: "dude", phon: "[duːd]", ger: "Mann, Alter (Anrede)", ctx: "informal" },
    { id: "10_1_155", eng: "incident", phon: "['ɪnsɪdənt]", ger: "Vorfall, Zwischenfall", ctx: "The police are asking people about the incident." },
    { id: "10_1_156", eng: "(to) define", phon: "[dɪ'faɪn]", ger: "definieren", ctx: "noun: definition" },
    { id: "10_1_157", eng: "chameleon", phon: "[kə'miːliən]", ger: "Chamäleon (Echsenart)", ctx: "noun" },
    { id: "10_1_158", eng: "perception", phon: "[pə'sepʃn]", ger: "Wahrnehmung", ctx: "the way you notice things with your senses" },
    { id: "10_1_159", eng: "barrier", phon: "['bæriə]", ger: "Barriere", ctx: "These stairs are a barrier for wheelchair users." },
    { id: "10_1_160", eng: "architect", phon: "['ɑːkɪtekt]", ger: "Architekt/in", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_1_161", eng: "effort", phon: "['efət]", ger: "Anstrengung, Mühe", ctx: "(to) make an effort = sich Mühe geben" },
    { id: "10_1_162", eng: "physical", phon: "['fɪzɪkl]", ger: "körperlich, physisch", ctx: "I try to keep physically fit." },
    { id: "10_1_163", eng: "mood", phon: "[muːd]", ger: "Stimmung, Laune", ctx: "💡 Idiom-Unterschied: English: *in* a terrible mood – German: schlechte Laune *haben*!" },
    { id: "10_1_164", eng: "atmosphere", phon: "['ætməsfɪə]", ger: "Atmosphäre", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_1_165", eng: "theme", phon: "[θiːm]", ger: "Thema", ctx: "the main theme of this play / theme with variations" },
    { id: "10_1_166", eng: "misunderstanding", phon: "[ˌmɪsʌndə'stændɪŋ]", ger: "Missverständnis", ctx: "verb: (to) misunderstand, misunderstood, misunderstood" },
    { id: "10_1_167", eng: "(to) clarify", phon: "['klærəfaɪ]", ger: "klären, klarstellen", ctx: "meaning: to make sth. clear(er)" },
    { id: "10_1_168", eng: "(to) rephrase", phon: "[ˌriː'freɪz]", ger: "umformulieren, anders ausdrücken", ctx: "Let me rephrase my point." },
    { id: "10_1_169", eng: "in other words", phon: "[ɪn 'ʌðə wɜːdz]", ger: "mit anderen Worten", ctx: "This project failed. In other words, it didn't give us the results." }
];