const e10u3_data = [
    { id: "10_3_1", eng: "gap", phon: "[ɡæp]", ger: "Lücke, Abstand", ctx: "gap year = Brückenjahr, ein Jahr Auszeit; gapper = junger Mensch im gap year" },
    { id: "10_3_2", eng: "au pair", phon: "[əʊ 'peə]", ger: "Au-pair-Mädchen/-Junge", ctx: "Want to live with a family in a foreign country? Become an au pair!" },
    { id: "10_3_3", eng: "(to) tidy (sth.) up", phon: "['taɪdi]", ger: "(etwas) aufräumen", ctx: "I can't find anything in my room... time to tidy up!" },
    { id: "10_3_4", eng: "(to) iron", phon: "['aɪən]", ger: "bügeln", ctx: "💡 Das 'r' wird nicht gesprochen! noun: iron = Bügeleisen/Eisen; do the ironing = bügeln" },
    { id: "10_3_5", eng: "(to) manage", phon: "['mænɪdʒ]", ger: "verwalten, regeln", ctx: "My brother is too young to manage his own money." },
    { id: "10_3_6", eng: "(to) budget", phon: "['bʌdʒɪt]", ger: "haushalten (sparsam sein)", ctx: "💡 noun: budget = Etat/Budget; adjective: budget = preisgünstig; on a budget = mit begrenztem Budget" },
    { id: "10_3_7", eng: "I run out of money.", phon: "[rʌn]", ger: "Mir geht das Geld aus. / Bei mir wird das Geld knapp.", ctx: "💡 (to) run out = knapp werden; Time is running out. / We're running out of time." },
    { id: "10_3_8", eng: "(to) overspend (on sth.), overspent, overspent", phon: "[ˌəʊvə'spend]", ger: "zu viel Geld ausgeben (für etwas)", ctx: "meaning: to spend too much money; opposite: (to) budget" },
    { id: "10_3_9", eng: "heating", phon: "['hiːtɪŋ]", ger: "Heizung", ctx: "noun: heat = Hitze; verb: (to) heat = erwärmen; adjective: hot" },
    { id: "10_3_10", eng: "Yippee!", phon: "[jɪ'piː]", ger: "Hurra!", ctx: "You say/shout 'Yippee!' when you're very pleased or excited." },
    { id: "10_3_11", eng: "I can't wait!", phon: "[weɪt]", ger: "Ich kann es kaum erwarten!", ctx: "I'm looking forward to my holiday. I can't wait to go!" },
    { id: "10_3_12", eng: "term", phon: "[tɜːm]", ger: "Trimester", ctx: "The school year in Britain has three terms." },
    { id: "10_3_13", eng: "(to) make up your mind", phon: "[maɪnd]", ger: "sich entscheiden, sich entschließen", ctx: "synonym: (to) make a decision" },
    { id: "10_3_14", eng: "placemat", phon: "['pleɪsmæt]", ger: "Platzdeckchen", ctx: "noun" },
    { id: "10_3_15", eng: "essential", phon: "[ɪ'senʃl]", ger: "(absolut) notwendig, wesentlich", ctx: "synonym: very important" },
    { id: "10_3_16", eng: "(to) assist (with)", phon: "[ə'sɪst]", ger: "assistieren, helfen (bei)", ctx: "💡 nouns: assistance = Hilfe/Unterstützung; assistant = Helfer/in, Verkäufer/in" },
    { id: "10_3_17", eng: "candidate", phon: "['kændɪdət]", ger: "Bewerber/in, Kandidat/in", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_3_18", eng: "(to) meet (requirements, qualifications, etc.)", phon: "[miːt]", ger: "(Voraussetzungen, Anforderungen) erfüllen, entsprechen", ctx: "💡 (to) meet = 1. Leute treffen; 2. Anforderungen erfüllen" },
    { id: "10_3_19", eng: "(to) list", phon: "[lɪst]", ger: "auflisten, aufzählen", ctx: "noun: list = Liste" },
    { id: "10_3_20", eng: "partly", phon: "['pɑːtli]", ger: "teilweise, teils", ctx: "What he said is only partly true. (noun: part)" },
    { id: "10_3_21", eng: "in order to", phon: "[ɪn 'ɔːdə tuː]", ger: "um ... zu", ctx: "We should go there early in order to get good seats." },
    { id: "10_3_22", eng: "resident", phon: "['rezɪdənt]", ger: "Anwohner/in, Bewohner/in", ctx: "a permanent resident = ein ständiger Einwohner" },
    { id: "10_3_23", eng: "valid", phon: "['vælɪd]", ger: "gültig; begründet, berechtigt", ctx: "a valid passport / valid excuses / a valid question" },
    { id: "10_3_24", eng: "(to) endanger", phon: "[ɪn'deɪndʒə]", ger: "bedrohen, gefährden", ctx: "meaning: to put sb./sth. in a dangerous situation" },
    { id: "10_3_25", eng: "clinic", phon: "['klɪnɪk]", ger: "Klinik; Ambulanz; Sprechstunde", ctx: "a place where you go or a period of time for special medical treatment" },
    { id: "10_3_26", eng: "hands-on", phon: "[hændz 'ɒn]", ger: "praktisch, praxisnah", ctx: "hands-on experience = praktische Erfahrung" },
    { id: "10_3_27", eng: "care", phon: "[keə]", ger: "Versorgung, Betreuung; Pflege", ctx: "💡 care = 1. Versorgung/Pflege (day care = Kindergarten); 2. Sorgfalt/Vorsicht" },
    { id: "10_3_28", eng: "construction", phon: "[kən'strʌkʃn]", ger: "Bau; Bauweise; Bauwerk, Konstruktion", ctx: "verb: (to) construct [kən'strʌkt] = (auf)bauen" },
    { id: "10_3_29", eng: "(to) immerse", phon: "[ɪ'mɜːs]", ger: "(ein)tauchen", ctx: "immerse yourself in sth. = sich in etwas vertiefen; adjective: immersive = umfassend" },
    { id: "10_3_30", eng: "(to) strengthen", phon: "['streŋkθn]", ger: "(ver)stärken; stärker werden", ctx: "meaning: to make sb./sth. stronger; noun: strength; adjective: strong" },
    { id: "10_3_31", eng: "(to) renovate", phon: "['renəveɪt]", ger: "renovieren, restaurieren", ctx: "💡 Betonung auf der 1. Silbe! noun: renovation [ˌrenə'veɪʃn]" },
    { id: "10_3_32", eng: "background", phon: "['bækɡraʊnd]", ger: "Herkunft; Hintergrund", ctx: "💡 background = 1. Herkunft (people of different backgrounds); 2. Hintergrund" },
    { id: "10_3_33", eng: "disadvantaged", phon: "[ˌdɪsəd'vɑːntɪdʒd]", ger: "benachteiligt", ctx: "disadvantaged children; noun: disadvantage = Nachteil" },
    { id: "10_3_34", eng: "valuable", phon: "['væljuəbl]", ger: "wertvoll", ctx: "noun: value = Wert; valuables (pl.) = Wertsachen" },
    { id: "10_3_35", eng: "(to) overcome, overcame, overcome", phon: "[ˌəʊvə'kʌm]", ger: "überwinden, besiegen; bewältigen, meistern (z. B. Problem)", ctx: "Find a way to overcome challenges!" },
    { id: "10_3_36", eng: "coastline", phon: "['kəʊstlaɪn]", ger: "Küste, Küstenlinie", ctx: "From the boat we could see the Irish coastline." },
    { id: "10_3_37", eng: "(to) hatch", phon: "[hætʃ]", ger: "ausbrüten; (aus)schlüpfen (z. B. Vogel-, Schildkrötenjunge)", ctx: "A baby chicken is hatching." },
    { id: "10_3_38", eng: "(to) educate sb.", phon: "['edʒuːkeɪt]", ger: "jn. ausblenden, unterrichten, erziehen", ctx: "noun: education; adjective: educational" },
    { id: "10_3_39", eng: "(to) be located in ...", phon: "[ləʊ'keɪtɪd]", ger: "in ... liegen, sich in ... befinden", ctx: "noun: location" },
    { id: "10_3_40", eng: "preparation", phon: "[ˌprepə'reɪʃn]", ger: "Vorbereitung; Zubereitung", ctx: "verb: (to) prepare (for)" },
    { id: "10_3_41", eng: "(to) serve", phon: "[sɜːv]", ger: "(Dienst) leisten; (z. B. Praktikum) absolvieren; servieren/bedienen", ctx: "💡 serve = 1. Dienst leisten / Praktikum absolvieren; 2. Essen servieren, bedienen" },
    { id: "10_3_42", eng: "ecological", phon: "[ˌiːkə'lɒdʒɪkl]", ger: "ökologisch", ctx: "noun: ecology [i'kɒlədʒi] = Ökologie" },
    { id: "10_3_43", eng: "mistake", phon: "[mɪ'steɪk]", ger: "Fehler", ctx: "💡 phrase: by mistake = aus Versehen (I took it by mistake.)" },
    { id: "10_3_44", eng: "understandable", phon: "[ˌʌndə'stændəbl]", ger: "verständlich", ctx: "meaning: easy to understand" },
    { id: "10_3_45", eng: "besides", phon: "[bɪ'saɪdz]", ger: "außer; außerdem", ctx: "💡 preposition: besides (außer); adverb: besides (außerdem - And besides, I've seen it.)" },
    { id: "10_3_46", eng: "(to) be prepared to do sth.", phon: "[prɪ'peəd]", ger: "bereit sein, etwas zu tun", ctx: "synonym: (to) be ready to do sth." },
    { id: "10_3_47", eng: "(to) take a year out (pl. years out)", phon: "[teɪk]", ger: "ein Jahr Auszeit nehmen", ctx: "Do you want to go straight to university or take a year out?" },
    { id: "10_3_48", eng: "work placement", phon: "['wɜːk ˌpleɪsmənt]", ger: "Praktikum", ctx: "synonyms: work experience, internship; placement = Unterbringung" },
    { id: "10_3_49", eng: "(to) transcribe", phon: "[træn'skraɪb]", ger: "niederschreiben, aufschreiben; transkribieren", ctx: "noun: transcript ['trænskrɪpt] = Niederschrift, Protokoll" },
    { id: "10_3_50", eng: "(to) clean sth. up", phon: "[kliːn]", ger: "etwas aufräumen, sauber machen", ctx: "noun: clean-up = Säuberung (A clean-up of our oceans)" },
    { id: "10_3_51", eng: "(to) restore", phon: "[rɪ'stɔː]", ger: "wiederherstellen", ctx: "She's restoring an old chair." },
    { id: "10_3_52", eng: "meaningful", phon: "['miːnɪŋfl]", ger: "wichtig; bedeutend; bedeutsam; aussagekräftig", ctx: "meaningful example / message / statistics" },
    { id: "10_3_53", eng: "relevant (to sb.)", phon: "['reləvənt]", ger: "relevant, wichtig (für jn.)", ctx: "💡 Betonung auf der 1. Silbe! opposite: irrelevant" },
    { id: "10_3_54", eng: "(to) transition ((in)to) sth.", phon: "[træn'zɪʃn]", ger: "übergehen (in/zu etwas); (sich) umstellen (auf etwas); das Geschlecht wechseln", ctx: "noun: transition = Übergang" },
    { id: "10_3_55", eng: "uni", phon: "['juːni]", ger: "Uni(versität)", ctx: "informal; short for university" },
    { id: "10_3_56", eng: "worth", phon: "[wɜːθ]", ger: "wert", ctx: "💡 structure: It was worth it. / The film is worth watching. (Es lohnt sich, ihn anzuschauen.)" },
    { id: "10_3_57", eng: "confidence", phon: "['kɒnfɪdəns]", ger: "(Selbst-)Vertrauen, Zuversicht", ctx: "adjective: confident" },
    { id: "10_3_58", eng: "down under", phon: "[daʊn 'ʌndə]", ger: "umgangssprachlicher Name für Australien und Neuseeland", ctx: "informal word" },
    { id: "10_3_59", eng: "visa", phon: "['viːzə]", ger: "Visum", ctx: "💡 plural English: visas vs. German: Visa / Ein Visum – zwei Visa" },
    { id: "10_3_60", eng: "... though.", phon: "[ðəʊ]", ger: "... allerdings ...", ctx: "💡 Das Adverb stands always at the end of the sentence: She isn't French though." },
    { id: "10_3_61", eng: "gardener", phon: "['ɡɑːdnə]", ger: "Gärtner/in", ctx: "landscape gardener = Landschaftsgärtner/in" },
    { id: "10_3_62", eng: "trek", phon: "[trek]", ger: "Wanderung; Wanderritt", ctx: "going on a horse trek" },
    { id: "10_3_63", eng: "resort", phon: "[rɪ'zɔːt]", ger: "Urlaubsort", ctx: "e.g., a ski resort, a seaside resort" },
    { id: "10_3_64", eng: "on offer", phon: "[ɒfə]", ger: "im Angebot", ctx: "There are several different programmes on offer." },
    { id: "10_3_65", eng: "laneway", phon: "['leɪnweɪ]", ger: "Gässchen", ctx: "Australian English (AustE); e.g., in Melbourne's laneways" },
    { id: "10_3_66", eng: "(to) note", phon: "[nəʊt]", ger: "beachten; (sich etwas) notieren", ctx: "note sth. down = aufschreiben; noun: note = Notiz, Hinweis" },
    { id: "10_3_67", eng: "(to) store", phon: "[stɔː]", ger: "aufbewahren, lagern; speichern", ctx: "nouns: store = Geschäft/Lager; storage ['stɔːrɪdʒ] = Aufbewahrung/Speicherplatz" },
    { id: "10_3_68", eng: "dormitory", phon: "['dɔːmɪtri]", ger: "Schlafsaal", ctx: "informal short form: dorm" },
    { id: "10_3_69", eng: "double room", phon: "[dabl 'ruːm]", ger: "Doppelzimmer", ctx: "informal short form: double; single room (Einzel-), twin room (Zwei-Bett-)" },
    { id: "10_3_70", eng: "en suite", phon: "[ɒ̃ 'swiːt]", ger: "mit eigenem Bad", ctx: "an en suite single room / a room with en suite bathroom" },
    { id: "10_3_71", eng: "(to) stock sth. (with sth.)", phon: "[stɒk]", ger: "etwas (mit etwas) ausstatten", ctx: "fully stocked kitchen; noun: stock = Vorrat, (Waren-)Bestand" },
    { id: "10_3_72", eng: "common room", phon: "['kɒmən ruːm]", ger: "Aufenthaltsraum", ctx: "a room shared by people who live together in a house or hostel" },
    { id: "10_3_73", eng: "pool", phon: "[puːl]", ger: "Poolbillard; (Schwimm-)Bad; Becken", ctx: "💡 pool = 1. Poolbillard; 2. Schwimmbad; 3. Wasserbecken" },
    { id: "10_3_74", eng: "block", phon: "[blɒk]", ger: "Wohnblock", ctx: "two blocks from here = zwei Blocks weit weg; block of flats = Mehrfamilienhaus" },
    { id: "10_3_75", eng: "(to) take advantage of sth.", phon: "[əd'vɑːntɪdʒ]", ger: "sich etwas zunutze machen, etwas (aus)nutzen", ctx: "take advantage of the huge crowds / take advantage of every bit of space" },
    { id: "10_3_76", eng: "agency", phon: "['eɪdʒənsi]", ger: "Agentur, Organisation", ctx: "An employment agency helps people to find work." },
    { id: "10_3_77", eng: "(to) depend on", phon: "[dɪ'pend]", ger: "abhängen von", ctx: "It depends. = Es kommt darauf an. / depending on the weather = je nach Wetter" },
    { id: "10_3_78", eng: "(to) accept", phon: "[ək'sept]", ger: "akzeptieren, annehmen", ctx: "accept the invitation; opposite: unacceptable = inakzeptabel" },
    { id: "10_3_79", eng: "return (ticket/flight)", phon: "[rɪ'tɜːn]", ger: "(Hin- und) Rückfahrkarte, (Hin- und) Rückflugticket", ctx: "opposite: one-way ticket / one-way flight" },
    { id: "10_3_80", eng: "(to) consider sb./sth. (to be) sth.", phon: "[kən'sɪdə]", ger: "jn./etwas halten für etwas, jn./etwas betrachten als etwas", ctx: "Everyone considers her (to be) a computer expert." },
    { id: "10_3_81", eng: "trade-off (between ...)", phon: "['treɪd ɒf]", ger: "Kompromiss (zwischen ...); (Kosten-Nutzen-)Abwägung", ctx: "a good trade-off between cost and quality" },
    { id: "10_3_82", eng: "up to", phon: "[ʌp tuː]", ger: "bis (zu)", ctx: "meaning: until; no more than" },
    { id: "10_3_83", eng: "housecleaning", phon: "['haʊskliːnɪŋ]", ger: "Saubermachen/Reinemachen im Haus", ctx: "meaning: cleaning a/the house" },
    { id: "10_3_84", eng: "literally", phon: "['lɪtərəli]", ger: "wörtlich; im Wortsinn; buchstäblich", ctx: "You shouldn't translate idioms literally. / literally hundreds of programmes" },
    { id: "10_3_85", eng: "(to) be on a par with sb./sth.", phon: "[pɑː]", ger: "mit jm./etwas auf einer Stufe stehen, vergleichbar sein", ctx: "meaning: to be as good, important, etc. as somebody/something else" },
    { id: "10_3_86", eng: "(to) be on good/friendly/bad/... terms with sb.", phon: "[tɜːmz]", ger: "mit jm. auf gutem, freundschaftlichem, schlechtem etc. Fuß stehen", ctx: "💡 on equal terms (with sb.) = gleichgestellt, auf Augenhöhe (mit jm.)" },
    { id: "10_3_87", eng: "expectation", phon: "[ˌekspek'teɪʃn]", ger: "Erwartung", ctx: "verb: (to) expect" },
    { id: "10_3_88", eng: "precise", phon: "[prɪ'saɪs]", ger: "genau, präzise", ctx: "synonym: exact; noun: precision [prɪ'sɪʒn] = Genauigkeit" },
    { id: "10_3_89", eng: "additional", phon: "[ə'dɪʃənl]", ger: "zusätzliche(r, s)", ctx: "I'd like some additional information." },
    { id: "10_3_90", eng: "(to) go round", phon: "[ɡəʊ raʊnd]", ger: "sich drehen, im Kreis gehen/fahren", ctx: "synonym: (to) rotate" },
    { id: "10_3_91", eng: "(to) slide, slid, slid", phon: "[slaɪd], [slɪd]", ger: "schieben; rutschen; gleiten (lassen)", ctx: "I slid down the rock into the river." },
    { id: "10_3_92", eng: "narrow", phon: "['nærəʊ]", ger: "eng, schmal", ctx: "opposite: wide" },
    { id: "10_3_93", eng: "(to) give sb. a hand", phon: "[ɡɪv]", ger: "jm. behilflich sein", ctx: "meaning: to help sb. (Can you give me a hand with these heavy boxes?)" },
    { id: "10_3_94", eng: "(to) wheel", phon: "[wiːl]", ger: "fahren; schieben; ziehen", ctx: "I wheeled grandad up the hill. / noun: wheel = Rad" },
    { id: "10_3_95", eng: "sour", phon: "['saʊə]", ger: "sauer, säuerlich; griesgrämig, verdrießlich", ctx: "Lemons taste sour." },
    { id: "10_3_96", eng: "(to) skip", phon: "[skɪp]", ger: "überspringen, auslassen", ctx: "I skipped the introduction because it was too long." },
    { id: "10_3_97", eng: "enthusiastic (about)", phon: "[ɪnˌθjuːzi'æstɪk]", ger: "begeistert (von)", ctx: "Jack is enthusiastic about cooking. / adverb: enthusiastically" },
    { id: "10_3_98", eng: "enthusiasm", phon: "[ɪn'θjuːziæzm]", ger: "Begeisterung, Enthusiasmus", ctx: "Jack's enthusiasm for cooking is amazing." },
    { id: "10_3_99", eng: "(to) walk sb. somewhere", phon: "[wɔːk]", ger: "jn. irgendwohin begleiten/führen (zu Fuß)", ctx: "💡 walk sb. through sth. = etwas mit jm. Schritt für Schritt durchgehen" },
    { id: "10_3_100", eng: "Damn!", phon: "[dæm]", ger: "Verdammt!", ctx: "Oh damn! I've forgotten my bag at home." },
    { id: "10_3_101", eng: "warehouse", phon: "['weəhaʊs]", ger: "Lager(haus)", ctx: "noun (often combined with safety vest, hard hat, clipboard)" },
    { id: "10_3_102", eng: "safety vest", phon: "['seɪfti vest]", ger: "Sicherheitsweste, Warnweste", ctx: "noun phrase" },
    { id: "10_3_103", eng: "hard hat", phon: "[hɑːd hæt]", ger: "Schutzhelm", ctx: "noun phrase" },
    { id: "10_3_104", eng: "clipboard", phon: "['klɪpbɔːd]", ger: "Klemmbrett", ctx: "noun" },
    { id: "10_3_105", eng: "logistics", phon: "[lə'dʒɪstɪks]", ger: "Logistik", ctx: "💡 The word is uncountable but can use singular or plural verbs: Logistics is/are important." },
    { id: "10_3_106", eng: "No idea.", phon: "[aɪ'dɪə]", ger: "Keine Ahnung.", ctx: "informal phrase (Do you know where it is? – No idea, sorry.)" },
    { id: "10_3_107", eng: "(to) slump", phon: "[slʌmp]", ger: "fallen; sinken", ctx: "(to) slump down (in your chair) = sich in den Sessel/auf den Stuhl fallen lassen" },
    { id: "10_3_108", eng: "dodo", phon: "['dəʊdəʊ]", ger: "Dodo (ausgestorbener Vogel); Dummkopf", ctx: "💡 plural: dodos; But dodo can also mean 'idiot'." },
    { id: "10_3_109", eng: "(to) bet, bet, bet", phon: "[bet]", ger: "wetten", ctx: "I bet you'll enjoy your holiday!" },
    { id: "10_3_110", eng: "hard-working", phon: "[hɑːd 'wɜːkɪŋ]", ger: "fleißig", ctx: "meaning: working a lot and trying to do your job well" },
    { id: "10_3_111", eng: "(to) boom", phon: "[buːm]", ger: "dröhnen, donnern (auch z. B. Stimme)", ctx: "I heard thunder booming outside. / a booming voice = eine laute, tiefe Stimme" },
    { id: "10_3_112", eng: "(to) startle sb.", phon: "['stɑːtl]", ger: "jn. erschrecken, aufschrecken", ctx: "The loud noise startled me. (= was very sudden and shocked me)" },
    { id: "10_3_113", eng: "slight", phon: "[slaɪt]", ger: "leicht, gering(fügig)", ctx: "a slight difference / adverb: slightly (slightly more expensive)" },
    { id: "10_3_114", eng: "It's not rocket science.", phon: "['rɒkɪt ˌsaɪəns]", ger: "Das ist keine Hexerei. / Das ist nicht so kompliziert.", ctx: "idiomatic phrase" },
    { id: "10_3_115", eng: "She's worth her weight in gold.", phon: "[wɜːθ]", ger: "Sie ist Gold wert. / Sie ist nicht mit Gold zu bezahlen.", ctx: "meaning: She is very valuable / does her job very well." },
    { id: "10_3_116", eng: "loving", phon: "['lʌvɪŋ]", ger: "liebevoll", ctx: "meaning: feeling or showing love for sb. or sth." },
    { id: "10_3_117", eng: "(to) manoeuvre", phon: "[mə'nuːvə]", ger: "manövrieren, steuern", ctx: "💡 AE spelling: maneuver; pronounced [mə'nuːvə]; noun: manoeuvre = Manöver" },
    { id: "10_3_118", eng: "Shall I ...?", phon: "[ʃæl]", ger: "Soll ich ...?", ctx: "It's hot in here. Shall I open the window?" },
    { id: "10_3_119", eng: "(to) extend", phon: "[ɪk'stend]", ger: "ausstrecken (z.B. Hand); sich erstrecken; (sich) ausdehnen", ctx: "extended a hand / an extended holiday = ein ausgedehnter Urlaub" },
    { id: "10_3_120", eng: "I've got it.", phon: "[ɡɒt]", ger: "Ich hab's (schon). / Ich hab's schon geschafft/hinbekommen.", ctx: "meaning: It's OK, I can manage." },
    { id: "10_3_121", eng: "downtown (Vancouver)", phon: "[daʊn'taʊn]", ger: "(das/im/ins) Stadtzentrum von Vancouver", ctx: "American English (AE); British English equivalent: (in) the centre of Vancouver" },
    { id: "10_3_122", eng: "sheepish", phon: "['ʃiːpɪʃ]", ger: "verlegen, betreten", ctx: "the way you look when you are embarrassed because you have done something silly" },
    { id: "10_3_123", eng: "(to) shuffle", phon: "['ʃʌfl]", ger: "(ver)schieben, anders anordnen; (Jobs) umbesetzen", ctx: "💡 shuffle = 1. verschieben/ Jobs umbesetzen; 2. schlürfen/ mit den Füßen scharren" },
    { id: "10_3_124", eng: "(to) accommodate", phon: "[ə'kɒmədeɪt]", ger: "Platz bieten für; unterbringen, beherbergen", ctx: "noun: accommodation = Unterbringung" },
    { id: "10_3_125", eng: "(to) make a fuss (of/over)", phon: "[fʌs]", ger: "Theater/Wirbel machen (wegen)", ctx: "Stop making such a fuss! / noun: fuss (about) = Theater machen, sich aufregen" },
    { id: "10_3_126", eng: "sleek", phon: "[sliːk]", ger: "elegant; (Auto) schnittig; glatt, (seidig) glänzend, geschmeidig", ctx: "e.g., sleek hair" },
    { id: "10_3_127", eng: "weird", phon: "[wɪəd]", ger: "seltsam, komisch", ctx: "synonym: strange (I had a weird feeling.)" },
    { id: "10_3_128", eng: "(to) ship", phon: "[ʃɪp]", ger: "(aus)liefern, versenden", ctx: "ship with sb. = jn. mit der Auslieferung beauftragen; noun: ship = Schiff" },
    { id: "10_3_129", eng: "honey", phon: "['hʌni]", ger: "Honig; (als Anrede:) Schatz, Schätzchen", ctx: "Bees make honey. / Don't worry, honey." },
    { id: "10_3_130", eng: "degree", phon: "[dɪ'ɡriː]", ger: "Universitätsabschluss, Diplom", ctx: "💡 degree = 1. Universitätsabschluss; 2. Grad (auch bei Temperatur)" },
    { id: "10_3_131", eng: "pose", phon: "[pəʊz]", ger: "Stellung; Haltung; Pose", ctx: "This yoga pose is called the camel." },
    { id: "10_3_132", eng: "(to) straighten sth. (out)", phon: "['streɪtn]", ger: "etwas gerade machen", ctx: "straighten (out) = gerade werden; straighten (up) = sich aufrichten; adj/adv: straight" },
    { id: "10_3_133", eng: "silent", phon: "['saɪlənt]", ger: "still, lautlos", ctx: "fall/go silent = still werden, verstummen; noun: silence" },
    { id: "10_3_134", eng: "glow", phon: "[ɡləʊ]", ger: "Schein (z. B. eines Feuers); (das) Leuchten", ctx: "verb: (to) glow = glühen, leuchten, strahlen" },
    { id: "10_3_135", eng: "distant", phon: "['dɪstənt]", ger: "(weit) entfernt, fern", ctx: "in the distant past = in der fernen Vergangenheit; noun: distance" },
    { id: "10_3_136", eng: "surf", phon: "[s3ːf]", ger: "Brandung", ctx: "noun" },
    { id: "10_3_137", eng: "timeless", phon: "['taɪmləs]", ger: "zeitlos", ctx: "💡 Adjective built with -less suffix meaning '-los'" },
    { id: "10_3_138", eng: "boneless", phon: "['bəʊnləs]", ger: "knochenlos", ctx: "built with -less suffix" },
    { id: "10_3_139", eng: "endless", phon: "['endləs]", ger: "endlos", ctx: "built with -less suffix" },
    { id: "10_3_140", eng: "flightless", phon: "['flaɪtləs]", ger: "flugunfähig", ctx: "built with -less suffix" },
    { id: "10_3_141", eng: "friendless", phon: "['frendləs]", ger: "ohne Freunde", ctx: "built with -less suffix" },
    { id: "10_3_142", eng: "helpless", phon: "['helpləs]", ger: "hilflos", ctx: "built with -less suffix" },
    { id: "10_3_143", eng: "homeless", phon: "['həʊmləs]", ger: "obdachlos", ctx: "built with -less suffix" },
    { id: "10_3_144", eng: "hopeless", phon: "['həʊpləs]", ger: "hoffnungslos", ctx: "built with -less suffix" },
    { id: "10_3_145", eng: "jobless", phon: "['dʒɒbləs]", ger: "arbeitslos", ctx: "built with -less suffix" },
    { id: "10_3_146", eng: "sleepless", phon: "['sliːpləs]", ger: "schlaflos", ctx: "built with -less suffix" },
    { id: "10_3_147", eng: "thoughtless", phon: "['θɔːtləs]", ger: "gedankenlos", ctx: "built with -less suffix" },
    { id: "10_3_148", eng: "useless", phon: "['juːsləs]", ger: "unnütz, nutzlos", ctx: "built with -less suffix" },
    { id: "10_3_149", eng: "(to) hug (sb.)", phon: "[hʌɡ]", ger: "(jn.) umarmen; einander umarmen", ctx: "They're hugging each other. / noun: hug = Umarmung" },
    { id: "10_3_150", eng: "(to) fall over", phon: "[fɔːl]", ger: "hinfallen, umkippen", ctx: "I slipped on the snow and fell over." },
    { id: "10_3_151", eng: "anecdote", phon: "['ænɪkdəʊt]", ger: "Anekdote; Geschichte, persönlicher Bericht", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "10_3_152", eng: "exercise (no pl.)", phon: "['eksəsaɪz]", ger: "Bewegung (sportliche Aktivität)", ctx: "💡 exercise = 1. Übung; 2. Bewegung; (to) do/take exercise = sich Bewegung verschaffen" },
    { id: "10_3_153", eng: "(to) shove", phon: "[ʃʌv]", ger: "stopfen; stoßen; schieben, drängeln", ctx: "noun: shove = Stoß, Schubs" },
    { id: "10_3_154", eng: "work out", phon: "[wɜːk 'aʊt]", ger: "funktionieren, klappen", ctx: "Luckily everything worked out well." },
    { id: "10_3_155", eng: "(to) get lucky", phon: "[ɡet]", ger: "Glück haben", ctx: "meaning: to have good luck" },
    { id: "10_3_156", eng: "It pays to have ....", phon: "[peɪz]", ger: "Es zahlt sich aus, wenn man ... hat.", ctx: "It pays to get a good education." },
    { id: "10_3_157", eng: "There you go.", phon: "[ðeə juː ɡəʊ]", ger: "Da hast du's! / Na siehst du! / Hier, bitte schön.", ctx: "💡 There you go! = Na siehst du! / There you are. = Hier, bitte schön." },
    { id: "10_3_158", eng: "(to) get a taste (of sth.)", phon: "[teɪst]", ger: "(in etwas) hineinschnuppern", ctx: "informal (During my internship I got a first taste of work in a zoo.)" },
    { id: "10_3_159", eng: "nerd", phon: "[nɜːd]", ger: "Nerd (hochintelligente, aber kontaktarme Person)", ctx: "adjective: nerdy ['nɜːdi] = absonderlich, streberhaft; be nerdy = ein Nerd sein" },
    { id: "10_3_160", eng: "(to) sink, sank, sunk", phon: "[sɪŋk], [sæŋk], [sʌŋk]", ger: "sinken", ctx: "The ship is sinking." },
    { id: "10_3_161", eng: "yep", phon: "[jep]", ger: "ja", ctx: "informal for yes" },
    { id: "10_3_162", eng: "pretty cool/old/expensive/...", phon: "['prɪti]", ger: "ziemlich cool/alt/teuer/...", ctx: "💡 pretty = 1. (adjective) hübsch; 2. (adverb) ziemlich (pretty expensive)" },
    { id: "10_3_163", eng: "flat", phon: "[flæt]", ger: "flach, eben; (Stimme) tonlos", ctx: "💡 flat = 1. flach/eben; 2. tonlos (Stimme); 3. BE: Wohnung" },
    { id: "10_3_164", eng: "(to) poke", phon: "[pəʊk]", ger: "stoßen, stechen", ctx: "She poked me with her elbow." },
    { id: "10_3_165", eng: "moon", phon: "[muːn]", ger: "Mond", ctx: "💡 phrase: be over the moon = ganz aus dem Häuschen sein / hocherfreut sein" }
];