// Vocabulary Data for Grade 5 - Unit 0
// Sources referenced: Bildschirmfoto 2026-06-27 um 22.50.55.jpg, Bildschirmfoto 2026-06-27 um 22.51.11.jpg, Bildschirmfoto 2026-06-27 um 22.51.25.jpg

const e5u0_data = [
    // --- Page 1 (Bildschirmfoto 2026-06-27 um 22.50.55.jpg) ---
    { eng: "Let's go!", ger: "Auf geht's! / Dann mal los!", ctx: "Let's start!" },
    { eng: "let's", ger: "lass uns / lasst uns", ctx: "short for: let us" },
    { eng: "(to) go", ger: "gehen, fahren", ctx: "verb" },
    { eng: "(to) meet", ger: "kennenlernen; (sich) treffen", ctx: "verb" },
    { eng: "kid", ger: "Kind, Jugendliche/-r", ctx: "one kid - two kids" },
    { eng: "Hi.", ger: "Hallo.", ctx: "friendly greeting" },
    { eng: "I'm", ger: "ich bin", ctx: "short for: I am" },
    { eng: "from", ger: "aus", ctx: "e.g., from Plymouth" },
    { eng: "one", ger: "eins", ctx: "Number 1" },
    { eng: "two", ger: "zwei", ctx: "Number 2" },
    { eng: "three", ger: "drei", ctx: "Number 3" },
    { eng: "four", ger: "vier", ctx: "Number 4" },
    { eng: "five", ger: "fünf", ctx: "Number 5" },
    { eng: "six", ger: "sechs", ctx: "Number 6" },
    { eng: "seven", ger: "sieben", ctx: "Number 7" },
    { eng: "eight", ger: "acht", ctx: "Number 8" },
    { eng: "nine", ger: "neun", ctx: "Number 9" },
    { eng: "ten", ger: "zehn", ctx: "Number 10" },
    { eng: "eleven", ger: "elf", ctx: "Number 11" },
    { eng: "twelve", ger: "zwölf", ctx: "Number 12" },
    { eng: "thirteen", ger: "dreizehn", ctx: "Number 13" },
    { eng: "fourteen", ger: "vierzehn", ctx: "Number 14" },
    { eng: "fifteen", ger: "fünfzehn", ctx: "Number 15" },
    { eng: "in England", ger: "in England", ctx: "place" },
    { eng: "my", ger: "mein / meine", ctx: "possessive pronoun" },
    { eng: "dad", ger: "Papa, Vati", ctx: "family" },
    { eng: "the USA", ger: "die USA (die Vereinigten Staaten von Amerika)", ctx: "country" },
    { eng: "Hello.", ger: "Hallo.", ctx: "greeting" },
    { eng: "name", ger: "Name", ctx: "What's your name?" },
    { eng: "mum", ger: "Mama, Mutti", ctx: "family" },
    { eng: "and", ger: "und", ctx: "linking word" },
    { eng: "China", ger: "China", ctx: "country" },
    { eng: "What's your name?", ger: "Wie heißt du?", ctx: "Question" },
    { eng: "what?", ger: "was?", ctx: "Question word" },
    { eng: "your", ger: "dein/e; euer/eure; Ihr/e", ctx: "possessive" },
    { eng: "Poland", ger: "Polen", ctx: "country" },
    { eng: "How old are you?", ger: "Wie alt bist du?", ctx: "Question" },
    { eng: "you're", ger: "du bist; ihr seid; Sie sind", ctx: "short for: you are" },
    { eng: "Where are you from?", ger: "Wo kommst du her?", ctx: "Question" },

    // --- Page 2 (Bildschirmfoto 2026-06-27 um 22.51.11.jpg) ---
    { eng: "where?", ger: "wo? / wohin?", ctx: "Question word" },
    { eng: "Nice to meet you.", ger: "Freut mich, dich/euch/Sie kennenzulernen.", ctx: "Phrase" },
    { eng: "nice", ger: "nett, schön", ctx: "adjective" },
    { eng: "Germany", ger: "Deutschland", ctx: "country (Always capitalized!)" },
    { eng: "Turkey", ger: "(die) Türkei", ctx: "country" },
    { eng: "crab", ger: "Krebs", ctx: "animal" },
    { eng: "town", ger: "Stadt", ctx: "in town = in der Stadt" },
    { eng: "great", ger: "toll, großartig", ctx: "adjective" },
    { eng: "place", ger: "Ort, Platz", ctx: "noun" },
    { eng: "swimming pool", ger: "Schwimmbad", ctx: "place" },
    { eng: "aquarium", ger: "Aquarium", ctx: "place" },
    { eng: "sea", ger: "Meer, (die) See", ctx: "nature" },
    { eng: "now", ger: "nun, jetzt", ctx: "time" },
    { eng: "favourite place", ger: "Lieblingsort", ctx: "Plymouth is my favourite town." },
    { eng: "it's", ger: "es ist", ctx: "short for: it is" },
    { eng: "very", ger: "sehr", ctx: "e.g., very popular" },
    { eng: "popular", ger: "beliebt, populär", ctx: "adjective" },
    { eng: "classroom", ger: "Klassenraum", ctx: "school" },
    { eng: "thing", ger: "Ding, Sache", ctx: "noun" },
    { eng: "I can see ...", ger: "ich kann ... sehen", ctx: "phrase" },
    { eng: "can", ger: "können", ctx: "verb" },
    { eng: "window", ger: "Fenster", ctx: "classroom / house" },
    { eng: "girl", ger: "Mädchen", ctx: "person" },
    { eng: "boy", ger: "Junge, Bub", ctx: "person" },
    { eng: "teacher", ger: "Lehrer/in", ctx: "school" },
    { eng: "desk", ger: "Schreibtisch, Schülertisch", ctx: "school furniture" },
    { eng: "chair", ger: "Stuhl", ctx: "furniture" },
    { eng: "board", ger: "Tafel", ctx: "school" },
    { eng: "door", ger: "Tür", ctx: "classroom" },
    { eng: "clock", ger: "(Wand-, Stand-, Turm-)Uhr", ctx: "noun" },
    { eng: "different", ger: "verschieden; anders", ctx: "six different colours" },

    // --- Page 3 (Bildschirmfoto 2026-06-27 um 22.51.25.jpg) ---
    { eng: "colour", ger: "Farbe", ctx: "What colour is...?" },
    { eng: "red", ger: "rot", ctx: "colour" },
    { eng: "yellow", ger: "gelb", ctx: "colour" },
    { eng: "blue", ger: "blau", ctx: "colour" },
    { eng: "green", ger: "grün", ctx: "colour" },
    { eng: "brown", ger: "braun", ctx: "colour" },
    { eng: "orange", ger: "orange", ctx: "colour" },
    { eng: "grey", ger: "grau", ctx: "colour" },
    { eng: "pink", ger: "pink, rosa", ctx: "colour" },
    { eng: "purple", ger: "violett, lila", ctx: "colour" },
    { eng: "white", ger: "weiß", ctx: "colour" },
    { eng: "black", ger: "schwarz", ctx: "colour" },
    { eng: "in my picture", ger: "auf meinem Bild", ctx: "phrase" },
    { eng: "a door", ger: "eine Tür", ctx: "article 'a' before consonants" },
    { eng: "an orange door", ger: "eine orangefarbene Tür", ctx: "article 'an' before vowels" },
    { eng: "that's", ger: "das (da) ist", ctx: "short for: that is" },
    { eng: "the same", ger: "gleich; derselbe/dieselbe/dasselbe", ctx: "we are in the same classroom" },
    { eng: "schoolbag", ger: "Schultasche", ctx: "school item" },
    { eng: "book", ger: "Buch", ctx: "school item" },
    { eng: "exercise book", ger: "(Schul-)Heft", ctx: "school item" },
    { eng: "pen", ger: "Kugelschreiber, Stift, Füller", ctx: "writing item" },
    { eng: "pencil", ger: "Bleistift", ctx: "writing item" },
    { eng: "pencil case", ger: "Federmäppchen", ctx: "school item" },
    { eng: "pencil sharpener", ger: "(Bleistift-)Spitzer", ctx: "school item" },
    { eng: "rubber", ger: "Radiergummi", ctx: "school item" },
    { eng: "ruler", ger: "Lineal", ctx: "school item" },
    { eng: "(to) borrow", ger: "(aus)leihen, sich borgen", ctx: "verb" },
    { eng: "yes", ger: "ja", ctx: "opposite of no" },
    { eng: "Here you are.", ger: "Bitte schön. / Hier, bitte.", ctx: "When giving something to someone" },
    { eng: "no", ger: "nein", ctx: "opposite of yes" },
    { eng: "Sorry. / I'm sorry.", ger: "Tut mir leid. / Entschuldigung.", ctx: "phrase" },
    { eng: "thank you / thanks", ger: "danke (schön)", ctx: "phrase" },
    { eng: "I'm late.", ger: "Ich habe mich verspätet.", ctx: "phrase" },
    { eng: "in English", ger: "auf Englisch", ctx: "What's this in English?" },
    { eng: "English", ger: "Englisch; englisch", ctx: "language / subject" },
    { eng: "to", ger: "zu, nach", ctx: "preposition" },
    { eng: "toilet", ger: "Toiletette", ctx: "noun" },
    { eng: "I don't understand ...", ger: "ich verstehe ... nicht", ctx: "phrase" },
    { eng: "(to) understand", ger: "verstehen", ctx: "verb" },
    { eng: "activity", ger: "Aktivität, Tätigkeit", ctx: "noun" }
];