// Vocabulary Data for Grade 5 - Unit 1
// Sources referenced: Bildschirmfoto 2026-06-27 um 22.54.55.jpg to 22.55.58.jpg

const e5u1_data = [
    // --- Page 1 (Bildschirmfoto 2026-06-27 um 22.54.55.jpg) ---
    { eng: "our", ger: "unser / unsere", ctx: "e.g., our class" },
    { eng: "first", ger: "erste(-r, -s)", ctx: "opposite of last" },
    { eng: "day", ger: "Tag", ctx: "noun" },
    { eng: "at", ger: "an; in; bei; auf", ctx: "preposition (e.g., at school)" },
    { eng: "school", ger: "Schule", ctx: "place" },
    { eng: "the name of the school", ger: "der Name der Schule", ctx: "phrase" },
    { eng: "uniform", ger: "Uniform", ctx: "a uniform" },
    { eng: "who", ger: "wer", ctx: "question word" },
    { eng: "new", ger: "neu", ctx: "opposite of old" },
    { eng: "student", ger: "Schüler/-in; Student/-in", ctx: "person at school" },
    { eng: "friend", ger: "Freund/-in", ctx: "noun" },
    { eng: "big", ger: "groß", ctx: "opposite of small" },
    { eng: "small", ger: "klein", ctx: "opposite of big" },
    { eng: "I'm fine. / Li is fine.", ger: "Mir geht es gut. / Li geht es gut.", ctx: "phrase" },
    { eng: "fine", ger: "gut, in Ordnung; schön", ctx: "a fine day" },
    { eng: "OK", ger: "okay, gut, in Ordnung", ctx: "adjective" },
    { eng: "boring", ger: "langweilig", ctx: "opposite of exciting" },
    { eng: "hair", ger: "Haar, Haare", ctx: "uncountable: Your hair is black." },
    { eng: "horrible", ger: "schrecklich", ctx: "adjective" },
    { eng: "Welcome to ...", ger: "Willkommen in/an ...", ctx: "greeting" },
    { eng: "community college", ger: "weiterführende Schule mit gymnasialer Oberstufe", ctx: "school system (BE)" },
    { eng: "How are you?", ger: "Wie geht's? / Wie geht es dir/euch/Ihnen?", ctx: "question" },
    { eng: "What about you?", ger: "Und du? / Was ist mit dir?", ctx: "question" },
    { eng: "(to) like", ger: "mögen", ctx: "verb" },
    { eng: "word", ger: "Wort", ctx: "noun" },

    // --- Page 2 (Bildschirmfoto 2026-06-27 um 22.55.06.jpg) ---
    { eng: "Mr Taylor", ger: "Herr Taylor", ctx: "title for men" },
    { eng: "Mr Taylor's favourite subject", ger: "Herr Taylors Lieblingsfach", ctx: "phrase" },
    { eng: "subject", ger: "(Schul-)Fach", ctx: "noun" },
    { eng: "before", ger: "bevor; vor (zeitlich)", ctx: "before the lesson" },
    { eng: "(to) read", ger: "lesen", ctx: "verb" },
    { eng: "Monday", ger: "Montag", ctx: "day of the week" },
    { eng: "Tuesday", ger: "Dienstag", ctx: "day of the week" },
    { eng: "Wednesday", ger: "Mittwoch", ctx: "day of the week" },
    { eng: "Thursday", ger: "Donnerstag", ctx: "day of the week" },
    { eng: "Friday", ger: "Freitag", ctx: "day of the week" },
    { eng: "Saturday", ger: "Samstag", ctx: "day of the week" },
    { eng: "Sunday", ger: "Sonntag", ctx: "day of the week" },
    { eng: "morning", ger: "Morgen", ctx: "time of day" },
    { eng: "registration", ger: "Anwesenheitskontrolle und Ankündigung aktueller Ereignisse vor dem Unterricht", ctx: "school routine" },
    { eng: "for", ger: "für", ctx: "preposition" },
    { eng: "class", ger: "Klasse; Unterricht; Kurs", ctx: "plural: classes" },
    { eng: "she's", ger: "sie ist", ctx: "short for: she is" },
    { eng: "I'm not ...", ger: "ich bin nicht ...; ich bin kein/e ...", ctx: "negative form" },
    { eng: "he", ger: "er", ctx: "pronoun (male)" },
    { eng: "funny", ger: "witzig, komisch", ctx: "adjective" },
    { eng: "he/she/it isn't ...", ger: "er/sie/es ist nicht ... / kein/e ...", ctx: "short for: is not" },
    { eng: "strict", ger: "streng", ctx: "Mr Taylor isn't very strict." },
    { eng: "Good morning.", ger: "Guten Morgen.", ctx: "greeting" },
    { eng: "good", ger: "gut", ctx: "adjective" },
    { eng: "noisy", ger: "laut, voller Lärm", ctx: "opposite of quiet" },
    { eng: "please", ger: "bitte", ctx: "Can I borrow your pen, please?" },
    { eng: "(to) be", ger: "sein", ctx: "verb" },
    { eng: "quiet", ger: "ruhig, still, leise", ctx: "opposite of noisy" },
    { eng: "(to) talk (to)", ger: "sprechen, reden (mit)", ctx: "verb" },
    { eng: "Don't talk.", ger: "Sprich/Rede nicht.", ctx: "command" },
    { eng: "(to) sit down", ger: "sich (hin)setzen", ctx: "verb" },
    { eng: "(to) have", ger: "haben", ctx: "verb" },
    { eng: "timetable", ger: "Stundenplan", ctx: "school item" },
    { eng: "IT", ger: "IT (Informationstechnologie)", ctx: "short for: information technology" },
    { eng: "when", ger: "wann", ctx: "question word" },

    // --- Page 3 (Bildschirmfoto 2026-06-27 um 22.55.18.jpg) ---
    { eng: "lesson", ger: "(Unterrichts-)Stunde", ctx: "school" },
    { eng: "today", ger: "heute", ctx: "time" },
    { eng: "maths", ger: "Mathe(matik)", ctx: "school subject" },
    { eng: "then", ger: "dann, danach", ctx: "linking word" },
    { eng: "geography", ger: "Geografie, Erdkunde", ctx: "school subject" },
    { eng: "technology", ger: "Technik(unterricht); Technologie", ctx: "school subject" },
    { eng: "art", ger: "Kunst", ctx: "school subject" },
    { eng: "easy", ger: "einfach, leicht", ctx: "opposite of hard" },
    { eng: "hard", ger: "schwer, schwierig; hart", ctx: "opposite of easy" },
    { eng: "but", ger: "aber", ctx: "linking word" },
    { eng: "about the story", ger: "über die Geschichte", ctx: "phrase" },
    { eng: "he has", ger: "er hat", ctx: "from: to have" },
    { eng: "(to) act", ger: "aufführen, spielen", ctx: "verb" },
    { eng: "assembly", ger: "Schulversammlung", ctx: "school routine" },
    { eng: "science", ger: "Naturwissenschaft", ctx: "school subject" },
    { eng: "break", ger: "Pause", ctx: "school" },
    { eng: "PE", ger: "(Schul-)Sport", ctx: "short for: physical education" },
    { eng: "lunch", ger: "Mittagessen", ctx: "meal" },
    { eng: "French", ger: "Französisch; französisch", ctx: "language / subject" },
    { eng: "history", ger: "Geschichte", ctx: "school subject" },
    { eng: "music", ger: "Musik", ctx: "school subject" },
    { eng: "drama", ger: "Schauspiel, darstellende Kunst", ctx: "school subject" },
    { eng: "on Wednesday", ger: "am Mittwoch", ctx: "preposition with days" },
    { eng: "classmate", ger: "Mitschüler/-in", ctx: "school friend" },
    { eng: "principal", ger: "Rektor/-in, Schulleiter/-in", ctx: "person" },
    { eng: "This is ...", ger: "Dies ist ... / Das ist ...", ctx: "phrase" },
    { eng: "we're", ger: "wir sind", ctx: "short for: we are" },
    { eng: "year", ger: "Jahr(gang)", ctx: "I'm in year six." },
    { eng: "sixteen", ger: "sechzehn", ctx: "Number 16" },
    { eng: "seventeen", ger: "siebzehn", ctx: "Number 17" },
    { eng: "eighteen", ger: "achtzehn", ctx: "Number 18" },
    { eng: "nineteen", ger: "neunzehn", ctx: "Number 19" },
    { eng: "twenty", ger: "zwanzig", ctx: "Number 20" },
    { eng: "twenty-one", ger: "einundzwanzig", ctx: "Number 21" },
    { eng: "twenty-two", ger: "zweiundzwanzig", ctx: "Number 22" },
    { eng: "thirty", ger: "dreißig", ctx: "Number 30" },
    { eng: "thirty-one", ger: "einunddreißig", ctx: "Number 31" },
    { eng: "thirty-two", ger: "zweiunddreißig", ctx: "Number 32" },
    { eng: "they aren't ...", ger: "sie sind nicht ...; sie sind keine ...", ctx: "short for: they are not" },
    { eng: "Ms Borowski", ger: "Frau Borowski", ctx: "title for women" },

    // --- Page 4 (Bildschirmfoto 2026-06-27 um 22.55.29.jpg) ---
    { eng: "too", ger: "auch", ctx: "I'm from Bamberg too." },
    { eng: "they're", ger: "sie sind", ctx: "short for: they are" },
    { eng: "guys", ger: "Leute (als Anrede verwendet)", ctx: "plural noun" },
    { eng: "language", ger: "Sprache", ctx: "noun" },
    { eng: "happy", ger: "glücklich, froh", ctx: "opposite of sad" },
    { eng: "quiz", ger: "Quiz", ctx: "plural: quizzes" },
    { eng: "game", ger: "Spiel", ctx: "noun" },
    { eng: "right", ger: "richtig", ctx: "opposite of wrong" },
    { eng: "or", ger: "oder; sonst", ctx: "conjunction" },
    { eng: "wrong", ger: "falsch", ctx: "opposite of right (silent w!)" },
    { eng: "pullover", ger: "Pullover", ctx: "clothes" },
    { eng: "blazer", ger: "Blazer (Jackett, oft Teil der Schuluniform)", ctx: "clothes" },
    { eng: "shirt", ger: "Hemd", ctx: "clothes" },
    { eng: "shoe", ger: "Schuh", ctx: "clothes" },
    { eng: "skirt", ger: "Rock", ctx: "clothes" },
    { eng: "tie", ger: "Krawatte", ctx: "clothes" },
    { eng: "trousers", ger: "Hose", ctx: "always plural! They're cool." },
    { eng: "shop", ger: "Laden, Geschäft", ctx: "noun" },
    { eng: "magazine", ger: "Zeitschrift", ctx: "noun" },
    { eng: "7 to 12", ger: "(von) 7 bis 12", ctx: "range" },
    { eng: "The shirts are £6.", ger: "Die Hemden kosten 6 Pfund.", ctx: "phrase" },
    { eng: "The shirt is £2.", ger: "Das Hemd kostet 2 Pfund.", ctx: "phrase" },
    { eng: "pound (£)", ger: "Pfund (britische Währung)", ctx: "currency" },
    { eng: "(to) buy", ger: "kaufen", ctx: "verb" },
    { eng: "here", ger: "hier; hierher", ctx: "I'm here." },
    { eng: "clothes", ger: "Kleidung, Kleidungsstücke", ctx: "always plural! All her clothes are black." },
    { eng: "all", ger: "alle(s)", ctx: "pronoun" },
    { eng: "(to) speak", ger: "sprechen", ctx: "verb" },

    // --- Page 5 (Bildschirmfoto 2026-06-27 um 22.55.43.jpg) ---
    { eng: "with", ger: "mit", ctx: "preposition" },
    { eng: "(to) write", ger: "schreiben", ctx: "verb" },
    { eng: "jeans", ger: "Jeans", ctx: "always plural noun" },
    { eng: "lots (of)", ger: "viel / viele", ctx: "There are lots of books." },
    { eng: "question", ger: "Frage", ctx: "noun" },
    { eng: "short", ger: "kurz", ctx: "opposite of long" },
    { eng: "answer (to)", ger: "Antwort (auf)", ctx: "noun / verb: (to) answer" },
    { eng: "ready", ger: "fertig, bereit", ctx: "adjective" },
    { eng: "there", ger: "da, dort; dahin, dorthin", ctx: "adjective" },
    { eng: "together", ger: "zusammen", ctx: "adjective" },
    { eng: "football club (FC)", ger: "Fußballverein", ctx: "noun" },
    { eng: "football", ger: "Fußball", ctx: "sport" },
    { eng: "(to) wear", ger: "tragen, anhaben (Kleidung)", ctx: "verb" },
    { eng: "(to) listen (to)", ger: "(sich etwas) anhören; zuhören", ctx: "verb" },
    { eng: "(to) stand up", ger: "aufstehen", ctx: "verb" },
    { eng: "(to) open", ger: "öffnen; aufschlagen (Buch)", ctx: "verb" },
    { eng: "(to) close", ger: "schließen, zumachen", ctx: "verb" },
    { eng: "(to) look at sth.", ger: "sich etwas anschauen", ctx: "verb" },
    { eng: "(to) learn", ger: "lernen", ctx: "verb" },
    { eng: "word web", ger: "Wortnetz", ctx: "noun" },
    { eng: "web", ger: "Netz", ctx: "noun" },
    { eng: "people", ger: "Leute, Menschen", ctx: "plural noun: five people" },
    { eng: "sentence", ger: "Satz", ctx: "noun" },
    { eng: "after", ger: "nach", ctx: "after the first day" },
    { eng: "idea", ger: "Idee", ctx: "noun" },
    { eng: "there's", ger: "es ist ... / es gibt ...", ctx: "short for: there is" },
    { eng: "there are", ger: "es sind ... / es gibt ...", ctx: "plural format" },
    { eng: "group", ger: "Gruppe", ctx: "noun" },
    { eng: "(to) be good at sth.", ger: "etwas gut können; gut in etwas sein", ctx: "phrase" },
    { eng: "his favourite game", ger: "sein Lieblingsspiel", ctx: "phrase" },
    { eng: "player", ger: "Spieler/-in", ctx: "noun" },

    // --- Page 6 (Bildschirmfoto 2026-06-27 um 22.55.58.jpg) ---
    { eng: "other", ger: "andere(-r, -s)", ctx: "the others = die anderen" },
    { eng: "(to) play", ger: "spielen", ctx: "verb" },
    { eng: "me", ger: "mich; mir", ctx: "pronoun: Meet me / Help me" },
    { eng: "(to) run", ger: "rennen, laufen", ctx: "verb" },
    { eng: "goal", ger: "Tor (im Sport)", ctx: "noun" },
    { eng: "near", ger: "nahe (bei), in der Nähe von", ctx: "preposition" },
    { eng: "why", ger: "warum", ctx: "question word" },
    { eng: "grandma", ger: "Oma", ctx: "family" },
    { eng: "sad", ger: "traurig", ctx: "opposite of happy" },
    { eng: "friendly", ger: "freundlich", ctx: "adjective" },
    { eng: "important", ger: "wichtig", ctx: "adjective" },
    { eng: "See you tomorrow.", ger: "Bis morgen.", ctx: "phrase" },
    { eng: "tomorrow", ger: "morgen", ctx: "time" },
    { eng: "Bye.", ger: "Tschüs.", ctx: "short for goodbye" },
    { eng: "Goodbye.", ger: "Auf Wiedersehen!", ctx: "phrase" },
    { eng: "her mum", ger: "ihre Mutter (weibliche Person)", ctx: "phrase" },
    { eng: "I think ...", ger: "Ich denke / meine / glaube / finde, ...", ctx: "phrase" },
    { eng: "(to) think", ger: "denken, meinen, glauben", ctx: "verb" },
    { eng: "task", ger: "Aufgabe", ctx: "noun" },
    { eng: "Get ready.", ger: "Bereite dich vor.", ctx: "phrase" },
    { eng: "Go ahead.", ger: "Nur zu! / Dann mal los!", ctx: "phrase" },
    { eng: "(to) finish", ger: "beenden, zu Ende machen", ctx: "verb" }
];