// Vocabulary Data for Grade 5 - Unit 2
// Sources referenced: Bildschirmfoto 2026-06-27 um 22.58.03.png to 22.58.58.png

const e5u2_data = [
    // --- Page 1 (Bildschirmfoto 2026-06-27 um 22.58.03.png) ---
    { eng: "family", ger: "Familie", ctx: "noun" },
    { eng: "in the photo", ger: "auf dem Foto", ctx: "phrase" },
    { eng: "divorced", ger: "geschieden", ctx: "Mum and dad are divorced." },
    { eng: "dog", ger: "Hund", ctx: "animal" },
    { eng: "half-brother", ger: "Halbbruder", ctx: "family" },
    { eng: "cousin", ger: "Cousin, Cousine", ctx: "family" },
    { eng: "grandad", ger: "Oma", ctx: "family" },
    { eng: "parents", ger: "Eltern", ctx: "always plural noun" },
    { eng: "dead", ger: "tot", ctx: "adjective" },
    { eng: "brother", ger: "Bruder", ctx: "family" },

    // --- Page 2 (Bildschirmfoto 2026-06-27 um 22.58.14.jpg) ---
    { eng: "aunt", ger: "Tante", ctx: "family" },
    { eng: "father", ger: "Vater", ctx: "family" },
    { eng: "mother", ger: "Mutter", ctx: "family" },
    { eng: "sister", ger: "Schwester", ctx: "family" },
    { eng: "uncle", ger: "Onkel", ctx: "family" },
    { eng: "their", ger: "ihr / ihre (Plural)", ctx: "possessive pronoun" },
    { eng: "stepsister", ger: "Stiefschwester", ctx: "family" },
    { eng: "breakfast", ger: "Frühstück", ctx: "meal" },
    { eng: "time", ger: "Zeit; Uhrzeit", ctx: "What's the time?" },
    { eng: "dinner", ger: "Abendessen", ctx: "for dinner = zum Abendessen" },
    { eng: "time to go", ger: "Zeit, zu gehen", ctx: "It's time to eat." },
    { eng: "at Ben's house", ger: "bei Ben zu Hause, bei Ben daheim", ctx: "phrase" },
    { eng: "house", ger: "Haus", ctx: "building" },
    { eng: "(to) wake up", ger: "aufwachen", ctx: "verb" },
    { eng: "at 7 o'clock", ger: "um 7 Uhr", ctx: "time phrase" },
    { eng: "(to) get up", ger: "aufstehen", ctx: "verb" },
    { eng: "ten past seven", ger: "zehn nach sieben", ctx: "7:10" },
    { eng: "It's quarter past 6.", ger: "Es ist Viertel nach sechs.", ctx: "6:15" },
    { eng: "It's half past 6.", ger: "Es ist halb sieben.", ctx: "6:30 (Note: half past 6!)" },
    { eng: "It's quarter to 7.", ger: "Es ist Viertel vor sieben.", ctx: "6:45" },
    { eng: "(to) get dressed", ger: "sich anziehen", ctx: "verb" },
    { eng: "(to) have breakfast", ger: "frühstücken", ctx: "verb" },
    { eng: "(to) have lunch", ger: "zu Mittag essen", ctx: "verb" },
    { eng: "(to) have dinner", ger: "zu Abend essen", ctx: "verb" },
    { eng: "at home", ger: "zu Hause, daheim", ctx: "Ben is at home." },
    { eng: "home", ger: "Heim, Zuhause", ctx: "noun" },

    // --- Page 3 (Bildschirmfoto 2026-06-27 um 22.58.25.jpg) ---
    { eng: "at work", ger: "bei der Arbeit, am Arbeitsplatz", ctx: "I'm at work." },
    { eng: "at the supermarket", ger: "im Supermarkt", ctx: "phrase" },
    { eng: "open", ger: "offen, geöffnet", ctx: "opposite of closed" },
    { eng: "hour", ger: "Stunde", ctx: "the 'h' is silent!" },
    { eng: "evening", ger: "Abend", ctx: "in the evening = am Abend" },
    { eng: "(to) come", ger: "(mit)kommen", ctx: "verb" },
    { eng: "(to) come home", ger: "nach Hause kommen", ctx: "verb" },
    { eng: "(to) start", ger: "beginnen, anfangen (mit)", ctx: "verb" },
    { eng: "(to) do", ger: "machen, tun", ctx: "verb" },
    { eng: "homework", ger: "Hausaufgabe(n)", ctx: "uncountable! Homework is important." },
    { eng: "when", ger: "wenn / wann", ctx: "conjunction / question word" },
    { eng: "(to) watch TV", ger: "fernsehen", ctx: "verb" },
    { eng: "(to) watch", ger: "(sich etwas) anschauen; beobachten", ctx: "verb" },
    { eng: "shower", ger: "Dusche", ctx: "(to) have a shower = sich duschen" },
    { eng: "bed", ger: "Bett", ctx: "(to) go to bed = ins Bett gehen" },
    { eng: "night", ger: "Nacht", ctx: "at night = nachts, in der Nacht" },
    { eng: "Good night.", ger: "Gute Nacht.", ctx: "phrase" },
    { eng: "What time is it?", ger: "Wie spät ist es?", ctx: "question" },
    { eng: "oh", ger: "Null", ctx: "used when saying phone numbers or zero" },
    { eng: "forty", ger: "vierzig", ctx: "Number 40" },
    { eng: "fifty", ger: "fünfzig", ctx: "Number 50" },
    { eng: "sixty", ger: "sechzig", ctx: "Number 60" },
    { eng: "seventy", ger: "siebzig", ctx: "Number 70" },
    { eng: "eighty", ger: "achtzig", ctx: "Number 80" },
    { eng: "ninety", ger: "neunzig", ctx: "Number 90" },
    { eng: "a hundred / one hundred", ger: "hundert", ctx: "Number 100" },
    { eng: "weekend", ger: "Wochenende", ctx: "at the weekend = am Wochenende" },
    { eng: "(to) make", ger: "machen, herstellen", ctx: "verb" },

    // --- Page 4 (Bildschirmfoto 2026-06-27 um 22.58.37.jpg) ---
    { eng: "ball", ger: "Ball", ctx: "noun" },
    { eng: "(to) eat", ger: "essen; fressen", ctx: "verb" },
    { eng: "(to) take", ger: "(mit)nehmen; bringen", ctx: "take the bus / take a coat" },
    { eng: "afternoon", ger: "Nachmittag", ctx: "in the afternoon = nachmittags" },
    { eng: "(to) help", ger: "helfen", ctx: "verb / noun: help" },
    { eng: "first", ger: "zuerst, als Erstes", ctx: "adverb" },
    { eng: "(to) work", ger: "arbeiten; funktionieren", ctx: "It works = Es funktioniert." },
    { eng: "pet", ger: "(Haus-)Tier", ctx: "noun" },
    { eng: "animal", ger: "Tier", ctx: "noun" },
    { eng: "bird", ger: "Vogel", ctx: "animal" },
    { eng: "fish", ger: "Fisch", ctx: "plural is also: fish! (one fish, two fish)" },
    { eng: "number", ger: "Zahl, Ziffer, Nummer", ctx: "noun" },
    { eng: "rabbit", ger: "Kaninchen", ctx: "animal" },
    { eng: "ferret", ger: "Frettchen", ctx: "animal" },
    { eng: "guinea pig", ger: "Meerschweinchen", ctx: "animal" },
    { eng: "horse", ger: "Pferd", ctx: "animal" },
    { eng: "mouse", ger: "Maus", ctx: "irregular plural: mice! (two mice)" },
    { eng: "spider", ger: "Spinne", ctx: "animal" },
    { eng: "turtle", ger: "(Wasser-)Schildkröte", ctx: "animal" },
    { eng: "hamster", ger: "Hamster", ctx: "animal" },
    { eng: "it can't play", ger: "es kann nicht spielen", ctx: "short for: cannot" },
    { eng: "(to) live", ger: "leben, wohnen", ctx: "verb" },
    { eng: "garden", ger: "Garten", ctx: "noun" },
    { eng: "(to) sit", ger: "sitzen; sich setzen", ctx: "verb" },
    { eng: "on", ger: "auf", ctx: "preposition" },

    // --- Page 5 (Bildschirmfoto 2026-06-27 um 22.58.48.jpg) ---
    { eng: "its name", ger: "sein Name / ihr Name", ctx: "possessive for things/animals" },
    { eng: "hermit crab", ger: "Einsiedlerkrebs", ctx: "animal" },
    { eng: "interesting", ger: "interessant", ctx: "opposite of boring" },
    { eng: "(to) walk", ger: "wandern, (zu Fuß) gehen", ctx: "verb" },
    { eng: "expensive", ger: "teuer", ctx: "opposite of cheap" },
    { eng: "child", ger: "Kind", ctx: "irregular plural: children!" },
    { eng: "water", ger: "Wasser", ctx: "noun" },
    { eng: "food", ger: "Essen, Lebensmittel; Futter", ctx: "noun" },
    { eng: "fruit", ger: "Obst", ctx: "uncountable noun" },
    { eng: "for 30 years", ger: "30 Jahre (lang)", ctx: "time span" },
    { eng: "cat", ger: "Katze", ctx: "animal" },
    { eng: "(to) smell", ger: "riechen; schlecht riechen", ctx: "verb" },
    { eng: "(to) sleep", ger: "schlafen", ctx: "verb" },
    { eng: "a lot (of)", ger: "viel / e; sehr", ctx: "a lot of books / I read a lot." },
    { eng: "they like to play", ger: "sie spielen gern", ctx: "phrase" },
    { eng: "(to) know", ger: "wissen; kennen", ctx: "silent k!" },
    { eng: "(to) sing", ger: "singen", ctx: "verb" },
    { eng: "(to) say", ger: "sagen", ctx: "verb (he/she/it says [sez])" },
    { eng: "it doesn't help", ger: "es hilft nicht", ctx: "phrase" },
    { eng: "(to) think of", ger: "denken an", ctx: "verb" },

    // --- Page 6 (Bildschirmfoto 2026-06-27 um 22.58.58.png) ---
    { eng: "(to) want", ger: "wollen", ctx: "verb" },
    { eng: "bad", ger: "schlecht; schlimm", ctx: "opposite of good" },
    { eng: "dress", ger: "Kleid", ctx: "clothes" },
    { eng: "early", ger: "früh", ctx: "opposite of late" },
    { eng: "tennis", ger: "Tennis", ctx: "sport" },
    { eng: "spelling", ger: "Schreibweise, Rechtschreibung", ctx: "noun" },
    { eng: "alphabet", ger: "Alphabet", ctx: "noun (stressed on first syllable)" },
    { eng: "(to) spell", ger: "buchstabieren", ctx: "verb" },
    { eng: "under", ger: "unter", ctx: "opposite of on" },
    { eng: "cage", ger: "Käfig", ctx: "noun" },
    { eng: "like", ger: "wie", ctx: "preposition (e.g., 'supermarket' is like 'Supermarkt')" },
    { eng: "how many?", ger: "wie viele?", ctx: "question phrase" }
];