// Vocabulary Data for Grade 5 - Unit 3
// Sources referenced: Bildschirmfoto 2026-06-27 um 23.00.28.png to 23.01.24.png

const e5u3_data = [
    // --- Page 1 (Bildschirmfoto 2026-06-27 um 23.00.28.png) ---
    { eng: "room", ger: "Raum, Zimmer", ctx: "noun (e.g., My room)" },
    { eng: "carpet", ger: "Teppich", ctx: "noun" },
    { eng: "chest of drawers", ger: "Kommode", ctx: "plural: chests of drawers" },
    { eng: "cupboard", ger: "Schrank (z. B. Küchenschrank)", ctx: "noun" },
    { eng: "curtain", ger: "Vorhang, Gardine", ctx: "noun" },
    { eng: "lamp", ger: "Lampe", ctx: "noun" },
    { eng: "shelf", ger: "Regal", ctx: "irregular plural: shelves! (one shelf - two shelves)" },
    { eng: "table", ger: "Tisch", ctx: "furniture (a table)" },
    { eng: "wardrobe", ger: "Kleiderschrank", ctx: "furniture" },

    // --- Page 2 (Bildschirmfoto 2026-06-27 um 23.00.39.jpg) ---
    { eng: "some", ger: "einige, ein paar; etwas, ein wenig", ctx: "some books / some water" },
    { eng: "(to) share a room (with ...)", ger: "sich ein Zimmer teilen mit ...", ctx: "verb" },
    { eng: "noise", ger: "Geräusch; Lärm", ctx: "noun (What's that noise?)" },
    { eng: "flat", ger: "Wohnung", ctx: "noun" },
    { eng: "neighbour", ger: "Nachbar/in", ctx: "noun" },
    { eng: "nobody / no one", ger: "niemand", ctx: "Nobody is at home." },
    { eng: "chocolate", ger: "Schokolade", ctx: "noun" },
    { eng: "biscuit", ger: "Keks, Plätzchen", ctx: "noun" },
    { eng: "living room", ger: "Wohnzimmer", ctx: "house" },
    { eng: "(to) hear", ger: "hören", ctx: "verb ((to) hear = hören können / (to) listen (to) = zuhören)" },
    { eng: "kitchen", ger: "Küche", ctx: "house" },
    { eng: "dining room", ger: "Esszimmer", ctx: "house (Please come to the dining room.)" },
    { eng: "(to) check", ger: "(über)prüfen, kontrollieren", ctx: "verb / noun: check" },
    { eng: "bedroom", ger: "Schlafzimmer", ctx: "house" },
    { eng: "upstairs", ger: "(nach) oben (die Treppe hoch)", ctx: "adverb" },
    { eng: "always", ger: "immer", ctx: "adverb (The cat always sleeps in my bed.)" },
    { eng: "(to) put", ger: "(etwas wohin) tun, legen, stellen, stecken", ctx: "verb (Please put your clothes in the wardrobe.)" },
    { eng: "floor", ger: "Fußboden", ctx: "... not on the floor!" },
    { eng: "tidy", ger: "ordentlich", ctx: "adjective (My room is always very tidy.)" },
    { eng: "into the room", ger: "in das Zimmer (hinein)", ctx: "phrase" },
    { eng: "these rooms", ger: "diese Räume/Zimmer (hier)", ctx: "plural pronoun (this dog - these dogs)" },
    { eng: "bathroom", ger: "Bad(ezimmer)", ctx: "house" },
    { eng: "again", ger: "wieder, noch einmal", ctx: "adverb" },
    { eng: "downstairs", ger: "(nach) unten (die Treppe hinunter)", ctx: "adverb" },
    { eng: "hall", ger: "Flur, Diele", ctx: "house" },
    { eng: "burglar", ger: "Einbrecher/in", ctx: "noun" },

    // --- Page 3 (Bildschirmfoto 2026-06-27 um 23.01.01.jpg) ---
    { eng: "project", ger: "Projekt", ctx: "noun (stressed on first syllable)" },
    { eng: "(to) tidy", ger: "aufräumen", ctx: "verb / adjective: tidy" },
    { eng: "balcony", ger: "Balkon", ctx: "plural: balconies" },
    { eng: "with us", ger: "bei uns", ctx: "He's with Ben. = Er ist bei Ben." },
    { eng: "us", ger: "uns", ctx: "pronoun (Can you see us?)" },
    { eng: "wall", ger: "Wand, Mauer", ctx: "noun" },
    { eng: "mom", ger: "Mama, Mutti", ctx: "American English (AE)" },
    { eng: "apartment", ger: "Wohnung", ctx: "American English (AE)" },
    { eng: "dream", ger: "Traum(-)", ctx: "my dream job" },
    { eng: "drink", ger: "Getränk", ctx: "noun / verb: (to) drink" },
    { eng: "milk", ger: "Milch", ctx: "noun" },
    { eng: "bread", ger: "Brot", ctx: "white bread / black bread" },
    { eng: "butter", ger: "Butter", ctx: "noun" },
    { eng: "cheese", ger: "Käse", ctx: "noun (some cheese)" },
    { eng: "chicken", ger: "Huhn; (Brat-)Hähnchen", ctx: "noun" },
    { eng: "egg", ger: "Ei", ctx: "noun" },
    { eng: "orange juice", ger: "Orangensaft", ctx: "drink" },
    { eng: "meat", ger: "Fleisch", ctx: "noun" },
    { eng: "potato", ger: "Kartoffel", ctx: "irregular plural: potatoes" },
    { eng: "salad", ger: "Salat (als Gericht oder Beilage)", ctx: "potato salad" },
    { eng: "tea", ger: "Tee", ctx: "drink" },
    { eng: "vegetables", ger: "Gemüse", ctx: "always plural! Vegetables are good for you." },
    { eng: "really", ger: "wirklich", ctx: "Our teachers are really nice." },
    { eng: "(to) be hungry", ger: "Hunger haben", ctx: "phrase (I'm hungry. = Ich habe Hunger.)" },
    { eng: "Mrs Pozniak", ger: "Frau Pozniak", ctx: "title for married women" },
    { eng: "Would you like some tea/potatoes?", ger: "Möchtest du (etwas) Tee / (ein paar) Kartoffeln?", ctx: "question phrase" },
    { eng: "I'd like ...", ger: "Ich hätte gern ... / Ich möchte ...", ctx: "short for: I would like" },

    // --- Page 4 (Bildschirmfoto 2026-06-27 um 23.01.14.jpg) ---
    { eng: "(to) mix", ger: "(ver)mischen", ctx: "verb" },
    { eng: "everything", ger: "alles", ctx: "pronoun (Everything is in my bag.)" },
    { eng: "minute", ger: "Minute", ctx: "noun" },
    { eng: "often", ger: "oft", ctx: "adverb (I often walk to school.)" },
    { eng: "it says that ...", ger: "es (be)sagt, dass ...", ctx: "The text says that..." },
    { eng: "every", ger: "jede(r, s)", ctx: "every day" },
    { eng: "usually", ger: "normalerweise, meistens", ctx: "adverb" },
    { eng: "nearly", ger: "fast", ctx: "It's nearly 8 o'clock!" },
    { eng: "sometimes", ger: "manchmal", ctx: "adverb" },
    { eng: "vegetarian", ger: "vegetarisch; Vegetarier/in", ctx: "I don't eat meat. I'm a vegetarian." },
    { eng: "never", ger: "nie, niemals", ctx: "adverb" },
    { eng: "per cent (%)", ger: "Prozent", ctx: "noun" },
    { eng: "apple", ger: "Apfel", ctx: "fruit" },
    { eng: "restaurant", ger: "Restaurant", ctx: "at a restaurant = in einem Restaurant" },
    { eng: "we should ...", ger: "wir sollten ...", ctx: "What should I do?" },
    { eng: "fresh", ger: "frisch", ctx: "adjective" },
    { eng: "meal", ger: "Mahlzeit, Essen", ctx: "noun" },
    { eng: "chips", ger: "Pommes frites", ctx: "British English (BE)" },
    { eng: "canteen", ger: "Kantine, (Schul-)Mensa", ctx: "school building" },
    { eng: "warm", ger: "warm", ctx: "adjective (a warm meal)" },
    { eng: "cold", ger: "kalt", ctx: "adjective (a cold drink)" },
    { eng: "There aren't any ...", ger: "Es gibt/sind keine ...", ctx: "There aren't any apples." },
    { eng: "sweets", ger: "Bonbons, Süßigkeiten", ctx: "always plural noun" },
    { eng: "tomato", ger: "Tomate", ctx: "irregular plural: tomatoes" },
    { eng: "cake", ger: "Kuchen, Torte", ctx: "a chocolate cake" },
    { eng: "Are there any ...?", ger: "Gibt es (irgendwelche) ...?", ctx: "question phrase" },
    { eng: "fish finger", ger: "Fischstäbchen", ctx: "food" },

    // --- Page 5 (Bildschirmfoto 2026-06-27 um 23.01.24.png) ---
    { eng: "those", ger: "die dort, jene (dort)", ctx: "plural pronoun for distant things" },
    { eng: "talk", ger: "Vortrag, Rede; Gespräch", ctx: "noun" },
    { eng: "(to) give a talk", ger: "einen Vortrag halten", ctx: "phrase" },
    { eng: "(to) give", ger: "geben", ctx: "verb" },
    { eng: "I'd like to talk about ...", ger: "Ich würde gern über ... sprechen.", ctx: "phrase" },
    { eng: "because", ger: "weil", ctx: "conjunction (I'm sad because it's Monday!)" },
    { eng: "end", ger: "Ende, Schluss", ctx: "noun" },
    { eng: "fast", ger: "schnell", ctx: "adjective / adverb (How fast can you run?)" },
    { eng: "(to) smile", ger: "lächeln", ctx: "verb / noun: smile = ein Lächeln" },
    { eng: "country", ger: "Land", ctx: "noun" },
    { eng: "market", ger: "Markt", ctx: "at a market = auf einem Markt" },
    { eng: "week", ger: "Woche", ctx: "noun" },
    { eng: "how much?", ger: "wie viel?", ctx: "used for uncountable things (How much time?)" },
    { eng: "(to) spend money (on)", ger: "Geld ausgeben (für)", ctx: "verb (I spend £10 on sweets.)" },
    { eng: "(to) spend time", ger: "Zeit verbringen", ctx: "verb (spend time in front of my computer)" },
    { eng: "euro", ger: "Euro", ctx: "plural: euros" },
    { eng: "crisps", ger: "(Kartoffel-)Chips", ctx: "British English (BE / crisps = Kartoffelchips; chips = Pommes)" },
    { eng: "rice", ger: "Reis", ctx: "noun" },
    { eng: "bacon", ger: "Speck", ctx: "noun" },
    { eng: "(to) plan", ger: "planen", ctx: "verb (Let's plan a meal together.)" },
    { eng: "German", ger: "deutsch; Deutsch; Deutsche/r", ctx: "language / nationality" },
    { eng: "ice cream", ger: "(Speise-)Eis", ctx: "noun" }
];