// Vocabulary Data for Grade 5 - Unit 4
// Sources referenced: Bildschirmfoto 2026-06-27 um 23.03.15.jpg to 23.04.04.png

const e5u4_data = [
    // --- Page 1 (Bildschirmfoto 2026-06-27 um 23.03.15.jpg) ---
    { eng: "cinema", ger: "Kino", ctx: "at the cinema = im Kino" },
    { eng: "church", ger: "Kirche", ctx: "building" },
    { eng: "library", ger: "Bücherei, Bibliothek", ctx: "place for books" },
    { eng: "museum", ger: "Museum", ctx: "building" },
    { eng: "post office", ger: "Post(amt)", ctx: "noun" },
    { eng: "shopping centre", ger: "Einkaufszentrum", ctx: "noun" },
    { eng: "station", ger: "Bahnhof", ctx: "train station" },
    { eng: "theatre", ger: "Theater", ctx: "building" },
    { eng: "(to) want to do sth.", ger: "etwas tun wollen", ctx: "verb (I want to buy it now.)" },
    { eng: "(to) get", ger: "(sich etwas) holen / besorgen; bekommen", ctx: "verb (Where can I get help?)" },
    { eng: "(to) send", ger: "senden, schicken", ctx: "verb (I'd like to send a card.)" },
    { eng: "card", ger: "Karte", ctx: "noun" },
    { eng: "Excuse me, ...", ger: "Entschuldigung, ... / Entschuldigen Sie, ...", ctx: "phrase" },
    { eng: "man", ger: "Mann", ctx: "irregular plural: men" },
    { eng: "(to) turn right/left", ger: "(nach) rechts/links abbiegen", ctx: "direction" },
    { eng: "right", ger: "rechts; nach rechts", ctx: "direction" },
    { eng: "left", ger: "links; nach links", ctx: "direction" },
    { eng: "straight on", ger: "geradeaus (weiter)", ctx: "Go straight on." },
    { eng: "on the right", ger: "rechts, auf der rechten Seite", ctx: "direction" },
    { eng: "on the left", ger: "links, auf der linken Seite", ctx: "direction" },
    { eng: "You're welcome.", ger: "Bitte, gern geschehen. / Nichts zu danken.", ctx: "reply to Thank you" },

    // --- Page 2 (Bildschirmfoto 2026-06-27 um 23.03.26.jpg) ---
    { eng: "woman", ger: "Frau", ctx: "irregular plural: women" },
    { eng: "second", ger: "zweite(r, s)", ctx: "2nd (e.g., second floor)" },
    { eng: "directions", ger: "Wegbeschreibung(en)", ctx: "always plural (to give/ask for directions)" },
    { eng: "street", ger: "Straße (in Ortschaften)", ctx: "in the street = auf der Straße" },
    { eng: "area", ger: "Gegend, Bereich", ctx: "I live in an area with shops." },
    { eng: "they were", ger: "sie waren", ctx: "past of 'to be' (we were, you were, they were)" },
    { eng: "harbour", ger: "Hafen", ctx: "noun" },
    { eng: "cafe", ger: "Café", ctx: "noun (stressed on first syllable)" },
    { eng: "(to) go shopping", ger: "einkaufen gehen", ctx: "phrase" },
    { eng: "(to) sell", ger: "verkaufen", ctx: "verb (opposite of buy)" },
    { eng: "skating", ger: "Schlittschuhlaufen; (Inline-)Skaten", ctx: "activity" },
    { eng: "skating rink", ger: "Schlittschuhbahn", ctx: "noun" },
    { eng: "all year", ger: "das ganze Jahr (über)", ctx: "phrase" },
    { eng: "tower", ger: "Turm", ctx: "building" },
    { eng: "it was", ger: "es war", ctx: "past of 'to be' (I was, he/she/it was)" },
    { eng: "step", ger: "Stufe; Schritt", ctx: "She's sitting on the steps." },
    { eng: "best", ger: "beste(r, s); am besten", ctx: "superlative" },
    { eng: "(to) ask", ger: "fragen", ctx: "verb (Can I ask you a question?)" },
    { eng: "in front of", ger: "vor", ctx: "preposition of place" },

    // --- Page 3 (Bildschirmfoto 2026-06-27 um 23.03.36.jpg) ---
    { eng: "tired", ger: "müde", ctx: "adjective" },
    { eng: "line", ger: "Zeile; Reihe", ctx: "a line of houses" },
    { eng: "village", ger: "Dorf", ctx: "noun" },
    { eng: "yesterday", ger: "gestern", ctx: "time" },
    { eng: "last", ger: "letzte(r, s)", ctx: "last week = letzte Woche (opposite of first)" },
    { eng: "them", ger: "sie, ihnen", ctx: "object pronoun (they -> them)" },
    { eng: "it wasn't", ger: "es war nicht", ctx: "short for: was not" },
    { eng: "they weren't", ger: "sie waren nicht", ctx: "short for: were not" },
    { eng: "journey", ger: "Reise", ctx: "noun" },
    { eng: "free", ger: "frei; kostenlos", ctx: "adjective" },
    { eng: "sport", ger: "Sport; Sportart", ctx: "noun" },
    { eng: "size", ger: "Größe", ctx: "What size do you take?" },
    { eng: "How much is ...?", ger: "Was (Wie viel) kostet ...?", ctx: "uncountable (How much is the football?)" },
    { eng: "How much are ...?", ger: "Was (Wie viel) kosten ...?", ctx: "plural format (How much are the books?)" },
    { eng: "shop assistant", ger: "Verkäufer/in", ctx: "person" },
    { eng: "penny", ger: "Penny, Pence (Plural)", ctx: "currency unit (short: p [pi:])" },

    // --- Page 4 (Bildschirmfoto 2026-06-27 um 23.03.48.jpg) ---
    { eng: "(to) try sth. on", ger: "anprobieren (Kleidung)", ctx: "verb" },
    { eng: "(to) try", ger: "versuchen, (aus)probieren", ctx: "verb" },
    { eng: "age", ger: "Alter", ctx: "at the age of 12 = im Alter von 12" },
    { eng: "famous (for)", ger: "berühmt (für, wegen)", ctx: "famous for its old churches" },
    { eng: "when", ger: "als", ctx: "conjunction (I started when I was ready.)" },
    { eng: "(to) learn", ger: "lernen", ctx: "past form: learned" },
    { eng: "(to) swim", ger: "schwimmen", ctx: "irregular verb (past: swam)" },
    { eng: "(to) dive", ger: "einen Kopfsprung machen, ins Wasser springen", ctx: "verb" },
    { eng: "he was born", ger: "er wurde geboren", ctx: "phrase (When were you born?)" },
    { eng: "the Olympics", ger: "die olympischen Spiele", ctx: "always plural" },
    { eng: "the world", ger: "die Welt", ctx: "the best place in the world" },
    { eng: "championship", ger: "Meisterschaft", ctx: "noun" },
    { eng: "(to) move (to)", ger: "(um)ziehen (nach); (Schule) wechseln (auf/zu)", ctx: "verb" },
    { eng: "college", ger: "Hochschule", ctx: "noun" },
    { eng: "(to) die", ger: "sterben", ctx: "verb (past form: died / continuous: dying)" },
    { eng: "(to) become", ger: "werden", ctx: "irregular verb (past: became)" },
    { eng: "model", ger: "(Foto-)Modell", ctx: "noun (stressed on first syllable)" },
    { eng: "university", ger: "Universität", ctx: "noun" },
    { eng: "Dear ...", ger: "Liebe/r ...", ctx: "letter greeting" },

    // --- Page 5 (Bildschirmfoto 2026-06-27 um 23.03.55.jpg) ---
    { eng: "him", ger: "ihm, ihn", ctx: "object pronoun (he -> him)" },
    { eng: "her", ger: "sie; ihr", ctx: "object pronoun / possessive pronoun (her dog)" },
    { eng: "Best wishes", ger: "Viele Grüße ...", ctx: "letter closing" },
    { eng: "(to) tell (about)", ger: "sagen; erzählen (von), berichten (über)", ctx: "irregular verb (past: told)" },
    { eng: "soon", ger: "bald", ctx: "adverb" },
    { eng: "Love ...", ger: "Liebe Grüße, ...", ctx: "letter closing" },
    { eng: "Note: (to) use", ger: "benutzen, verwenden", ctx: "verb" },
    { eng: "dictionary", ger: "Wörterbuch, Wörterverzeichnis", ctx: "noun" },
    { eng: "poem", ger: "Gedicht", ctx: "noun" },
    { eng: "around ...", ger: "um (... herum)", ctx: "to sail around the world" },
    { eng: "Africa", ger: "Afrika", ctx: "continent" },
    { eng: "gold", ger: "Gold", ctx: "noun (pronounced [gəʊld])" },
    { eng: "ship", ger: "Schiff", ctx: "noun" },
    { eng: "great", ger: "groß (bedeutend, angesehen)", ctx: "adjective alternative meaning" },
    { eng: "in 1540", ger: "(im Jahre) 1540", ctx: "date format" },
    { eng: "(to) sail", ger: "segeln, (mit dem Schiff) fahren", ctx: "verb" },
    { eng: "pirate", ger: "Pirat/in", ctx: "noun (stressed on first syllable)" },
    { eng: "Spanish", ger: "spanisch; Spanisch", ctx: "language / nationality" },

    // --- Page 6 (Bildschirmfoto 2026-06-27 um 23.04.04.png) ---
    { eng: "rich", ger: "reich", ctx: "opposite of poor" },
    { eng: "queen", ger: "Königin", ctx: "noun" },
    { eng: "South America", ger: "Südamerika", ctx: "continent" },
    { eng: "(to) fight", ger: "kämpfen (gegen), bekämpfen", ctx: "irregular verb (past: fought / noun: fight)" },
    { eng: "terrible", ger: "schrecklich, fürchterlich", ctx: "synonym for horrible" },
    { eng: "guide (to)", ger: "Ratgeber (für), Reiseführer (Buch, Broschüre)", ctx: "noun" }
];