// Vocabulary Data for Grade 5 - Unit 5
// Sources referenced: Bildschirmfoto 2026-06-27 um 23.05.37.jpg to 23.06.15.png

const e5u5_data = [
    // --- Page 1 (Bildschirmfoto 2026-06-27 um 23.05.37.jpg) ---
    { eng: "free time", ger: "Freizeit, freie Zeit", ctx: "in my free time / free-time activities" },
    { eng: "outside", ger: "draußen; nach draußen", ctx: "The dogs are outside in the garden." },
    { eng: "(to) take a photo", ger: "ein Foto machen", ctx: "irregular verb (simple past: took)" },
    { eng: "piano", ger: "Klavier", ctx: "musical instrument ((to) play the piano)" },
    { eng: "(to) feel", ger: "sich fühlen; fühlen", ctx: "irregular verb (simple past: felt)" },
    { eng: "(to) ride a bike", ger: "mit dem Fahrrad fahren", ctx: "irregular verb (simple past: rode)" },
    { eng: "bike", ger: "Fahrrad", ctx: "noun" },
    { eng: "something", ger: "etwas", ctx: "pronoun (Would you like something to eat?)" },
    { eng: "text (message)", ger: "SMS", ctx: "noun (message = Nachricht; text = SMS)" },
    { eng: "singer", ger: "Sänger/in", ctx: "person" },
    { eng: "song", ger: "Lied", ctx: "noun" },
    { eng: "instrument", ger: "Instrument", ctx: "noun (stressed on the first syllable)" },
    { eng: "guitar", ger: "Gitarre", ctx: "musical instrument" },
    { eng: "(to) dance", ger: "tanzen", ctx: "verb (dancing = das Tanzen)" },

    // --- Page 2 (Bildschirmfoto 2026-06-27 um 23.05.45.jpg) ---
    { eng: "phone", ger: "Telefon", ctx: "on the phone = am Telefon" },
    { eng: "difference", ger: "Unterschied", ctx: "noun" },
    { eng: "(to) make a difference", ger: "etwas bewirken, etwas ausmachen", ctx: "irregular verb (simple past: made)" },
    { eng: "(to) need", ger: "brauchen, benötigen", ctx: "verb" },
    { eng: "trouble", ger: "Ärger, Schwierigkeiten", ctx: "in trouble = in Schwierigkeiten" },
    { eng: "bus", ger: "Bus", ctx: "on the bus = im Bus" },
    { eng: "everybody / everyone", ger: "jeder, alle", ctx: "pronoun" },
    { eng: "gymnastics", ger: "Turnen, Gymnastik", ctx: "uncountable noun ((to) do gymnastics)" },
    { eng: "horse riding", ger: "(das) Reiten, Reitsport", ctx: "sport ((to) ride a horse)" },
    { eng: "netball", ger: "Korbball", ctx: "sport" },
    { eng: "(to) ski", ger: "Ski laufen, Ski fahren", ctx: "verb (skiing = das Skifahren)" },
    { eng: "(to) do sport", ger: "Sport treiben", ctx: "phrase" },
    { eng: "so", ger: "also, daher", ctx: "conjunction (It's Sunday, so I can get up late.)" },
    { eng: "month", ger: "Monat", ctx: "noun" },
    { eng: "I didn't like ...", ger: "ich mochte ... nicht", ctx: "short for: did not like" },
    { eng: "(to) love", ger: "lieben, sehr mögen", ctx: "verb" },
    { eng: "(to) love doing / to do sth.", ger: "etwas sehr gerne tun", ctx: "phrase (I love running.)" },
    { eng: "beach", ger: "Strand", ctx: "on the beach = am Strand" },
    { eng: "(to) choose", ger: "(aus)wählen", ctx: "irregular verb (simple past: chose)" },
    { eng: "(to) fall", ger: "fallen; hinfallen", ctx: "irregular verb (simple past: fell)" },
    { eng: "also", ger: "auch", ctx: "adverb (I like apples and I also like oranges.)" },

    // --- Page 3 (Bildschirmfoto 2026-06-27 um 23.05.58.jpg) ---
    { eng: "(to) be fun", ger: "Spaß machen", ctx: "phrase (Swimming is fun.)" },
    { eng: "winter", ger: "Winter", ctx: "season" },
    { eng: "I could", ger: "ich konnte / ich könnte", ctx: "past modal form (negative: couldn't)" },
    { eng: "(to) like sth. best", ger: "etwas am liebsten mögen", ctx: "phrase (I like football best.)" },
    { eng: "(to) remember", ger: "daran denken, nicht vergessen; sich erinnern an", ctx: "verb" },
    { eng: "(to) take", ger: "dauern, (Zeit) brauchen, in Anspruch nehmen", ctx: "irregular verb (simple past: took)" },
    { eng: "only", ger: "nur, bloß; erst", ctx: "adverb (My sister is only two.)" },
    { eng: "tree", ger: "Baum", ctx: "noun (an apple tree)" },
    { eng: "hot", ger: "heiß, warm", ctx: "opposite of cold (hot chocolate = heiße Schokolade)" },
    { eng: "money", ger: "Geld", ctx: "uncountable noun" },
    { eng: "locker", ger: "Spind, Schließfach", ctx: "noun" },
    { eng: "adult", ger: "Erwachsene/-r", ctx: "person" },
    { eng: "(to) order", ger: "bestellen", ctx: "verb" },
    { eng: "I'll have ...", ger: "ich nehme ... (beim Essen)", ctx: "short for: I will have" },
    { eng: "That's £2.", ger: "Das macht 2 Pfund.", ctx: "phrase" },
    { eng: "menu", ger: "Speisekarte", ctx: "noun" },
    { eng: "ham", ger: "Schinken", ctx: "food" },
    { eng: "banana", ger: "Banane", ctx: "fruit" },
    { eng: "no", ger: "kein, keine; verboten", ctx: "Sorry, no dogs! = Hunde verboten!" },
    { eng: "(school) club", ger: "AG (in der Schule)", ctx: "noun" },
    { eng: "It isn't only about ...", ger: "Es geht nicht nur darum, ...", ctx: "phrase" },
    { eng: "chess", ger: "Schach", ctx: "game" },
    { eng: "trampolining", ger: "Trampolinspringen/-turnen", ctx: "sport" },
    { eng: "gym", ger: "Turnhalle, Sporthalle; Fitnessstudio", ctx: "building" },
    { eng: "dangerous", ger: "gefährlich", ctx: "adjective (a dangerous fish)" },
    { eng: "(to) hate", ger: "hassen", ctx: "verb (opposite of to love)" },

    // --- Page 4 (Bildschirmfoto 2026-06-27 um 23.06.06.jpg) ---
    { eng: "mind map", ger: "Gedankenkarte, Wortnetz, Mindmap", ctx: "noun" },
    { eng: "ramp", ger: "Rampe", ctx: "noun (riding a bike on a ramp)" },
    { eng: "drive", ger: "Zufahrt (z. B. zu einer Garage)", ctx: "noun" },
    { eng: "(to) turn (a)round", ger: "(sich) umdrehen", ctx: "verb" },
    { eng: "up", ger: "hinauf, hoch", ctx: "opposite of down" },
    { eng: "(to) hit", ger: "treffen auf, schlagen, prallen, stoßen gegen/auf", ctx: "irregular verb (simple past: hit)" },
    { eng: "(to) fly", ger: "fliegen", ctx: "irregular verb (simple past: flew)" },
    { eng: "air", ger: "Luft", ctx: "noun" },
    { eng: "garage", ger: "Garage", ctx: "noun (stressed on the first syllable)" },
    { eng: "stupid", ger: "dumm, blöd", ctx: "adjective" },
    { eng: "fault", ger: "Fehler; Schuld", ctx: "It wasn't my fault. = Es war nicht meine Schuld." },
    { eng: "(to) move", ger: "(sich) bewegen; verschieben; umziehen", ctx: "verb" },
    { eng: "(to) swap", ger: "tauschen", ctx: "verb" },
    { eng: "(to) shout", ger: "rufen", ctx: "verb" },
    { eng: "(to) disappear", ger: "verschwinden", ctx: "verb" },
    { eng: "(to) crash (into)", ger: "krachen; einen Unfall haben, zusammenstoßen (mit)", ctx: "verb" },
    { eng: "Never mind.", ger: "Das macht nichts. / Nicht so schlimm.", ctx: "phrase (Never mind him.)" },
    { eng: "(tea) set", ger: "Set, Garnitur, (Tee-)Service", ctx: "noun" },
    { eng: "cup", ger: "Tasse", ctx: "noun (a cup of tea)" },
    { eng: "(to) say sorry to sb.", ger: "sich bei jemandem entschuldigen", ctx: "phrase" },
    { eng: "(to) break", ger: "(zer)brechen; kaputtgehen; kaputtmachen", ctx: "irregular verb (simple past: broke)" },
    { eng: "competition", ger: "Wettbewerb", ctx: "noun" },
    { eng: "page (= p.)", ger: "(Buch-, Heft-)Seite", ctx: "on page 15 / on p. 15" },
    { eng: "drawing", ger: "Zeichnung", ctx: "noun" },
    { eng: "speech bubble", ger: "Sprechblase", ctx: "noun" },

    // --- Page 5 (Irregular Verbs Summary - Bildschirmfoto 2026-06-27 um 23.06.15.png) ---
    { eng: "(to) buy", ger: "kaufen", ctx: "irregular verb summary (simple past: bought)" },
    { eng: "(to) do", ger: "machen, tun", ctx: "irregular verb summary (simple past: did)" },
    { eng: "(to) meet", ger: "treffen", ctx: "irregular verb summary (simple past: met)" },
    { eng: "(to) say", ger: "sagen", ctx: "irregular verb summary (simple past: said [sed])" },
    { eng: "(to) sing", ger: "singen", ctx: "irregular verb summary (simple past: sang)" }
];