// Vocabulary Data for Grade 5 - Unit 6
// Sources referenced: Bildschirmfoto 2026-06-27 um 23.07.24.jpg to 23.08.00.png

const e5u6_data = [
    // --- Page 1 (Bildschirmfoto 2026-06-27 um 23.07.24.jpg) ---
    { eng: "special", ger: "besondere(-r, -s)", ctx: "... is special / What's special about this place?" },
    { eng: "January", ger: "Januar", ctx: "Month 1" },
    { eng: "February", ger: "Februar", ctx: "Month 2" },
    { eng: "March", ger: "März", ctx: "Month 3" },
    { eng: "April", ger: "April", ctx: "Month 4" },
    { eng: "May", ger: "Mai", ctx: "Month 5" },
    { eng: "June", ger: "Juni", ctx: "Month 6" },
    { eng: "July", ger: "Juli", ctx: "Month 7" },
    { eng: "August", ger: "August", ctx: "Month 8" },
    { eng: "September", ger: "September", ctx: "Month 9" },
    { eng: "October", ger: "Oktober", ctx: "Month 10" },
    { eng: "November", ger: "November", ctx: "Month 11" },
    { eng: "December", ger: "Dezember", ctx: "Month 12" },
    { eng: "birthday", ger: "Geburtstag", ctx: "Happy birthday!" },
    { eng: "fancy dress", ger: "Kostüm, Verkleidung", ctx: "no plural (a fancy dress party)" },
    { eng: "balloon", ger: "Ballon", ctx: "noun" },
    { eng: "(to) blow", ger: "pusten, blasen; wehen", ctx: "irregular verb (simple past: blew)" },
    { eng: "out (of ...)", ger: "aus, heraus/hinaus; aus ... (heraus/hinaus)", ctx: "into the house <-> out of the house" },
    { eng: "wish", ger: "Wunsch", ctx: "noun ((to) make a wish = sich etwas wünschen)" },
    { eng: "(to) wish", ger: "wünschen", ctx: "verb" },
    { eng: "present", ger: "Geschenk", ctx: "noun" },
    { eng: "candle", ger: "Kerze", ctx: "noun" },
    { eng: "(to) look", ger: "aussehen", ctx: "Your school uniform looks great." },
    { eng: "plum", ger: "Pflaume", ctx: "fruit" },
    { eng: "strawberry", ger: "Erdbeere", ctx: "fruit" },
    { eng: "date", ger: "Datum", ctx: "noun" },
    { eng: "Halloween", ger: "Halloween (der Abend des 31. Oktober)", ctx: "holiday" },
    { eng: "When's your birthday?", ger: "Wann hast du Geburtstag?", ctx: "Question (short for: When is)" },

    // --- Page 2 (Bildschirmfoto 2026-06-27 um 23.07.32.jpg) ---
    { eng: "invitation (to)", ger: "Einladung (zu, nach)", ctx: "noun" },
    { eng: "whose", ger: "wessen", ctx: "question word" },
    { eng: "which", ger: "welche(-r, -s)", ctx: "pronoun" },
    { eng: "(to) celebrate", ger: "feiern", ctx: "verb (My grandmother celebrated her 70th birthday.)" },
    { eng: "(to) invite (to)", ger: "einladen (zu, nach)", ctx: "verb ((to) invite -> invitation)" },
    { eng: "smart", ger: "schick", ctx: "adjective (Max, bring me the shoe!)" },
    { eng: "(to) bring", ger: "bringen, mitbringen", ctx: "irregular verb (simple past: brought)" },
    { eng: "RSVP", ger: "u.A.w.g. (um Antwort wird gebeten)", ctx: "short for French: répondez s'il vous plaît" },
    { eng: "Polish", ger: "polnisch; Polnisch", ctx: "country: Poland -> language/adjective: Polish" },
    { eng: "(to) hold", ger: "halten", ctx: "irregular verb (simple past: held)" },
    { eng: "flower", ger: "Blume; Blüte", ctx: "noun" },
    { eng: "Chinese", ger: "chinesisch; Chinesisch", ctx: "country: China -> language/adjective: Chinese" },
    { eng: "long", ger: "lang", ctx: "opposite of short" },
    { eng: "noodles", ger: "Nudeln", ctx: "always plural noun (In China people have noodles.)" },
    { eng: "person", ger: "Person", ctx: "plural is usually: people (one person - five people)" },
    { eng: "life", ger: "Leben", ctx: "irregular plural: lives (one life - nine lives)" },
    { eng: "envelope", ger: "(Brief-)Umschlag", ctx: "noun" },
    { eng: "lucky", ger: "Glücks-, glücklich", ctx: "She was lucky = Sie hatte Glück. / She was happy = Sie war glücklich." },
    { eng: "(to) ask sb. to do sth.", ger: "jn. bitten, etwas zu tun", ctx: "phrase (Jalen asked Li to help him.)" },
    { eng: "(to) drive", ger: "(mit dem Auto) fahren", ctx: "irregular verb (simple past: drove)" },
    { eng: "car", ger: "Auto", ctx: "noun (a green car)" },
    { eng: "moment", ger: "Moment", ctx: "at the moment = im Moment, zurzeit" },
    { eng: "bored", ger: "gelangweilt", ctx: "The film was boring (langweilig). I was really bored (gelangweilt)." },
    { eng: "(to) stop", ger: "(an)halten; stoppen; aufhören (mit)", ctx: "verb (The car stopped. / Stop hitting your brother!)" },
    { eng: "away", ger: "weg, fort", ctx: "(to) walk away / (to) go away = weggehen" },

    // --- Page 3 (Bildschirmfoto 2026-06-27 um 23.07.44.jpg) ---
    { eng: "(to) describe (sth. to sb.)", ger: "(jm. etwas) beschreiben", ctx: "verb (Describe the picture to him/her.)" },
    { eng: "back", ger: "Rücken; Rückseite, hinterer Teil", ctx: "at the back (of the bus/cinema) = hinten" },
    { eng: "middle", ger: "Mitte", ctx: "noun (Lily is in the middle.)" },
    { eng: "front", ger: "vorderer Teil, Vorderseite", ctx: "at the front (of the bus/cinema) = vorne" },
    { eng: "wheelchair", ger: "Rollstuhl", ctx: "noun" },
    { eng: "angry", ger: "wütend", ctx: "adjective" },
    { eng: "excited", ger: "aufgeregt, gespannt", ctx: "adjective (pay attention to spelling!)" },
    { eng: "nervous", ger: "nervös, aufgeregt", ctx: "adjective (stressed on the first syllable)" },
    { eng: "scared", ger: "ängstlich, verängstigt", ctx: "Are you scared of spiders? / (to) be scared (of)" },
    { eng: "(to) be worried (about)", ger: "beunruhigt sein, besorgt sein (wegen)", ctx: "phrase (I'm worried about Dave.)" },
    { eng: "barbecue", ger: "Grillfest, Grillen", ctx: "noun" },
    { eng: "event", ger: "Ereignis", ctx: "noun (A big event in a child's life.)" },
    { eng: "trip", ger: "Ausflug; Reise", ctx: "class trip / school trip = Klassen-/Schulausflug" },
    { eng: "holiday(s)", ger: "Urlaub(s-); Ferien", ctx: "on holiday = im/in den Urlaub" },
    { eng: "(to) visit", ger: "besuchen", ctx: "verb (Can we visit Sophie on Sunday?)" },
    { eng: "next", ger: "nächste(-r, -s)", ctx: "last weekend -> this weekend -> next weekend" },
    { eng: "(to) happen (to sb.)", ger: "(jm.) geschehen, passieren", ctx: "verb (Say what's happening in the pictures.)" },
    { eng: "summer", ger: "Sommer", ctx: "season (winter <-> summer)" },
    { eng: "information", ger: "Information(en)", ctx: "never with 'an' or plural -s! (Read this information.)" },
    { eng: "May I ...?", ger: "Darf ich ...?", ctx: "modal verb (no -s for he/she/it! May she go home?)" },
    { eng: "must", ger: "müssen", ctx: "modal verb (He must buy milk.)" },
    { eng: "(to) leave", ger: "lassen, etwas zurücklassen", ctx: "irregular verb (simple past: left / Leave your pets at home.)" },

    // --- Page 4 (Bildschirmfoto 2026-06-27 um 23.07.51.jpg) ---
    { eng: "rubbish", ger: "(Haus-)Müll, Abfall", ctx: "noun (Don't leave your rubbish.)" },
    { eng: "bin", ger: "(Müll-)Eimer", ctx: "Please put it in the bin." },
    { eng: "shorts", ger: "kurze Hose", ctx: "always plural noun (These shorts are new.)" },
    { eng: "mobile (phone)", ger: "Handy", ctx: "noun (In English always use mobile or mobile phone!)" },
    { eng: "my cousins' shoes", ger: "die Schuhe meiner Cousins/Cousinen", ctx: "plural possessive apostrophe rule" },
    { eng: "(to) find", ger: "finden", ctx: "irregular verb (simple past: found / Max, find Nick!)" },
    { eng: "British", ger: "britisch", ctx: "adjective" },
    { eng: "(Great) Britain", ger: "Großbritannien", ctx: "country (England, Scotland, Wales)" },
    { eng: "the United Kingdom", ger: "das Vereinigte Königreich", ctx: "the UK = England, Scotland, Wales, Northern Ireland" },
    { eng: "flag", ger: "Fahne, Flagge", ctx: "the British flag" },
    { eng: "the most", ger: "die meisten Menschen / am meisten Zeit", ctx: "the most people / time" },
    { eng: "later", ger: "später", ctx: "adverb" },
    { eng: "firework", ger: "Feuerwerkskörper", ctx: "noun (a firework / fireworks)" },
    { eng: "(to) wait (for)", ger: "warten (auf)", ctx: "verb (Wait a minute. / Wait for me, please!)" },
    { eng: "It's me.", ger: "Ich bin's.", ctx: "phrase (Hello, Mrs Palmer, it's me, Tim.)" },
    { eng: "hospital", ger: "Krankenhaus", ctx: "building" },
    { eng: "little", ger: "klein", ctx: "adjective" },
    { eng: "accident", ger: "Unfall", ctx: "noun" },
    { eng: "hand", ger: "Hand", ctx: "noun" },

    // --- Page 5 (Bildschirmfoto 2026-06-27 um 23.08.00.png) ---
    { eng: "(to) hurt", ger: "verletzen; wehtun", ctx: "irregular verb (simple past: hurt / I hurt my hand. / My hand hurts.)" },
    { eng: "careful", ger: "vorsichtig", ctx: "adjective" }
];