const e6u1_data = [
    { id: "1_1", eng: "media", phon: "['mi:diə]", ger: "Medien", ctx: "Today it's so easy to use media like chat or email. The story of the pop star's accident was in all the media." },
    { id: "1_2", eng: "screen", phon: "[skri:n]", ger: "Bildschirm", ctx: "Abbildung eines Fernsehers/Monitors im Buch." },
    { id: "1_3", eng: "(to) download", phon: "[daʊn'ləʊd]", ger: "herunterladen", ctx: "Gegenteil: (to) upload = hochladen" },
    { id: "1_4", eng: "(to) phone", phon: "[fəʊn]", ger: "anrufen, telefonieren", ctx: "verb: (to) phone – noun: phone = Telefon" },
    { id: "1_5", eng: "camera", phon: "['kæmərə]", ger: "Fotoapparat; Kamera", ctx: "Kontext-Satz: a camera" },
    { id: "1_6", eng: "games console", phon: "[kən'səʊl]", ger: "Spielekonsole", ctx: "Eintrag unter der Rubrik Medien." },
    { id: "1_7", eng: "on TV", phon: "-", ger: "im Fernsehen", ctx: "Text 1 Einleitung" },
    { id: "1_8", eng: "(to) be on", phon: "[ɒn]", ger: "gezeigt werden (Kino, Fernsehen), stattfinden", ctx: "What's on at the theatre this evening?" },
    { id: "1_9", eng: "news", phon: "[nju:z]", ger: "Nachrichten", ctx: "English: That's good news. / German: Das sind gute Nachrichten." },
    { id: "1_10", eng: "9 am", phon: "[eɪ'em]", ger: "9 Uhr morgens / vormittags", ctx: "Zeitangabe" },
    { id: "1_11", eng: "7 pm", phon: "[pi:'em]", ger: "7 Uhr nachmittags / abends, 19 Uhr", ctx: "Zeitangabe" },
    { id: "1_12", eng: "international", phon: "[ɪntə'næʃnəl]", ger: "international", ctx: "Gegenteil: national ◀▶ international" },
    { id: "1_13", eng: "past", phon: "[pɑ:st]", ger: "Vergangenheit", ctx: "Substantiv" },
    { id: "1_14", eng: "gamer", phon: "['ɡeɪmə]", ger: "Spieler, Gamer", ctx: "Gamer-Szene" },
    { id: "1_15", eng: "exciting", phon: "[ɪk'saɪtɪŋ]", ger: "aufregend", ctx: "Gegenteil: exciting ◀▶ boring" },
    { id: "1_16", eng: "(to) test", phon: "[test]", ger: "testen", ctx: "verb: (to) test – noun: test = Klassenarbeit, Test" },
    { id: "1_17", eng: "company", phon: "['kʌmpəni]", ger: "Firma, Gesellschaft", ctx: "Wirtschaft / Business" },
    { id: "1_18", eng: "stone", phon: "[stəʊn]", ger: "Stein", ctx: "Beispiel: a stone circle (Steinkreis)" },
    { id: "1_19", eng: "circle", phon: "['sɜ:kl]", ger: "Kreis", ctx: "Geometrie / Formen" },
    { id: "1_20", eng: "calendar", phon: "['kælɪndə]", ger: "Kalender", ctx: "⚠️ Betonung auf der 1. Silbe: calendar" },
    { id: "1_21", eng: "(to) build, built", phon: "[bɪld], [bɪlt]", ger: "bauen", ctx: "Unregelmäßiges Verb" },
    { id: "1_22", eng: "against", phon: "[ə'ɡenst]", ger: "gegen", ctx: "Gegenteil: against ◀▶ for | Satz: Dave is fighting against Nick." },
    { id: "1_23", eng: "stadium", phon: "['steɪdiəm]", ger: "Stadion", ctx: "Sportstätten" },
    { id: "1_24", eng: "match", phon: "[mætʃ]", ger: "Spiel, Wettkampf", ctx: "Sport" },
    { id: "1_25", eng: "(to) win, won", phon: "[wɪn], [wʌn]", ger: "gewinnen", ctx: "Satz: I feel good when my football team wins." },
    { id: "1_26", eng: "subject", phon: "['sʌbdʒɪkt]", ger: "Thema", ctx: "⚠️ subject = 1. Schulfach; 2. Thema" },
    { id: "1_27", eng: "winner", phon: "['wɪnə]", ger: "Gewinner/in, Sieger/in", ctx: "Personenbezeichnung" },
    { id: "1_28", eng: "problem", phon: "['prɒbləm]", ger: "Problem", ctx: "⚠️ Betonung auf der 1. Silbe: problem" },
    { id: "1_29", eng: "prize", phon: "[praɪz]", ger: "Preis, Gewinn", ctx: "Auszeichnung" },
    { id: "1_30", eng: "another", phon: "[ə'nʌðə]", ger: "ein/e andere/r/s; noch ein/e", ctx: "Sätze: Can I have another pet? Can I have another apple?" },
    { id: "1_31", eng: "(to) go wrong", phon: "-", ger: "schiefgehen", ctx: "Idiom / Wendung" },
    { id: "1_32", eng: "programme", phon: "['prəʊɡræm]", ger: "(Fernseh-)Sendung", ctx: "Medienbegriff" },
    { id: "1_33", eng: "who", phon: "[hu:]", ger: "wem; wen", ctx: "Fragewort. Sätze: Who have you seen? Who is the message from?" },
    { id: "1_34", eng: "detective", phon: "[dɪ'tektɪv]", ger: "Detektiv/in", ctx: "⚠️ Betonung auf der 2. Silbe: detective" },
    { id: "1_35", eng: "detective series", phon: "[dɪ'tektɪv 'sɪəri:z]", ger: "Krimiserie", ctx: "Plural: detective series" },
    { id: "1_36", eng: "documentary", phon: "[dɒkju'mentri]", ger: "Dokumentarfilm", ctx: "TV-Genre" },
    { id: "1_37", eng: "reality", phon: "[ri'æliti]", ger: "Realität, Wirklichkeit", ctx: "⚠️ Betonung auf der 2. Silbe: reality" },
    { id: "1_38", eng: "soap (opera)", phon: "[səʊp]", ger: "Seifenoper, Soap", ctx: "soap = Seife | opera = Oper" },
    { id: "1_39", eng: "crime", phon: "[kraɪm]", ger: "Verbrechen; Kriminalität", ctx: "⚠️ Crime is a big problem. EN: crime film, detective series" },
    { id: "1_40", eng: "real", phon: "[rɪəl]", ger: "echt, wirklich", ctx: "Adjektiv" },
    { id: "1_41", eng: "type (of)", phon: "[taɪp]", ger: "Art, Sorte", ctx: "Kategorisierung" },
    { id: "1_42", eng: "survey", phon: "['sɜ:veɪ]", ger: "Umfrage", ctx: "Introduction 1 | Wendung: (to) do a survey" },
    { id: "1_43", eng: "(to) count", phon: "[kaʊnt]", ger: "zählen", ctx: "Verb" },
    { id: "1_44", eng: "(to) chat (with)", phon: "[tʃæt]", ger: "chatten (mit); sich unterhalten (mit)", ctx: "verb: (to) chat – noun: chat = Unterhaltung" },
    { id: "1_45", eng: "safe", phon: "[seɪf]", ger: "sicher (gefahrlos)", ctx: "Gegenteil: safe ◀▶ dangerous" },
    { id: "1_46", eng: "more than", phon: "-", ger: "mehr als", ctx: "⚠️ Steigerung: much/many – more – (the) most" },
    { id: "1_47", eng: "dark", phon: "[dɑ:k]", ger: "dunkel", ctx: "Skills training | Haarfarbe/Licht" },
    { id: "1_48", eng: "straight", phon: "[streɪt]", ger: "gerade; (Haare) glatt", ctx: "Haarstruktur: dark and straight" },
    { id: "1_49", eng: "curly", phon: "['kɜ:li]", ger: "lockig", ctx: "Haarstruktur: blond and curly" },
    { id: "1_50", eng: "bald", phon: "[bɔ:ld]", ger: "kahl, glatzköpfig", ctx: "He's bald." },
    { id: "1_51", eng: "braces (pl)", phon: "['breɪsɪz]", ger: "(eine) Zahnklammer", ctx: "Pluralwort" },
    { id: "1_52", eng: "tooth, pl teeth", phon: "[tu:θ], [ti:θ]", ger: "Zahn", ctx: "Unregelmäßiger Plural" },
    { id: "1_53", eng: "glasses (pl)", phon: "['ɡlɑ:sɪz]", ger: "(eine) Brille", ctx: "Pluralwort" },
    { id: "1_54", eng: "young", phon: "[jʌŋ]", ger: "jung", ctx: "Gegenteil: young ◀▶ old" },
    { id: "1_55", eng: "kind", phon: "[kaɪnd]", ger: "nett, freundlich", ctx: "Charaktereigenschaft" },
    { id: "1_56", eng: "serious", phon: "['sɪəriəs]", ger: "ernst", ctx: "Sätze: Jen is a very serious person. Are you serious?" },
    { id: "1_57", eng: "shy", phon: "[ʃaɪ]", ger: "scheu, schüchtern", ctx: "Charaktereigenschaft" },
    { id: "1_58", eng: "e-friend", phon: "['i:frend]", ger: "E-Mail-Freund/in", ctx: "Internet-Kontakte" },
    { id: "1_59", eng: "eye", phon: "[aɪ]", ger: "Auge", ctx: "Körperteil (an eye)" },
    { id: "1_60", eng: "(to) stand, stood", phon: "[stænd], [stʊd]", ger: "stehen; sich (hin)stellen", ctx: "Introduction 2 | You don't need to stand." },
    { id: "1_61", eng: "jacket", phon: "['dʒækɪt]", ger: "Jacke, Jackett", ctx: "Kleidung" },
    { id: "1_62", eng: "exercise", phon: "['eksəsaɪz]", ger: "Übung, Aufgabe", ctx: "Schule/Lernen" },
    { id: "1_63", eng: "cook", phon: "[kʊk]", ger: "Koch, Köchin", ctx: "Beruf (two cooks)" },
    { id: "1_64", eng: "I'd like you to be ...", phon: "-", ger: "Ich möchte, dass ihr ... seid.", ctx: "Study skills | Lehrer-Anweisung" },
    { id: "1_65", eng: "(to) put ... away", phon: "-", ger: "... weglegen, zur Seite legen", ctx: "Klassenzimmer-Anweisung" },
    { id: "1_66", eng: "(to) put up your hand", phon: "-", ger: "sich melden, aufzeigen", ctx: "They're putting up their hands." },
    { id: "1_67", eng: "(to) repeat", phon: "[rɪ'pi:t]", ger: "wiederholen", ctx: "Could you repeat that, please?" },
    { id: "1_68", eng: "Repeat after me.", phon: "-", ger: "Sprich / Sprecht mir nach.", ctx: "Aufforderung im Unterricht" },
    { id: "1_69", eng: "What's for homework?", phon: "-", ger: "Was haben wir als Hausaufgabe(n) auf?", ctx: "Schüler-Frage" },
    { id: "1_70", eng: "message in a bottle", phon: "-", ger: "Flaschenpost", ctx: "Text 2 | a message in a bottle by the sea" },
    { id: "1_71", eng: "by the sea", phon: "[baɪ]", ger: "am Meer", ctx: "by ◀▶ near" },
    { id: "1_72", eng: "situation", phon: "[sɪtʃu'eɪʃn]", ger: "Situation", ctx: "⚠️ Betonung auf der 3. Silbe: situation" },
    { id: "1_73", eng: "path", phon: "[pɑ:θ]", ger: "Weg, Pfad", ctx: "Abbildung eines Waldwegs" },
    { id: "1_74", eng: "suddenly", phon: "['sʌdənli]", ger: "plötzlich, auf einmal", ctx: "Adverb" },
    { id: "1_75", eng: "(to) pick sth. up", phon: "[pɪk 'ʌp]", ger: "etwas aufheben (vom Boden), etwas hochheben", ctx: "Aktion" },
    { id: "1_76", eng: "(to) seem (to be / do)", phon: "[si:m]", ger: "erscheinen; (zu sein / zu tun) scheinen", ctx: "It seems big. He seems to be very sad." },
    { id: "1_77", eng: "joke", phon: "[dʒəʊk]", ger: "Witz, Scherz", ctx: "I want to become a pirate. - Good joke!" },
    { id: "1_78", eng: "alone", phon: "[ə'ləʊn]", ger: "allein", ctx: "Gegenteil: alone ◀▶ together" },
    { id: "1_79", eng: "piece of paper", phon: "[pi:s əv 'peɪpə]", ger: "Stück Papier, Zettel", ctx: "piece = Stück, Teil" },
    { id: "1_80", eng: "through", phon: "[θru:]", ger: "durch", ctx: "Satz: I can see the writing through the envelope." },
    { id: "1_81", eng: "writing", phon: "['raɪtɪŋ]", ger: "Schrift", ctx: "Substantiv" },
    { id: "1_82", eng: "trust", phon: "[trʌst]", ger: "vertrauen", ctx: "verb: (to) trust – noun: trust = Vertrauen" },
    { id: "1_83", eng: "if", phon: "[ɪf]", ger: "wenn, falls", ctx: "what if ...? = was wäre, wenn?" },
    { id: "1_84", eng: "writer", phon: "['raɪtə]", ger: "Autor/in, Verfasser/in", ctx: "Beruf" },
    { id: "1_85", eng: "danger", phon: "['deɪndʒə]", ger: "Gefahr", ctx: "there is no danger = it's not dangerous" },
    { id: "1_86", eng: "(to) go around and around", phon: "-", ger: "sich (immer wieder) drehen", ctx: "Bewegung" },
    { id: "1_87", eng: "head", phon: "[hed]", ger: "Kopf", ctx: "Körperteil" },
    { id: "1_88", eng: "maybe", phon: "['meɪbi]", ger: "vielleicht", ctx: "Let me think - maybe this isn't a bad idea!" },
    { id: "1_89", eng: "experiment", phon: "[ɪk'sperɪmənt]", ger: "Experiment", ctx: "In our science club we do great experiments." },
    { id: "1_90", eng: "sand", phon: "[sænd]", ger: "Sand", ctx: "Abbildung mit Erklärungen (wood, rocks, sand)" },
    { id: "1_91", eng: "(to) prove", phon: "[pru:v]", ger: "nachweisen, beweisen", ctx: "Verb" },
    { id: "1_92", eng: "wood", phon: "[wʊd]", ger: "Holz; Wald", ctx: "Naturmaterial" },
    { id: "1_93", eng: "drop", phon: "[drɒp]", ger: "(sich) fallen lassen", ctx: "Aktion" },
    { id: "1_94", eng: "onto the rocks", phon: "['ɒntu, 'ɒntə]", ger: "auf die Felsen (hinauf)", ctx: "Abbildung eines Springers (onto the box)" },
    { id: "1_95", eng: "rock", phon: "[rɒk]", ger: "Felsen", ctx: "⚠️ German: Rock = skirt | English: rock = Felsen" },
    { id: "1_96", eng: "presentation", phon: "[prezn'teɪʃn]", ger: "Referat, Präsentation", ctx: "Your task | (to) give a presentation = ein Referat halten" }
];