const e6u2_data = [
    { id: "2_1", eng: "waterfall", phon: "['wɔ:təfɔ:l]", ger: "Wasserfall", ctx: "Geografisches Merkmal auf der Übersichtskarte." },
    { id: "2_2", eng: "mountain", phon: "['maʊntən]", ger: "Berg", ctx: "Plural: mountains (Abbildung)." },
    { id: "2_3", eng: "lake", phon: "[leɪk]", ger: "(Binnen-)See", ctx: "⚠️ Unterscheide: the sea = das Meer (die See) ◀▶ the lake = der See." },
    { id: "2_4", eng: "coast", phon: "[kəʊst]", ger: "Küste", ctx: "Übergang von Land zu Meer." },
    { id: "2_5", eng: "field", phon: "[fi:ld]", ger: "Feld; Weide", ctx: "⚠️ Präposition beachten: EN: 'the ponies in the field' ◀▶ DE: 'die Ponys auf der Weide'." },
    { id: "2_6", eng: "grass", phon: "[ɡrɑ:s]", ger: "Gras; Rasen", ctx: "Bodenbewuchs." },
    { id: "2_7", eng: "postcard", phon: "['pəʊstkɑ:d]", ger: "Postkarte", ctx: "Urlaubsgrüße." },
    { id: "2_8", eng: "pony", phon: "['pəʊni]", ger: "Pony", ctx: "⚠️ Phonetischer Fehltritt-Schutz: ['pəʊni] klingt anders als im Deutschen! Plural: the ponies." },
    { id: "2_9", eng: "farm", phon: "[fɑ:m]", ger: "Bauernhof, Farm", ctx: "Abbildung mit Waldhütte." },
    { id: "2_10", eng: "moor", phon: "[mɔ:]", ger: "Heide(land); Moor", ctx: "Landschaftsform." },
    { id: "2_11", eng: "hill", phon: "[hɪl]", ger: "Hügel", ctx: "Landschaftsform." },
    { id: "2_12", eng: "forest", phon: "['fɒrɪst]", ger: "Wald", ctx: "Dichter Baumbewuchs." },
    { id: "2_13", eng: "bridge", phon: "[brɪdʒ]", ger: "Brücke", ctx: "Überquerungshilfe für Flüsse." },
    { id: "2_14", eng: "over", phon: "['əʊvə]", ger: "über, hinüber", ctx: "Richtungsangabe." },
    { id: "2_15", eng: "river", phon: "['rɪvə]", ger: "Fluss", ctx: "Fließgewässer." },
    { id: "2_16", eng: "(to) get (to)", phon: "-", ger: "gelangen, (hin)kommen (nach)", ctx: "Text 1 Einstieg" },
    { id: "2_17", eng: "(to) get, got", phon: "-", ger: "bekommen / holen / gelangen", ctx: "⚠️ Drei Bedeutungen: 1. bekommen (He got a job), 2. holen/besorgen (get some milk), 3. gelangen/kommen (get to the museum)." },
    { id: "2_18", eng: "raft", phon: "[rɑ:ft]", ger: "Floß", ctx: "Wasserfahrzeug." },
    { id: "2_19", eng: "wetsuit", phon: "['wetsu:t]", ger: "Taucheranzug, Neoprenanzug", ctx: "Wassersportbekleidung." },
    { id: "2_20", eng: "swimming costume", phon: "['swɪmɪŋ kɒstju:m]", ger: "Badeanzug", ctx: "Für Damen." },
    { id: "2_21", eng: "swimming trunks (pl)", phon: "['swɪmɪŋ trʌŋks]", ger: "Badehose", ctx: "Pluralwort (Abbildung Strand)." },
    { id: "2_22", eng: "towel", phon: "['taʊəl]", ger: "Handtuch", ctx: "Zum Abtrocknen." },
    { id: "2_23", eng: "you'll (= you will) fall", phon: "[wɪl]", ger: "du wirst fallen", ctx: "⚠️ Grammatik: I will have fun = Ich werde Spaß haben. (Zukunft)" },
    { id: "2_24", eng: "definitely", phon: "['defɪnətli]", ger: "auf jeden Fall; ganz bestimmt", ctx: "Adverb der Sicherheit." },
    { id: "2_25", eng: "you won't need (= will not)", phon: "[wəʊnt]", ger: "du wirst ... nicht brauchen", ctx: "Verneintes Futur." },
    { id: "2_26", eng: "(to) forget, forgot", phon: "[fə'ɡet], [fə'ɡɒt]", ger: "vergessen", ctx: "Gegenteil: forget ◀▶ remember. Beispielsatz: It's dad's birthday tomorrow. Don't forget it." },
    { id: "2_27", eng: "(to) hike", phon: "[haɪk]", ger: "wandern", ctx: "Nomen: hiking = das Wandern. Hiking in the mountains is fun." },
    { id: "2_28", eng: "boot", phon: "[bu:t]", ger: "Stiefel", ctx: "Schuhwerk." },
    { id: "2_29", eng: "map", phon: "[mæp]", ger: "Landkarte, Stadtplan", ctx: "Plural: maps (Abbildung im Buch)." },
    { id: "2_30", eng: "public", phon: "['pʌblɪk]", ger: "öffentlich", ctx: "Gegenteil: public ◀▶ private." },
    { id: "2_31", eng: "private", phon: "['praɪvət]", ger: "privat; persönlich", ctx: "⚠️ Betonung auf der 1. Silbe: private." },
    { id: "2_32", eng: "gate", phon: "[ɡeɪt]", ger: "Tor, Gatter", ctx: "Abbildung Holztor." },
    { id: "2_33", eng: "tent", phon: "[tent]", ger: "Zelt", ctx: "Campingausrüstung." },
    { id: "2_34", eng: "fire", phon: "['faɪə]", ger: "Feuer", ctx: "Abbildung Lagerfeuer." },
    { id: "2_35", eng: "penknife, pl penknives", phon: "['pennaɪf], ['pennaɪvz]", ger: "Taschenmesser", ctx: "Unregelmäßiger Plural mit v." },
    { id: "2_36", eng: "across a bridge", phon: "[ə'krɒs]", ger: "über eine Brücke", ctx: "Satz: Birds can fly across the sea." },
    { id: "2_37", eng: "just", phon: "[dʒʌst]", ger: "nur, bloß; einfach", ctx: "Satz: Just listen to me for five minutes, please." },
    { id: "2_38", eng: "beautiful", phon: "['bju:tɪfl]", ger: "wunderschön", ctx: "Satz: Your baby sister is a beautiful little girl." },
    { id: "2_39", eng: "probably", phon: "['prɒbəbli]", ger: "wahrscheinlich", ctx: "Adverb." },
    { id: "2_40", eng: "deer, pl deer", phon: "[dɪə]", ger: "Reh; Hirsch", ctx: "Numerus-Besonderheit: Singular & Plural identisch. red deer = Rotwild." },
    { id: "2_41", eng: "fox", phon: "[fɒks]", ger: "Fuchs", ctx: "Abbildung Comic-Fuchs." },
    { id: "2_42", eng: "litter", phon: "['lɪtə]", ger: "Abfall", ctx: "Wendung: litter bin = Mülleimer." },
    { id: "2_43", eng: "(to) feed, fed", phon: "[fi:d], [fed]", ger: "füttern; ernähren", ctx: "Satz: Can I feed the rabbits?" },
    { id: "2_44", eng: "cave", phon: "[keɪv]", ger: "Höhle", ctx: "Felsformation." },
    { id: "2_45", eng: "hat", phon: "[hæt]", ger: "Hut, Mütze", ctx: "Kopfbedeckung." },
    { id: "2_46", eng: "glove", phon: "[ɡʌv]", ger: "Handschuh", ctx: "Wendung: a pair of gloves = ein Paar Handschuhe." },
    { id: "2_47", eng: "torch", phon: "[tɔ:tʃ]", ger: "Taschenlampe", ctx: "Abbildung Leuchtfunktion." },
    { id: "2_48", eng: "wet", phon: "[wet]", ger: "nass", ctx: "Zustand." },
    { id: "2_49", eng: "rule", phon: "[ru:l]", ger: "Regel", ctx: "Satz: Football is fun because its rules are so easy." },
    { id: "2_50", eng: "sign", phon: "[saɪn]", ger: "Schild, Zeichen", ctx: "Wegweiser / Hinweisschild." },
    { id: "2_51", eng: "road", phon: "[rəʊd]", ger: "Straße (Landstraße zwischen Orten)", ctx: "⚠️ Unterschied im Buch: 'in Hill Road' / 'in Park Street' nutzen die Präposition 'in'." },
    { id: "2_52", eng: "equipment (no pl)", phon: "[ɪ'kwɪpmənt]", ger: "Ausrüstung", ctx: "⚠️ Nicht zählbar, kein Plural-s im Englischen!" },
    { id: "2_53", eng: "(to) agree (with sb./sth.)", phon: "[ə'ɡri:]", ger: "jm. zustimmen; mit etwas einverstanden sein", ctx: "⚠️ Präpositionswechsel: DE: 'Ich stimme DIR zu' ◀▶ EN: 'I agree WITH you'." },
    { id: "2_54", eng: "(to) look after", phon: "[lʊk 'ɑ:ftə]", ger: "sich kümmern um; aufpassen auf", ctx: "Introduction 1 | Phrasal Verbs." },
    { id: "2_55", eng: "(to) look + Präposition", phon: "-", ger: "look after (aufpassen) / look at (ansehen) / look for (suchen)", ctx: "⚠️ Beispiele: look after my baby sister / look at my photos / looking for the post office." },
    { id: "2_56", eng: "sure", phon: "[ʃʊə, ʃɔ:]", ger: "sicher (ohne Zweifel)", ctx: "⚠️ Kontrast: 'Be careful and you'll be safe' (nicht in Gefahr) ◀▶ 'I'm sure you'll be OK' (ohne Zweifel)." },
    { id: "2_57", eng: "farmer", phon: "['fɑ:mə]", ger: "Bauer, Bäuerin; Landwirt/in", ctx: "Berufsbezeichnung." },
    { id: "2_58", eng: "training", phon: "['treɪnɪŋ]", ger: "Training, Ausbildung, Dressur", ctx: "Substantiv." },
    { id: "2_59", eng: "along the path", phon: "[ə'lɒŋ]", ger: "den Weg entlang", ctx: "⚠️ Präposition am Satzanfang: German: Geh die Straße entlang ◀▶ English: Go along the road." },
    { id: "2_60", eng: "past (the wood)", phon: "[pɑ:st]", ger: "(am Wald) vorbei", ctx: "Ortsangabe." },
    { id: "2_61", eng: "quite", phon: "[kwaɪt]", ger: "ziemlich, ganz", ctx: "Sätze: This text is quite long (ziemlich lang). Our new English teacher is quite nice (ganz nett)." },
    { id: "2_62", eng: "report", phon: "[rɪ'pɔ:t]", ger: "Bericht, Referat", ctx: "Introduction 2 | noun: report – verb: (to) report (on) = berichten (über)." },
    { id: "2_63", eng: "(to) charge (a mobile phone)", phon: "[tʃɑ:dʒ]", ger: "(ein Mobiltelefon) aufladen", ctx: "Technik-Wort." },
    { id: "2_64", eng: "(to) lend, lent", phon: "[lend], [lent]", ger: "leihen, verleihen", ctx: "⚠️ Kontrast-Wiederholung: (to) lend sb. sth. = jm. etwas leihen ◀▶ (to) borrow sth. = sich von jm. etwas ausleihen." },
    { id: "2_65", eng: "mine", phon: "[maɪn]", ger: "meine, meiner, meins", ctx: "Possessivpronomen: 'this is my bike = this bike is mine'." },
    { id: "2_66", eng: "Possessivpronomen Tabelle", phon: "-", ger: "mine, yours, his, hers, ours, yours, theirs", ctx: "⚠️ Gesamte Buch-Tabelle: I->mine, you->yours, he->his, she->hers, we->ours, you->yours, they->theirs." },
    { id: "2_67", eng: "mean, meant", phon: "[mi:n], [ment]", ger: "bedeuten; meinen (sagen wollen)", ctx: "Sätze: What does this word mean? What do you mean?" },
    { id: "2_68", eng: "as a singer", phon: "[əz]", ger: "als Sänger/in", ctx: "Study skills | Satz: As a dancer she was very good, but she couldn't sing." },
    { id: "2_69", eng: "ghost", phon: "[ɡəʊst]", ger: "Geist, Gespenst", ctx: "Text 2 Einstieg | Beispiel: a scary ghost." },
    { id: "2_70", eng: "scary", phon: "['skeəri]", ger: "unheimlich, beängstigend, gruselig", ctx: "Adjektiv." },
    { id: "2_71", eng: "strange", phon: "[streɪndʒ]", ger: "seltsam, sonderbar", ctx: "Adjektiv." },
    { id: "2_72", eng: "monk", phon: "[mʌŋk]", ger: "Mönch", ctx: "Abbildung mit Geist." },
    { id: "2_73", eng: "many years ago", phon: "[ə'ɡəʊ]", ger: "vor vielen Jahren", ctx: "⚠️ Wortstellung beachten! German: VOR 20 Minuten ◀▶ English: 20 minutes AGO." },
    { id: "2_74", eng: "heart", phon: "[hɑ:t]", ger: "Herz", ctx: "Anatomie / Metapher." },
    { id: "2_75", eng: "(to) cry", phon: "[kraɪ]", ger: "weinen", ctx: "Satz: She's crying (Abbildung einer weinenden Frau)." },
    { id: "2_76", eng: "until", phon: "[ən'tɪl]", ger: "bis (zeitlich)", ctx: "Satz: We can play until 2 o'clock." },
    { id: "2_77", eng: "not ... until", phon: "-", ger: "erst, wenn ...", ctx: "Satz: We won't eat until mum comes home (Wir essen erst, wenn Mama nach Hause kommt)." },
    { id: "2_78", eng: "ferryman, pl ferrymen", phon: "['ferɪmən]", ger: "Fährmann", ctx: "Beruf (Plural wechselt zu -men)." },
    { id: "2_79", eng: "voice", phon: "[vɔɪs]", ger: "Stimme", ctx: "Akustik." },
    { id: "2_80", eng: "lady", phon: "['leɪdi]", ger: "Dame", ctx: "Anrede / Bezeichnung." },
    { id: "2_81", eng: "brave", phon: "[breɪv]", ger: "mutig", ctx: "⚠️ Fehlübersetzungs-Schutz: brave = mutig (Molly was brave) ◀▶ brav = good (good dog!)." },
    { id: "2_82", eng: "(to) laugh", phon: "[lɑ:f]", ger: "lachen", ctx: "Aktion." },
    { id: "2_83", eng: "the next day / morning", phon: "[nekst]", ger: "am nächsten Tag / Morgen", ctx: "Zeitangabe." },
    { id: "2_84", eng: "Zeitangaben Übersicht", phon: "-", ger: "last, this, next weekend / this evening / one day", ctx: "⚠️ Buch-Tabelle: last weekend (letztes), this weekend (dieses), next weekend (nächstes), this evening (heute Abend), one day (eines Tages)." },
    { id: "2_85", eng: "crazy", phon: "['kreɪzi]", ger: "verrückt", ctx: "Satz: You want to go out in this weather? You must be crazy." },
    { id: "2_86", eng: "figure", phon: "['fɪɡə]", ger: "Figur", ctx: "Nomen." },
    { id: "2_87", eng: "hood", phon: "[hʊd]", ger: "Kapuze", ctx: "Kleidungsdetail." },
    { id: "2_88", eng: "poor", phon: "[pɔ:, pʊə]", ger: "arm", ctx: "Gegenteil: poor ◀▶ rich." },
    { id: "2_89", eng: "(to) be cold", phon: "[kəʊld]", ger: "frieren", ctx: "⚠️ Bedeutungsvielfalt: cold = 1. kalt, 2. Kälte/Erkältung. (to) be cold = frieren, (to) have a cold = erkältet sein." },
    { id: "2_90", eng: "ill", phon: "[ɪl]", ger: "krank", ctx: "Zustand." },
    { id: "2_91", eng: "knock (at sth.)", phon: "[nɒk]", ger: "(an)klopfen (an etwas)", ctx: "Satz: I knocked and went into the room." },
    { id: "2_92", eng: "turn to sth.", phon: "-", ger: "zu etwas werden", ctx: "⚠️ Phrasal-Verzeichnis: turn around (umdrehen), turn left/right (abbiegen), turn to sth. (zu etwas werden)." },
    { id: "2_93", eng: "ice", phon: "[aɪs]", ger: "Eis (gefrorenes Wasser)", ctx: "⚠️ Kontrast im Buch: ice cream (Speiseeis) ◀▶ water turns to ice (gefrorenes Wasser)." },
    { id: "2_94", eng: "leaflet", phon: "['li:flət]", ger: "Faltblatt, Informationsblatt", ctx: "Your task Einstieg" },
    { id: "2_95", eng: "frog", phon: "[frɒɡ]", ger: "Frosch", ctx: "Abbildung eines grünen Laubfrosches (a frog)." },
    { id: "2_96", eng: "contact", phon: "['kɒntækt]", ger: "Kontakt", ctx: "⚠️ Betonung auf der 1. Silbe: contact. noun: contact – verb: (to) contact sb. = Kontakt aufnehmen mit." },
    { id: "2_97", eng: "pigeon", phon: "['pɪdʒɪn]", ger: "Taube", ctx: "Abbildung einer Straßentaube (a pigeon)." }
];