const e6u3_data = [
    { id: "3_1", eng: "skyscraper", phon: "['skaɪskreɪpə]", ger: "Wolkenkratzer", ctx: "Abbildung einer Skyline mit Hochhäusern" },
    { id: "3_2", eng: "modern", phon: "['mɒdn]", ger: "modern", ctx: "⚠️ Betonung auf der 1. Silbe: modern" },
    { id: "3_3", eng: "cathedral", phon: "[kə'θi:drəl]", ger: "Kathedrale, Dom", ctx: "Kirchengebäude" },
    { id: "3_4", eng: "parliament", phon: "['pɑ:ləmənt]", ger: "Parlament", ctx: "⚠️ Das 'i' wird nicht gesprochen!" },
    { id: "3_5", eng: "wheel", phon: "[wi:l]", ger: "Rad", ctx: "wheel = Rad | big wheel = Riesenrad" },
    { id: "3_6", eng: "hairdresser's", phon: "['hedresəz]", ger: "Friseursalon", ctx: "⚠️ Für den Laden wird ein 's angehängt. hairdresser = Friseur/in. Jack is at the hairdresser's" },
    { id: "3_7", eng: "bell", phon: "[bel]", ger: "Glocke", ctx: "Klangkörper" },
    { id: "3_8", eng: "floor", phon: "[flɔ:]", ger: "Etage, Stock", ctx: "⚠️ floor = Fußboden / Etage. BE: first floor = 1. Etage | AE: first floor = Erdgeschoss" },
    { id: "3_9", eng: "busy", phon: "['bɪzi]", ger: "hektisch, belebt", ctx: "Text 1 | It was too busy in the dining room, so we went upstairs" },
    { id: "3_10", eng: "multicultural", phon: "[mʌlti'kʌltʃərəl]", ger: "multikulturell", ctx: "Kulturelle Vielfalt" },
    { id: "3_11", eng: "capital (city)", phon: "['kæpɪtl]", ger: "Hauptstadt", ctx: "Regierungssitz " },
    { id: "3_12", eng: "million", phon: "['mɪljən]", ger: "Million", ctx: "⚠️ Zahlwort: three million people (ohne s), aber: millions of people" },
    { id: "3_13", eng: "nationality", phon: "[næʃə'næləti]", ger: "Nationalität", ctx: "⚠️ Betonung auf der 3. Silbe: nationality " },
    { id: "3_14", eng: "Indian", phon: "['ɪndiən]", ger: "indisch", ctx: "Herkunft " },
    { id: "3_15", eng: "Irish", phon: "['aɪrɪʃ]", ger: "irisch, aus Irland", ctx: "Herkunft" },
    { id: "3_16", eng: "point", phon: "[pɔɪnt]", ger: "Punkt", ctx: "You get one point for every right answer. / two point three (= 2.3) million" },
    { id: "3_17", eng: "thousand", phon: "['θaʊznd]", ger: "tausend", ctx: "Zahlwort" },
    { id: "3_18", eng: "while", phon: "[waɪl]", ger: "während", ctx: "Satz: We met Mr Petrock while we were in Cornwall" },
    { id: "3_19", eng: "so many", phon: "-", ger: "so viele", ctx: "⚠️ Bedeutung von so: 1. also, daher; 2. so " },
    { id: "3_20", eng: "Russian", phon: "['rʌʃn]", ger: "russisch, Russisch; Russe / Russin", ctx: "Herkunft / Sprache" },
    { id: "3_21", eng: "Iraqi", phon: "[ɪ'rɑ:ki]", ger: "irakisch", ctx: "Herkunft" },
    { id: "3_22", eng: "Pakistani", phon: "[pækɪ'stɑ:ni]", ger: "pakistanisch", ctx: "Herkunft" },
    { id: "3_23", eng: "Arabic", phon: "['ærəbɪk]", ger: "arabisch; Arabisch", ctx: "⚠️ Betonung auf der 1. Silbe: Arabic" },
    { id: "3_24", eng: "Kurdish", phon: "['kɜ:dɪʃ]", ger: "Kurdisch", ctx: "Sprache / Kultur" },
    { id: "3_25", eng: "(to) get on / get off", phon: "[get ɒn], [get ɒf]", ger: "einsteigen / aussteigen (in/aus einen Bus)", ctx: "⚠️ Gegenteile. Satz: Get off the bus at Green Road. I live in the white house" },
    { id: "3_26", eng: "Romanian", phon: "[ru'meɪniən]", ger: "Rumäne / Rumänin; rumänisch, Rumänisch", ctx: "Herkunft / Sprache" },
    { id: "3_27", eng: "over there", phon: "[əʊvə 'ðeə]", ger: "da drüben, dort drüben", ctx: "Gegenteil: over there ◀▶ over here" },
    { id: "3_28", eng: "Lithuanian", phon: "[lɪθju'eɪniən]", ger: "Litauer/in; litauisch, Litauisch", ctx: "Herkunft / Sprache" },
    { id: "3_29", eng: "anywhere else", phon: "[eniweə 'els]", ger: "irgendwo anders", ctx: "anywhere = irgendwo/überall(hin) | not ... anywhere = nirgends" },
    { id: "3_30", eng: "artist", phon: "['ɑ:tɪst]", ger: "Künstler/in", ctx: "⚠️ Betonung auf der 1. Silbe: artist" },
    { id: "3_31", eng: "amazing", phon: "[ə'meɪzɪŋ]", ger: "erstaunlich; großartig", ctx: "Synonym: great. 24 million people live in Shanghai? Amazing!" },
    { id: "3_32", eng: "(to) miss", phon: "[mɪs]", ger: "vermissen", ctx: "Satz: I enjoyed my trip to France, but I missed my friends" },
    { id: "3_33", eng: "Bangladeshi", phon: "[bæŋɡlə'deʃi]", ger: "Bangladescher/in; bangladeschisch", ctx: "Herkunft" },
    { id: "3_34", eng: "Japanese", phon: "[dʒæpə'ni:z]", ger: "Japaner/in; japanisch, Japanisch", ctx: "⚠️ Betonung auf der 3. Silbe: Japanese" },
    { id: "3_35", eng: "Egyptian", phon: "[i'dʒɪpʃn]", ger: "Ägypter/in; ägyptisch", ctx: "Herkunft" },
    { id: "3_36", eng: "Thai", phon: "[taɪ]", ger: "Thailänder/in; thailändisch, Thailändisch", ctx: "Herkunft / Sprache" },
    { id: "3_37", eng: "takeaway", phon: "['teɪkəweɪ]", ger: "Schnellrestaurant; Essen zum Mitnehmen", ctx: "Gastronomie" },
    { id: "3_38", eng: "dancer", phon: "['dɑ:nsə]", ger: "Tänzer/in", ctx: "Abbildung Breakdancerin" },
    { id: "3_39", eng: "Romania", phon: "[ru'meɪniə]", ger: "Rumänien", ctx: "Land" },
    { id: "3_40", eng: "Lithuania", phon: "[lɪθju'eɪniə]", ger: "Litauen", ctx: "Land " },
    { id: "3_41", eng: "Egypt", phon: "['i:dʒɪpt]", ger: "Ägypten", ctx: "Land" },
    { id: "3_42", eng: "underground", phon: "['ʌndəɡraʊnd]", ger: "U-Bahn", ctx: "Introduction 1 | Another name for the underground in London is 'the Tube'" },
    { id: "3_43", eng: "the Tube", phon: "[tju:b]", ger: "(infml) die Londoner U-Bahn", ctx: "Synonym: the underground in London" },
    { id: "3_44", eng: "far", phon: "[fɑ:]", ger: "weit (entfernt)", ctx: "Gegenteil: far ◀▶ near. Sätze: You want to go to Africa? But that's so far away! Steigerung: far - further - furthest" },
    { id: "3_45", eng: "FAQ", phon: "[ef eɪ 'kju:]", ger: "häufig gestellte Fragen", ctx: "Abkürzung für: frequently asked questions" },
    { id: "3_46", eng: "line", phon: "[laɪn]", ger: "U-Bahn-Linie", ctx: "Verkehrsnetz" },
    { id: "3_47", eng: "kilometre (km)", phon: "['kɪləmi:tə]", ger: "Kilometer", ctx: "Maßeinheit. 1,000 metres = 1 kilometre" },
    { id: "3_48", eng: "worst", phon: "[wɜ:st]", ger: "der/die/das schlechteste, schlimmste", ctx: "Gegenteil-Kette: bad - worse - worst ◀▶ good - better - best" },
    { id: "3_49", eng: "off-peak", phon: "[ɒf 'pi:k]", ger: "außerhalb der Stoßzeiten", ctx: "Tarifzeit" },
    { id: "3_50", eng: "bat", phon: "[bæt]", ger: "Fledermaus", ctx: "Abbildung Tier" },
    { id: "3_51", eng: "high", phon: "[haɪ]", ger: "hoch", ctx: "Steigerung: high - higher - highest" },
    { id: "3_52", eng: "price", phon: "[praɪs]", ger: "(Kauf-)Preis", ctx: "⚠️ Verwechslungsgefahr: She won a prize (Gewinn). £150 is a good price for this bike" },
    { id: "3_53", eng: "sight", phon: "[saɪt]", ger: "Sehenswürdigkeit", ctx: "Bedeutungen: 1. Anblick, Bild; 2. Sehenswürdigkeit" },
    { id: "3_54", eng: "tall", phon: "[tɔ:l]", ger: "groß (Person); hoch (Gebäude)", ctx: "⚠️ Gegenteil: tall ◀▶ short (klein bei Personen). Wenn man einen Menschen 'big' nennt, meint man 'schwer' oder 'dick'" },
    { id: "3_55", eng: "as good as", phon: "-", ger: "genauso gut wie", ctx: "Vergleich: as ... as = genauso ... wie | not as ... as = nicht so ... wie" },
    { id: "3_56", eng: "(to) be right / wrong", phon: "-", ger: "Recht / Unrecht haben", ctx: "Satz: You're wrong - the party is tomorrow, not today!" },
    { id: "3_57", eng: "escalator", phon: "['eskəleɪtə]", ger: "Rolltreppe", ctx: "Skills training | You should stand on the right on British escalators" },
    { id: "3_58", eng: "exit", phon: "['eksɪt]", ger: "Ausgang; Ausfahrt", ctx: "Infrastruktur" },
    { id: "3_59", eng: "platform", phon: "['plætfɔ:m]", ger: "Bahnsteig", ctx: "⚠️ Präpositionsunterschied: EN: 'arrive AT platform 4' ◀▶ DE: 'auf Gleis 4 einfahren'" },
    { id: "3_60", eng: "passenger", phon: "['pæsɪndʒə]", ger: "Passagier/in, Fahrgast", ctx: "Reisende" },
    { id: "3_61", eng: "ticket gate", phon: "['tɪkɪt ɡeɪt]", ger: "Sperre (zur Fahrkartenkontrolle)", ctx: "U-Bahn-Zugang" },
    { id: "3_62", eng: "machine", phon: "[mə'ʃi:n]", ger: "Automat, Maschine", ctx: "Gerät" },
    { id: "3_63", eng: "(to) mind", phon: "[maɪnd]", ger: "beachten, achten auf", ctx: "Wendung: Mind the gap! - Achten Sie auf den Abstand! (zwischen Zug und Bahnsteig)" },
    { id: "3_64", eng: "(to) change", phon: "[tʃeɪndʒ]", ger: "umsteigen", ctx: "Sätze: Where do I have to change (trains)? Change at Notting Hill Gate for the Central Line" },
    { id: "3_65", eng: "for example", phon: "[fər ɪɡ'zɑ:mpl]", ger: "zum Beispiel", ctx: "I like ball games - basketball, for example" },
    { id: "3_66", eng: "eastbound", phon: "['i:stbaʊnd]", ger: "in Richtung Osten (Zug, Bus)", ctx: "Satz: Take an eastbound train from here. Kompassrose zeigt: northbound, eastbound, southbound, westbound " },
    { id: "3_67", eng: "direction", phon: "[də'rekʃn]", ger: "Richtung", ctx: "direction = Richtung | directions (pl) = Wegbeschreibung" },
    { id: "3_68", eng: "zone", phon: "[zəʊn]", ger: "Zone", ctx: "Bereichseinteilung" },
    { id: "3_69", eng: "department store", phon: "[dɪ'pɑ:tmənt stɔ:]", ger: "Kaufhaus", ctx: "Introduction 2" },
    { id: "3_70", eng: "too expensive", phon: "[tu:]", ger: "zu teuer", ctx: "Satz: It was too busy in the dining room, so we went upstairs" },
    { id: "3_71", eng: "(to) afford", phon: "[ə'fɔ:d]", ger: "sich etwas leisten können", ctx: "Wendung: (to) afford sth. / to do sth." },
    { id: "3_72", eng: "carnival", phon: "['kɑ:nɪvl]", ger: "Karneval", ctx: "Festlichkeit" },
    { id: "3_73", eng: "costume", phon: "['kɒstju:m]", ger: "Kostüm, Verkleidung", ctx: "Satz: This is my carnival costume: I'm a pirate!" },
    { id: "3_74", eng: "usual", phon: "['ju:ʒuəl]", ger: "üblich, gewöhnlich", ctx: "Adjektiv" },
    { id: "3_75", eng: "have a good time", phon: "-", ger: "Spaß haben, sich vergnügen", ctx: "Satz: We're going to a party. - Have a good time!" },
    { id: "3_76", eng: "(to) enjoy", phon: "[ɪn'dʒɔɪ]", ger: "genießen", ctx: "Wendung: (to) enjoy doing sth. = genießen, etwas zu tun" },
    { id: "3_77", eng: "I don't mind ...", phon: "[maɪnd]", ger: "Es macht mir nichts aus ...", ctx: "Satz: I don't mind helping you (Ich helfe dir gern)" },
    { id: "3_78", eng: "play", phon: "[pleɪ]", ger: "Schauspiel, Theaterstück", ctx: "⚠️ Nomen: play = Schauspiel. Verb: (to) play = spielen. Unterschied: Spiel (Sport/Gesellschaft) = game | Wettkampf = match" },
    { id: "3_79", eng: "lion", phon: "['laɪən]", ger: "Löwe", ctx: "Wendung: The Lion King = König der Löwen" },
    { id: "3_80", eng: "(to) decide", phon: "[dɪ'saɪd]", ger: "beschließen, sich entscheiden", ctx: "Wendung: (to) decide to do sth." },
    { id: "3_81", eng: "Grammatik: Infinitiv vs. -ing", phon: "-", ger: "Verwendung mit Infinitiv oder -ing-Form", ctx: "⚠️ Infinitiv: decide / want / try / plan / afford / love TO DO sth. | -ing-Form: enjoy / miss / love / don't mind DOING sth." },
    { id: "3_82", eng: "remember to do / doing", phon: "-", ger: "daran denken / sich erinnern", ctx: "⚠️ Bedeutungswechsel: remember to do sth. = daran denken, etwas zu tun | remember doing sth. = sich erinnern, etwas getan zu haben" },
    { id: "3_83", eng: "part (of)", phon: "[pɑ:t]", ger: "Teil (von)", ctx: "Study skills" },
    { id: "3_84", eng: "drug", phon: "[drʌɡ]", ger: "Droge, Rauschgift"},
    { id: "3_85", eng: "homeless", phon: "['həʊmləs]", ger: "obdachlos"},
    { id: "3_86", eng: "without", phon: "[wɪ'ðaʊt]", ger: "ohne", ctx: "Gegenteil: with ◀▶ without" },
    { id: "3_87", eng: "hopeless", phon: "['həʊpləs]", ger: "hoffnungslos", ctx: "Adjektiv" },
    { id: "3_88", eng: "still", phon: "[stɪl]", ger: "(immer) noch; trotzdem", ctx: "Sätze: It's 4.30 and Joe still isn't here (noch). It's cold, but I'll still walk to school (trotzdem)" },
    { id: "3_89", eng: "vet", phon: "[vet]", ger: "Tierarzt / -ärztin", ctx: "Beruf" },
    { id: "3_90", eng: "bus stop", phon: "['bʌs stɒp]", ger: "Bushaltestelle", ctx: "stop = Halt, Haltepunkt" },
    { id: "3_91", eng: "shoulder", phon: "['ʃəʊldə]", ger: "Schulter", ctx: "Körperteil" },
    { id: "3_92", eng: "reason", phon: "['ri:zn]", ger: "Grund, Begründung", ctx: "Wendung: for this reason = aus diesem Grund" },
    { id: "3_93", eng: "jobless", phon: "['dʒɒbləs]", ger: "arbeitslos", ctx: "Zustand" },
    { id: "3_94", eng: "newspaper", phon: "['nju:zpeɪpə]", ger: "(Tages-)Zeitung", ctx: "Printmedium" }
];