const e6u4_data = [
    { id: "4_1", eng: "Scotland", phon: "['skɒtlənd]", ger: "Schottland", ctx: "Landesbezeichnung." },
    { id: "4_2", eng: "porridge", phon: "['pɒrɪdʒ]", ger: "Haferbrei", ctx: "Traditionelles Frühstücksgericht." },
    { id: "4_3", eng: "bagpipes (pl)", phon: "['bæɡpaɪps]", ger: "Dudelsack", ctx: "⚠️ Mit bestimmtem Artikel: He's playing the bagpipes = Er spielt Dudelsack." },
    { id: "4_4", eng: "haggis", phon: "['hæɡɪs]", ger: "schottisches Gericht aus gefülltem Schafsmagen", ctx: "Kulinarische Spezialität." },
    { id: "4_5", eng: "island", phon: "['aɪlənd]", ger: "Insel", ctx: "Das 's' ist stumm." },
    { id: "4_6", eng: "top", phon: "[tɒp]", ger: "Spitze, das obere Ende", ctx: "⚠️ Gegenteil: top ◀▶ bottom. Satz: There's a pony at the top of the hill, and there are many deer at the bottom." },
    { id: "4_7", eng: "Scottish", phon: "['skɒtɪʃ]", ger: "schottisch, aus Schottland", ctx: "Herkunftsbezeichnung." },
    { id: "4_8", eng: "loch", phon: "[lɒx]", ger: "schottisches Wort für „lake“", ctx: "Wird genauso ausgesprochen wie das deutsche Wort „Loch“." },
    { id: "4_9", eng: "traditional", phon: "[trə'dɪʃənl]", ger: "traditionell", ctx: "⚠️ Betonung auf der 2. Silbe: traditional." },
    { id: "4_10", eng: "the Highlands (pl)", phon: "['haɪləndz]", ger: "das schottische Hochland (der bergige Norden Schottlands)", ctx: "Region." },
    { id: "4_11", eng: "(to) cook", phon: "[kʊk]", ger: "kochen, (Essen) zubereiten", ctx: "noun: cook = Koch/Köchin | verb: (to) cook = kochen." },
    { id: "4_12", eng: "business", phon: "['bɪznəs]", ger: "Geschäft, Betrieb", ctx: "Wirtschaftsberiff." },
    { id: "4_13", eng: "businessman / -woman", phon: "['bɪznəsmæn]", ger: "Geschäftsmann / Geschäftsfrau", ctx: "Plural: businessmen / businesswomen." },
    { id: "4_14", eng: "(to) fry", phon: "[fraɪ]", ger: "frittieren, braten", ctx: "Adjektiv: fried = frittiert, gebraten." },
    { id: "4_15", eng: "oil", phon: "[ɔɪl]", ger: "Öl", ctx: "Satz: Oh no, look, now there's oil everywhere." },
    { id: "4_16", eng: "everywhere", phon: "['evriweə]", ger: "überall", ctx: "Ortsangabe." },
    { id: "4_17", eng: "home-made", phon: "[həʊm'meɪd]", ger: "hausgemacht, selbstgemacht", ctx: "Satz: Taste these home-made burgers!" },
    { id: "4_18", eng: "(to) taste", phon: "[teɪst]", ger: "schmecken; kosten (probieren)", ctx: "Satz: They taste wonderful (schmecken) / Taste these! (probieren)." },
    { id: "4_19", eng: "healthy", phon: "['helθi]", ger: "gesund", ctx: "noun: health = Gesundheit | adjective: healthy. Stay fit and healthy!" },
    { id: "4_20", eng: "busy", phon: "['bɪzi]", ger: "(viel)beschäftigt", ctx: "⚠️ Bedeutungsvielfalt: 1. hektisch/belebt; 2. vielbeschäftigt. I'm busy! / The kitchen is too busy." },
    { id: "4_21", eng: "Mexican", phon: "['meksɪkən]", ger: "mexikanisch; Mexikaner/in", ctx: "⚠️ Betonung auf der 1. Silbe: Mexican." },
    { id: "4_22", eng: "pepper", phon: "['pepə]", ger: "Paprika, Peperoni; Pfeffer", ctx: "Abbildung rote Paprika (a pepper)." },
    { id: "4_23", eng: "pea", phon: "[pi:]", ger: "Erbse", ctx: "Plural: peas (Abbildung)." },
    { id: "4_24", eng: "carrot", phon: "['kærət]", ger: "Möhre, Karotte", ctx: "Plural: carrots (Abbildung)." },
    { id: "4_25", eng: "beef", phon: "[bi:f]", ger: "Rindfleisch", ctx: "Fleischsorte." },
    { id: "4_26", eng: "sausage", phon: "['sɒsɪdʒ]", ger: "(Brat-, Bock-)Würstchen, Wurst", ctx: "Fleischprodukt." },
    { id: "4_27", eng: "simple", phon: "['sɪmpl]", ger: "einfach", ctx: "Synonym: easy." },
    { id: "4_28", eng: "tasty", phon: "['teɪsti]", ger: "schmackhaft, lecker", ctx: "noun: taste = Geschmack | adjective: tasty." },
    { id: "4_29", eng: "spice", phon: "[spaɪs]", ger: "Gewürz", ctx: "Zutat." },
    { id: "4_30", eng: "garlic", phon: "['ɡɑ:lɪk]", ger: "Knoblauch", ctx: "Abbildung Knoblauchzehe." },
    { id: "4_31", eng: "soup", phon: "[su:p]", ger: "Suppe", ctx: "Vorspeise / Gericht." },
    { id: "4_32", eng: "main course", phon: "[meɪn 'kɔ:s]", ger: "Hauptgericht", ctx: "Menübestandteil." },
    { id: "4_33", eng: "side dish", phon: "['saɪd dɪʃ]", ger: "Beilage", ctx: "⚠️ Vorsicht: dish = Gericht | dishes (pl) = Abwasch." },
    { id: "4_34", eng: "lemonade", phon: "[lemə'neɪd]", ger: "Limonade", ctx: "Getränk." },
    { id: "4_35", eng: "(to) make (money)", phon: "-", ger: "(Geld) verdienen", ctx: "Satz: He made a lot of money by selling computers." },
    { id: "4_36", eng: "not (...) anything", phon: "['eniθɪŋ]", ger: "nichts", ctx: "Introduction 1 | Satz: Without money you can't do anything." },
    { id: "4_37", eng: "recipe", phon: "['resəpi]", ger: "(Koch-)Rezept", ctx: "Anleitung." },
    { id: "4_38", eng: "pan", phon: "[pæn]", ger: "Pfanne", ctx: "Kochgeschirr." },
    { id: "4_39", eng: "fridge", phon: "[frɪdʒ]", ger: "Kühlschrank", ctx: "Satz: There are two apples and two bottles of milk in the fridge." },
    { id: "4_40", eng: "(to) disagree", phon: "[dɪsə'ɡri:]", ger: "nicht zustimmen, widersprechen", ctx: "Skills training | Gegenteil: (to) agree ◀▶ (to) disagree." },
    { id: "4_41", eng: "opinion", phon: "[ə'pɪnjən]", ger: "Meinung", ctx: "⚠️ Feste Wendung: 'in my opinion' = meiner Meinung nach." },
    { id: "4_42", eng: "sugar", phon: "['ʃʊɡə]", ger: "Zucker", ctx: "Abbildung Zuckerwürfel (sugar and salt)." },
    { id: "4_43", eng: "salt", phon: "[sɔ:lt]", ger: "Salz", ctx: "Abbildung Salzstreuer." },
    { id: "4_44", eng: "boiled", phon: "[bɔɪld]", ger: "gekocht", ctx: "Zubereitungsart." },
    { id: "4_45", eng: "raw", phon: "[rɔ:]", ger: "roh", ctx: "Gegenteil: raw ◀▶ boiled." },
    { id: "4_46", eng: "roasted", phon: "['rəʊstɪd]", ger: "gebraten, geröstet", ctx: "⚠️ Satz: You can eat your meat boiled or roasted. Aber: 'roast meat' = Braten." },
    { id: "4_47", eng: "oven", phon: "['ʌvn]", ger: "Backofen", ctx: "Küchengerät." },
    { id: "4_48", eng: "true", phon: "[tru:]", ger: "wahr, richtig", ctx: "Synonym: right." },
    { id: "4_49", eng: "(to) worry (about)", phon: "['wʌri]", ger: "sich Sorgen machen (wegen, um)", ctx: "Satz: Mum always worries about me when I come home late." },
    { id: "4_50", eng: "(to) believe (in sth.)", phon: "[bɪ'li:v]", ger: "(an etwas) glauben", ctx: "⚠️ Präpositionsunterschied: DE: 'Glaubst du AN Geister?' ◀▶ EN: 'Do you believe IN ghosts?'." },
    { id: "4_51", eng: "in my view", phon: "[vju:]", ger: "meiner Ansicht nach", ctx: "Synonym: in my opinion." },
    { id: "4_52", eng: "Bavaria", phon: "[bə'veəriə]", ger: "Bayern", ctx: "Bundesland." },
    { id: "4_53", eng: "shopping list", phon: "['ʃɒpɪŋ lɪst]", ger: "Einkaufsliste", ctx: "Introduction 2." },
    { id: "4_54", eng: "anything", phon: "['eniθɪŋ]", ger: "irgendetwas / nichts", ctx: "⚠️ 1. In Fragen: (irgend)etwas (Do you know anything about dogs?). 2. In verneinten Sätzen: nichts (We don't know anything)." },
    { id: "4_55", eng: "somebody / someone", phon: "['sʌmbədi]", ger: "jemand", ctx: "Satz: There's somebody/someone at the door. Systematik: somebody/someone (jemand), everybody/everyone (jeder), nobody/no one (niemand)." },
    { id: "4_56", eng: "anybody / anyone", phon: "['enibɒdi]", ger: "irgendjemand; jede/r (beliebige)", ctx: "⚠️ Kombinationen: not ... anybody = niemand | not ... anywhere = nirgends | not ... anything = nichts." },
    { id: "4_57", eng: "somewhere", phon: "['sʌmweə]", ger: "irgendwo(hin)", ctx: "Satz: Can we go somewhere where it's hot this summer?" },
    { id: "4_58", eng: "seconds (pl)", phon: "['sekəndz]", ger: "Nachschlag", ctx: "Beim Essen." },
    { id: "4_59", eng: "charity", phon: "['tʃærəti]", ger: "wohltätige Organisation", ctx: "Institution." },
    { id: "4_60", eng: "(to) cost, cost", phon: "[kɒst]", ger: "kosten", ctx: "Satz: How much did your new computer cost?" },
    { id: "4_61", eng: "surprised", phon: "[sə'praɪzd]", ger: "überrascht", ctx: "Satz: Only £200! I was really surprised." },
    { id: "4_62", eng: "(to) miss", phon: "[mɪs]", ger: "auslassen; verpassen", ctx: "⚠️ Drei Bedeutungen gelernt: 1. vermissen; 2. auslassen; 3. verpassen (I'll miss the bus)." },
    { id: "4_63", eng: "(to) explain sth. to sb.", phon: "[ɪk'spleɪn]", ger: "jm. etwas erklären", ctx: "⚠️ Präpositionswechsel: DE: 'Erkläre es MIR bitte' ◀▶ EN: 'Please explain it TO me'." },
    { id: "4_64", eng: "umbrella", phon: "[ʌm'brelə]", ger: "(Regen-)Schirm", ctx: "Study skills | Nutzt unbestimmten Artikel 'an': an umbrella." },
    { id: "4_65", eng: "(to) do the cleaning", phon: "[du: ðə 'kli:nɪŋ]", ger: "putzen", ctx: "Text 2 | Systematik: do the cleaning (putzen), do the washing (waschen), do the cooking (kochen), do the shopping (einkaufen)." },
    { id: "4_66", eng: "(to) empty", phon: "['empti]", ger: "leeren", ctx: "verb: (to) empty | adjective: empty = leer. She's emptying the dishwasher." },
    { id: "4_67", eng: "dishwasher", phon: "['dɪʃwɒʃə]", ger: "Geschirrspülmaschine", ctx: "Küchengerät." },
    { id: "4_68", eng: "(to) load", phon: "[ləʊd]", ger: "(be)laden", ctx: "Satz: He's loading the dishwasher." },
    { id: "4_69", eng: "washing", phon: "['wɒʃɪŋ]", ger: "Wäsche", ctx: "Zustand." },
    { id: "4_70", eng: "(to) hang, hung", phon: "[hæŋ], [hʌŋ]", ger: "hängen", ctx: "Satz: He's hanging out the washing." },
    { id: "4_71", eng: "puzzled", phon: "['pʌzld]", ger: "verwundert", ctx: "Synonym: surprised." },
    { id: "4_72", eng: "(to) need to do sth.", phon: "-", ger: "etwas tun müssen", ctx: "Synonym: must do sth." },
    { id: "4_73", eng: "(to) call", phon: "[kɔ:l]", ger: "nennen; rufen; anrufen", ctx: "⚠️ Drei Bedeutungen: 1. nennen (call her Jess), 2. rufen (Please call your dog), 3. anrufen (Call me tomorrow)." },
    { id: "4_74", eng: "embarrassed", phon: "[ɪm'bærəst]", ger: "verlegen", ctx: "Satz: I felt so embarrassed when my mobile rang." },
    { id: "4_75", eng: "engineer", phon: "[endʒɪ'nɪə]", ger: "Ingenieur/in; Techniker/in", ctx: "Berufsbezeichnung." },
    { id: "4_76", eng: "oil rig", phon: "['ɔɪl rɪɡ]", ger: "Ölbohrinsel", ctx: "Abbildung auf offener See: an oil rig." },
    { id: "4_77", eng: "since", phon: "[sɪns]", ger: "seit", ctx: "Zeitliche Angabe." },
    { id: "4_78", eng: "(to) pay (for sth.), paid", phon: "[peɪ], [peɪd]", ger: "etwas (be)zahlen", ctx: "⚠️ Präpositionswechsel: EN: 'pay FOR the pizzas' ◀▶ DE: 'die Pizzas bezahlen'." },
    { id: "4_79", eng: "(to) worry sb.", phon: "['wʌri]", ger: "jn. beunruhigen", ctx: "⚠️ Unterschied zu worry about: I don't want to worry you (nicht beunruhigen). Don't worry! (Mach dir keine Sorgen)." },
    { id: "4_80", eng: "herself", phon: "[hɜ:'self]", ger: "sich (selbst)", ctx: "Reflexivpronomen (Singular)." },
    { id: "4_81", eng: "Reflexivpronomen Übersicht", phon: "-", ger: "myself, yourself, himself, herself, itself, ourselves, yourselves, themselves", ctx: "⚠️ Buch-Tabelle: I->myself, you->yourself, he->himself, she->herself, it->itself | Plural: we->ourselves, you->yourselves, they->themselves. Endung -self [-'self] vs -selves [-'selvz]." },
    { id: "4_82", eng: "volunteer organisation", phon: "[vɒləntɪər ɔ:ɡənaɪ'zeɪʃn]", ger: "Freiwilligenorganisation", ctx: "⚠️ Betonung auf der 4. Silbe: organisation." },
    { id: "4_83", eng: "feeling", phon: "['fi:lɪŋ]", ger: "Gefühl", ctx: "verb: (to) feel = fühlen | noun: feeling." },
    { id: "4_84", eng: "buffet", phon: "['bʊfeɪ]", ger: "Büfett", ctx: "Your task | ⚠️ Betonung auf der 1. Silbe: buffet." },
    { id: "4_85", eng: "meatball", phon: "['mi:tbɔ:l]", ger: "Fleischbällchen, Frikadelle", ctx: "Speise." },
    { id: "4_86", eng: "beetroot", phon: "['bi:tru:t]", ger: "Rote Beete", ctx: "Gemüsesorte." },
    { id: "4_87", eng: "sour cream", phon: "['saʊə kri:m]", ger: "saure Sahne", ctx: "Bestandteile: cream = Sahne/Creme | sour = sauer." }
];