const e6u5_data = [
    { id: "5_1", eng: "Canada", phon: "['kænədə]", ger: "Kanada", ctx: "Landesbezeichnung [Bildschirmfoto 2026-06-27 um 14.49.16.png]." },
    { id: "5_2", eng: "Pacific Ocean", phon: "[pəsɪfɪk 'əʊʃn]", ger: "Pazifischer Ozean, Pazifik", ctx: "Gewässer [Bildschirmfoto 2026-06-27 um 14.49.16.png]." },
    { id: "5_3", eng: "Atlantic Ocean", phon: "[ətlæntɪk 'əʊʃn]", ger: "atlantischer Ozean, Atlantik", ctx: "Gewässer [Bildschirmfoto 2026-06-27 um 14.49.16.png]." },
    { id: "5_4", eng: "north", phon: "[nɔ:θ]", ger: "Norden; nördlich; Nord-", ctx: "Kompassrose zeigt auch: north-west, west, south-west, south, south-east, east, north-east [Bildschirmfoto 2026-06-27 um 14.49.16.png]." },
    { id: "5_5", eng: "state", phon: "[steɪt]", ger: "(Bundes-)Staat", ctx: "Politische Gliederung [Bildschirmfoto 2026-06-27 um 14.49.16.png]." },
    { id: "5_6", eng: "California", phon: "[kælə'fɔ:niə]", ger: "Kalifornien", ctx: "US-Bundesstaat [Bildschirmfoto 2026-06-27 um 14.49.16.png]." },
    { id: "5_7", eng: "highway (AE)", phon: "['haɪweɪ]", ger: "Fernstraße (in den USA; oft mit vier oder mehr Spuren)", ctx: "Abbildung Wüstenstraße: a highway [Bildschirmfoto 2026-06-27 um 14.49.16.png]." },
    { id: "5_8", eng: "national park", phon: "[næʃnəl 'pɑ:k]", ger: "Nationalpark (staatliches Naturschutzgebiet)", ctx: "Natur [Bildschirmfoto 2026-06-27 um 14.49.16.png]." },
    { id: "5_9", eng: "American", phon: "[ə'merɪkən]", ger: "Amerikaner/in; amerikanisch", ctx: "Herkunft [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_10", eng: "car park", phon: "['kɑ: pɑ:k]", ger: "Parkplatz", ctx: "Britische Bezeichnung [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_11", eng: "petrol station", phon: "['petrəl steɪʃn]", ger: "Tankstelle", ctx: "BE: petrol = Benzin [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_12", eng: "airport", phon: "['eəpɔ:t]", ger: "Flughafen", ctx: "Infrastruktur [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_13", eng: "cab (AE)", phon: "[kæb]", ger: "Taxi", ctx: "⚠️ AE: cab ◀▶ BE: taxi. Abbildung gelbes Auto: a cab [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_14", eng: "parking lot (AE)", phon: "['pɑ:kɪŋ lɒt]", ger: "Parkplatz", ctx: "⚠️ AE: parking lot ◀▶ BE: car park [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_15", eng: "gas station (AE)", phon: "['ɡæs steɪʃn]", ger: "Tankstelle", ctx: "⚠️ AE: gas station ◀▶ BE: petrol station (AE: gas = Benzin) [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_16", eng: "candy (AE)", phon: "['kændi]", ger: "Süßigkeit(en), Bonbon", ctx: "⚠️ AE: candy ◀▶ BE: sweets [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_17", eng: "vacation (AE)", phon: "[və'keɪʃn]", ger: "Urlaub, Ferien", ctx: "Text 1 | ⚠️ AE: vacation ◀▶ BE: holidays [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_18", eng: "movie (AE)", phon: "['mu:vi]", ger: "Film, Spielfilm", ctx: "⚠️ AE: movie ◀▶ BE: film [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_19", eng: "earthquake", phon: "['ɜ:θkweɪk]", ger: "Erdbeben", ctx: "Naturkatastrophe [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_20", eng: "letter", phon: "['letə]", ger: "Buchstabe", ctx: "⚠️ Doppelbedeutung: 1. Brief; 2. Buchstabe [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_21", eng: "actor", phon: "['æktə]", ger: "Schauspieler/in", ctx: "Beruf [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_22", eng: "director", phon: "[də'rektə]", ger: "Regisseur/in", ctx: "Beruf [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_23", eng: "photographer", phon: "[fə'tɒɡrəfə]", ger: "Fotograf/in", ctx: "⚠️ Betonung auf der 2. Silbe: photographer [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_24", eng: "doctor", phon: "['dɒktə]", ger: "Arzt, Ärztin", ctx: "⚠️ Bei Ortsangaben Genitiv-s: DE: 'beim Arzt / zum Arzt' ◀▶ EN: 'at the doctor's / to the doctor's' [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_25", eng: "dentist", phon: "['dentɪst]", ger: "Zahnarzt / -ärztin", ctx: "⚠️ Genitiv-s bei Ortsangaben: at the dentist's / to the dentist's [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_26", eng: "Walk of Fame", phon: "[wɔ:k əv 'feɪm]", ger: "„Weg des Ruhms“ – Gehweg in Los Angeles", ctx: "Sterne für Berühmtheiten im Boden. fame = Ruhm [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_27", eng: "sidewalk (AE)", phon: "['saɪdwɔ:k]", ger: "Bürgersteig", ctx: "Gehweg [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_28", eng: "movie theater (AE)", phon: "['mu:vi θɪətə]", ger: "Kino", ctx: "⚠️ AE: movie theater ◀▶ BE: cinema [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_29", eng: "Spelling: BE vs. AE", phon: "-", ger: "Unterschiedliche Schreibweisen", ctx: "⚠️ BE -tre / AE -ter (theatre/theater, centre/center, kilometre/kilometer) & BE -our / AE -or (colour/color, favourite/favorite, harbour/harbor) [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_30", eng: "walk around", phon: "-", ger: "umhergehen", ctx: "Satz: Let’s walk around the village = im Dorf umhergehen [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_31", eng: "pavement", phon: "['peɪvmənt]", ger: "Gehweg, Bürgersteig", ctx: "⚠️ BE: pavement ◀▶ AE: sidewalk [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_32", eng: "(to) clean", phon: "[kli:n]", ger: "sauber machen, putzen", ctx: "verb: (to) clean | adjective: clean = sauber [Bildschirmfoto 2026-06-27 um 14.49.27.jpg]." },
    { id: "5_33", eng: "nothing", phon: "['nʌθɪŋ]", ger: "nichts", ctx: "Synonym: not anything | Gegenteil: nothing ◀▶ something [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_34", eng: "just", phon: "[dʒʌst]", ger: "gerade (eben)", ctx: "Satz: I'm new in New York. I've just moved here [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_35", eng: "recently", phon: "['ri:sntli]", ger: "in letzter Zeit, neulich", ctx: "Satz: I've started doing more sport recently [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_36", eng: "wedding", phon: "['wedɪŋ]", ger: "Hochzeit", ctx: "Wendung: wedding present = Hochzeitsgeschenk [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_37", eng: "(to) wash", phon: "[wɒʃ]", ger: "(sich) waschen", ctx: "Körperpflege / Reinigung [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_38", eng: "(to) board", phon: "[bɔ:d]", ger: "an Bord gehen", ctx: "Skills training | ⚠️ Satz: flight 934 boarding at gate B12. boarding card = Bordkarte [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_39", eng: "flight", phon: "[flaɪt]", ger: "Flug", ctx: "Flugreise [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_40", eng: "baggage (AE)", phon: "['bæɡɪdʒ]", ger: "Gepäck", ctx: "⚠️ AE: baggage ◀▶ BE: luggage ['lʌɡɪdʒ] [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_41", eng: "passport", phon: "['pɑ:spɔ:t]", ger: "(Reise-)Pass", ctx: "Abbildung rote/blaue Dokumente: passports [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_42", eng: "arrival", phon: "[ə'raɪvl]", ger: "Ankunft", ctx: "Flughafenbegriff [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_43", eng: "delayed", phon: "[dɪ'leɪd]", ger: "verspätet", ctx: "⚠️ Präpositionen: delayed TO 15.20 (bis) / BY 30 minutes (um) [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_44", eng: "zoo", phon: "[zu:]", ger: "Zoo", ctx: "Tierpark [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_45", eng: "ring", phon: "[rɪŋ]", ger: "Ring", ctx: "Introduction 2 [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_46", eng: "yet", phon: "[jet]", ger: "schon ...? / noch nicht", ctx: "⚠️ Grammatik: 1. In verneinten Sätzen: noch nicht (I haven't had dinner yet). 2. In Fragen: schon (Have you had dinner yet?) [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_47", eng: "already", phon: "[ɔ:l'redi]", ger: "schon", ctx: "Satz: I've already had dinner [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_48", eng: "list", phon: "[lɪst]", ger: "Liste", ctx: "Wendung: to-do list = Aufgabenliste [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_49", eng: "take off, took, taken", phon: "[teɪk ɒf]", ger: "ausziehen, ablegen", ctx: "Kleidung ablegen. Where are my sunglasses? I must have taken them off somewhere [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_50", eng: "sunglasses (pl)", phon: "['sʌnɡlɑ:sɪz]", ger: "(eine) Sonnenbrille", ctx: "⚠️ Pluraletantum-Kasten im Buch (Wörter, die immer im Plural stehen): sunglasses, glasses, swimming trunks, trousers, shorts, bagpipes, vegetables (=Gemüse) [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_51", eng: "ever", phon: "['evə]", ger: "jemals, schon einmal", ctx: "Gegenteil: ever ◀▶ never. Have you ever ...? = Bist/Hast du schon einmal ...? [Bildschirmfoto 2026-06-27 um 14.49.41.jpg]." },
    { id: "5_52", eng: "bear", phon: "[beə]", ger: "Bär", ctx: "Abbildung Braunbör: a bear [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_53", eng: "whale", phon: "[weɪl]", ger: "Wal", ctx: "Abbildung Meeressäuger: a whale [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_54", eng: "inside", phon: "[ɪn'saɪd]", ger: "innen, auf der Innenseite", ctx: "Study skills | Gegenteil: inside ◀▶ outside [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_55", eng: "heavy", phon: "['hevi]", ger: "schwer (Gewicht)", ctx: "⚠️ Kontrast: schwer vom Gewicht = a heavy box | schwer/schwierig = a hard question [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_56", eng: "furniture (no pl)", phon: "['fɜ:nɪtʃə]", ger: "Möbel", ctx: "⚠️ Steht im Englischen immer im Singular! The furniture IS new [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_57", eng: "cover", phon: "['kʌvə]", ger: "bedecken", ctx: "Satz: It was cold so she covered her baby with her jacket [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_58", eng: "arm", phon: "[ɑ:m]", ger: "Arm", ctx: "Körperteil [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_59", eng: "elevator (AE)", phon: "['elɪveɪtə]", ger: "Aufzug", ctx: "⚠️ AE: elevator ◀▶ BE: lift [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_60", eng: "building", phon: "['bɪldɪŋ]", ger: "Gebäude", ctx: "Abbildung Hochhauskomplex [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_61", eng: "power line", phon: "['paʊə laɪn]", ger: "Stromleitung", ctx: "Abbildung Strommast [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_62", eng: "police officer", phon: "[pə'li:s ɒfɪsə]", ger: "Polizeibeamter / -beamtin", ctx: "Text 2 [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_63", eng: "smell", phon: "[smel]", ger: "Geruch; Gestank", ctx: "noun: smell | verb: (to) smell = riechen. What's that horrible smell? (Abbildung) [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_64", eng: "burn, burnt, burnt", phon: "[bɜ:n], [bɜ:nt]", ger: "brennen, verbrennen", ctx: "Unregelmäßiges Verb [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_65", eng: "strong", phon: "[strɒŋ]", ger: "stark", ctx: "Adjektiv [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_66", eng: "board", phon: "[bɔ:d]", ger: "Brett", ctx: "Satz: There’s a hole in this board. I think it’s broken (Abbildung) [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_67", eng: "hole", phon: "[həʊl]", ger: "Loch", ctx: "Öffnung im Brett [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_68", eng: "broken", phon: "['brəʊkən]", ger: "zerbrochen, kaputt", ctx: "Zustand [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_69", eng: "cellar", phon: "['selə]", ger: "Keller", ctx: "Untergeschoss [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_70", eng: "be hurt / get hurt", phon: "-", ger: "verletzt sein, sich verletzen", ctx: "Zustand / Aktion [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_71", eng: "point (at / to)", phon: "[pɔɪnt]", ger: "zeigen, deuten (auf)", ctx: "verb: (to) point | noun: point = Punkt [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_72", eng: "hold out, held, held", phon: "[həʊld aʊt]", ger: "hinhalten", ctx: "Satz: 'Can you give me that book, please?', she said and held out her hand [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_73", eng: "shake, shook, shaken", phon: "[ʃeɪk], [ʃʊk], ['ʃeɪkən]", ger: "schütteln", ctx: "Abbildung Händeschütteln: They’re shaking hands [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_74", eng: "enough", phon: "[ɪ'nʌf]", ger: "genug", ctx: "Satz: Is one sandwich enough? Or are you still hungry? [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_75", eng: "make a decision", phon: "-", ger: "eine Entscheidung fällen", ctx: "Wendung [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_76", eng: "(to) save", phon: "[seɪv]", ger: "retten; sparen", ctx: "Sätze: The man saved the dog's life (retten) / I need to save money (sparen) [Bildschirmfoto 2026-06-27 um 14.49.50.jpg]." },
    { id: "5_77", eng: "(to) hope", phon: "[həʊp]", ger: "hoffen", ctx: "Satz: I hope you like my school uniform [Bildschirmfoto 2026-06-27 um 14.50.01.png]." },
    { id: "5_78", eng: "bark (at sb.)", phon: "[bɑ:k]", ger: "(jn. an)bellen", ctx: "Tierlaut [Bildschirmfoto 2026-06-27 um 14.50.01.png]." },
    { id: "5_79", eng: "owe sb. sth.", phon: "[əʊ]", ger: "jm. etwas schulden, schuldig sein", ctx: "Sätze: I still owe you some money. You don't owe me anything, it's OK [Bildschirmfoto 2026-06-27 um 14.50.01.png]." },
    { id: "5_80", eng: "Irregular past participles", phon: "-", ger: "Unregelmäßige 3. Formen", ctx: "⚠️ Gesamte Kasten-Tabelle: be->been, come->come, do->done, drink->drunk, eat->eaten, forget->forgotten, find->found, give->given, go->gone, get->got, have->had, leave->left, make->made, meet->met, put->put, ride->ridden, swim->swam/swum, take->taken, tell->told [Bildschirmfoto 2026-06-27 um 14.50.01.png]." }
];