const e6u6_data = [
    { id: "6_1", eng: "niece", phon: "[ni:s]", ger: "Nichte", ctx: "Familienmitglied [Bildschirmfoto 2026-06-27 um 14.51.37.png]." },
    { id: "6_2", eng: "desert", phon: "['dezət]", ger: "Wüste", ctx: "⚠️ Verwechshlungsgefahr: desert ['dezət] = Wüste ◀▶ dessert [dɪ'zɜ:t] = Nachspeise [Bildschirmfoto 2026-06-27 um 14.51.37.png]." },
    { id: "6_3", eng: "grade (AE)", phon: "[ɡreɪd]", ger: "Klasse, Schuljahr", ctx: "⚠️ AE: grade ◀▶ BE: (school) year. My sister is now in third grade [Bildschirmfoto 2026-06-27 um 14.51.37.png]." },
    { id: "6_4", eng: "Hispanic", phon: "[hɪ'spænɪk]", ger: "hispanisch (lateinamerikanischer Herkunft)", ctx: "Abbildung Junge mit Cap: a Hispanic boy [Bildschirmfoto 2026-06-27 um 14.51.37.png]." },
    { id: "6_5", eng: "baggy", phon: "['bæɡi]", ger: "weit (geschnitten) (Kleidung)", ctx: "baggy pants = Schlabberhose [Bildschirmfoto 2026-06-27 um 14.51.37.png]." },
    { id: "6_6", eng: "pants (pl) (AE)", phon: "[pænts]", ger: "(eine) Hose", ctx: "⚠️ AE: pants ◀▶ BE: trousers [Bildschirmfoto 2026-06-27 um 14.51.37.png]." },
    { id: "6_7", eng: "period", phon: "['pɪəriəd]", ger: "(Unterrichts-)Stunde", ctx: "⚠️ AE: period ◀▶ BE: lesson [Bildschirmfoto 2026-06-27 um 14.51.37.png]." },
    { id: "6_8", eng: "recess (AE)", phon: "[rɪ'ses]", ger: "Pause", ctx: "⚠️ AE: recess ◀▶ BE: break [Bildschirmfoto 2026-06-27 um 14.51.37.png]." },
    { id: "6_9", eng: "after-school activities", phon: "-", ger: "AGs (freiwillige Veranstaltungen nach Unterrichtsschluss)", ctx: "Schulalltag [Bildschirmfoto 2026-06-27 um 14.51.37.png]." },
    { id: "6_10", eng: "backpack", phon: "['bækpæk]", ger: "Rucksack", ctx: "BE nutzt auch das deutsche Lehnwort 'rucksack' ['rʌksæk] [Bildschirmfoto 2026-06-27 um 14.51.37.png]." },
    { id: "6_11", eng: "schedule (AE)", phon: "['skedʒu:l]", ger: "Stundenplan", ctx: "⚠️ AE: schedule ◀▶ BE: timetable [Bildschirmfoto 2026-06-27 um 14.51.37.png]." },
    { id: "6_12", eng: "Pronunciation: BE vs. AE", phon: "-", ger: "Lautliche Unterschiede", ctx: "⚠️ BE [ɑ:] vs AE [æ] (ask, can't) | BE [ju:] vs AE [u:] (new, Tuesday) | BE [ɒ] vs AE [ɑ:] (clock, hot). AE spricht das 'r' hörbar (mother, hard) und das 't' zwischen Vokalen wie ein weiches 'd' (city ['sɪdi], better, writer) [Bildschirmfoto 2026-06-27 um 14.51.37.png]." },
    { id: "6_13", eng: "special", phon: "['speʃl]", ger: "Sonderausgabe (Magazin); Sondersendung (Fernsehen)", ctx: "Bedeutungen: 1. besondere(r, s); 2. Sonderausgabe [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_14", eng: "even", phon: "['i:vn]", ger: "sogar, selbst", ctx: "Satz: Everybody tried to help, even the children. Verneinung: not even = nicht einmal (not even ice cream) [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_15", eng: "(to) support", phon: "[sə'pɔ:t]", ger: "unterstützen", ctx: "Synonym: (to) help [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_16", eng: "leg", phon: "[leɡ]", ger: "Bein", ctx: "Körperteil: We have two arms and two legs [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_17", eng: "(to) practice (AE)", phon: "['præktɪs]", ger: "üben, trainieren", ctx: "⚠️ Schreibweise: BE verb: (to) practise | Nomen generell: practice = Übung, Erfahrung [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_18", eng: "time", phon: "[taɪm]", ger: "Mal / Zeit", ctx: "Beispiele: Do you have time? (Zeit) / three times (dreimal) / the last time / this time [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_19", eng: "three times a week", phon: "-", ger: "dreimal pro Woche", ctx: "Satz: We love Indian food. We have it three times a month [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_20", eng: "(to) lose, lost, lost", phon: "[lu:z], [lɒst]", ger: "verlieren", ctx: "Unregelmäßiges Verb [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_21", eng: "I'm going to play ...", phon: "-", ger: "ich werde ... spielen", ctx: "Zukunftsform (Absicht) [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_22", eng: "(to) beat, beat, beaten", phon: "[bi:t], ['bi:tn]", ger: "schlagen, besiegen", ctx: "Satz: I beat my brother at tennis last Sunday (= I won and he lost) [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_23", eng: "score", phon: "[skɔ:]", ger: "Spiel-/Punktestand; Punkt erzielen", ctx: "noun: score = Spielstand | verb: (to) score = (Punkt/Tor) erzielen [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_24", eng: "picnic", phon: "['pɪknɪk]", ger: "Picknick", ctx: "Wendung: (to) have a picnic = ein Picknick machen [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_25", eng: "before", phon: "[bɪ'fɔ:]", ger: "zuvor, vorher / vor", ctx: "⚠️ Nuancen: 1. vor der Schule (before school), 2. bevor du gehst (before you go), 3. noch nie zuvor gehört (I've never heard this song before) [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_26", eng: "(to) hang out", phon: "[hæŋ 'aʊt]", ger: "rumhängen, abhängen", ctx: "Freizeitbeschäftigung [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_27", eng: "day out, pl days out", phon: "-", ger: "(Tages-)Ausflug", ctx: "Freizeit [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_28", eng: "football (AE)", phon: "['fʊtbɔ:l]", ger: "American Football", ctx: "⚠️ Verwechslungsgefahr: BE: football = Fußball | AE: football = American Football [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_29", eng: "whole", phon: "[həʊl]", ger: "ganze(r, s)", ctx: "Satz: Yesterday we played cards the whole evening [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_30", eng: "(to) cheer", phon: "[tʃɪə]", ger: "jubeln, anfeuern", ctx: "Satz: Everyone cheered when Amy's team won the match [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_31", eng: "(to) teach, taught, taught", phon: "[ti:tʃ], [tɔ:t]", ger: "lehren, unterrichten", ctx: "Sätze: Mr Schwarz teaches English. My sister is teaching me to play the guitar (bringt mir bei) [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_32", eng: "coach", phon: "[kəʊtʃ]", ger: "Trainer/in; Reisebus", ctx: "⚠️ Doppelbedeutung: 1. Reisebus; 2. Trainer/in [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_33", eng: "grade", phon: "[ɡreɪd]", ger: "(Schul-)Note", ctx: "⚠️ Nuancen: 1. AE Klasse/Schuljahr; 2. (Schul-)Note. This year I'll get good grades in maths [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_34", eng: "final", phon: "['faɪnl]", ger: "Finale", ctx: "⚠️ Betonung auf der 1. Silbe: final ['faɪnl] [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_35", eng: "half", phon: "[hɑ:f]", ger: "halbe(r, s)", ctx: "Wendungen: half-time show (Halbzeitpause) | half an apple / hour (ein halber Apfel / eine halbe Stunde) [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_36", eng: "soccer", phon: "['sɒkə]", ger: "Fußball", ctx: "⚠️ In den USA meint 'football' American Football. Wenn man über echten Fußball spricht, nutzt man 'soccer' [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_37", eng: "cheerleading", phon: "['tʃɪəlɪ:dɪŋ]", ger: "Cheerleading", ctx: "Introduction 1 | Sportart. Die Ausübenden heißen cheerleaders (Abbildung) [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_38", eng: "No way!", phon: "[nəʊ 'weɪ]", ger: "Auf keinen Fall!", ctx: "Satz: Do you want green hair? - No way! (Abbildung Comic) [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_39", eng: "(to) have to do sth.", phon: "-", ger: "etwas tun müssen", ctx: "⚠️ Satz: Look, it's late. We have to go now. Info: 'have to' wird im Alltag häufiger verwendet als 'must' [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_40", eng: "dogs' home", phon: "-", ger: "Hundeheim", ctx: "Tierschutz [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_41", eng: "everybody / everyone else", phon: "[els]", ger: "alle anderen; jede/r andere", ctx: "Satz: Would you like anything else? (sonst noch etwas) [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_42", eng: "finger", phon: "['fɪŋɡə]", ger: "Finger", ctx: "Körperteil [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_43", eng: "(to) get wet", phon: "-", ger: "nass werden", ctx: "Zustandsänderung [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_44", eng: "Übersetzung von „werden“", phon: "-", ger: "get / become / turn to sth.", ctx: "⚠️ Systematik: 1. get (We got wet / It gets hot), 2. become (It became warmer), 3. turn to (The ice turned to water) [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_45", eng: "body", phon: "['bɒdi]", ger: "Körper", ctx: "Skills training | Anatomie [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_46", eng: "foot, pl feet", phon: "[fʊt], [fi:t]", ger: "Fuß", ctx: "⚠️ Doppelbedeutung: 1. Fuß (Körperteil); 2. Längenmaß (ca. 30 cm) [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_47", eng: "ear", phon: "[ɪə]", ger: "Ohr", ctx: "Abbildung Gesicht [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_48", eng: "face", phon: "[feɪs]", ger: "Gesicht", ctx: "Abbildung Kopfseite [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_49", eng: "nose", phon: "[nəʊz]", ger: "Nase", ctx: "Abbildung [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_50", eng: "throat", phon: "[θrəʊt]", ger: "Hals", ctx: "Abbildung [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_51", eng: "mouth", phon: "[maʊθ]", ger: "Mund", ctx: "Abbildung [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_52", eng: "stomach", phon: "['stʌmək]", ger: "Bauch; Magen", ctx: "⚠️ Aussprache beachten: stomach ['stʌmək] [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_53", eng: "What's wrong?", phon: "-", ger: "Was fehlt dir / Ihnen? (beim Arzt)", ctx: "Arzt-Frage [Bildschirmfoto 2026-06-27 um 14.51.47.jpg]." },
    { id: "6_54", eng: "have a stomach ache / headache", phon: "[eɪk], ['hedeɪk]", ger: "Bauchschmerzen / Kopfschmerzen haben", ctx: "⚠️ Immer mit Artikel: I have a stomach ache / a headache [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_55", eng: "a sore throat", phon: "[sɔ: 'θrəʊt]", ger: "Halsschmerzen", ctx: "Satz: I have a sore throat [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_56", eng: "temperature", phon: "['temprətʃə]", ger: "Temperatur; Fieber", ctx: "Satz: I have a temperature [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_57", eng: "cough", phon: "[kʌf]", ger: "Husten", ctx: "noun: cough | verb: (to) cough = husten. He's coughing (Abbildung) [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_58", eng: "medicine (no pl)", phon: "['medsn]", ger: "Medizin; Medikament(e)", ctx: "⚠️ Unzählbares Substantiv im Englischen! [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_59", eng: "sick", phon: "[sɪk]", ger: "krank", ctx: "Gegenteil: sick ◀▶ healthy [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_60", eng: "Usage: ill vs. sick", phon: "-", ger: "Krankheitsadjektive im Vergleich", ctx: "⚠️ Nach Verben geht beiderlei (look ill/sick), im AE wird meist 'sick' genutzt. Vor Nomen geht NUR 'sick' (a sick child). Achtung: 'to be sick' meint auch 'sich übergeben müssen' [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_61", eng: "camp", phon: "[kæmp]", ger: "(Zelt-)Lager", ctx: "Introduction 2 | summer camp = Ferienlager [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_62", eng: "awesome", phon: "['ɔ:səm]", ger: "klasse, stark, großartig", ctx: "⚠️ AE, infml. Synonyme: super, great [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_63", eng: "it sounds fun", phon: "-", ger: "es klingt, als ob es Spaß macht", ctx: "verb: (to) sound = klingen | noun: sound = Geräusch [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_64", eng: "public holiday", phon: "['hɒlədeɪ]", ger: "öffentlicher / gesetzlicher Feiertag", ctx: "Kalenderbegriff [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_65", eng: "Easter", phon: "['i:stə]", ger: "Ostern", ctx: "Abbildung Osterhase mit Osterei [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_66", eng: "Christmas", phon: "['krɪsməs]", ger: "Weihnachten", ctx: "Abbildung Christbaumkugel [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_67", eng: "listener", phon: "['lɪsənə]", ger: "Zuhörer/in", ctx: "Personenbezeichnung [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_68", eng: "research", phon: "[rɪ'sɜ:tʃ]", ger: "Forschung(en), Recherche(n)", ctx: "Study skills | Wendung: (to) do research = recherchieren [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_69", eng: "Independence Day", phon: "[ɪndɪ'pendəns deɪ]", ger: "(US-amerikanischer) Unabhängigkeitstag (4. Juli)", ctx: "Feiertag [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_70", eng: "Memorial Day", phon: "[mə'mɔ:riəl deɪ]", ger: "Gedenktag (zur Erinnerung an Kriegsopfer)", ctx: "Feiertag [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "7_71", eng: "parade", phon: "[pə'reɪd]", ger: "Parade, Umzug", ctx: "Festlichkeit [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_72", eng: "turkey", phon: "['tɜ:ki]", ger: "Truthahn, Pute; Putenfleisch", ctx: "Abbildung Comic-Truthahn (a turkey) [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_73", eng: "Thanksgiving Day", phon: "[θæŋks'ɡɪvɪŋ deɪ]", ger: "Erntedankfest", ctx: "Feiertag [Bildschirmfoto 2026-06-27 um 14.51.59.jpg]." },
    { id: "6_74", eng: "nurse", phon: "[nɜ:s]", ger: "Krankenpfleger/in", ctx: "Text 2 | Abbildung medizinisches Personal (nurses) [Bildschirmfoto 2026-06-27 um 14.52.21.jpg]." },
    { id: "6_75", eng: "Well, ...", phon: "[wel]", ger: "Nun, ... / Also, ... / Na ja, ...", ctx: "Gesprächseinleitung [Bildschirmfoto 2026-06-27 um 14.52.21.jpg]." },
    { id: "6_76", eng: "chance", phon: "[tʃɑ:ns]", ger: "Chance, Gelegenheit", ctx: "Satz: If you have the chance, you should visit the British Museum [Bildschirmfoto 2026-06-27 um 14.52.21.jpg]." },
    { id: "6_77", eng: "have got", phon: "[hæv 'ɡɒt]", ger: "haben", ctx: "Synonym: (to) have [Bildschirmfoto 2026-06-27 um 14.52.21.jpg]." },
    { id: "6_78", eng: "Grammatik: German „haben“", phon: "-", ger: "Anwendung im Simple Present vs. Past", ctx: "⚠️ Im Simple Present wird oft 'have got' genutzt (We haven't got a dog). Aber Vorsicht im Simple Past: NICHT had got! Richtig: When I was little, I had a hamster [Bildschirmfoto 2026-06-27 um 14.52.21.jpg]." },
    { id: "6_79", eng: "both", phon: "[bəʊθ]", ger: "beide", ctx: "Satz: Do you want to buy both T-shirts? [Bildschirmfoto 2026-06-27 um 14.52.21.jpg]." },
    { id: "6_80", eng: "(not) at all", phon: "-", ger: "überhaupt (nicht)", ctx: "Your task | Sätze: Have you seen Jack at all this week? No, I haven't seen him at all [Bildschirmfoto 2026-06-27 um 14.52.21.jpg]." },
    { id: "6_81", eng: "Austria", phon: "['ɒstriə]", ger: "Österreich", ctx: "Nachbarland [Bildschirmfoto 2026-06-27 um 14.52.21.jpg]." },
    { id: "6_82", eng: "table", phon: "['teɪbl]", ger: "Tabelle / Tisch", ctx: "⚠️ Doppelbedeutung: 1. Tisch; 2. Tabelle [Bildschirmfoto 2026-06-27 um 14.52.21.jpg]." },
    { id: "6_83", eng: "graph", phon: "[ɡræf]", ger: "Graph, Schaubild", ctx: "Präsentation [Bildschirmfoto 2026-06-27 um 14.52.21.jpg]." },
    { id: "6_84", eng: "chart", phon: "[tʃɑ:t]", ger: "Diagramm; Tabelle", ctx: "Wendung: pie chart = Tortendiagramm [Bildschirmfoto 2026-06-27 um 14.52.21.jpg]." },
    { id: "6_85", eng: "present vs. (to) present", phon: "-", ger: "Aussprache- und Bedeutungswechsel", ctx: "⚠️ Gleiche Schreibweise: 1. present ['preznt] (Geschenk; Gegenwart) ◀▶ 2. (to) present [prɪ'zent] (präsentieren, vorstellen) [Bildschirmfoto 2026-06-27 um 14.52.21.jpg]." },
    { id: "6_86", eng: "result", phon: "[rɪ'zʌlt]", ger: "Ergebnis", ctx: "Wendung: as a result = folglich, demzufolge [Bildschirmfoto 2026-06-27 um 14.52.21.jpg]." },
    { id: "6_87", eng: "clear", phon: "[klɪə]", ger: "klar, deutlich", ctx: "Kombinationen: clear directions (deutliche Anweisungen) | Adverb: speak clearly (deutlich sprechen) [Bildschirmfoto 2026-06-27 um 14.52.21.jpg]." }
];