const e7u1_data = [
    { id: "7_1_1", eng: "island", phon: "['aɪlənd]", ger: "Insel", ctx: "The 's' is silent." },
    { id: "7_1_2", eng: "scenery", phon: "['siːnəri]", ger: "Landschaft, Gegend", ctx: "noun" },
    { id: "7_1_3", eng: "dramatic", phon: "[drə'mætɪk]", ger: "dramatisch", ctx: "adjective" },
    { id: "7_1_4", eng: "landscape", phon: "['lændskeɪp]", ger: "Landschaft", ctx: "noun" },
    { id: "7_1_5", eng: "sheep (pl. sheep)", phon: "[ʃiːp]", ger: "Schaf", ctx: "One sheep, two sheep. Plural stays the same!" },
    { id: "7_1_6", eng: "castle", phon: "['kɑːsl]", ger: "Burg, Schloss", ctx: "The 't' is silent." },
    { id: "7_1_7", eng: "outdoor", phon: "['aʊtdɔː]", ger: "Außen-, Freiluft-, im Freien", ctx: "adjective (e.g., outdoor activities)" },
    { id: "7_1_8", eng: "activity", phon: "[æk'tɪvəti]", ger: "Aktivität", ctx: "plural: activities" },
    { id: "7_1_9", eng: "myth", phon: "[mɪθ]", ger: "Mythos, Sage", ctx: "noun" },
    { id: "7_1_10", eng: "legend", phon: "['ledʒənd]", ger: "Legende, Sage", ctx: "noun" },
    { id: "7_1_11", eng: "championship", phon: "['tʃæmpiənʃɪp]", ger: "Meisterschaft", ctx: "noun" },
    { id: "7_1_12", eng: "stadium", phon: "['steɪdiəm]", ger: "Stadion", ctx: "plural: stadiums" },
    { id: "7_1_13", eng: "spectator", phon: "[spek'teɪtə]", ger: "Zuschauer/-in", ctx: "at a sports event" },
    { id: "7_1_14", eng: "cheer", phon: "[tʃɪə]", ger: "jubeln, anfeuern", ctx: "verb" },
    { id: "7_1_15", eng: "event", phon: "[ɪ'vent]", ger: "Ereignis, Veranstaltung", ctx: "Note the stress on the second syllable!" },
    { id: "7_1_16", eng: "tradition", phon: "[trə'dɪʃn]", ger: "Tradition", ctx: "noun" },
    { id: "7_1_17", eng: "kilts", phon: "[kɪlts]", ger: "Schottenröcke", ctx: "plural noun" },
    { id: "7_1_18", eng: "bagpipes", phon: "['bæɡpaɪps]", ger: "Dudelsack", ctx: "noun" },
    { id: "7_1_19", eng: "caber tossing", phon: "['keɪbə ˌtɒsɪŋ]", ger: "Baumstammwerfen", ctx: "Traditional Scottish sport" },
    { id: "7_1_20", eng: "clans", phon: "[klænz]", ger: "Clans, Sippen, Stämme", ctx: "plural noun" },
    { id: "7_1_21", eng: "gather", phon: "['ɡæðə]", ger: "(sich) versammeln, ansammeln", ctx: "verb" },
    { id: "7_1_22", eng: "compete", phon: "[kəm'piːt]", ger: "wetteifern, antreten", ctx: "verb" },
    { id: "7_1_23", eng: "athlete", phon: "['æθliːt]", ger: "Athlet/-in, Sportler/-in", ctx: "noun" },
    { id: "7_1_24", eng: "heavy", phon: "['hevi]", ger: "schwer", ctx: "opposite of light" },
    { id: "7_1_25", eng: "hammer", phon: "['hæmə]", ger: "Hammer", ctx: "noun" },
    { id: "7_1_26", eng: "throw", phon: "[θrəʊ]", ger: "werfen", ctx: "verb" },
    { id: "7_1_27", eng: "toss", phon: "[tɒs]", ger: "werfen, stoßen", ctx: "verb" },
    { id: "7_1_28", eng: "trunk", phon: "[trʌŋk]", ger: "Baumstamm", ctx: "noun" },
    { id: "7_1_29", eng: "tug-of-war", phon: "[ˌtʌɡəv'wɔː]", ger: "Tauziehen", ctx: "noun" },
    { id: "7_1_30", eng: "rope", phon: "[rəʊp]", ger: "Seil, Tau", ctx: "noun" },
    { id: "7_1_31", eng: "pull", phon: "[pʊl]", ger: "ziehen", ctx: "opposite of push" },
    { id: "7_1_32", eng: "direction", phon: "[də'rekʃn]", ger: "Richtung", ctx: "noun" },
    { id: "7_1_33", eng: "highland dancing", phon: "[ˌhaɪlənd 'dɑːnsɪŋ]", ger: "schottischer Volkstanz", ctx: "noun" },
    { id: "7_1_34", eng: "fringe", phon: "[frɪndʒ]", ger: "Rand, Peripherie", ctx: "e.g., Edinburgh Fringe Festival" },
    { id: "7_1_35", eng: "perform", phon: "[pə'fɔːm]", ger: "auftreten, darbieten, aufführen", ctx: "verb" },
    { id: "7_1_36", eng: "performer", phon: "[pə'fɔːmə]", ger: "Darsteller/-in, Künstler/-in", ctx: "noun" },
    { id: "7_1_37", eng: "performance", phon: "[pə'fɔːməns]", ger: "Aufführung, Vorstellung", ctx: "noun" },
    { id: "7_1_38", eng: "venue", phon: "['venjuː]", ger: "Veranstaltungsort", ctx: "noun" },
    { id: "7_1_39", eng: "comedy", phon: "['kɒmədi]", ger: "Komödie", ctx: "noun" },
    { id: "7_1_40", eng: "theatre", phon: "['θɪətə]", ger: "Theater", ctx: "noun" },
    { id: "7_1_41", eng: "street performance", phon: "[striːt pə'fɔːməns]", ger: "Straßenkunst, Straßenauftritt", ctx: "noun" },
    { id: "7_1_42", eng: "audience", phon: "['ɔːdiəns]", ger: "Publikum, Zuhörer", ctx: "noun" },
    { id: "7_1_43", eng: "huge", phon: "[hjuːdʒ]", ger: "riesig, gewaltig", ctx: "adjective" },
    { id: "7_1_44", eng: "attract", phon: "[ə'trækt]", ger: "anziehen, herbeilocken", ctx: "verb" },
    { id: "7_1_45", eng: "visitor", phon: "['vɪzɪtə]", ger: "Besucher/-in", ctx: "noun" },
    { id: "7_1_46", eng: "popular", phon: "['pɒpjʊlə]", ger: "beliebt, populär", ctx: "adjective" },
    { id: "7_1_47", eng: "arts", phon: "[ɑːts]", ger: "Künste", ctx: "plural noun" },
    { id: "7_1_48", eng: "festival", phon: "['festɪvl]", ger: "Festival, Festspiele", ctx: "noun" }
];