const e7u2_data = [
    { id: "7_2_1", eng: "daily", phon: "['deɪli]", ger: "täglich", ctx: "happens every day" },
    { id: "7_2_2", eng: "(to) exchange", phon: "[ɪks'tʃeɪndʒ]", ger: "austauschen", ctx: "verb" },
    { id: "7_2_3", eng: "chore", phon: "[tʃɔː]", ger: "(Haus-)Arbeit, (lästige) Pflicht", ctx: "(to) do chores" },
    { id: "7_2_4", eng: "(to) take notes", phon: "[teɪk 'nəʊts]", ger: "(sich) Notizen machen", ctx: "beim Lesen oder Zuhören" },
    { id: "7_2_5", eng: "scene", phon: "[siːn]", ger: "Szene", ctx: "-" },
    { id: "7_2_6", eng: "script", phon: "[skrɪpt]", ger: "Drehbuch", ctx: "-" },
    { id: "7_2_7", eng: "(to) relax", phon: "[rɪ'læks]", ger: "sich entspannen", ctx: "English: I'm relaxing. (no reflexive pronoun!)" },
    { id: "7_2_8", eng: "(to) concentrate (on)", phon: "['kɒnsntreɪt]", ger: "sich konzentrieren (auf)", ctx: "verb" },
    { id: "7_2_9", eng: "weekday", phon: "['wiːkdeɪ]", ger: "Werktag, Wochentag", ctx: "Monday to Friday" },
    { id: "7_2_10", eng: "(to) text sb.", phon: "[tekst]", ger: "jm. eine SMS schicken", ctx: "verb" },
    { id: "7_2_11", eng: "(to) play sport(s)", phon: "[pleɪ 'spɔːts]", ger: "Sport treiben", ctx: "-" },
    { id: "7_2_12", eng: "hero (pl. heroes)", phon: "['hɪərəʊ]", ger: "Held/in", ctx: "noun" },
    { id: "7_2_13", eng: "suit", phon: "[suːt]", ger: "(Herren-)Anzug; (Damen-)Kostüm", ctx: "noun" },
    { id: "7_2_14", eng: "evil", phon: "['iːvl]", ger: "böse; (das) Böse", ctx: "can be adjective or noun" },
    { id: "7_2_15", eng: "power", phon: "['paʊə]", ger: "Kraft, Macht", ctx: "noun" },
    { id: "7_2_16", eng: "(to) catch, caught, caught", phon: "[kætʃ], [kɔːt]", ger: "(ein)fangen; erwischen; nehmen", ctx: "e.g., to catch a train" },
    { id: "7_2_17", eng: "scarf (pl. scarves)", phon: "[skɑːf], [skɑːvz]", ger: "Schal", ctx: "Note the plural form!" },
    { id: "7_2_18", eng: "(to) escape (from)", phon: "[ɪ'skeɪp]", ger: "entkommen (aus), fliehen (vor/aus)", ctx: "verb" },
    { id: "7_2_19", eng: "prince", phon: "[prɪns]", ger: "Prinz", ctx: "-" },
    { id: "7_2_20", eng: "king", phon: "[kɪŋ]", ger: "König", ctx: "opposite of queen" },
    { id: "7_2_21", eng: "well", phon: "[wel]", ger: "gut", ctx: "adverb" },
    { id: "7_2_22", eng: "(to) change (into)", phon: "[tʃeɪndʒ]", ger: "(sich) (ver)ändern (zu/in); wechseln; umziehen", ctx: "verb" },
    { id: "7_2_23", eng: "mask", phon: "[mɑːsk]", ger: "Maske", ctx: "-" },
    { id: "7_2_24", eng: "claw", phon: "[klɔː]", ger: "Kralle; Klaue", ctx: "-" },
    { id: "7_2_25", eng: "so (that)", phon: "[səʊ]", ger: "sodass", ctx: "conjunction" },
    { id: "7_2_26", eng: "emergency", phon: "[i'mɜːdʒənsi]", ger: "Notfall", ctx: "noun" },
    { id: "7_2_27", eng: "weapon", phon: "['wepən]", ger: "Waffe", ctx: "-" },
    { id: "7_2_28", eng: "quick", phon: "[kwɪk]", ger: "schnell", ctx: "synonym: fast" },
    { id: "7_2_29", eng: "accountant", phon: "[ə'kaʊntənt]", ger: "Buchhalter/in", ctx: "noun" },
    { id: "7_2_30", eng: "gay", phon: "[ɡeɪ]", ger: "schwal", ctx: "adjective" },
    { id: "7_2_31", eng: "(to) behave", phon: "[bɪ'heɪv]", ger: "sich benehmen; sich verhalten", ctx: "English: He's behaving strangely. (no reflexive!)" },
    { id: "7_2_32", eng: "peace", phon: "[piːs]", ger: "Frieden", ctx: "-" },
    { id: "7_2_33", eng: "bracelet", phon: "['breɪslət]", ger: "Armband", ctx: "noun" },
    { id: "7_2_34", eng: "lasso (pl. lassos/lassoes)", phon: "[læ'suː]", ger: "Lasso", ctx: "Note the pronunciation!" },
    { id: "7_2_35", eng: "truth", phon: "[truːθ]", ger: "Wahrheit", ctx: "(to) tell the truth" },
    { id: "7_2_36", eng: "(to) scan (a text for)", phon: "[skæn]", ger: "(einen Text) überfliegen (nach), absuchen (nach)", ctx: "verb" },
    { id: "7_2_37", eng: "paragraph", phon: "['pærəɡrɑːf]", ger: "(Text-)Abschnitt", ctx: "noun" },
    { id: "7_2_38", eng: "(to) jump", phon: "[dʒʌmp]", ger: "springen", ctx: "verb" },
    { id: "7_2_39", eng: "(to) fit", phon: "[fɪt]", ger: "passen (zu)", ctx: "can be adjective or verb" },
    { id: "7_2_40", eng: "comfortable", phon: "['kʌmftəbl]", ger: "bequem, gemütlich", ctx: "adjective" },
    { id: "7_2_41", eng: "(to) train", phon: "[treɪn]", ger: "trainieren; ausbilden", ctx: "verb" },
    { id: "7_2_42", eng: "(to) train hard", phon: "[treɪn hɑːd]", ger: "hart trainieren", ctx: "hard = adverb here" },
    { id: "7_2_43", eng: "(to) mime", phon: "[maɪm]", ger: "vorspielen, pantomimisch darstellen", ctx: "verb" },
    { id: "7_2_44", eng: "thunder", phon: "['θʌndə]", ger: "Donner (bei Gewitter)", ctx: "noun" },
    { id: "7_2_45", eng: "setting", phon: "['setɪŋ]", ger: "Schauplatz (z. B. Film/Geschichte)", ctx: "noun" },
    { id: "7_2_46", eng: "(to) be down (by) ... %", phon: "[biː daʊn]", ger: "um ... % gesunken sein", ctx: "e.g., Crime is down by 10%." },
    { id: "7_2_47", eng: "(to) steal, stole, stolen", phon: "[stiːl], [stəʊl], ['stəʊlən]", ger: "stehlen, rauben", ctx: "verb" },
    { id: "7_2_48", eng: "character", phon: "['kærəktə]", ger: "Charakter; Figur (aus einer Geschichte)", ctx: "Stress on 1st syllable!" },
    { id: "7_2_49", eng: "plot", phon: "[plɒt]", ger: "Handlung(sverlauf) (z. B. Film/Geschichte)", ctx: "noun" },
    { id: "7_2_50", eng: "Next ...", phon: "[nekst]", ger: "Als Nächstes ...", ctx: "-" },
    { id: "7_2_51", eng: "(to) get in(to) a car", phon: "[ɡet ɪn'tuː]", ger: "in ein Auto einsteigen", ctx: "opposite: (to) get out of a car" },
    { id: "7_2_52", eng: "typical (of)", phon: "['tɪpɪkl]", ger: "typisch (für)", ctx: "That's typical of him." },
    { id: "7_2_53", eng: "dialogue", phon: "['daɪəlɒɡ]", ger: "Dialog", ctx: "Stress on 1st syllable!" },
    { id: "7_2_54", eng: "soundtrack", phon: "['saʊndtræk]", ger: "Filmmusik; Tonspur", ctx: "noun" },
    { id: "7_2_55", eng: "Oh my god!", phon: "[gɒd]", ger: "Oh mein Gott!", ctx: "god = Gott" },
    { id: "7_2_56", eng: "the only student", phon: "['əʊnli]", ger: "der einzige Schüler / die einzige Schülerin", ctx: "only = einzige / nur" },
    { id: "7_2_57", eng: "actually", phon: "['æktʃuəli]", ger: "eigentlich; tatsächlich", ctx: "adverb" },
    { id: "7_2_58", eng: "hopeful", phon: "['həʊpfl]", ger: "zuversichtlich, hoffnungsvoll", ctx: "adjective" },
    { id: "7_2_59", eng: "gross", phon: "[ɡrəʊs]", ger: "widerlich", ctx: "informal" },
    { id: "7_2_60", eng: "dirty", phon: "['dɜːti]", ger: "schmutzig", ctx: "opposite of clean" },
    { id: "7_2_61", eng: "twins", phon: "[twɪnz]", ger: "Zwillinge", ctx: "plural noun" },
    { id: "7_2_62", eng: "(to) vacuum", phon: "['vækjuəm]", ger: "Staub saugen", ctx: "verb" },
    { id: "7_2_63", eng: "because of", phon: "[bɪ'kɒz ɒv]", ger: "wegen", ctx: "preposition" },
    { id: "7_2_64", eng: "(to) set the table", phon: "[set]", ger: "den Tisch decken", ctx: "set, set, set" },
    { id: "7_2_65", eng: "(to) load the dishwasher", phon: "[ləʊd]", ger: "die Spülmaschine einräumen", ctx: "verb" },
    { id: "7_2_66", eng: "trash", phon: "[træʃ]", ger: "Abfall, Müll", ctx: "American English (BE = rubbish)" },
    { id: "7_2_67", eng: "comment", phon: "['kɒment]", ger: "Kommentar", ctx: "noun or verb" },
    { id: "7_2_68", eng: "(to) cut, cut, cut", phon: "[kʌt]", ger: "schneiden; (Rasen) mähen", ctx: "verb" },
    { id: "7_2_69", eng: "mustn't do", phon: "['mʌsnt]", ger: "nicht tun dürfen", ctx: "you mustn't = du darfst nicht" },
    { id: "7_2_70", eng: "potluck (dinner)", phon: "['pɒtlʌk]", ger: "(Abend-)Essen, zu dem jeder etwas mitbringt", ctx: "American English" },
    { id: "7_2_71", eng: "macaroni", phon: "[mækə'rəʊni]", ger: "Makkaroni", ctx: "noun" },
    { id: "7_2_72", eng: "sloppy", phon: "['slɒpi]", ger: "schlabberig; nachlässig, schlampig", ctx: "adjective" },
    { id: "7_2_73", eng: "(to) listen for sth.", phon: "['lɪsn]", ger: "auf etwas horchen, (beim Zuhören) auf etwas achten", ctx: "verb" },
    { id: "7_2_74", eng: "(to) ask for sth.", phon: "[ɑːsk]", ger: "um etwas bitten, nach etwas fragen", ctx: "verb" },
    { id: "7_2_75", eng: "voice message", phon: "['vɔɪs ˌmesɪdʒ]", ger: "Sprachnachricht", ctx: "noun" },
    { id: "7_2_76", eng: "concert", phon: "['kɒnsət]", ger: "Konzert", ctx: "Stress on 1st syllable!" },
    { id: "7_2_77", eng: "hall", phon: "[hɔːl]", ger: "Halle, Saal", ctx: "noun" },
    { id: "7_2_78", eng: "accessible (to)", phon: "[ək'sesəbl]", ger: "erreichbar (für), zugänglich (für)", ctx: "e.g., wheelchair accessible" },
    { id: "7_2_79", eng: "glass", phon: "[ɡlɑːs]", ger: "Glas", ctx: "noun" },
    { id: "7_2_80", eng: "truck", phon: "[trʌk]", ger: "Last(kraft)wagen, LKW", ctx: "American English (= lorry)" },
    { id: "7_2_81", eng: "guest", phon: "[ɡest]", ger: "Gast", ctx: "noun" },
    { id: "7_2_82", eng: "bow tie", phon: "[bəʊ 'taɪ]", ger: "Fliege (Krawatte)", ctx: "bow = Schleife" },
    { id: "7_2_83", eng: "style", phon: "[staɪl]", ger: "Stil; Art", ctx: "noun" },
    { id: "7_2_84", eng: "creative", phon: "[kri'eɪtɪv]", ger: "kreativ", ctx: "Stress on 2nd syllable!" },
    { id: "7_2_85", eng: "sporty", phon: "['spɔːti]", ger: "sportlich", ctx: "adjective" },
    { id: "7_2_86", eng: "heading", phon: "['hedɪŋ]", ger: "Überschrift", ctx: "noun" },
    { id: "7_2_87", eng: "(to) express", phon: "[ɪk'spres]", ger: "ausdrücken, zum Ausdruck bringen", ctx: "(to) express yourself" },
    { id: "7_2_88", eng: "(to) make sb. do sth.", phon: "[meɪk]", ger: "jn. dazu bringen, etwas zu tun", ctx: "verb" },
    { id: "7_2_89", eng: "(to) sew, sewed, sewn", phon: "[səʊ], [səʊd], [səʊn]", ger: "nähen", ctx: "Note the pronunciation [səʊ]!" },
    { id: "7_2_90", eng: "sewing machine", phon: "['səʊɪŋ məˌʃiːn]", ger: "Nähmaschine", ctx: "noun" },
    { id: "7_2_91", eng: "material", phon: "[mə'tɪəriəl]", ger: "Stoff; Material", ctx: "noun" },
    { id: "7_2_92", eng: "(to) start a business", phon: "['bɪznəs]", ger: "ein Geschäft aufmachen, einen Betrieb gründen/eröffnen", ctx: "verb" },
    { id: "7_2_93", eng: "CEO (Chief Executive Officer)", phon: "[ˌsiːiː'əʊ]", ger: "Geschäftsführer/in", ctx: "the boss of a company" },
    { id: "7_2_94", eng: "customer", phon: "['kʌstəmə]", ger: "Kunde, Kundin", ctx: "noun" },
    { id: "7_2_95", eng: "successful", phon: "[sək'sesfl]", ger: "erfolgreich", ctx: "adjective" },
    { id: "7_2_96", eng: "profit", phon: "['prɒfɪt]", ger: "Gewinn (Profit)", ctx: "Stress on 1st syllable!" },
    { id: "7_2_97", eng: "advice (no pl.)", phon: "[əd'vaɪs]", ger: "Rat, Ratschlag, Ratschläge", ctx: "Uncountable! (some advice)" },
    { id: "7_2_98", eng: "president", phon: "['prezɪdənt]", ger: "Präsident/in", ctx: "Stress on 1st syllable!" },
    { id: "7_2_99", eng: "future", phon: "['fjuːtʃə]", ger: "Zukunft; zukünftig(er, s)", ctx: "can be noun or adjective" },
    { id: "7_2_100", eng: "fashion", phon: "['fæʃn]", ger: "Mode", ctx: "noun" },
    { id: "7_2_101", eng: "(to) design", phon: "[dɪ'zaɪn]", ger: "entwerfen, gestalten", ctx: "verb" },
    { id: "7_2_102", eng: "at any age / at the age of ...", phon: "[eɪdʒ]", ger: "in jedem Alter / im Alter von ... Jahren", ctx: "phrase" },
    { id: "7_2_103", eng: "(to) find out (about) sth.", phon: "[faɪnd 'aʊt]", ger: "herausfinden; sich (über etwas) informieren", ctx: "verb" },
    { id: "7_2_104", eng: "(to) tie", phon: "[taɪ]", ger: "binden, schnüren", ctx: "e.g., to tie a tie" },
    { id: "7_2_105", eng: "article", phon: "['ɑːtɪkl]", ger: "Artikel", ctx: "Stress on 1st syllable!" },
    { id: "7_2_106", eng: "vote", phon: "[vəʊt]", ger: "Abstimmung, Votum", ctx: "noun or verb ((to) vote)" }
];