const e7u3_data = [
    { id: "7_3_1", eng: "(to) link (to/with)", phon: "[lɪŋk]", ger: "verbinden (mit)", ctx: "verb: (to) link – noun: link = Verbindung" },
    { id: "7_3_2", eng: "capsule", phon: "['kæpsjuːl]", ger: "Kapsel", ctx: "-" },
    { id: "7_3_3", eng: "ancient", phon: "['eɪnʃənt]", ger: "(ur)alt, historisch", ctx: "meaning: very old" },
    { id: "7_3_4", eng: "Briton", phon: "['brɪtn]", ger: "Brite/Britin", ctx: "-" },
    { id: "7_3_5", eng: "Roman", phon: "['rəʊmən]", ger: "Römer/in; römisch", ctx: "-" },
    { id: "7_3_6", eng: "Viking", phon: "['vaɪkɪŋ]", ger: "Wikinger/in", ctx: "Note the pronunciation!" },
    { id: "7_3_7", eng: "the Angles", phon: "['æŋglz]", ger: "die Angeln", ctx: "germanisches Volk" },
    { id: "7_3_8", eng: "Saxon", phon: "['sæksn]", ger: "Sachse/Sächsin; sächsisch", ctx: "-" },
    { id: "7_3_9", eng: "Norman", phon: "['nɔːmən]", ger: "Normanne/Normannin; normannisch", ctx: "-" },
    { id: "7_3_10", eng: "about", phon: "[ə'baʊt]", ger: "ungefähr", ctx: "e.g., We get up at about 8.30." },
    { id: "7_3_11", eng: "750 BC", phon: "[biː 'siː]", ger: "750 v. Chr.", ctx: "BC = before Christ" },
    { id: "7_3_12", eng: "400 AD", phon: "[eɪ 'diː]", ger: "400 n. Chr.", ctx: "AD = after Christ was born" },
    { id: "7_3_13", eng: "tribe", phon: "[traɪb]", ger: "(Volks-)Stamm", ctx: "-" },
    { id: "7_3_14", eng: "land", phon: "[lænd]", ger: "Land", ctx: "Grund und Boden (Staat = country)" },
    { id: "7_3_15", eng: "(to) settle", phon: "['setl]", ger: "sich niederlassen, sich ansiedeln", ctx: "noun: settler = Siedler/in" },
    { id: "7_3_16", eng: "(to) conquer", phon: "['kɒŋkə]", ger: "erobern", ctx: "verb" },
    { id: "7_3_17", eng: "castle", phon: "['kɑːsl]", ger: "Burg", ctx: "-" },
    { id: "7_3_18", eng: "(to) divide (up) (into)", phon: "[dɪ'vaɪd]", ger: "auf-/einteilen (in)", ctx: "e.g., divided the class into groups" },
    { id: "7_3_19", eng: "empire", phon: "['empaɪə]", ger: "Imperium, Reich", ctx: "-" },
    { id: "7_3_20", eng: "temple", phon: "['templ]", ger: "Tempel", ctx: "-" },
    { id: "7_3_21", eng: "bath", phon: "[bɑːθ]", ger: "Bad; Badewanne", ctx: "have a bath / take a bath" },
    { id: "7_3_22", eng: "(to) invade", phon: "[ɪn'veɪd]", ger: "einmarschieren (in), eindringen (in)", ctx: "The Romans invaded Britain." },
    { id: "7_3_23", eng: "precious metal", phon: "[preʃəs 'metl]", ger: "Edelmetall", ctx: "precious = wertvoll" },
    { id: "7_3_24", eng: "(to) trade", phon: "[treɪd]", ger: "handeln, Handel (be)treiben", ctx: "noun: trade = Handel" },
    { id: "7_3_25", eng: "army", phon: "['ɑːmi]", ger: "Armee", ctx: "Stress on 1st syllable!" },
    { id: "7_3_26", eng: "emperor", phon: "['empərə]", ger: "Kaiser", ctx: "woman = empress" },
    { id: "7_3_27", eng: "daughter", phon: "['dɔːtə]", ger: "Tochter", ctx: "noun" },
    { id: "7_3_28", eng: "fine", phon: "[faɪn]", ger: "fein, dünn", ctx: "e.g., fine hair or cloth" },
    { id: "7_3_29", eng: "wool", phon: "[wʊl]", ger: "Wolle", ctx: "noun" },
    { id: "7_3_30", eng: "linen", phon: "['lɪnɪn]", ger: "Leinen; Wäsche", ctx: "noun" },
    { id: "7_3_31", eng: "husband", phon: "['hʌzbənd]", ger: "Ehemann", ctx: "noun" },
    { id: "7_3_32", eng: "soldier", phon: "['səʊldʒə]", ger: "Soldat/in", ctx: "-" },
    { id: "7_3_33", eng: "side", phon: "[saɪd]", ger: "Seite", ctx: "e.g., other side of the street (Buchseite = page)" },
    { id: "7_3_34", eng: "bone", phon: "[bəʊn]", ger: "Knochen", ctx: "boneless = knochenlos" },
    { id: "7_3_35", eng: "(to) create", phon: "[kri'eɪt]", ger: "(er)schaffen, erstellen", ctx: "verb" },
    { id: "7_3_36", eng: "object", phon: "['ɒbdʒɪkt]", ger: "Objekt, Gegenstand", ctx: "Stress on 1st syllable!" },
    { id: "7_3_37", eng: "knife (pl. knives)", phon: "[naɪf], [naɪvz]", ger: "Messer", ctx: "The 'k' is silent!" },
    { id: "7_3_38", eng: "silver", phon: "['sɪlvə]", ger: "Silber", ctx: "-" },
    { id: "7_3_39", eng: "leather", phon: "['leðə]", ger: "Leder", ctx: "-" },
    { id: "7_3_40", eng: "son", phon: "[sʌn]", ger: "Sohn", ctx: "opposite of daughter" },
    { id: "7_3_41", eng: "axe", phon: "[æks]", ger: "Axt, Beil", ctx: "-" },
    { id: "7_3_42", eng: "kind (of)", phon: "[kaɪnd]", ger: "Art, Sorte", ctx: "What kind of shoes...?" },
    { id: "7_3_43", eng: "(to) dig, dug, dug", phon: "[dɪg], [dʌg]", ger: "graben", ctx: "verb" },
    { id: "7_3_44", eng: "earth", phon: "[3ːθ]", ger: "Erde", ctx: "-" },
    { id: "7_3_45", eng: "(to) discover", phon: "[dɪ'skʌvə]", ger: "entdecken", ctx: "verb" },
    { id: "7_3_46", eng: "dish", phon: "[dɪʃ]", ger: "Schüssel, Schale; Gericht", ctx: "plural: dishes" },
    { id: "7_3_47", eng: "sock", phon: "[sɒk]", ger: "Socke", ctx: "-" },
    { id: "7_3_48", eng: "(to) complete", phon: "[kəm'pliːt]", ger: "vervollständigen", ctx: "adjective: complete = vollständig" },
    { id: "7_3_49", eng: "specific", phon: "[spə'sɪfɪk]", ger: "bestimmte(r, s), spezielle(r, s); genau", ctx: "adjective" },
    { id: "7_3_50", eng: "beard", phon: "[bɪəd]", ger: "Bart", ctx: "noun" },
    { id: "7_3_51", eng: "exact", phon: "[ɪg'zækt]", ger: "genau, exakt", ctx: "adverb: exactly" },
    { id: "7_3_52", eng: "fantasy", phon: "['fæntəsi]", ger: "Fantasie; Fantasy", ctx: "Literatur-/Filmgattung" },
    { id: "7_3_53", eng: "(to) kneel, knelt, knelt", phon: "[niːl], [nelt]", ger: "knien", ctx: "The 'k' is silent!" },
    { id: "7_3_54", eng: "plough", phon: "[plaʊ]", ger: "Pflug", ctx: "noun or verb ((to) plough)" },
    { id: "7_3_55", eng: "he had dug ...", phon: "[dʌg]", ger: "er hatte ... gegraben", ctx: "Past perfect" },
    { id: "7_3_56", eng: "(to) touch", phon: "[tʌtʃ]", ger: "anfassen, berühren", ctx: "verb" },
    { id: "7_3_57", eng: "(to) scrape", phon: "[skreɪp]", ger: "kratzen, schaben", ctx: "-" },
    { id: "7_3_58", eng: "a bit", phon: "[bɪt]", ger: "ein bisschen", ctx: "bit = auch Teil, Stück(chen)" },
    { id: "7_3_59", eng: "(to) lean", phon: "[liːn]", ger: "lehnen", ctx: "e.g., leaning forward" },
    { id: "7_3_60", eng: "forward", phon: "['fɔːwəd]", ger: "vorwärts, nach vorne", ctx: "opposite: back" },
    { id: "7_3_61", eng: "way", phon: "[weɪ]", ger: "Weg; Art und Weise", ctx: "in the way = im Weg" },
    { id: "7_3_62", eng: "although", phon: "[ɔːl'ðəʊ]", ger: "obwohl", ctx: "short form: though" },
    { id: "7_3_63", eng: "(to) explode", phon: "[ɪk'spləʊd]", ger: "explodieren", ctx: "noun: explosion" },
    { id: "7_3_64", eng: "soft", phon: "[sɒft]", ger: "weich; leise (Stimme)", ctx: "adjective" },
    { id: "7_3_65", eng: "spade", phon: "[speɪd]", ger: "Spaten, Schaufel", ctx: "-" },
    { id: "7_3_66", eng: "deep", phon: "[diːp]", ger: "tief", ctx: "in a deep voice = mit tiefer Stimme" },
    { id: "7_3_67", eng: "(to) throw, threw, thrown", phon: "[θrəʊ], [θruː]", ger: "werfen", ctx: "verb" },
    { id: "7_3_68", eng: "at last", phon: "[æt 'lɑːst]", ger: "schließlich, endlich", ctx: "phrase" },
    { id: "7_3_69", eng: "round", phon: "[raʊnd]", ger: "rund", ctx: "preposition: round = um ... herum (= around)" },
    { id: "7_3_70", eng: "plate", phon: "[pleɪt]", ger: "Teller", ctx: "-" },
    { id: "7_3_71", eng: "(to) turn sth. (over)", phon: "[tɜːn]", ger: "etwas umdrehen", ctx: "(to) turn = (sich) umdrehen" },
    { id: "7_3_72", eng: "excitement", phon: "[ɪk'saɪtmənt]", ger: "Aufregung, Spannung", ctx: "adjective: exciting" },
    { id: "7_3_73", eng: "(to) boil", phon: "[bɔɪl]", ger: "kochen (in Wasser); sieden", ctx: "Mahlzeit zubereiten = (to) cook" },
    { id: "7_3_74", eng: "(to) hide, hid, hidden", phon: "[haɪd], [hɪd]", ger: "verstecken; sich verstecken", ctx: "verb" },
    { id: "7_3_75", eng: "upset", phon: "[ʌp'set]", ger: "aufgebracht, verärgert", ctx: "can be adjective or verb" },
    { id: "7_3_76", eng: "greedy", phon: "['griːdi]", ger: "gierig, habgierig", ctx: "adjective" },
    { id: "7_3_77", eng: "century", phon: "['sentʃəri]", ger: "Jahrhundert", ctx: "100 years" },
    { id: "7_3_78", eng: "factory", phon: "['fæktri]", ger: "Fabrik", ctx: "-" },
    { id: "7_3_79", eng: "stranger", phon: "['streɪndʒə]", ger: "Fremde/r", ctx: "adjective: strange = seltsam" },
    { id: "7_3_80", eng: "on time", phon: "[ɒn 'taɪm]", ger: "pünktlich", ctx: "phrase" },
    { id: "7_3_81", eng: "death", phon: "[deθ]", ger: "Tod", ctx: "date of death = Todesdatum (verb: (to) die)" },
    { id: "7_3_82", eng: "structure", phon: "['strʌktʃə]", ger: "Struktur", ctx: "verb: (to) structure = strukturieren" },
    { id: "7_3_83", eng: "(to) sum sth. up", phon: "[sʌm]", ger: "etwas zusammenfassen", ctx: "To sum up, ... = Zusammenfassend..." },
    { id: "7_3_84", eng: "(to) point sb./sth. out", phon: "[pɔɪnt 'aʊt]", ger: "auf etwas hinweisen, aufmerksam machen", ctx: "verb" },
    { id: "7_3_85", eng: "confident", phon: "['kɒnfɪdənt]", ger: "(selbst)sicher; zuversichtlich", ctx: "adjective" },
    { id: "7_3_86", eng: "source", phon: "[sɔːs]", ger: "Quelle (z. B. Website, Text)", ctx: "noun" },
    { id: "7_3_87", eng: "fact", phon: "[fækt]", ger: "Tatsache", ctx: "noun" },
    { id: "7_3_88", eng: "(to) highlight", phon: "['haɪlaɪt]", ger: "hervorheben, unterstreichen", ctx: "noun: highlight = Höhepunkt" },
    { id: "7_3_89", eng: "main", phon: "[meɪn]", ger: "Haupt-, wichtigste(r, s)", ctx: "e.g., the main problem" },
    { id: "7_3_90", eng: "royal", phon: "['rɔɪəl]", ger: "königlich", ctx: "adjective" },
    { id: "7_3_91", eng: "symbol (of)", phon: "['sɪmbl]", ger: "Symbol (für)", ctx: "Stress on 1st syllable!" },
    { id: "7_3_92", eng: "flyer", phon: "['flaɪə]", ger: "Flieger/in", ctx: "someone who flies" },
    { id: "7_3_93", eng: "visit", phon: "['vɪzɪt]", ger: "Besuch", ctx: "noun or verb ((to) visit)" },
    { id: "7_3_94", eng: "rug", phon: "[rʌg]", ger: "Teppich, Läufer", ctx: "meaning: a small carpet" },
    { id: "7_3_95", eng: "ground", phon: "[graʊnd]", ger: "(Erd-)Boden", ctx: "noun" },
    { id: "7_3_96", eng: "(to) spin, spun, spun", phon: "[spɪn], [spʌn]", ger: "(sich) drehen", ctx: "meaning: (to) turn" },
    { id: "7_3_97", eng: "(to) arrive", phon: "[ə'raɪv]", ger: "ankommen", ctx: "opposite: leave" },
    { id: "7_3_98", eng: "a few", phon: "[fjuː]", ger: "ein paar, einige", ctx: "e.g., a few apples" },
    { id: "7_3_99", eng: "(to) nod (your head)", phon: "[nɒd]", ger: "(mit dem Kopf) nicken", ctx: "(to) nod to sb. = jm. zunicken" },
    { id: "7_3_100", eng: "disappointed (with)", phon: "[ˌdɪsə'pɔɪntɪd]", ger: "enttäuscht (von)", ctx: "verb: (to) disappoint sb." },
    { id: "7_3_101", eng: "duck", phon: "[dʌk]", ger: "Ente", ctx: "plural: ducks" },
    { id: "7_3_102", eng: "towards / toward (AE)", phon: "[tə'wɔːdz]", ger: "nach, auf ... zu, in Richtung (von)", ctx: "preposition" },
    { id: "7_3_103", eng: "I didn't know what to say.", phon: "[weɪ]", ger: "Ich wusste nicht, was ich sagen sollte.", ctx: "phrase" },
    { id: "7_3_104", eng: "(to) continue", phon: "[kən'tɪnjuː]", ger: "fortfahren, weitermachen; (sich) fortsetzen", ctx: "verb" },
    { id: "7_3_105", eng: "light", phon: "[laɪt]", ger: "leicht; hell", ctx: "also noun: Licht, Lampe" },
    { id: "7_3_106", eng: "rude", phon: "[ruːd]", ger: "unhöflich, frech", ctx: "opposite of polite" },
    { id: "7_3_107", eng: "distance", phon: "['dɪstəns]", ger: "Distanz, Entfernung", ctx: "in the distance = in der Ferne" },
    { id: "7_3_108", eng: "halfway", phon: "[hɑːf'weɪ]", ger: "auf halbem Wege, halb(wegs)", ctx: "e.g., halfway there" },
    { id: "7_3_109", eng: "below", phon: "[bɪ'ləʊ]", ger: "unter(halb von); unten", ctx: "opposite: above" },
    { id: "7_3_110", eng: "hardly", phon: "['hɑːdli]", ger: "kaum", ctx: "e.g., hardly any work (adverb)" },
    { id: "7_3_111", eng: "caption", phon: "['kæpʃn]", ger: "Bildunterschrift", ctx: "noun" },
    { id: "7_3_112", eng: "entry", phon: "['entri]", ger: "Eintritt, Zutritt; (Tagebuch-)Eintrag", ctx: "e.g., a diary entry" },
    { id: "7_3_113", eng: "interest (in)", phon: "['ɪntrəst]", ger: "Interesse (an)", ctx: "adjective: interesting" },
    { id: "7_3_114", eng: "(to) decorate", phon: "['dekəreɪt]", ger: "dekorieren, schmücken", ctx: "Stress on 1st syllable!" }
];