const e7u4_data = [
    { id: "7_4_1", eng: "similar (to sb./sth.)", phon: "['sɪmələ]", ger: "(jm./einer Sache) ähnlich", ctx: "Your new bike is similar to mine." },
    { id: "7_4_2", eng: "snapshot", phon: "['snæpʃɒt]", ger: "Schnappschuss", ctx: "a photo that you take quickly" },
    { id: "7_4_3", eng: "pub", phon: "[pʌb]", ger: "Kneipe", ctx: "-" },
    { id: "7_4_4", eng: "Gaelic", phon: "['ɡeɪlɪk]", ger: "Gälisch (Sprache)", ctx: "a language spoken in Ireland" },
    { id: "7_4_5", eng: "dock", phon: "[dɒk]", ger: "Hafen, Dock", ctx: "-" },
    { id: "7_4_6", eng: "stew", phon: "[stjuː]", ger: "Eintopf(gericht)", ctx: "a meal of meat and vegetables cooked together" },
    { id: "7_4_7", eng: "St = Saint", phon: "[seɪnt]", ger: "St = Sankt", ctx: "e.g., St Patrick" },
    { id: "7_4_8", eng: "statue", phon: "['stætʃuː]", ger: "Statue", ctx: "-" },
    { id: "7_4_9", eng: "monument", phon: "['mɒnjʊmənt]", ger: "Monument, Denkmal", ctx: "Stress on 1st syllable!" },
    { id: "7_4_10", eng: "musician", phon: "[mju'zɪʃn]", ger: "Musiker/in", ctx: "noun" },
    { id: "7_4_11", eng: "famine", phon: "['fæmɪn]", ger: "Hungersnot", ctx: "-" },
    { id: "7_4_12", eng: "memorial (to sb./sth.)", phon: "[mə'mɔːriəl]", ger: "Denkmal (für jn./etwas), Gedenkstätte", ctx: "e.g., a memorial to heroes" },
    { id: "7_4_13", eng: "(to) skim a text", phon: "[skɪm]", ger: "einen Text überfliegen", ctx: "um den Inhalt grob zu erfassen" },
    { id: "7_4_14", eng: "population", phon: "[pɒpjʊ'leɪʃn]", ger: "Bevölkerung, Einwohner(zahl)", ctx: "noun" },
    { id: "7_4_15", eng: "(to) choose to do sth.", phon: "[tʃuːz]", ger: "sich entscheiden, beschließen etwas zu tun", ctx: "chose to do" },
    { id: "7_4_16", eng: "(to) starve", phon: "[stɑːv]", ger: "verhungern", ctx: "to die because you don't have enough to eat" },
    { id: "7_4_17", eng: "disease", phon: "[dɪ'ziːz]", ger: "Krankheit", ctx: "für ansteckende/ernsthafte Erkrankungen (allgemein = illness)" },
    { id: "7_4_18", eng: "crowded", phon: "['kraʊdɪd]", ger: "überfüllt, voll (von Menschen)", ctx: "noun: crowd = Menschenmenge" },
    { id: "7_4_19", eng: "deck", phon: "[dek]", ger: "Deck", ctx: "Let's go on deck. (an Deck gehen)" },
    { id: "7_4_20", eng: "bucket", phon: "['bʌkɪt]", ger: "Eimer", ctx: "e.g., a bucket and a spade" },
    { id: "7_4_21", eng: "(to) spread, spread, spread", phon: "[spred]", ger: "(etwas) verbreiten; sich ausbreiten", ctx: "e.g., a disease is spreading" },
    { id: "7_4_22", eng: "coffin", phon: "['kɒfɪn]", ger: "Sarg", ctx: "-" },
    { id: "7_4_23", eng: "shark", phon: "[ʃɑːk]", ger: "Hai", ctx: "-" },
    { id: "7_4_24", eng: "(to) manage (to do sth.)", phon: "['mænɪdʒ]", ger: "(es) schaffen (etwas zu tun)", ctx: "followed by infinitive with 'to'" },
    { id: "7_4_25", eng: "captain", phon: "['kæptɪn]", ger: "Kapitän/in", ctx: "-" },
    { id: "7_4_26", eng: "(to) make sure that ...", phon: "[meɪk ʃʊə]", ger: "sicherstellen, dass ...; dafür sorgen, dass ...", ctx: "phrase" },
    { id: "7_4_27", eng: "owner", phon: "['əʊnə]", ger: "Besitzer/in", ctx: "verb: (to) own = etwas besitzen" },
    { id: "7_4_28", eng: "root", phon: "[ruːt]", ger: "Wurzel", ctx: "can be a family's roots" },
    { id: "7_4_29", eng: "(to) be called", phon: "[kɔːld]", ger: "heißen", ctx: "e.g., a dog called Fido" },
    { id: "7_4_30", eng: "emigration", phon: "[emɪ'ɡreɪʃn]", ger: "Auswanderung", ctx: "verb: (to) emigrate = auswandern" },
    { id: "7_4_31", eng: "immigration", phon: "[ɪmɪ'ɡreɪʃn]", ger: "Einwanderung", ctx: "verb: (to) immigrate = einwandern" },
    { id: "7_4_32", eng: "pattern", phon: "['pætn]", ger: "(wiederkehrendes) Muster, Schema", ctx: "-" },
    { id: "7_4_33", eng: "southern", phon: "['sʌðən]", ger: "südlich, Süd-", ctx: "Note pronunciation change from south [saʊθ]!" },
    { id: "7_4_34", eng: "northern", phon: "['nɔːðən]", ger: "nördlich, Nord-", ctx: "-" },
    { id: "7_4_35", eng: "eastern", phon: "['iːstən]", ger: "östlich, Ost-", ctx: "-" },
    { id: "7_4_36", eng: "western", phon: "['westən]", ger: "westlich, West-", ctx: "-" },
    { id: "7_4_37", eng: "violence", phon: "['vaɪələns]", ger: "Gewalt; Gewalttätigkeit", ctx: "adjective: violent" },
    { id: "7_4_38", eng: "Catholic", phon: "['kæθlɪk]", ger: "Katholik/in; katholisch", ctx: "Stress on 1st syllable!" },
    { id: "7_4_39", eng: "independence (from)", phon: "[ɪndɪ'pendəns]", ger: "Unabhängigkeit (von)", ctx: "adjective: independent" },
    { id: "7_4_40", eng: "Protestant", phon: "['prɒtɪstənt]", ger: "Protestant/in; protestantisch", ctx: "Stress on 1st syllable!" },
    { id: "7_4_41", eng: "pleased", phon: "[pliːzd]", ger: "froh, erfreut, zufrieden", ctx: "Pleased to meet you." },
    { id: "7_4_42", eng: "slave", phon: "[sleɪv]", ger: "Sklave, Sklavin", ctx: "-" },
    { id: "7_4_43", eng: "(to) pray", phon: "[preɪ]", ger: "beten", ctx: "noun: prayer = Gebet" },
    { id: "7_4_44", eng: "(to) study", phon: "['stʌdi]", ger: "studieren; lernen", ctx: "e.g., to study for tomorrow's test" },
    { id: "7_4_45", eng: "priest", phon: "[priːst]", ger: "Priester/in", ctx: "-" },
    { id: "7_4_46", eng: "shamrock", phon: "['ʃæmrɒk]", ger: "Kleeblatt", ctx: "-" },
    { id: "7_4_47", eng: "holy", phon: "['həʊli]", ger: "heilig", ctx: "adjective" },
    { id: "7_4_48", eng: "national day", phon: "[næʃnəl 'deɪ]", ger: "Nationalfeiertag", ctx: "-" },
    { id: "7_4_49", eng: "tradition", phon: "[trə'dɪʃn]", ger: "Tradition", ctx: "Stress on 2nd syllable! (adjective: traditional)" },
    { id: "7_4_50", eng: "snake", phon: "[sneɪk]", ger: "Schlange", ctx: "-" },
    { id: "7_4_51", eng: "(to) attack", phon: "[ə'tæk]", ger: "angreifen", ctx: "noun: attack = Angriff" },
    { id: "7_4_52", eng: "(to) drive, drove, driven", phon: "[draɪv], [drəʊv], ['drɪvn]", ger: "fahren; (an)treiben (Tiere)", ctx: "You drive a car, but you ride a bike." },
    { id: "7_4_53", eng: "scientist", phon: "['saɪəntɪst]", ger: "(Natur-)Wissenschaftler/in", ctx: "noun" },
    { id: "7_4_54", eng: "background", phon: "['bækɡraʊnd]", ger: "Hintergrund", ctx: "opposite: foreground = Vordergrund" },
    { id: "7_4_55", eng: "bank", phon: "[bæŋk]", ger: "Bank (Geldinstitut)", ctx: "-" },
    { id: "7_4_56", eng: "the nearest ...", phon: "['nɪərəst]", ger: "der/die/das nächstgelegene ...", ctx: "räumlich (Reihenfolge = next)" },
    { id: "7_4_57", eng: "the nearest one", phon: "[wʌn]", ger: "der/die/das Nächstgelegene", ctx: "one/ones is used to avoid repeating a noun" },
    { id: "7_4_58", eng: "oyster", phon: "['ɔɪstə]", ger: "Auster", ctx: "-" },
    { id: "7_4_59", eng: "surprise", phon: "[sə'praɪz]", ger: "Überraschung", ctx: "verb: (to) surprise = überraschen" },
    { id: "7_4_60", eng: "cavern", phon: "['kævən]", ger: "Höhle", ctx: "meaning: a big cave" },
    { id: "7_4_61", eng: "hunt", phon: "[hʌnt]", ger: "Jagd", ctx: "verb: (to) hunt = jagen" },
    { id: "7_4_62", eng: "you might find ...", phon: "[maɪt]", ger: "du könntest ... finden, vielleicht findest du ...", ctx: "expresses possibility" },
    { id: "7_4_63", eng: "coin", phon: "[kɔɪn]", ger: "Münze", ctx: "-" },
    { id: "7_4_64", eng: "beer", phon: "[bɪə]", ger: "Bier", ctx: "-" },
    { id: "7_4_65", eng: "flour", phon: "['flaʊə]", ger: "Mehl", ctx: "-" },
    { id: "7_4_66", eng: "wholemeal", phon: "['həʊlmiːl]", ger: "Vollkorn-", ctx: "e.g., wholemeal bread" },
    { id: "7_4_67", eng: "teaspoon", phon: "['tiːspuːn]", ger: "Teelöffel", ctx: "spoon = Löffel (tablespoon = Esslöffel)" },
    { id: "7_4_68", eng: "baking soda", phon: "['beɪkɪŋ ˌsəʊdə]", ger: "Back-Natron, Backsoda", ctx: "-" },
    { id: "7_4_69", eng: "buttermilk", phon: "['bʌtəmɪlk]", ger: "Buttermilch", ctx: "-" },
    { id: "7_4_70", eng: "a little", phon: "['lɪtl]", ger: "ein wenig, ein bisschen", ctx: "synonym: a bit" },
    { id: "7_4_71", eng: "cross", phon: "[krɒs]", ger: "Kreuz", ctx: "verb: (to) cross = kreuzen, überqueren" },
    { id: "7_4_72", eng: "(to) bake", phon: "[beɪk]", ger: "backen", ctx: "verb" },
    { id: "7_4_73", eng: "bowl", phon: "[bəʊl]", ger: "Schüssel, Schale", ctx: "noun" },
    { id: "7_4_74", eng: "baking sheet", phon: "['beɪkɪŋ ʃiːt]", ger: "Backblech", ctx: "-" },
    { id: "7_4_75", eng: "(to) cool", phon: "[kuːl]", ger: "(ab)kühlen", ctx: "adjective: cool = kühl" },
    { id: "7_4_76", eng: "(to) knead", phon: "[niːd]", ger: "kneten", ctx: "The 'k' is silent!" },
    { id: "7_4_77", eng: "impatient", phon: "[ɪm'peɪʃnt]", ger: "ungeduldig", ctx: "opposite: patient = geduldig" },
    { id: "7_4_78", eng: "(to) stand up (straight)", phon: "[stænd ʌp]", ger: "(gerade) stehen; sich (gerade) hinstellen", ctx: "phrase" },
    { id: "7_4_79", eng: "(to) tap sth.", phon: "[tæp]", ger: "(leise) klopfen, tippen an etwas", ctx: "e.g., tap your fingers" },
    { id: "7_4_80", eng: "(to) frown", phon: "[fraʊn]", ger: "die Stirn runzeln", ctx: "noun: frown" },
    { id: "7_4_81", eng: "(to) shrug (your shoulders)", phon: "[ʃrʌɡ]", ger: "mit den Achseln/Schultern zucken", ctx: "noun: shrug" },
    { id: "7_4_82", eng: "elbow", phon: "['elbəʊ]", ger: "Ellbogen", ctx: "noun" },
    { id: "7_4_83", eng: "(to) roll", phon: "[rəʊl]", ger: "rollen; (sich) verdrehen (Augen)", ctx: "e.g., roll your eyes" },
    { id: "7_4_84", eng: "I don't care.", phon: "[keə]", ger: "Es ist mir egal.", ctx: "I care about you = Du bist mir nicht egal." },
    { id: "7_4_85", eng: "(to) annoy sb.", phon: "[ə'nɔɪ]", ger: "jn. ärgern", ctx: "adjective: annoying = ärgerlich" },
    { id: "7_4_86", eng: "lonely", phon: "['ləʊnli]", ger: "einsam", ctx: "adjective" },
    { id: "7_4_87", eng: "unsure", phon: "[ʌn'ʃʊə]", ger: "unsicher", ctx: "opposite: sure = sicher" },
    { id: "7_4_88", eng: "movement", phon: "['muːvmənt]", ger: "Bewegung", ctx: "verb: (to) move" },
    { id: "7_4_89", eng: "hostel", phon: "['hɒstl]", ger: "Wohnheim; Hostel", ctx: "günstige Unterkunft für Reisende" },
    { id: "7_4_90", eng: "(to) emphasize", phon: "['emfəsaɪz]", ger: "betonen, deutlich machen", ctx: "verb" },
    { id: "7_4_91", eng: "review", phon: "[rɪ'vjuː]", ger: "Besprechung, Rezension, Kritik", ctx: "noun or verb" },
    { id: "7_4_92", eng: "(to) recommend sth. (to sb.)", phon: "[rekə'mend]", ger: "(jm.) etwas empfehlen", ctx: "verb" },
    { id: "7_4_93", eng: "tech", phon: "[tek]", ger: "Technik", ctx: "informal for technology" },
    { id: "7_4_94", eng: "farming", phon: "['fɑːmɪŋ]", ger: "Landwirtschaft", ctx: "noun (farmers live from farming)" },
    { id: "7_4_95", eng: "European Union (EU)", phon: "[ˌjʊərəpiːən 'juːniən]", ger: "Europäische Union (EU)", ctx: "-" },
    { id: "7_4_96", eng: "economy", phon: "[ɪ'kɒnəmi]", ger: "(Volks-)Wirtschaft", ctx: "adjective: economic = wirtschaftlich" },
    { id: "7_4_97", eng: "(to) crash", phon: "[kræʃ]", ger: "abstürzen (lassen), zusammenbrechen", ctx: "also noun: crash = Zusammenstoß, Absturz" },
    { id: "7_4_98", eng: "profile", phon: "['prəʊfaɪl]", ger: "Profil; Beschreibung, Portrait", ctx: "Stress on 1st syllable!" },
    { id: "7_4_99", eng: "mentor", phon: "['mentɔː]", ger: "Mentor/in (Ratgeber/in)", ctx: "verb: (to) mentor = betreuen" },
    { id: "7_4_100", eng: "award", phon: "[ə'wɔːd]", ger: "Preis (Auszeichnung)", ctx: "e.g., award-winning" },
    { id: "7_4_101", eng: "digital", phon: "['dɪdʒɪtl]", ger: "digital", ctx: "Stress on 1st syllable!" },
    { id: "7_4_102", eng: "skill", phon: "[skɪl]", ger: "Fähigkeit, Fertigkeit", ctx: "e.g., computer skills" },
    { id: "7_4_103", eng: "(to) suggest", phon: "[sə'dʒest]", ger: "vorschlagen", ctx: "suggested doing sth. or suggested (that) we go" },
    { id: "7_4_104", eng: "(to) develop", phon: "[dɪ'veləp]", ger: "entwickeln; sich entwickeln", ctx: "verb" },
    { id: "7_4_105", eng: "especially", phon: "[ɪ'speʃəli]", ger: "insbesondere", ctx: "adverb" },
    { id: "7_4_106", eng: "(to) set sth. up", phon: "[set ʌp]", ger: "etwas einrichten, aufbauen", ctx: "e.g., to set up a business" },
    { id: "7_4_107", eng: "according to ...", phon: "[ə'kɔːdɪŋ tu]", ger: "laut ...; ... zufolge", ctx: "e.g., according to my mum" },
    { id: "7_4_108", eng: "(to) imagine", phon: "[ɪ'mædʒɪn]", ger: "sich etwas vorstellen", ctx: "followed by -ing form" },
    { id: "7_4_109", eng: "be allowed to do sth.", phon: "[ə'laʊd]", ger: "etwas tun dürfen", ctx: "e.g., dictionaries are not allowed" },
    { id: "7_4_110", eng: "dolphin", phon: "['dɒlfɪn]", ger: "Delfin", ctx: "-" },
    { id: "7_4_111", eng: "handover", phon: "['hændəʊvə]", ger: "Übergabe", ctx: "noun" }
];