const e7u5_data = [
    { id: "7_5_1", eng: "strategy", phon: "['strætədʒi]", ger: "Strategie", ctx: "Betonung auf der 1. Silbe!" },
    { id: "7_5_2", eng: "webpage", phon: "['webpeɪdʒ]", ger: "Webseite", ctx: "-" },
    { id: "7_5_3", eng: "happiness", phon: "['hæpinəs]", ger: "Glück, Zufriedenheit", ctx: "adjective: happy" },
    { id: "7_5_4", eng: "skate park", phon: "['skeɪt pɑːk]", ger: "Skatepark", ctx: "verb: (to) skateboard or (to) skate" },
    { id: "7_5_5", eng: "(to) prefer sth. to sth.", phon: "[prɪ'fɜː]", ger: "etwas einer Sache vorziehen, etwas lieber tun/haben als etwas", ctx: "past: preferred (-rr-)" },
    { id: "7_5_6", eng: "biking", phon: "['baɪkɪŋ]", ger: "(das) Radfahren", ctx: "synonym: riding a bike" },
    { id: "7_5_7", eng: "friendship", phon: "['frendʃɪp]", ger: "Freundschaft", ctx: "noun" },
    { id: "7_5_8", eng: "What/Where/... the heck is ...?", phon: "[hek]", ger: "Was/Wo/... ist denn nur/bloß ...?", ctx: "informal" },
    { id: "7_5_9", eng: "sponsor", phon: "['spɒnsə]", ger: "Sponsor/in (Geldgeber/in)", ctx: "verb: (to) sponsor" },
    { id: "7_5_10", eng: "subscriber", phon: "[səb'skraɪbə]", ger: "Aonnent/in", ctx: "verb: (to) subscribe to sth." },
    { id: "7_5_11", eng: "total", phon: "['təʊtl]", ger: "Gesamt-; total", ctx: "can be adjective or noun" },
    { id: "7_5_12", eng: "view", phon: "[vjuː]", ger: "Aufruf (Internet); (An-)Blick, (Aus-)Sicht", ctx: "noun or verb" },
    { id: "7_5_13", eng: "site", phon: "[saɪt]", ger: "Website; Stelle, Platz, Stätte", ctx: "e.g., site of the accident" },
    { id: "7_5_14", eng: "founder", phon: "['faʊndə]", ger: "Gründer/in", ctx: "verb: (to) found (founded, NOT find/found)" },
    { id: "7_5_15", eng: "since then", phon: "[sɪns 'ðen]", ger: "seitdem", ctx: "phrase" },
    { id: "7_5_16", eng: "(to) entertain sb.", phon: "[entə'teɪn]", ger: "jn. unterhalten", ctx: "verb" },
    { id: "7_5_17", eng: "silly", phon: "['sɪli]", ger: "dumm, blöd; albern", ctx: "adjective" },
    { id: "7_5_18", eng: "giraffe", phon: "[dʒə'rɑːf]", ger: "Giraffe", ctx: "plural: giraffe or giraffes" },
    { id: "7_5_19", eng: "underwater", phon: "[ʌndə'wɔːtə]", ger: "unter Wasser, Unterwasser-", ctx: "adjective or adverb" },
    { id: "7_5_20", eng: "quality", phon: "['kwɒləti]", ger: "Qualität, Qualitäts-; Eigenschaft", ctx: "noun" },
    { id: "7_5_21", eng: "chewing gum", phon: "['tʃuːɪŋ ɡʌm]", ger: "Kaugummi", ctx: "(to) chew = kauen" },
    { id: "7_5_22", eng: "however", phon: "[haʊ'evə]", ger: "allerdings, jedoch", ctx: "adverb" },
    { id: "7_5_23", eng: "Firstly / Secondly / Thirdly", phon: "['fɜːstli], ['sekəndli], ['θɜːdli]", ger: "Erstens / Zweitens / Drittens", ctx: "adverbs" },
    { id: "7_5_24", eng: "crowdfunding", phon: "['kraʊdfʌndɪŋ]", ger: "Crowdfunding (Schwarmfinanzierung)", ctx: "noun" },
    { id: "7_5_25", eng: "advertising", phon: "['ædvətaɪzɪŋ]", ger: "Werbung, Reklame", ctx: "verb: (to) advertise" },
    { id: "7_5_26", eng: "social media", phon: "[səʊʃl 'miːdiə]", ger: "soziale Medien", ctx: "Note: *on* social media" },
    { id: "7_5_27", eng: "social", phon: "['səʊʃl]", ger: "sozial", ctx: "adjective" },
    { id: "7_5_28", eng: "(to) earn", phon: "[ɜːn]", ger: "verdienen (Geld)", ctx: "Gehalt bekommen (Profit machen = to make money)" },
    { id: "7_5_29", eng: "(to) go viral", phon: "[ɡəʊ 'vaɪrəl]", ger: "sich rasend schnell verbreiten", ctx: "viral = wie ein Virus" },
    { id: "7_5_30", eng: "elephant", phon: "['elɪfənt]", ger: "Elefant", ctx: "-" },
    { id: "7_5_31", eng: "several", phon: "['sevrəl]", ger: "mehrere, einige", ctx: "adjective" },
    { id: "7_5_32", eng: "hyphen", phon: "['haɪfn]", ger: "Bindestrich, Trennstrich", ctx: "noun" },
    { id: "7_5_33", eng: "meme", phon: "[miːm]", ger: "Internet-Mem, Internetphänomen", ctx: "-" },
    { id: "7_5_34", eng: "pug", phon: "[pʌɡ]", ger: "Mops (Hund)", ctx: "-" },
    { id: "7_5_35", eng: "cute", phon: "[kjuːt]", ger: "niedlich, süß", ctx: "adjective" },
    { id: "7_5_36", eng: "attention", phon: "[ə'tenʃn]", ger: "Aufmerksamkeit", ctx: "(to) pay attention (to) = achten (auf)" },
    { id: "7_5_37", eng: "length", phon: "[leŋθ]", ger: "Länge; Dauer", ctx: "noun (adjective: long)" },
    { id: "7_5_38", eng: "violin", phon: "[vaɪə'lɪn]", ger: "Geige, Violine", ctx: "-" },
    { id: "7_5_39", eng: "career", phon: "[kə'rɪə]", ger: "Karriere; Werdegang", ctx: "noun" },
    { id: "7_5_40", eng: "billion", phon: "['bɪljən]", ger: "Milliarde", ctx: "meaning: one thousand million" },
    { id: "7_5_41", eng: "ludo", phon: "['luːdəʊ]", ger: "Mensch ärgere dich nicht (Spiel)", ctx: "-" },
    { id: "7_5_42", eng: "aim", phon: "[eɪm]", ger: "Ziel", ctx: "noun or verb ((to) aim at)" },
    { id: "7_5_43", eng: "token", phon: "['təʊkən]", ger: "Spielfigur; Chip; Gutschein", ctx: "noun" },
    { id: "7_5_44", eng: "dice", phon: "[daɪs]", ger: "Würfel", ctx: "singular and plural are the same here (two dice)" },
    { id: "7_5_45", eng: "square", phon: "[skweə]", ger: "Kästchen, Spielfeld; Platz (Stadt)", ctx: "noun" },
    { id: "7_5_46", eng: "block", phon: "[blɒk]", ger: "Block; Klotz", ctx: "-" },
    { id: "7_5_47", eng: "single", phon: "['sɪŋɡl]", ger: "Einzel-, einzelne(r, s)", ctx: "e.g., a single room" },
    { id: "7_5_48", eng: "multiplayer", phon: "['mʌltiˌpleɪə]", ger: "Mehrspieler-", ctx: "adjective" },
    { id: "7_5_49", eng: "unfortunately", phon: "[ʌn'fɔːtʃənətli]", ger: "unglücklicherweise, leider", ctx: "opposite: fortunately" },
    { id: "7_5_50", eng: "(to) offer", phon: "['ɒfə]", ger: "bieten, anbieten", ctx: "noun: offer = Angebot" },
    { id: "7_5_51", eng: "(to) change your mind", phon: "[tʃeɪndʒ]", ger: "seine Meinung ändern", ctx: "phrase" },
    { id: "7_5_52", eng: "(to) react (to)", phon: "[ri'ækt]", ger: "reagieren (auf)", ctx: "verb" },
    { id: "7_5_53", eng: "What do they think of/about ...?", phon: "[θɪŋk]", ger: "Was halten sie von ...? / Wie denken sie über ...?", ctx: "phrase" },
    { id: "7_5_54", eng: "lame", phon: "[leɪm]", ger: "lahm, langweilig", ctx: "synonym: boring, not interesting" },
    { id: "7_5_55", eng: "(to) turn sth. down", phon: "[tɜːn]", ger: "etwas leise(r) stellen, herunterregeln", ctx: "e.g., turn the music down" },
    { id: "7_5_56", eng: "in sb.'s shoes", phon: "[ʃuːz]", ger: "an jds. Stelle", ctx: "e.g., if I were in your shoes" },
    { id: "7_5_57", eng: "like this", phon: "[laɪk 'ðɪs]", ger: "so, auf diese Art", ctx: "phrase" },
    { id: "7_5_58", eng: "(to) switch sth. on/off", phon: "[swɪtʃ]", ger: "etwas einschalten / ausschalten", ctx: "noun: switch = Schalter" },
    { id: "7_5_59", eng: "you ought to switch off ...", phon: "['ɔːt tu]", ger: "du solltest ... ausschalten", ctx: "synonym: you should" },
    { id: "7_5_60", eng: "effect", phon: "[ɪ'fekt]", ger: "(Aus-)Wirkung, Einfluss, Effekt", ctx: "noun (adjective: effective)" },
    { id: "7_5_61", eng: "likely", phon: "['laɪkli]", ger: "wahrscheinlich", ctx: "opposite: unlikely" },
    { id: "7_5_62", eng: "hairstyle", phon: "['heəstaɪl]", ger: "Friseur", ctx: "noun" },
    { id: "7_5_63", eng: "(to) suit (sb.)", phon: "[suːt]", ger: "geeignet sein für, passen (zu); jm. stehen", ctx: "e.g., Does this hairstyle suit me?" },
    { id: "7_5_64", eng: "plastic", phon: "['plæstɪk]", ger: "Plastik, Kunststoff", ctx: "noun" },
    { id: "7_5_65", eng: "environment", phon: "[ɪn'vaɪrənmənt]", ger: "Umwelt; Umfeld, Umgebung", ctx: "adjective: environmental" },
    { id: "7_5_66", eng: "(to) recycle", phon: "[ˌriː'saɪkl]", ger: "recyceln, wiederverwerten", ctx: "noun: recycling" },
    { id: "7_5_67", eng: "(to) ban", phon: "[bæn]", ger: "verbieten", ctx: "noun: ban (on) = Verbot (von)" },
    { id: "7_5_68", eng: "etc. (et cetera)", phon: "[et'setərə]", ger: "usw. (und so weiter)", ctx: "-" },
    { id: "7_5_69", eng: "(to) protect (from/against)", phon: "[prə'tekt]", ger: "(be)schützen (vor)", ctx: "e.g., protect you from the rain" },
    { id: "7_5_70", eng: "meaning", phon: "['miːnɪŋ]", ger: "Bedeutung", ctx: "verb: (to) mean = bedeuten" },
    { id: "7_5_71", eng: "pronunciation", phon: "[prəˌnʌnsi'eɪʃn]", ger: "Aussprache", ctx: "verb: (to) pronounce" },
    { id: "7_5_72", eng: "(to) revise", phon: "[rɪ'vaɪz]", ger: "(Lernstoff) wiederholen", ctx: "noun: revision" },
    { id: "7_5_73", eng: "statistics (pl.)", phon: "[stə'tɪstɪks]", ger: "Statistik(en)", ctx: "The statistics show that..." },
    { id: "7_5_74", eng: "on the go", phon: "[ɒn ðə 'ɡəʊ]", ger: "unterwegs", ctx: "phrase" },
    { id: "7_5_75", eng: "postcode", phon: "['pəʊstkəʊd]", ger: "Postleitzahl", ctx: "-" },
    { id: "7_5_76", eng: "yum", phon: "[jʌm]", ger: "lecker", ctx: "informal" },
    { id: "7_5_77", eng: "(to) chill out", phon: "[tʃɪl 'aʊt]", ger: "sich entspannen, abhängen", ctx: "informal" },
    { id: "7_5_78", eng: "solution (to a problem)", phon: "[sə'luːʃn]", ger: "Lösung (eines Problems)", ctx: "Note: solution *to* a problem" },
    { id: "7_5_79", eng: "notification", phon: "[nəʊtɪfɪ'keɪʃn]", ger: "Benachrichtigung, Mitteilung", ctx: "-" },
    { id: "7_5_80", eng: "(to) go off", phon: "[ɡəʊ 'ɒf]", ger: "klingeln (Wecker); losgehen (Alarm)", ctx: "verb" },
    { id: "7_5_81", eng: "(to) click (on)", phon: "[klɪk]", ger: "klicken (auf)", ctx: "verb" },
    { id: "7_5_82", eng: "terror", phon: "['terə]", ger: "(panische) Angst", ctx: "noun" },
    { id: "7_5_83", eng: "all over the world", phon: "[ɔːl 'əʊvə ðə wɜːld]", ger: "überall auf der Welt, auf der ganzen Welt", ctx: "everywhere in the world" },
    { id: "7_5_84", eng: "nowhere", phon: "['nəʊweə]", ger: "nirgendwo(hin)", ctx: "meaning: not ... anywhere" },
    { id: "7_5_85", eng: "tear", phon: "[tɪə]", ger: "Träne", ctx: "e.g., Tears came to my eyes." },
    { id: "7_5_86", eng: "(to) pour", phon: "[pɔː]", ger: "strömen; gießen, schütten", ctx: "e.g., Tears poured down her face." },
    { id: "7_5_87", eng: "pressure", phon: "['preʃə]", ger: "Druck", ctx: "(to) put pressure on sb." },
    { id: "7_5_88", eng: "(to) breathe (in/out)", phon: "[briːð]", ger: "(ein-/aus-)atmen", ctx: "verb" },
    { id: "7_5_89", eng: "fairy tale", phon: "['feəri teɪl]", ger: "Märchen", ctx: "fairy = Fee, tale = Erzählung" },
    { id: "7_5_90", eng: "a couple (of)", phon: "['kʌpl]", ger: "ein paar; ein Paar", ctx: "some / several / two people together" },
    { id: "7_5_91", eng: "negative", phon: "['neɡətɪv]", ger: "negativ", ctx: "opposite: positive" },
    { id: "7_5_92", eng: "none", phon: "[nʌn]", ger: "keine(r, s)", ctx: "e.g., None of my friends..." },
    { id: "7_5_93", eng: "right", phon: "[raɪt]", ger: "Recht", ctx: "e.g., the right to read my mails" },
    { id: "7_5_94", eng: "(to) call sb. names", phon: "[kɔːl]", ger: "jn. beschimpfen", ctx: "phrase" },
    { id: "7_5_95", eng: "identity", phon: "[aɪ'dentəti]", ger: "Identität", ctx: "noun" },
    { id: "7_5_96", eng: "record deal", phon: "['rekɔːd diːl]", ger: "Plattenvertrag", ctx: "record = Schallplatte, deal = Geschäft" },
    { id: "7_5_97", eng: "relationship", phon: "[rɪ'leɪʃnʃɪp]", ger: "Beziehung, Verhältnis", ctx: "(to) be in a relationship with sb." },
    { id: "7_5_98", eng: "shallow", phon: "['ʃæləʊ]", ger: "flach, seicht; oberflächlich", ctx: "opposite of deep" },
    { id: "7_5_99", eng: "choice", phon: "[tʃɔɪs]", ger: "(Aus-)Wahl", ctx: "verb: (to) choose" },
    { id: "7_5_100", eng: "(to) delete", phon: "[dɪ'liːt]", ger: "löschen", ctx: "e.g., deleted the message from my phone" },
    { id: "7_5_101", eng: "sadness", phon: "['sædnəs]", ger: "Traurigkeit", ctx: "opposite: happiness" },
    { id: "7_5_102", eng: "not (...) any more", phon: "[eni 'mɔː]", ger: "nicht mehr", ctx: "e.g., I don't use it any more." },
    { id: "7_5_103", eng: "aka (= also known as)", phon: "[ˌeɪkeɪ'eɪ]", ger: "alias, auch bekannt als", ctx: "-" },
    { id: "7_5_104", eng: "weak", phon: "[wiːk]", ger: "schwach", ctx: "opposite of strong" },
    { id: "7_5_105", eng: "(to) give in (to sb./sth.)", phon: "[ɡɪv 'ɪn]", ger: "(jm./einer Sache) nachgeben", ctx: "verb" },
    { id: "7_5_106", eng: "(to) judge", phon: "[dʒʌdʒ]", ger: "(be)urteilen", ctx: "noun: judge = Richter/in" }
];