const e8u1_data = [
    { id: "8_1_1", eng: "km² = square kilometre(s)", phon: "['skweə ˌkɪləmiːtə]", ger: "Quadratkilometer", ctx: "The field is 7140 square metres." },
    { id: "8_1_2", eng: "melting pot", phon: "['meltɪŋ pɒt]", ger: "Schmelztiegel", ctx: "(to) melt = (ab)schmelzen; pot = Topf" },
    { id: "8_1_3", eng: "cultural", phon: "['kʌltʃərəl]", ger: "kulturell", ctx: "noun: culture" },
    { id: "8_1_4", eng: "(to) break away (from), broke, broken", phon: "[breɪk ə'weɪ], [brəʊk], ['brəʊkən]", ger: "sich trennen (von), sich abspalten (von)", ctx: "irregular verb" },
    { id: "8_1_5", eng: "stripe", phon: "[straɪp]", ger: "Streifen", ctx: "noun" },
    { id: "8_1_6", eng: "the Midwest", phon: "[mɪd'west]", ger: "der Mittlere Westen (der USA)", ctx: "-" },
    { id: "8_1_7", eng: "everyday", phon: "['evrideɪ]", ger: "alltäglich, Alltags-", ctx: "everyday life = Alltag" },
    { id: "8_1_8", eng: "impression", phon: "[ɪm'preʃn]", ger: "Eindruck", ctx: "to make a good impression" },
    { id: "8_1_9", eng: "measurement", phon: "['meʒəmənt]", ger: "Abmessung, Maß(einheit)", ctx: "verb: (to) measure = messen" },
    { id: "8_1_10", eng: "degree", phon: "[dɪ'ɡriː]", ger: "Grad", ctx: "used for temperatures" },
    { id: "8_1_11", eng: "Fahrenheit (F)", phon: "['færənhaɪt]", ger: "Fahrenheit", ctx: "e.g., 77 °F" },
    { id: "8_1_12", eng: "gallon", phon: "['ɡælən]", ger: "Gallone (= 3,78 l in den USA)", ctx: "Great Britain gallon is about 4.5 litres." },
    { id: "8_1_13", eng: "litre", phon: "['liːtə]", ger: "Liter", ctx: "English: 10 litres – German: 10 Liter" },
    { id: "8_1_14", eng: "mile", phon: "[maɪl]", ger: "Meile (ca. 1,6 km)", ctx: "miles per hour = Meilen pro Stunde" },
    { id: "8_1_15", eng: "volume", phon: "['vɒljuːm]", ger: "Volumen, Menge", ctx: "Stress on 1st syllable!" },
    { id: "8_1_16", eng: "(to) check in", phon: "[tʃek 'ɪn]", ger: "einchecken", ctx: "opposite: check out; noun: check-in" },
    { id: "8_1_17", eng: "(to) perform", phon: "[pə'fɔːm]", ger: "auftreten (Künstler/in); aufführen; durchführen", ctx: "noun: performance" },
    { id: "8_1_18", eng: "African American", phon: "[ˌæfrɪkən ə'merɪkən]", ger: "Afroamerikaner/in; afroamerikanisch", ctx: "-" },
    { id: "8_1_19", eng: "(to) huddle", phon: "['hʌdl]", ger: "sich (zusammen)drängen", ctx: "They're huddling together to keep warm." },
    { id: "8_1_20", eng: "mass", phon: "[mæs]", ger: "Masse(n-)", ctx: "e.g., a mass market" },
    { id: "8_1_21", eng: "(to) yearn for sth. / to do sth.", phon: "[jɜːn]", ger: "sich sehnen nach etwas / danach, etwas zu tun", ctx: "meaning: to want sth. very much" },
    { id: "8_1_22", eng: "liberty", phon: "['lɪbəti]", ger: "Freiheit", ctx: "the state of being free to live as you choose" },
    { id: "8_1_23", eng: "(to) achieve", phon: "[ə'tʃiːv]", ger: "erreichen, erzielen, schaffen", ctx: "noun: achievement" },
    { id: "8_1_24", eng: "definition", phon: "[defɪ'nɪʃn]", ger: "Definition", ctx: "Can you give a definition of this word?" },
    { id: "8_1_25", eng: "ancestor", phon: "['ænsestə]", ger: "Vorfahr/in", ctx: "the people in your family who lived before you" },
    { id: "8_1_26", eng: "personal", phon: "['pɜːsənl]", ger: "persönlich", ctx: "adjective (personal computer = PC)" },
    { id: "8_1_27", eng: "lyrics (pl.)", phon: "['lɪrɪks]", ger: "Liedtext", ctx: "English: The lyrics *are* very nice. (plural!)" },
    { id: "8_1_28", eng: "subway (AE)", phon: "['sʌbweɪ]", ger: "U-Bahn", ctx: "British English: underground" },
    { id: "8_1_29", eng: "route", phon: "[ruːt]", ger: "Route, Weg", ctx: "Which is the fastest route?" },
    { id: "8_1_30", eng: "borough (AE)", phon: "['bʌrə]", ger: "(Stadt-)Bezirk", ctx: "noun" },
    { id: "8_1_31", eng: "freedom", phon: "['friːdəm]", ger: "Freiheit", ctx: "synonym: liberty" },
    { id: "8_1_32", eng: "financial", phon: "[faɪ'nænʃl]", ger: "finanziell", ctx: "Stress on 2nd syllable!" },
    { id: "8_1_33", eng: "state of mind", phon: "[steɪt əv 'maɪnd]", ger: "Gefühlslage, Geisteszustand", ctx: "state = Zustand; mind = Geist, Verstand" },
    { id: "8_1_34", eng: "(to) interpret", phon: "[ɪn'tɜːprɪt]", ger: "interpretieren", ctx: "Stress on 2nd syllable!" },
    { id: "8_1_35", eng: "shelter", phon: "['ʃeltə]", ger: "(Obdachlosen-)Unterkunft; Schutzraum, Unterstand", ctx: "e.g., a bus shelter" },
    { id: "8_1_36", eng: "rent", phon: "[rent]", ger: "Miete", ctx: "verb: (to) rent = mieten, leihen" },
    { id: "8_1_37", eng: "stress", phon: "[stres]", ger: "Betonung", ctx: "noun or verb ((to) stress a word)" },
    { id: "8_1_38", eng: "curfew", phon: "['kɜːfjuː]", ger: "Ausgangssperre; Sperrstunde", ctx: "There is a night curfew." },
    { id: "8_1_39", eng: "insurance", phon: "[ɪn'ʃʊərəns]", ger: "Versicherung", ctx: "to take out insurance = eine Versicherung abschließen" },
    { id: "8_1_40", eng: "neighbourhood / neighborhood (AE)", phon: "['neɪbəhʊd]", ger: "Nachbarschaft, Gegend, Viertel", ctx: "noun" },
    { id: "8_1_41", eng: "roach (AE)", phon: "[rəʊtʃ]", ger: "Kakerlake(e), (Küchen-)Schabe", ctx: "informal" },
    { id: "8_1_42", eng: "homelessness", phon: "['həʊmləsnəs]", ger: "Obdachlosigkeit", ctx: "adjective: homeless" },
    { id: "8_1_43", eng: "responsibility", phon: "[rɪspɒnsə'bɪləti]", ger: "Verantwortung; Zuständigkeit", ctx: "adjective: responsible (for)" },
    { id: "8_1_44", eng: "advertisement", phon: "[əd'vɜːtɪsmənt]", ger: "Anzeige, Inserat; Werbespot", ctx: "short forms: ad, advert (informal)" },
    { id: "8_1_45", eng: "correct", phon: "[kə'rekt]", ger: "korrekt", ctx: "verb: (to) correct = korrigieren" },
    { id: "8_1_46", eng: "(to) enter sth. (in(to)/on sth.)", phon: "['entə]", ger: "etwas (in etwas) eintragen, eingeben", ctx: "Please enter your name and password." },
    { id: "8_1_47", eng: "(to) apply (to sb. for sth.)", phon: "[ə'plaɪ]", ger: "sich (bei jm. um etwas) bewerben", ctx: "e.g., apply for the job" },
    { id: "8_1_48", eng: "applicant", phon: "['æplɪkənt]", ger: "Antragsteller/in, Bewerber/in", ctx: "noun" },
    { id: "8_1_49", eng: "citizenship", phon: "['sɪtɪzənʃɪp]", ger: "Staatsbürgerschaft", ctx: "citizen = (Staats-)Bürger/in" },
    { id: "8_1_50", eng: "(to) issue", phon: "['ɪʃuː]", ger: "ausgeben, ausstellen (z. B. Dokument)", ctx: "issue date = Ausstellungsdatum" },
    { id: "8_1_51", eng: "expiration (AE)", phon: "[ekspə'reɪʃn]", ger: "Ablauf, Verfall", ctx: "British English: expiry [ɪk'spaɪəri]" },
    { id: "8_1_52", eng: "addict", phon: "['ædɪkt]", ger: "Abhängige/r, Süchtige/r", ctx: "adjective: addicted to" },
    { id: "8_1_53", eng: "(to) commit (a crime)", phon: "[kə'mɪt]", ger: "(ein Verbrechen) beheben", ctx: "committed" },
    { id: "8_1_54", eng: "harm", phon: "[hɑːm]", ger: "Schaden, Schäden, Verletzung", ctx: "verb: (to) harm = schaden, verletzen" },
    { id: "8_1_55", eng: "property", phon: "['prɒpəti]", ger: "Eigentum, Besitz", ctx: "The things you own are your property." },
    { id: "8_1_56", eng: "tip", phon: "[tɪp]", ger: "Trinkgeld", ctx: "verb: (to) tip sb." },
    { id: "8_1_57", eng: "waiter / waitress", phon: "['weɪtə], ['weɪtrəs]", ger: "Kellner / Kellnerin", ctx: "noun" },
    { id: "8_1_58", eng: "fare", phon: "[feə]", ger: "Fahrpreis", ctx: "the money you pay when you travel by bus, train, etc." },
    { id: "8_1_59", eng: "bill", phon: "[bɪl]", ger: "Rechnung", ctx: "-" },
    { id: "8_1_60", eng: "vending machine", phon: "['vendɪŋ məˌʃiːn]", ger: "Verkaufsautomat", ctx: "-" },
    { id: "8_1_61", eng: "coffee", phon: "['kɒfi]", ger: "Kaffee", ctx: "-" },
    { id: "8_1_62", eng: "closet (AE)", phon: "['klɒzɪt]", ger: "(Wand-)Schrank", ctx: "British English: wardrobe/cupboard" },
    { id: "8_1_63", eng: "first floor (AE)", phon: "[fɜːst 'flɔː]", ger: "Erdgeschoss", ctx: "British English: ground floor" },
    { id: "8_1_64", eng: "change", phon: "[tʃeɪndʒ]", ger: "Wechselgeld", ctx: "also verb: (to) change = (sich) verändern, umsteigen" },
    { id: "8_1_65", eng: "(to) book", phon: "[bʊk]", ger: "buchen; reservieren", ctx: "noun: booking" },
    { id: "8_1_66", eng: "key card", phon: "['kiː kɑːd]", ger: "Schlüsselkarte", ctx: "key = Schlüssel" },
    { id: "8_1_67", eng: "traffic", phon: "['træfɪk]", ger: "(Straßen-)Verkehr", ctx: "noun" },
    { id: "8_1_68", eng: "receptionist", phon: "[rɪ'sepʃənɪst]", ger: "Empfangsmitarbeiter/in", ctx: "reception = Empfang, Rezeption" },
    { id: "8_1_69", eng: "nickname", phon: "['nɪkneɪm]", ger: "Spitzname", ctx: "-" },
    { id: "8_1_70", eng: "(to) lead, led, led", phon: "[liːd], [led]", ger: "führen, leiten", ctx: "irregular verb" },
    { id: "8_1_71", eng: "during", phon: "['djʊərɪŋ]", ger: "während", ctx: "Präposition mit Nomen (Konjunktion mit Nebensatz = while)" },
    { id: "8_1_72", eng: "deli", phon: "['deli]", ger: "Feinkostgeschäft", ctx: "short form for delicatessen" },
    { id: "8_1_73", eng: "low", phon: "[ləʊ]", ger: "niedrig, tief", ctx: "opposite: high" },
    { id: "8_1_74", eng: "mustard", phon: "['mʌstəd]", ger: "Senf", ctx: "-" },
    { id: "8_1_75", eng: "conditions (pl.)", phon: "[kən'dɪʃnz]", ger: "Bedingungen, Verhältnisse", ctx: "e.g., in these conditions" },
    { id: "8_1_76", eng: "avenue", phon: "['ævənjuː]", ger: "Allee", ctx: "-" },
    { id: "8_1_77", eng: "opposite", phon: "['ɒpəzɪt]", ger: "Gegenteil; gegensätzlich, entgegengesetzt", ctx: "The opposite of 'with' is 'without'." },
    { id: "8_1_78", eng: "e.g. (exempli gratia)", phon: "[iː 'dʒiː]", ger: "z. B. (zum Beispiel)", ctx: "aus dem Lateinischen. Beim Sprechen sagt man 'for example'." },
    { id: "8_1_79", eng: "stoop (AE)", phon: "[stuːp]", ger: "kleine Terrasse vor der Tür", ctx: "noun" },
    { id: "8_1_71", eng: "makeup", phon: "['meɪkʌp]", ger: "Make-up", ctx: "Stress on 1st syllable!" },
    { id: "8_1_72", eng: "fat", phon: "[fæt]", ger: "dick, fett", ctx: "noun: fat = Fett" },
    { id: "8_1_73", eng: "overweight", phon: "[əʊvə'weɪt]", ger: "übergewichtig", ctx: "(to) be overweight = Übergewicht haben" },
    { id: "8_1_74", eng: "(to) vibrate", phon: "[vaɪ'breɪt]", ger: "vibrieren", ctx: "-" },
    { id: "8_1_75", eng: "cosmetics (pl.)", phon: "[kɒz'metɪks]", ger: "Kosmetikprodukte, Kosmetika", ctx: "-" },
    { id: "8_1_76", eng: "(to) nominate", phon: "['nɒmɪneɪt]", ger: "nominieren", ctx: "Stress on 1st syllable!" },
    { id: "8_1_77", eng: "as soon as", phon: "[æz 'suːn æz]", ger: "sobald; so bald wie", ctx: "as soon as I know more" },
    { id: "8_1_78", eng: "résumé (AE)", phon: "['rezjʊmeɪ]", ger: "Lebenslauf", ctx: "noun" },
    { id: "8_1_79", eng: "demonstraiton", phon: "[demən'streɪʃn]", ger: "Vorführung, Demonstration", ctx: "verb: (to) demonstrate" },
    { id: "8_1_80", eng: "professional", phon: "[prə'feʃənl]", ger: "Fachmann/Fachfrau, Profi", ctx: "informal: pro" },
    { id: "8_1_81", eng: "schedule (AE)", phon: "['skedʒuːl]", ger: "Zeitplan", ctx: "1. Zeitplan; 2. Stundenplan" },
    { id: "8_1_82", eng: "skinny", phon: "['skɪni]", ger: "mager, dürr; eng anliegend", ctx: "skinny vs. fat (people) / skinny vs. baggy (clothes)" },
    { id: "8_1_83", eng: "mosquito", phon: "[məs'kiːtəʊ]", ger: "Mücke", ctx: "plural: mosquitos or mosquitoes" },
    { id: "8_1_84", eng: "sneaker (AE)", phon: "['sniːkə]", ger: "Sportschuh", ctx: "British English: trainer" },
    { id: "8_1_85", eng: "(to) promise", phon: "['prɒmɪs]", ger: "versprechen", ctx: "noun: promise = Versprechen" },
    { id: "8_1_86", eng: "gel", phon: "[dʒel]", ger: "Gel", ctx: "-" },
    { id: "8_1_87", eng: "cheek", phon: "[tʃiːk]", ger: "Wange", ctx: "-" },
    { id: "8_1_88", eng: "manicure", phon: "['mænɪkjʊə]", ger: "Maniküre (Pflege der Fingernägel)", ctx: "Stress on 1st syllable!" },
    { id: "8_1_89", eng: "excellent", phon: "['eksələnt]", ger: "ausgezeichnet, hervorragend", ctx: "Stress on 1st syllable!" },
    { id: "8_1_90", eng: "(to) act", phon: "[ækt]", ger: "handeln, sich verhalten; so tun, als ob; Theater spielen", ctx: "He acted like a little kid." },
    { id: "8_1_91", eng: "all right", phon: "[ɔːl 'raɪt]", ger: "in Ordnung, OK", ctx: "-" },
    { id: "8_1_92", eng: "entrance", phon: "['entrəns]", ger: "Eingang; Zutritt", ctx: "noun" },
    { id: "8_1_93", eng: "store", phon: "[stɔː]", ger: "Geschäft", ctx: "British English: shop" },
    { id: "8_1_94", eng: "counter", phon: "['kaʊntə]", ger: "(Verkaufs-)Schalter, Ladentheke", ctx: "Please pay at the counter." },
    { id: "8_1_95", eng: "guard", phon: "[ɡɑːd]", ger: "Wärter/in; Wache; Schutz(vorrichtung)", ctx: "verb: (to) guard = schützen" },
    { id: "8_1_96", eng: "restroom (AE)", phon: "['restruːm]", ger: "Toilette (in öffentlichen Gebäuden)", ctx: "in privaten Häusern/Wohnungen = bathroom" },
    { id: "8_1_97", eng: "(to) give sb. a/the once-over", phon: "[ɡɪv], [wʌns 'əʊvə]", ger: "jn. (kurz) in Augenschein nehmen", ctx: "informal" },
    { id: "8_1_98", eng: "(to) appreciate", phon: "[ə'priːʃieɪt]", ger: "schätzen, zu schätzen wissen", ctx: "I really appreciate what you did for me." },
    { id: "8_1_99", eng: "helicopter", phon: "['helɪkɒptə]", ger: "Hubschrauber", ctx: "to get a helicopter view of sth." },
    { id: "8_1_100", eng: "(to) take your eyes off sth.", phon: "[teɪk]", ger: "den Blick abwenden von etwas", ctx: "phrase" },
    { id: "8_1_101", eng: "(light) bulb", phon: "[bʌlb]", ger: "Glühbirne", ctx: "noun" },
    { id: "8_1_102", eng: "inch", phon: "[ɪntʃ]", ger: "Zoll (Längenmaß = 2,54 cm)", ctx: "noun" },
    { id: "8_1_103", eng: "heel", phon: "[hiːl]", ger: "Absatz (Schuh); Ferse", ctx: "-" },
    { id: "8_1_104", eng: "cell (phone) (AE)", phon: "['sel fəʊn]", ger: "Handy", ctx: "British English: mobile (phone)" },
    { id: "8_1_105", eng: "(to) sweat", phon: "[swet]", ger: "schlitzen", ctx: "noun: sweat = Schweiß" },
    { id: "8_1_106", eng: "tight", phon: "[taɪt]", ger: "knapp, eng (anliegend) (Kleidung)", ctx: "This dress is too tight." },
    { id: "8_1_107", eng: "(to) collect", phon: "[kə'lekt]", ger: "sammeln", ctx: "noun: collection" },
    { id: "8_1_108", eng: "welcoming", phon: "['welkəmɪŋ]", ger: "(gast)freundlich", ctx: "meaning: friendly towards visitors" },
    { id: "8_1_109", eng: "(to) rhyme", phon: "[raɪm]", ger: "(sich) reimen", ctx: "noun: rhyme = Reim" },
    { id: "8_1_110", eng: "pretty", phon: "['prɪti]", ger: "hübsch", ctx: "e.g., a pretty face" },
    { id: "8_1_111", eng: "gritty", phon: "['ɡrɪti]", ger: "ungeschminkt, schonungslos", ctx: "the gritty reality of life" },
    { id: "8_1_112", eng: "rhythm", phon: "['rɪðəm]", ger: "Rhythmus", ctx: "-" },
    { id: "8_1_113", eng: "extreme", phon: "[ɪk'striːm]", ger: "extrem; Extrem", ctx: "adverb: extremely" }
];