const e8u2_data = [
    { id: "8_2_1", eng: "native", phon: "['neɪtɪv]", ger: "einheimisch, Heimat-; Einheimische/r", ctx: "native birds / my native city / native language" },
    { id: "8_2_2", eng: "aspect", phon: "['æspekt]", ger: "Aspekt", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_2_3", eng: "Native American", phon: "[ˌneɪtɪv ə'merɪkən]", ger: "amerikanischer Ureinvohner, amerikanische Ureinwohnerin", ctx: "noun or adjective" },
    { id: "8_2_4", eng: "(to) search (for sth.)", phon: "[sɜːtʃ]", ger: "(etwas/nach etwas) suchen", ctx: "noun: search (for) = Suche (nach)" },
    { id: "8_2_5", eng: "exhibition", phon: "[eksɪ'bɪʃn]", ger: "Messe; Ausstellung", ctx: "e.g., Van Gogh exhibition" },
    { id: "8_2_6", eng: "indigenous (to)", phon: "[ɪn'dɪdʒənəs]", ger: "einheimisch (in)", ctx: "indigenous people = Ureinwohner" },
    { id: "8_2_7", eng: "reservation", phon: "[rezə'veɪʃn]", ger: "Reservat (Gebiet)", ctx: "informal: rez" },
    { id: "8_2_8", eng: "tribal elder", phon: "[ˌtraɪbl 'eldə]", ger: "Stammesälteste/r", ctx: "tribal = Stammes-" },
    { id: "8_2_9", eng: "adobe", phon: "[ə'dəʊbi]", ger: "Lehmziegel", ctx: "an adobe wall" },
    { id: "8_2_10", eng: "member", phon: "['membə]", ger: "Mitglied", ctx: "e.g., member of the drama club" },
    { id: "8_2_11", eng: "headdress", phon: "['hedres]", ger: "Kopfschmuck", ctx: "noun" },
    { id: "8_2_12", eng: "jewellery", phon: "['dʒuːəlri]", ger: "Schmuck", ctx: "American English spelling: jewelry" },
    { id: "8_2_13", eng: "stereotype", phon: "['steriətaɪp]", ger: "Stereotyp, Klischee(vorstellung)", ctx: "adjective: stereotypical" },
    { id: "8_2_14", eng: "braid", phon: "[breɪd]", ger: "(geflochtener) Zopf", ctx: "noun" },
    { id: "8_2_15", eng: "feather", phon: "['feðə]", ger: "Feder (eines Vogels)", ctx: "-" },
    { id: "8_2_16", eng: "bead", phon: "[biːd]", ger: "Perle (aus Holz, Glas etc.)", ctx: "-" },
    { id: "8_2_17", eng: "great-(great-)grandmother", phon: "[ɡreɪt 'ɡrænmʌðə]", ger: "(Ur-)Urgroßmutter", ctx: "great-grandparents = your grandparents' parents" },
    { id: "8_2_18", eng: "great-(great-)grandfather", phon: "[ɡreɪt 'ɡrænfɑːðə]", ger: "(Ur-)Urgroßvater", ctx: "-" },
    { id: "8_2_19", eng: "(to) rub", phon: "[rʌb]", ger: "reiben, scheuern", ctx: "Bears sometimes rub their backs against trees." },
    { id: "8_2_20", eng: "(to) bleed, bled, bled", phon: "[bliːd], [bled]", ger: "bluten", ctx: "noun: blood [blʌd] = Blut" },
    { id: "8_2_21", eng: "(to) pull", phon: "[pʊl]", ger: "ziehen", ctx: "verb" },
    { id: "8_2_22", eng: "mud", phon: "[mʌd]", ger: "Schlamm, Matsch", ctx: "-" },
    { id: "8_2_23", eng: "above", phon: "[ə'bʌv]", ger: "über, oberhalb (von); oben", ctx: "opposite: below" },
    { id: "8_2_24", eng: "knee", phon: "[niː]", ger: "Knie", ctx: "The 'k' is silent!" },
    { id: "8_2_25", eng: "(to) crawl", phon: "[krɔːl]", ger: "kriechen; krabbeln", ctx: "verb" },
    { id: "8_2_26", eng: "wagon", phon: "['wæɡən]", ger: "Planwagen, (Pferde-)Fuhrwerk", ctx: "-" },
    { id: "8_2_27", eng: "blanket", phon: "['blæŋkɪt]", ger: "Decke (zum Zudecken u. Ä.)", ctx: "-" },
    { id: "8_2_28", eng: "(to) infect", phon: "[ɪn'fekt]", ger: "infizieren; verseuchen", ctx: "noun: infection" },
    { id: "8_2_29", eng: "(to) begin, began, begun", phon: "[bɪ'ɡɪn], [bɪ'ɡæn], [bɪ'ɡʌn]", ger: "anfangen, beginnen", ctx: "noun: beginning" },
    { id: "8_2_30", eng: "swamp", phon: "[swɒmp]", ger: "Sumpf", ctx: "-" },
    { id: "8_2_31", eng: "(to) bury", phon: "['beri]", ger: "begraben, beerdigen; vergraben", ctx: "Note the pronunciation ['beri]!" },
    { id: "8_2_32", eng: "touch", phon: "[tʌtʃ]", ger: "Berührung", ctx: "verb: (to) touch" },
    { id: "8_2_33", eng: "shadow", phon: "['ʃædəʊ]", ger: "Schatten (Umriss)", ctx: "a man and his shadow" },
    { id: "8_2_34", eng: "spirit", phon: "['spɪrɪt]", ger: "Geist, Seele", ctx: "-" },
    { id: "8_2_35", eng: "(to) lift", phon: "[lɪft]", ger: "heben, hochheben", ctx: "also noun: lift = Lift, Aufzug" },
    { id: "8_2_36", eng: "panther", phon: "['pænθə]", ger: "Panther; (AE) Puma", ctx: "In America, panther can mean a brown wild cat (Puma)." },
    { id: "8_2_37", eng: "awake", phon: "[ə'weɪk]", ger: "wach", ctx: "(to) shake sb. awake = jn. wachrütteln" },
    { id: "8_2_38", eng: "footprint", phon: "['fʊtprɪnt]", ger: "Fußabdruck", ctx: "-" },
    { id: "8_2_39", eng: "cloth", phon: "[klɒθ]", ger: "Tuch; Stoff", ctx: "e.g., cloth bags" },
    { id: "8_2_40", eng: "(to) float", phon: "[fləʊt]", ger: "schweben; (auf der Wasseroberfläche) treiben", ctx: "A feather floated through the air." },
    { id: "8_2_41", eng: "(to) drop out (of school)", phon: "[drɒp 'aʊt]", ger: "(die Schule) abbrechen", ctx: "phrase" },
    { id: "8_2_42", eng: "poverty", phon: "['pɒvəti]", ger: "Armut", ctx: "adjective: poor" },
    { id: "8_2_43", eng: "challenge", phon: "['tʃælɪndʒ]", ger: "Herausforderung", ctx: "verb: (to) challenge sb.; adjective: challenging" },
    { id: "8_2_44", eng: "unemployed", phon: "[ˌʌnɪm'plɔɪd]", ger: "arbeitslos", ctx: "verb: (to) employ = jn. anstellen" },
    { id: "8_2_45", eng: "difficult", phon: "['dɪfɪkəlt]", ger: "schwierig", ctx: "opposite: easy or simple" },
    { id: "8_2_46", eng: "(to) connect (to/with)", phon: "[kə'nekt]", ger: "(sich) verbinden (mit); verbunden sein (mit)", ctx: "noun: connection" },
    { id: "8_2_47", eng: "gun", phon: "[ɡʌn]", ger: "Schusswaffe, Pistole", ctx: "handgun = Faustfeuerwaffe; long gun = Gewehr" },
    { id: "8_2_48", eng: "alcohol", phon: "['ælkəhɒl]", ger: "Alkohol", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_2_49", eng: "drunk driving", phon: "[drʌŋk 'daɪvɪŋ]", ger: "Trunkenheit am Steuer", ctx: "driving after you've drunk alcohol" },
    { id: "8_2_50", eng: "driving licence (BE) / driver's license (AE)", phon: "['daɪvɪŋ ˌlaɪsns]", ger: "Führerschein", ctx: "-" },
    { id: "8_2_51", eng: "minimum", phon: "['mɪnɪməm]", ger: "Mindest-, minimal; Minimum", ctx: "opposite: maximum (max)" },
    { id: "8_2_52", eng: "bloodline", phon: "['blʌdlaɪn]", ger: "Stammbaum", ctx: "meaning: a person's or an animal's ancestors" },
    { id: "8_2_53", eng: "cattle (pl.)", phon: "['kætl]", ger: "Vieh, Rinder", ctx: "Plural verb! The cattle *were* driven... (Das Vieh *wurde*...)" },
    { id: "8_2_54", eng: "(to) shoot, shot, shot", phon: "[ʃuːt], [ʃɒt]", ger: "(er)schießen", ctx: "nouns: shot = Schuss/Aufnahme; shooting = Schießerei" },
    { id: "8_2_55", eng: "wolf (pl. wolves)", phon: "[wʊlf], [wʊlvz]", ger: "Wolf", ctx: "Note the plural form!" },
    { id: "8_2_56", eng: "(to) fall asleep", phon: "[fɔːl ə'sliːp]", ger: "einschlafen", ctx: "(to) be asleep = schlafen" },
    { id: "8_2_57", eng: "long shot", phon: "['lɒŋ ʃɒt]", ger: "Totale (Film)", ctx: "shot = Aufnahme, Foto" },
    { id: "8_2_58", eng: "medium shot", phon: "['miːdiəm ʃɒt]", ger: "Halbtotale (Film)", ctx: "medium = mittel(groß)" },
    { id: "8_2_59", eng: "close-up", phon: "['kləʊs ʌp]", ger: "Nahaufnahme (Film)", ctx: "noun" },
    { id: "8_2_60", eng: "(to) inspire", phon: "[ɪn'spaɪə]", ger: "begeistern, inspirieren", ctx: "adjective: inspiring" },
    { id: "8_2_61", eng: "nasty", phon: "['nɑːsti]", ger: "gemein, fies", ctx: "meaning: not nice, really bad" },
    { id: "8_2_62", eng: "grandson", phon: "['ɡrænsʌn]", ger: "Enkel", ctx: "your child's son" },
    { id: "8_2_63", eng: "granddaughter", phon: "['ɡrændɔːtə]", ger: "Enkelin", ctx: "your child's daughter" },
    { id: "8_2_64", eng: "campfire", phon: "['kæmpfaɪə]", ger: "Lagerfeuer", ctx: "-" },
    { id: "8_2_65", eng: "respectful", phon: "[rɪ'spektfl]", ger: "respektvoll", ctx: "noun: respect; verb: (to) respect" },
    { id: "8_2_66", eng: "wise", phon: "[waɪz]", ger: "weise", ctx: "e.g., a wise woman" },
    { id: "8_2_67", eng: "poor", phon: "[pɔː]", ger: "schlecht, schwach, minderwertig; arm", ctx: "poor = 1. arm; 2. schlecht, minderwertig" },
    { id: "8_2_68", eng: "(to) break down", phon: "[breɪk 'daʊn]", ger: "eine Panne haben, kaputtgehen (Auto)", ctx: "His car has broken down." },
    { id: "8_2_69", eng: "fantastic", phon: "[fæn'tæstɪk]", ger: "fantastisch", ctx: "adjective" },
    { id: "8_2_70", eng: "camerawork", phon: "['kæmrəwɜːk]", ger: "Kameraführung", ctx: "noun" },
    { id: "8_2_71", eng: "law", phon: "[lɔː]", ger: "Gesetz; Jura (Studium)", ctx: "by law = per Gesetz, gesetzlich" },
    { id: "8_2_72", eng: "suicide", phon: "['suːɪsaɪd]", ger: "Selbstmord; Selbstmörder/in", ctx: "e.g., He was bullied... and that led to his suicide." },
    { id: "8_2_73", eng: "(to) increase (by)", phon: "[ɪn'kriːs]", ger: "steigern, (sich) erhöhen; steigen, zunehmen (um)", ctx: "noun: increase ['ɪŋkriːs]" },
    { id: "8_2_74", eng: "control", phon: "[kən'trəʊl]", ger: "Kontrolle", ctx: "verb: (to) control = kontrollieren, regulieren" },
    { id: "8_2_75", eng: "debate", phon: "[dɪ'beɪt]", ger: "Debatte", ctx: "Let's hold/have a debate. (eine Debatte führen)" },
    { id: "8_2_76", eng: "chairperson (pl. chairpersons)", phon: "['tʃeəpɜːsn]", ger: "Vorsitzende/r", ctx: "the person who leads a meeting or a debate" },
    { id: "8_2_77", eng: "(to) thank sb.", phon: "[θæŋk]", ger: "sich bei jm. bedanken", ctx: "e.g., to say thank you to everybody" },
    { id: "8_2_78", eng: "guy", phon: "[ɡaɪ]", ger: "Typ, Kerl", ctx: "a nice guy / Hello, guys! (Hallo, Leute!)" },
    { id: "8_2_79", eng: "safety", phon: "['seɪfti]", ger: "Sicherheit", ctx: "noun (adjective: safe)" },
    { id: "8_2_80", eng: "keyword", phon: "['kiːwɜːd]", ger: "Stichwort, Schlagwort", ctx: "noun" },
    { id: "8_2_81", eng: "engine", phon: "['endʒɪn]", ger: "Motor, Maschine", ctx: "search engine = Suchmaschine" },
    { id: "8_2_82", eng: "quotation marks (pl.)", phon: "[kwəʊ'teɪʃn mɑːks]", ger: "Anführungszeichen", ctx: "-" },
    { id: "8_2_83", eng: "organization", phon: "[ˌɔːɡənaɪ'zeɪʃn]", ger: "Organisation", ctx: "noun: organizer; verb: (to) organize" },
    { id: "8_2_84", eng: "fake", phon: "[feɪk]", ger: "falsch, gefälscht", ctx: "e.g., fake news; noun: fake = Fälschung" },
    { id: "8_2_85", eng: "(to) bookmark", phon: "['bʊkmɑːk]", ger: "markieren; zu den Lesezeichen hinzufügen (Computer)", ctx: "noun: bookmark = Lesezeichen" },
    { id: "8_2_86", eng: "(to) print sth. (out)", phon: "[print]", ger: "etwas (aus)drucken", ctx: "noun: print = Druck, Schrift(art)" },
    { id: "8_2_87", eng: "(to) underline", phon: "[ˌʌndə'laɪn]", ger: "unterstreichen", ctx: "verb" },
    { id: "8_2_88", eng: "author", phon: "['ɔːθə]", ger: "Autor/in", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_2_89", eng: "less", phon: "[les]", ger: "weniger", ctx: "opposite: more" },
    { id: "8_2_90", eng: "topic", phon: "['tɒpɪk]", ger: "Thema", ctx: "The topic of my presentation is..." },
    { id: "8_2_91", eng: "(to) refer to", phon: "[rɪ'fɜː]", ger: "sich beziehen auf, Bezug nehmen auf", ctx: "past: referred (-rr-)" },
    { id: "8_2_92", eng: "such as", phon: "['sʌtʃ æz]", ger: "wie (zum Beispiel)", ctx: "synonym: for example / e.g." },
    { id: "8_2_93", eng: "such a", phon: "[sʌtʃ ə]", ger: "so(lch) (ein/e)", ctx: "such a thing = so eine Sache" },
    { id: "8_2_94", eng: "automatic", phon: "[ˌɔːtə'mætɪk]", ger: "automatisch", ctx: "adverb: automatically" },
    { id: "8_2_95", eng: "(to) pass (a test / an exam)", phon: "[pɑːs]", ger: "(einen Test / eine Prüfung) bestehen, schaffen", ctx: "opposite: to fail a test" },
    { id: "8_2_96", eng: "protest", phon: "['prəʊtest]", ger: "Protest(demonstration)", ctx: "Betonung auf der 1. Silbe! Verb: (to) protest [prə'test]" },
    { id: "8_2_97", eng: "LGBT", phon: "[ˌel dʒiː biː 'tiː]", ger: "LGBT", ctx: "lesbian, gay, bisexual, transgender" },
    { id: "8_2_98", eng: "straight", phon: "[streɪt]", ger: "heterosexuell; gerade; glatt (Haare)", ctx: "gay/lesbian vs. straight" },
    { id: "8_2_99", eng: "alliance", phon: "[ə'laɪəns]", ger: "Bündnis, Allianz", ctx: "Betonung auf der 2. Silbe!" },
    { id: "8_2_100", eng: "(to) shave", phon: "[ʃeɪv]", ger: "(sich) rasieren", ctx: "noun: shave = Rasur" },
    { id: "8_2_101", eng: "(to) survive", phon: "[sə'vaɪv]", ger: "überleben", ctx: "nouns: survival / survivor = Überlebende/r" },
    { id: "8_2_102", eng: "(to) include", phon: "[ɪn'kluːd]", ger: "(mit) einschließen", ctx: "including = einschließlich, inklusive" },
    { id: "8_2_103", eng: "experience", phon: "[ɪk'spɪəriəns]", ger: "Erfahrung; Erlebnis", ctx: "verb: (to) experience" },
    { id: "8_2_104", eng: "speech", phon: "[spiːtʃ]", ger: "Rede, Ansprache; Sprache", ctx: "to give a speech = eine Rede halten" },
    { id: "8_2_105", eng: "shame", phon: "[ʃeɪm]", ger: "Scham; Schande", ctx: "What a shame! = Wie schade! / Shame on you! = Schäm dich!" },
    { id: "8_2_106", eng: "politician", phon: "[ˌpɒlə'tɪʃn]", ger: "Politiker/in", ctx: "noun" },
    { id: "8_2_107", eng: "march", phon: "[mɑːtʃ]", ger: "Marsch", ctx: "verb: (to) march = marschieren" },
    { id: "8_2_108", eng: "(to) take part (in)", phon: "[teɪk 'pɑːt]", ger: "teilnehmen (an), mitmachen (bei)", ctx: "took part in" },
    { id: "8_2_109", eng: "silence", phon: "['saɪləns]", ger: "Stille; Schweigen", ctx: "verb: (to) silence = zum Schweigen bringen" },
    { id: "8_2_110", eng: "tear (noun)", phon: "[tɪə]", ger: "Träne", ctx: "💡 ACHTUNG bei gleicher Schreibweise: tear (noun) [tɪə] vs. (to) tear (verb) [teə]!" },
    { id: "8_2_111", eng: "(to) tear, tore, torn", phon: "[teə], [tɔː], [tɔːn]", ger: "reißen, zerreißen", ctx: "💡 (to) tear sth. up = etwas zerreißen" },
    { id: "8_2_122", eng: "sexuality", phon: "[ˌsekʃu'æləti]", ger: "Sexualität", ctx: "-" },
    { id: "8_2_123", eng: "skin", phon: "[skɪn]", ger: "Haut; Schale (z. B. Banane)", ctx: "e.g., skin colour" },
    { id: "8_2_124", eng: "religion", phon: "[rɪ'lɪdʒən]", ger: "Religion", ctx: "Betonung auf der 2. Silbe!" },
    { id: "8_2_125", eng: "sacred", phon: "['seɪkrɪd]", ger: "heilig", ctx: "e.g., Uluru is sacred to the indigenous people." },
    { id: "8_2_126", eng: "chief", phon: "[tʃiːf]", ger: "Häuptling; Haupt-, leitend", ctx: "the leaders of tribes / chief problem / Chief Executive Officer (CEO)" }
];