const e8u3_data = [
    { id: "8_3_1", eng: "(to) improve", phon: "[ɪm'pruːv]", ger: "verbessern; sich verbessern", ctx: "noun: improvement = Verbesserung" },
    { id: "8_3_2", eng: "product", phon: "['prɒdʌkt]", ger: "Produkt", ctx: "Betonung auf der 1. Silbe! (verb: to produce)" },
    { id: "8_3_3", eng: "volunteer", phon: "[ˌvɒlən'tɪə]", ger: "Freiwillige/r; ehrenamtliche/r Mitarbeiter/in", ctx: "can be noun, adjective or verb" },
    { id: "8_3_4", eng: "assembly line", phon: "[ə'sembli laɪn]", ger: "Montageband, Fließband", ctx: "I work on the assembly line." },
    { id: "8_3_5", eng: "robot", phon: "['rəʊbɒt]", ger: "Roboter", ctx: "-" },
    { id: "8_3_6", eng: "roof", phon: "[ruːf]", ger: "Dach", ctx: "-" },
    { id: "8_3_7", eng: "seat", phon: "[siːt]", ger: "(Sitz-)Platz", ctx: "(to) take a seat = Platz nehmen" },
    { id: "8_3_8", eng: "steering wheel", phon: "['stɪərɪŋ wiːl]", ger: "Lenkrad, Steuer", ctx: "(to) steer = steuern, lenken" },
    { id: "8_3_9", eng: "tyre", phon: "['taɪə]", ger: "Reifen", ctx: "My bike needs new tyres." },
    { id: "8_3_10", eng: "windscreen", phon: "['wɪndskriːn]", ger: "Windschutzscheibe (Auto)", ctx: "-" },
    { id: "8_3_11", eng: "network", phon: "['netwɜːk]", ger: "Netz; Netzwerk; Wortnetz", ctx: "-" },
    { id: "8_3_12", eng: "appliance", phon: "[ə'plaɪəns]", ger: "(Haushalts-)Gerät", ctx: "e.g., home appliances" },
    { id: "8_3_13", eng: "(to) track", phon: "[træk]", ger: "(zurück-, nach)verfolgen, beobachten", ctx: "noun: track = Pfad, Feldweg" },
    { id: "8_3_14", eng: "(to) program", phon: "['prəʊɡræm]", ger: "programmieren", ctx: "noun: program = Computer-Programm" },
    { id: "8_3_15", eng: "pillow", phon: "['pɪləʊ]", ger: "Kopfkissen", ctx: "-" },
    { id: "8_3_16", eng: "speaker", phon: "['spiːkə]", ger: "Lautsprecher; Sprecher/in", ctx: "speaker = 1. Lautsprecher; 2. Sprecher/in" },
    { id: "8_3_17", eng: "privacy", phon: "['prɪvəsi]", ger: "Privatsphäre", ctx: "Note pronunciation! (adjective: private ['praɪvət])" },
    { id: "8_3_18", eng: "security", phon: "[sɪ'kjʊərəti]", ger: "Sicherheit", ctx: "This is a security check." },
    { id: "8_3_19", eng: "data", phon: "['deɪtə]", ger: "Daten", ctx: "💡 ACHTUNG: data + Verb im Singular (The data shows...)" },
    { id: "8_3_20", eng: "complex", phon: "['kɒmpleks]", ger: "komplex, kompliziert", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_3_21", eng: "(to) reduce (by)", phon: "[rɪ'djuːs]", ger: "reduzieren, verringern (um)", ctx: "noun: reduction = Verringerung" },
    { id: "8_3_22", eng: "repair", phon: "[rɪ'peə]", ger: "Reparatur", ctx: "verb: (to) repair = reparieren" },
    { id: "8_3_23", eng: "(to) solve", phon: "[sɒlv]", ger: "lösen (Rätsel, Problem), lüften (Geheimnis)", ctx: "noun: solution = Lösung" },
    { id: "8_3_24", eng: "accidents may happen ...", phon: "[meɪ]", ger: "Unfälle passieren vielleicht; Unfälle können passieren", ctx: "expresses possibility" },
    { id: "8_3_25", eng: "in addition", phon: "[ɪn ə'dɪʃn]", ger: "außerdem", ctx: "in addition to ... = zusätzlich zu ..." },
    { id: "8_3_26", eng: "drone", phon: "[drəʊn]", ger: "Drohne", ctx: "-" },
    { id: "8_3_27", eng: "(to) transport", phon: "[træn'spɔːt]", ger: "transportieren, befördern", ctx: "💡 Noun: 'transport (auf 1. Silbe) – Verb: trans'port (auf 2. Silbe)!" },
    { id: "8_3_28", eng: "goods (pl.)", phon: "[ɡʊdz]", ger: "Waren, Güter", ctx: "plural noun" },
    { id: "8_3_29", eng: "space", phon: "[speɪs]", ger: "Raum, Fläche; Platz; Weltraum", ctx: "e.g., more space / space flight" },
    { id: "8_3_30", eng: "(to) unlock", phon: "[ʌn'lɒk]", ger: "aufschließen, entsperren", ctx: "opposite: (to) lock = abschließen" },
    { id: "8_3_31", eng: "disability", phon: "[ˌdɪsə'bɪləti]", ger: "Behinderung", ctx: "adjective: disabled = körperbehindert" },
    { id: "8_3_32", eng: "(to) prevent", phon: "[prɪ'vent]", ger: "verhindern", ctx: "prevent people from driving too fast" },
    { id: "8_3_33", eng: "battery", phon: "['bætri]", ger: "Batterie; Akku", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_3_34", eng: "body (of a car)", phon: "['bɒdi]", ger: "(Auto-)Karrosserie", ctx: "body = 1. Körper; 2. (Auto-)Karrosserie" },
    { id: "8_3_35", eng: "(to) paint", phon: "[peɪnt]", ger: "lackieren, (mit Farbe) streichen; malen", ctx: "noun: paint = Farbe, Lack" },
    { id: "8_3_36", eng: "(to) weld", phon: "[weld]", ger: "schweißen", ctx: "welding pieces of metal together" },
    { id: "8_3_37", eng: "tonne", phon: "[tʌn]", ger: "Tonne (= 1.000 kg)", ctx: "-" },
    { id: "8_3_38", eng: "household", phon: "['haʊshəʊld]", ger: "Haushalt; Haushalts-", ctx: "e.g., a one-parent household" },
    { id: "8_3_39", eng: "energy", phon: "['enədʒi]", ger: "Energie", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_3_40", eng: "pollution", phon: "[pə'luːʃn]", ger: "(Umwelt-)Verschmutzung", ctx: "noun" },
    { id: "8_3_41", eng: "(to) invent", phon: "[ɪn'vent]", ger: "erfinden", ctx: "nouns: invention = Erfindung; inventor = Erfinder/in" },
    { id: "8_3_42", eng: "electricity", phon: "[ɪlek'trɪsəti]", ger: "Strom, Elektrizität", ctx: "-" },
    { id: "8_3_43", eng: "process", phon: "['prəʊses]", ger: "Prozess; Verfahren, Ablauf", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_3_44", eng: "virtual", phon: "['vɜːtʃuəl]", ger: "virtuell", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_3_45", eng: "realistic", phon: "[rɪə'lɪstɪk]", ger: "realistisch", ctx: "adverb: realistically" },
    { id: "8_3_46", eng: "feature", phon: "['fiːtʃə]", ger: "Merkmal, Eigenschaft", ctx: "verb: (to) feature = bieten, eine Rolle spielen" },
    { id: "8_3_47", eng: "stand-alone", phon: "['stænd əˌləʊn]", ger: "eigenständig; autark", ctx: "-" },
    { id: "8_3_48", eng: "system", phon: "['sɪstəm]", ger: "System", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_3_49", eng: "headphones (pl.)", phon: "['hedfəʊnz]", ger: "(ein) Kopfhörer", ctx: "These *are* my new headphones. (Plural-Verb!)" },
    { id: "8_3_50", eng: "microphone", phon: "['maɪkrəfəʊn]", ger: "Mikrofon", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_3_51", eng: "graphics (pl.)", phon: "['ɡræfɪks]", ger: "Grafik", ctx: "The graphics *are* fantastic. (Plural-Verb!)" },
    { id: "8_3_52", eng: "radio", phon: "['reɪdiəʊ]", ger: "Radio", ctx: "-" },
    { id: "8_3_53", eng: "announcement", phon: "[ə'naʊnsmənt]", ger: "Durchsage, Ansage; Bekanntgabe, Ankündigung", ctx: "noun" },
    { id: "8_3_54", eng: "(radio/TV) station", phon: "['steɪʃn]", ger: "(Radio-/Fernseh-)Sender", ctx: "station = 1. Bahnhof; 2. Sender" },
    { id: "8_3_55", eng: "at least", phon: "[æt 'liːst]", ger: "wenigstens, zumindest", ctx: "e.g., at least £600" },
    { id: "8_3_56", eng: "once", phon: "[wʌns]", ger: "einmal; einst; sobald, wenn (erst)", ctx: "once = 1. einmal; 2. einst; 3. sobald" },
    { id: "8_3_57", eng: "success", phon: "[sək'ses]", ger: "Erfolg", ctx: "adjective: successful" },
    { id: "8_3_58", eng: "(to) record", phon: "[rɪ'kɔːd]", ger: "aufnehmen, aufzeichnen; dokumentieren", ctx: "💡 Noun: 'record (Schallplatte/Rekord) – Verb: re'cord!" },
    { id: "8_3_59", eng: "(to) recognize", phon: "['rekəɡnaɪz]", ger: "(wieder)erkennen", ctx: "spelled -ize (AE) or -ise/-ize (BE)" },
    { id: "8_3_60", eng: "installation", phon: "[ˌɪnstə'leɪʃn]", ger: "Installation (Kunst)", ctx: "verb: (to) install" },
    { id: "8_3_61", eng: "toy", phon: "[tɔɪ]", ger: "Spielzeug", ctx: "e.g., toy cars" },
    { id: "8_3_62", eng: "yard (AE)", phon: "[jɑːd]", ger: "Garten", ctx: "💡 yard (AE) = Garten; yard (BE) = Hof; garden (BE) = Garten" },
    { id: "8_3_63", eng: "colourful", phon: "['kʌləfl]", ger: "farbig, bunt", ctx: "American English spelling: colorful" },
    { id: "8_3_64", eng: "sculpture", phon: "['skʌlptʃə]", ger: "Skulptur", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_3_65", eng: "(to) replace (with)", phon: "[rɪ'pleɪs]", ger: "ersetzen (durch), austauschen (gegen)", ctx: "replaced it with a special bike" },
    { id: "8_3_66", eng: "detail", phon: "['diːteɪl]", ger: "Detail, Einzelheit", ctx: "in detail = im Detail; detailed = detailliert" },
    { id: "8_3_67", eng: "(to) remind sb. of sth.", phon: "[rɪ'maɪnd]", ger: "jn. an etwas erinnern", ctx: "💡 NOT remember! (e.g., I remind her of her brother.)" },
    { id: "8_3_68", eng: "(to) cause sth.", phon: "[kɔːz]", ger: "etwas bewirken, verursachen", ctx: "noun: cause = Ursache" },
    { id: "8_3_69", eng: "sustainable", phon: "[sə'steɪnəbl]", ger: "nachhaltig, umweltverträglich; zukunftsfähig", ctx: "sustainable living = nachhaltige Lebensweise" },
    { id: "8_3_70", eng: "(to) reuse", phon: "[ˌriː'juːz]", ger: "wiederverwenden", ctx: "verb" },
    { id: "8_3_71", eng: "stuff", phon: "[stʌf]", ger: "Zeug, Kram", ctx: "informal" },
    { id: "8_3_72", eng: "instead of", phon: "[ɪn'sted ɒv]", ger: "anstatt, anstelle von", ctx: "instead = stattdessen (e.g., Can I have pasta instead?)" },
    { id: "8_3_73", eng: "necessary", phon: "['nesəsəri]", ger: "notwendig, nötig, erforderlich", ctx: "adjective" },
    { id: "8_3_74", eng: "value", phon: "['væljuː]", ger: "Wert", ctx: "value for money = Preis-Leistungs-Verhältnis" },
    { id: "8_3_75", eng: "proper", phon: "['prɒpə]", ger: "anständig, richtig, ordnungsgemäß", ctx: "adverb: properly" },
    { id: "8_3_76", eng: "(to) last (for)", phon: "[lɑːst]", ger: "(an)dauern; halten (von Bestand sein)", ctx: "The concert will last for about an hour." },
    { id: "8_3_77", eng: "(to) be made of", phon: "[meɪd ɒv]", ger: "bestehen aus, (gemacht) sein aus", ctx: "It's made of glass. (aus Nüssen bestehend = made with nuts)" },
    { id: "8_3_78", eng: "organic", phon: "[ɔː'ɡænɪk]", ger: "biologisch (angebaut), Bio-", ctx: "adverb: organically" },
    { id: "8_3_79", eng: "chemical", phon: "['kemɪkl]", ger: "Chemikalie; chemisch", ctx: "can be noun or adjective" },
    { id: "8_3_80", eng: "pocket", phon: "['pɒkɪt]", ger: "Tasche (an Kleidungsstücken)", ctx: "pocket money = Taschengeld" },
    { id: "8_3_81", eng: "since", phon: "[sɪns]", ger: "weil, da; seit", ctx: "since = 1. seit; 2. weil, da" },
    { id: "8_3_82", eng: "(to) grow, grew, grown", phon: "[ɡrəʊ], [ɡruː], [ɡrəʊn]", ger: "werden; wachsen; anbauen", ctx: "growing old = alt werden" },
    { id: "8_3_83", eng: "therefore", phon: "['ðeəfɔː]", ger: "daher, deshalb", ctx: "synonym: so" },
    { id: "8_3_84", eng: "zipper", phon: "['zɪpə]", ger: "Reißverschluss", ctx: "noun" },
    { id: "8_3_85", eng: "overall", phon: "[ˌəʊvər'ɔːl]", ger: "allgemein, im Großen und Ganzen, (ins)gesamt", ctx: "can be adjective or adverb" },
    { id: "8_3_86", eng: "content", phon: "['kɒntent]", ger: "Inhalt", ctx: "What is the content of the text?" },
    { id: "8_3_87", eng: "grammar", phon: "['ɡræmə]", ger: "Grammatik", ctx: "noun" },
    { id: "8_3_88", eng: "punctuation", phon: "[ˌpʌŋktʃu'eɪʃn]", ger: "Zeichensetzung", ctx: "Punctuation makes a difference." },
    { id: "8_3_89", eng: "full stop", phon: "[fʊl 'stɒp]", ger: "Punkt (Satzzeichen)", ctx: "punctuation mark" },
    { id: "8_3_90", eng: "comma", phon: "['kɒmə]", ger: "Komma", ctx: "punctuation mark" },
    { id: "8_3_91", eng: "colon", phon: "['kəʊlən]", ger: "Doppelpunkt", ctx: "punctuation mark" },
    { id: "8_3_92", eng: "question mark", phon: "['kwestʃən mɑːk]", ger: "Fragezeichen", ctx: "punctuation mark" },
    { id: "8_3_93", eng: "exclamation mark", phon: "[eksklə'meɪʃn mɑːk]", ger: "Ausrufezeichen", ctx: "punctuation mark" },
    { id: "8_3_94", eng: "hyphen", phon: "['haɪfn]", ger: "Bindestrich", ctx: "punctuation mark" },
    { id: "8_3_95", eng: "nature", phon: "['neɪtʃə]", ger: "(die) Natur", ctx: "adjective: natural" },
    { id: "8_3_96", eng: "landscape", phon: "['lændskeɪp]", ger: "Landschaft; Landschaftsbild", ctx: "-" },
    { id: "8_3_97", eng: "wildlife", phon: "['waɪldlaɪf]", ger: "Tiere (in freier Wildbahn), Tierwelt", ctx: "-" },
    { id: "8_3_98", eng: "climate", phon: "['klaɪmət]", ger: "Klima", ctx: "climate change = Klimawandel" },
    { id: "8_3_99", eng: "tortoise", phon: "['tɔːtəs]", ger: "Schildkröte", ctx: "noun" },
    { id: "8_3_100", eng: "manatee", phon: "['mænətiː]", ger: "Seekuh", ctx: "noun" },
    { id: "8_3_101", eng: "natural disaster", phon: "[ˌnætʃrəl dɪ'zɑːstə]", ger: "Naturkatastrophe", ctx: "disaster = Katastrophe, Unglück" },
    { id: "8_3_102", eng: "behaviour", phon: "[bɪ'heɪvjə]", ger: "Verhalten; Benehmen", ctx: "verb: (to) behave = sich verhalten" },
    { id: "8_3_103", eng: "minus", phon: "['maɪnəs]", ger: "minus", ctx: "opposite: plus" },
    { id: "8_3_104", eng: "thin", phon: "[θɪn]", ger: "dünn; schlank", ctx: "opposite: fat" },
    { id: "8_3_105", eng: "speed", phon: "[spiːd]", ger: "Geschwindigkeit", ctx: "verb: (to) speed = rasen, zu schnell fahren" },
    { id: "8_3_106", eng: "(to) climb", phon: "[klaɪm]", ger: "klettern (auf)", ctx: "e.g., I climbed a hill / a tree. (Ich kletterte *auf*...)" },
    { id: "8_3_107", eng: "sleeping bag", phon: "['sliːpɪŋ bæɡ]", ger: "Schlafsack", ctx: "-" },
    { id: "8_3_108", eng: "peaceful", phon: "['piːsfl]", ger: "friedlich, friedfertig", ctx: "noun: peace" },
    { id: "8_3_109", eng: "(to) play dead", phon: "[pleɪ ded]", ger: "sich tot stellen", ctx: "phrase" },
    { id: "8_3_110", eng: "(to) threaten", phon: "['θretn]", ger: "(be)drohen", ctx: "noun: threat (to) = Drohung, Gefahr (für)" },
    { id: "8_3_111", eng: "global warming", phon: "[ˌɡləʊbl 'wɔːmɪŋ]", ger: "Erderwärmung", ctx: "global = global, weltweit; warming = Erwärmung" },
    { id: "8_3_112", eng: "drought", phon: "[draʊt]", ger: "Dürre", ctx: "💡 Note the pronunciation [draʊt]! (a long time without rain)" },
    { id: "8_3_113", eng: "flood", phon: "[flʌd]", ger: "Überschwemmung, Hochwasser; Flut", ctx: "verb: (to) flood = überfluten, überschwemmen" },
    { id: "8_3_114", eng: "wildfire", phon: "['waɪldfaɪə]", ger: "Flächenbrand", ctx: "-" },
    { id: "8_3_115", eng: "(to) rise, rose, risen", phon: "[raɪz], [rəʊz], ['rɪzən]", ger: "(an)steigen; sich erhebeb", ctx: "Temperatures are rising." },
    { id: "8_3_116", eng: "diet", phon: "['daɪət]", ger: "Ernährung, Kost; Diät", ctx: "Betonung auf der 1. Silbe! (went on a diet = machte eine Diät)" },
    { id: "8_3_117", eng: "salmon (pl. salmon)", phon: "['sæmən]", ger: "Lachs", ctx: "💡 Plural form is the same! The 'l' is silent." },
    { id: "8_3_118", eng: "(to) draw, drew, drawn", phon: "[drɔː], [druː], [drɔːn]", ger: "zeichnen", ctx: "noun: drawing = Zeichnung" }
];