const e8u4_data = [
    { id: "8_4_1", eng: "slavery", phon: "['sleɪvəri]", ger: "Sklaverei", ctx: "They were slaves. = They lived in slavery." },
    { id: "8_4_2", eng: "civil rights (pl.)", phon: "[ˌsɪvl 'raɪts]", ger: "Bürgerrechte", ctx: "civil = Bürger-, (staats-)bürgerlich" },
    { id: "8_4_3", eng: "hurricane", phon: "['hʌrɪkən]", ger: "Hurrikan, Orkan", ctx: "a bad storm with very strong winds" },
    { id: "8_4_4", eng: "(to) mediate", phon: "['miːdieɪt]", ger: "vermitteln (inhaltlich wiedergeben)", ctx: "noun: mediation [miːdi'eɪʃn] (Sprachmittlung)" },
    { id: "8_4_5", eng: "role model", phon: "['rəʊl ˌmɒdl]", ger: "Vorbild", ctx: "a person you try to be like" },
    { id: "8_4_6", eng: "wife (pl. wives)", phon: "[waɪf], [waɪvz]", ger: "(Ehe-)Frau", ctx: "husband and wife (woman = Frau allgemein; Mrs/Ms = Frau vor Namen)" },
    { id: "8_4_7", eng: "Mardi Gras", phon: "[ˌmɑːdi 'ɡrɑː]", ger: "Faschingsdienstag (auch: Karneval in New Orleans)", ctx: "-" },
    { id: "8_4_8", eng: "mostly", phon: "['məʊstli]", ger: "hauptsächlich", ctx: "e.g., I eat mostly healthy food." },
    { id: "8_4_9", eng: "(to) pass a law", phon: "[pɑːs ə 'lɔː]", ger: "ein Gesetz verabschieden", ctx: "Several countries have passed laws." },
    { id: "8_4_10", eng: "(to) be afraid (of)", phon: "[biː ə'freɪd]", ger: "Angst haben (vor), sich fürchten (vor)", ctx: "I'm afraid = leider, ich fürchte" },
    { id: "8_4_11", eng: "civil war", phon: "[ˌsɪvl 'wɔː]", ger: "Bürgerkrieg", ctx: "a war between groups of people in the same country" },
    { id: "8_4_12", eng: "segregation", phon: "[ˌseɡrɪ'ɡeɪʃn]", ger: "Trennung (nach Hautfarbe/Religion/Geschlecht)", ctx: "noun" },
    { id: "8_4_13", eng: "discrimination (against sb.)", phon: "[dɪˌskrɪmɪ'neɪʃn]", ger: "Diskriminierung (eines Menschen)", ctx: "verb: (to) discriminate against sb." },
    { id: "8_4_14", eng: "activist", phon: "['æktɪvɪst]", ger: "Aktivist/in", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_4_15", eng: "lawyer", phon: "['lɔːjə]", ger: "(Rechts-)Anwalt/Anwältin", ctx: "someone who has studied law" },
    { id: "8_4_16", eng: "education", phon: "[ˌedʒu'keɪʃn]", ger: "Erziehung, (Schul-)Bildung", ctx: "verb: (to) educate sb." },
    { id: "8_4_17", eng: "(to) matter", phon: "['mætə]", ger: "von Bedeutung sein, wichtig sein", ctx: "It doesn't matter. = Es/Das ist egal." },
    { id: "8_4_18", eng: "prison", phon: "['prɪzn]", ger: "Gefängnis", ctx: "noun" },
    { id: "8_4_19", eng: "victim", phon: "['vɪktɪm]", ger: "Opfer", ctx: "e.g., victim of bullying" },
    { id: "8_4_20", eng: "armed", phon: "[ɑːmd]", ger: "bewaffnet", ctx: "opposite: unarmed" },
    { id: "8_4_21", eng: "(to) go on", phon: "[ɡəʊ 'ɒn]", ger: "weitergehen; weitermachen, weiterreden; (sich) fortsetzen", ctx: "synonym: (to) continue" },
    { id: "8_4_22", eng: "neighbourhood watch", phon: "['neɪbəhʊd wɒtʃ]", ger: "Nachbarschaftswache", ctx: "noun" },
    { id: "8_4_23", eng: "suspicious (of)", phon: "[sə'spɪʃəs]", ger: "verdächtig; misstrauisch (gegenüber)", ctx: "looked suspicious / suspicious of the strange people" },
    { id: "8_4_24", eng: "(to) chase", phon: "[tʃeɪs]", ger: "verfolgen, jagen", ctx: "noun: chase = Verfolgung" },
    { id: "8_4_25", eng: "(to) charge sb. (with sth.)", phon: "[tʃɑːdʒ]", ger: "jn. anklagen (wegen etwas)", ctx: "noun: charge = Anlage, Beschuldigung" },
    { id: "8_4_26", eng: "murder", phon: "['mɜːdə]", ger: "Mord", ctx: "verb: (to) murder = ermorden; person: murderer = Mörder/in" },
    { id: "8_4_27", eng: "court", phon: "[kɔːt]", ger: "Gericht(shof)", ctx: "(to) go to court = vor Gericht ziehen; (to) take sb. to court = jn. verklagen" },
    { id: "8_4_28", eng: "trial", phon: "['traɪəl]", ger: "(Gerichts-)Verfahren, Prozess", ctx: "on trial for murder / right to a fair trial" },
    { id: "8_4_29", eng: "(to) clear sb. (of sth.)", phon: "[klɪə]", ger: "jn. (von etwas) freisprechen", ctx: "He was cleared of the charges." },
    { id: "8_4_30", eng: "bullet", phon: "['bʊlɪt]", ger: "(Gewehr-)Kugel", ctx: "bullets and bullet holes" },
    { id: "8_4_31", eng: "(to) lie, lay, lain", phon: "[laɪ], [leɪ], [leɪn]", ger: "liegen", ctx: "💡 -ing-Form ist knifflig: lying (e.g., lying on my bed)" },
    { id: "8_4_32", eng: "huge", phon: "[hjuːdʒ]", ger: "riesig, Riesen-", ctx: "huge present" },
    { id: "8_4_33", eng: "(to) raise", phon: "[reɪz]", ger: "(er)heben", ctx: "raise one's eyes = aufschauen; raise one's voice = die Stimme erheben" },
    { id: "8_4_34", eng: "awareness", phon: "[ə'weənəs]", ger: "Bewusstsein, Aufmerksamkeit", ctx: "to raise awareness of sth. / adjective: (to) be aware of" },
    { id: "8_4_35", eng: "(to) profile", phon: "['prəʊfaɪl]", ger: "beschreiben, porträtieren", ctx: "racial profiling / noun: profile = Profil" },
    { id: "8_4_36", eng: "race", phon: "[reɪs]", ger: "Rasse", ctx: "adjective: racial ['reɪʃl]" },
    { id: "8_4_37", eng: "point", phon: "[pɔɪnt]", ger: "Argument, Standpunkt", ctx: "That's a good point / make a point / take a point" },
    { id: "8_4_38", eng: "few", phon: "[fjuː]", ger: "wenige", ctx: "a few = einige, ein paar; few = wenige, nicht viele (Plural zählbar)" },
    { id: "8_4_39", eng: "interested (in)", phon: "['ɪntrəstɪd]", ger: "interessiert (an)", ctx: "💡 (to) be interested in + verb -ing (interested in learning)" },
    { id: "8_4_40", eng: "headline", phon: "['hedlaɪn]", ger: "Überschrift", ctx: "noun" },
    { id: "8_4_41", eng: "justice", phon: "['dʒʌstɪs]", ger: "Gerechtigkeit", ctx: "opposite: injustice; adjective: just = gerecht; just (adv) = nur, bloß, gerade" },
    { id: "8_4_42", eng: "certificate", phon: "[sə'tɪfɪkət]", ger: "Urkunde, Bescheinigung", ctx: "birth certificate = Geburtsurkunde" },
    { id: "8_4_43", eng: "Christian", phon: "['krɪstʃən]", ger: "Christ/in; christlich", ctx: "-" },
    { id: "8_4_44", eng: "industry", phon: "['ɪndəstri]", ger: "Industrie", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_4_45", eng: "scrapbook", phon: "['skræpbʊk]", ger: "Sammelalbum; Notizbuch", ctx: "-" },
    { id: "8_4_46", eng: "talent", phon: "['tælənt]", ger: "Talent", ctx: "Betonung auf der 1. Silbe! (adjective: talented)" },
    { id: "8_4_47", eng: "gymnast", phon: "['dʒɪmnæst]", ger: "Turner/in", ctx: "sport: gymnastics" },
    { id: "8_4_48", eng: "(to) award", phon: "[ə'wɔːd]", ger: "(Preis) verleihen", ctx: "noun: award = Preis, Auszeichnung" },
    { id: "8_4_49", eng: "medal", phon: "['medl]", ger: "Medaille", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_4_50", eng: "pain", phon: "[peɪn]", ger: "Schmerz; Plage", ctx: "to be in pain / to be a pain = lästig sein / What a pain!" },
    { id: "8_4_51", eng: "kidney", phon: "['kɪdni]", ger: "Niere", ctx: "You have two kidneys." },
    { id: "8_4_52", eng: "(to) box", phon: "[bɒks]", ger: "boxen", ctx: "verb" },
    { id: "8_4_53", eng: "sportsperson (pl. sportspeople)", phon: "['spɔːtspɜːsn]", ger: "Sportler/in", ctx: "-" },
    { id: "8_4_54", eng: "seafood", phon: "['siːfuːd]", ger: "Meeresfrüchte", ctx: "💡 ACHTUNG: seafood + Verb im Singular (The seafood *is* fresh.)" },
    { id: "8_4_55", eng: "(to) depress", phon: "[dɪ'pres]", ger: "deprimieren", ctx: "adjectives: depressing (deprimierend) / depressed (deprimiert)" },
    { id: "8_4_56", eng: "(to) shock sb.", phon: "[ʃɒk]", ger: "jn. schockieren", ctx: "noun: shock" },
    { id: "8_4_57", eng: "(to) destroy", phon: "[dɪ'strɔɪ]", ger: "zerstören, vernichten", ctx: "verb" },
    { id: "8_4_58", eng: "level", phon: "['levl]", ger: "Grad, Stufe; Niveau, Ebene", ctx: "at professional level / higher levels / sea level = Meeresspiegel" },
    { id: "8_4_59", eng: "mayor", phon: "[meə]", ger: "Bürgermeister/in", ctx: "Our town has a new mayor." },
    { id: "8_4_60", eng: "anyway", phon: "['eniweɪ]", ger: "sowieso; jedenfalls, wie dem auch sei", ctx: "I don't need it anyway." },
    { id: "8_4_61", eng: "power", phon: "['paʊə]", ger: "Energie, Strom; Kraft, Macht", ctx: "noun" },
    { id: "8_4_62", eng: "disgusted (by/that ...)", phon: "[dɪs'ɡʌstɪd]", ger: "empört (über/dass ...); angewidert (von)", ctx: "disgusted at/by / adjective: disgusting = ekelhaft, widerlich" },
    { id: "8_4_63", eng: "condition", phon: "[kən'dɪʃn]", ger: "Bedingung; Zustand", ctx: "in excellent condition / to work in/under these conditions" },
    { id: "8_4_64", eng: "(to) rebuild, rebuilt, rebuilt", phon: "[ˌriː'bɪld], [ˌriː'bɪlt]", ger: "wiederaufbauen", ctx: "irregular verb" },
    { id: "8_4_65", eng: "(to) graduate (from)", phon: "['ɡrædʒueɪt]", ger: "den Abschluss machen (an) (Schule, Hochschule)", ctx: "Sean graduated from Oxford University." },
    { id: "8_4_66", eng: "(to) grow up, grew, grown", phon: "[ɡrəʊ 'ʌp], [ɡruː], [ɡrəʊn]", ger: "aufwachsen; erwachsen werden", ctx: "grew up on a farm / when she grows up" },
    { id: "8_4_67", eng: "tornado", phon: "[tɔː'neɪdəʊ]", ger: "Tornado (Wirbelsturm)", ctx: "Note the pronunciation!" },
    { id: "8_4_68", eng: "appointment", phon: "[ə'pɔɪntmənt]", ger: "Termin (Verabredung)", ctx: "make an appointment / by appointment only (nur mit Termin)" },
    { id: "8_4_69", eng: "pill", phon: "[pɪl]", ger: "Tablette, Pille", ctx: "In Britain also: tablet (tablet = 1. Tablette; 2. Tablet-Computer)" },
    { id: "8_4_70", eng: "document", phon: "['dɒkjumənt]", ger: "Dokument; Text(datei)", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_4_71", eng: "allergy (to)", phon: "['ælədʒi]", ger: "Allergie (gegen)", ctx: "Betonung auf 1. Silbe! / adjective: allergic (to) [ə'lɜːdʒɪk]" },
    { id: "8_4_72", eng: "antibiotic", phon: "[ˌæntibaɪ'ɒtɪk]", ger: "Antibiotikum", ctx: "plural: antibiotics = (verschiedene) Antibiotika" },
    { id: "8_4_73", eng: "twice", phon: "[twaɪs]", ger: "zweimal", ctx: "once (einmal), twice (zweimal)" },
    { id: "8_4_74", eng: "prescription", phon: "[prɪ'skrɪpʃn]", ger: "Rezept (vom Arzt)", ctx: "💡 NOT recipe! (recipe = Kochrezept)" },
    { id: "8_4_75", eng: "drugstore (AE)", phon: "['drʌɡstɔː]", ger: "Drogerie", ctx: "noun" },
    { id: "8_4_76", eng: "(to) take sb.'s temperature", phon: "[teɪk]", ger: "bei jm. Fieber messen", ctx: "(to) take sb.'s blood pressure = bei jm. Blutdruck messen" },
    { id: "8_4_77", eng: "title", phon: "['taɪtl]", ger: "Titel, Überschrift", ctx: "Note the pronunciation ['taɪtl]!" },
    { id: "8_4_78", eng: "bee", phon: "[biː]", ger: "Biene", ctx: "plural: bees" },
    { id: "8_4_79", eng: "(to) arrest sb.", phon: "[ə'rest]", ger: "jn. festnehmen, verhaften", ctx: "noun: arrest = Festnahme" },
    { id: "8_4_80", eng: "fool", phon: "[fuːl]", ger: "Idiot, Dummkopf", ctx: "meaning: a stupid person" },
    { id: "8_4_81", eng: "flashlight (AE)", phon: "['flæʃlaɪt]", ger: "Taschenlampe", ctx: "British English: torch" },
    { id: "8_4_82", eng: "registration", phon: "[ˌredʒɪ'streɪʃn]", ger: "Anmeldung; Zulassung, KFZ-Schein", ctx: "registration number = Autokennzeichen" },
    { id: "8_4_83", eng: "proof (no pl.)", phon: "[pruːf]", ger: "Beweis(e); Nachweis(e)", ctx: "proof of insurance / verb: (to) prove" },
    { id: "8_4_84", eng: "(to) pull sb. over", phon: "[pʊl]", ger: "jn. an den (Straßen-)Rand winken", ctx: "The police officer pulled us over. / (to) pull over = anhalten" },
    { id: "8_4_85", eng: "wallet", phon: "['wɒlɪt]", ger: "Brieftasche; Portemonnaie", ctx: "-" },
    { id: "8_4_86", eng: "badge", phon: "[bædʒ]", ger: "Dienstmarke (Polizei); Anstecknadel, Button", ctx: "noun" },
    { id: "8_4_87", eng: "He's in his mid-thirties.", phon: "[mɪd]", ger: "Er ist Mitte dreißig.", ctx: "early thirties = Anfang dreißig; late thirties = Ende dreißig" },
    { id: "8_4_88", eng: "buzz cut", phon: "['bʌz kʌt]", ger: "Igelfrisur (extrem kurzer Haarschnitt)", ctx: "-" },
    { id: "8_4_89", eng: "scar", phon: "[skɑː]", ger: "Narbe", ctx: "verb: (to) scar sb. = bei jm. Narben hinterlassen / His face was scarred." },
    { id: "8_4_90", eng: "lip", phon: "[lɪp]", ger: "Lippe", ctx: "-" },
    { id: "8_4_91", eng: "business", phon: "['bɪznəs]", ger: "Sache, Angelegenheit; Geschäft, Betrieb", ctx: "That's none of your business. / business = 1. Geschäft; 2. Sache" },
    { id: "8_4_92", eng: "ticket", phon: "['tɪkɪt]", ger: "Strafzettel; Eintrittskarte, Fahrkarte", ctx: "ticket = 1. Eintrittskarte; 2. Strafzettel" },
    { id: "8_4_93", eng: "(to) push", phon: "[pʊʃ]", ger: "schieben, stoßen, schubsen", ctx: "opposite: pull / noun: push = Stoß, Schubs" },
    { id: "8_4_94", eng: "dashboard", phon: "['dæʃbɔːd]", ger: "Armaturenbrett", ctx: "-" },
    { id: "8_4_95", eng: "(to) pat", phon: "[pæt]", ger: "klopfen; tätscheln", ctx: "(to) pat sb. down = jn. abtasten (Polizeikontrolle)" },
    { id: "8_4_96", eng: "(to) hold onto sth.", phon: "[həʊld 'ɒntu]", ger: "sich an etwas festhalten; etwas festhalten", ctx: "phrase" },
    { id: "8_4_97", eng: "(to) gasp", phon: "[ɡɑːsp]", ger: "nach Luft ringen", ctx: "noun: gasp = tiefer Atemzug" },
    { id: "8_4_98", eng: "(to) be amazed at/by sth.", phon: "[ə'meɪzd]", ger: "über etwas staunen, erstaunt sein", ctx: "amazed = erstaunt; amazing = erstaunlich, großartig" },
    { id: "8_4_99", eng: "scream", phon: "[skriːm]", ger: "Schrei", ctx: "verb: (to) scream = schreien" },
    { id: "8_4_100", eng: "sky", phon: "[skaɪ]", ger: "Himmel", ctx: "e.g., the sun/stars in the sky (am Himmel)" },
    { id: "8_4_101", eng: "(to) blink (your eyes)", phon: "[blɪŋk]", ger: "blinzeln, (mit den Augen) zwinkern", ctx: "meaning: to close and open your eyes very quickly" },
    { id: "8_4_102", eng: "reaction (to)", phon: "[ri'ækʃn]", ger: "Reaktion (auf)", ctx: "verb: (to) react (to)" },
    { id: "8_4_103", eng: "(to) edit", phon: "['edɪt]", ger: "bearbeiten, editieren", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_4_104", eng: "voice-over", phon: "['vɔɪs ˌəʊvə]", ger: "Filmkommentar, Off-Stimme", ctx: "noun" }
];