const e8u5_data = [
    { id: "8_5_1", eng: "emphasis (pl. emphases)", phon: "['emfəsɪs], ['emfəsiːz]", ger: "Betonung, Schwerpunkt, Akzent", ctx: "noun (verb: to emphasize)" },
    { id: "8_5_2", eng: "diagram", phon: "['daɪəɡræm]", ger: "Diagramm", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_5_3", eng: "visuals (pl.)", phon: "['vɪʒuəlz]", ger: "visuelle Materialien / Hilfsmittel", ctx: "kurz für: visual materials" },
    { id: "8_5_4", eng: "brochure", phon: "['brəʊʃə]", ger: "Broschüre, Prospekt", ctx: "a thin book/magazine with information" },
    { id: "8_5_5", eng: "beaver", phon: "['biːvə]", ger: "Biber", ctx: "noun" },
    { id: "8_5_6", eng: "polar bear", phon: "['pəʊlə beə]", ger: "Eisbär", ctx: "Betonung auf der 1. Silbe bei 'polar'!" },
    { id: "8_5_7", eng: "nation", phon: "['neɪʃn]", ger: "Nation", ctx: "First Nations = indigene Völker Kanadas" },
    { id: "8_5_8", eng: "Arctic", phon: "['ɑːktɪk]", ger: "die Arktis; arktisch, Polar-", ctx: "life in the Arctic / arctic winters" },
    { id: "8_5_9", eng: "descendant", phon: "[dɪ'sendənt]", ger: "Nachfahren/-fahrin, Nachkomme", ctx: "opposite: ancestor" },
    { id: "8_5_10", eng: "maple leaf", phon: "['meɪpl liːf]", ger: "Ahornblatt", ctx: "maple = Ahorn; plural: maple leaves" },
    { id: "8_5_11", eng: "wilderness", phon: "['wɪldənəs]", ger: "Wildnis", ctx: "noun (adjective: wild [waɪld])" },
    { id: "8_5_12", eng: "health care", phon: "['helθ keə]", ger: "Gesundheitsfürsorge, medizinische Versorgung", ctx: "access to good health care" },
    { id: "8_5_13", eng: "mosaic", phon: "[məʊ'zeɪɪk]", ger: "Mosaik", ctx: "Achte auf die Betonung auf der 2. Silbe!" },
    { id: "8_5_14", eng: "bilingualism", phon: "[baɪ'lɪŋɡwəlɪzm]", ger: "Zweisprachigkeit", ctx: "adjective: bilingual" },
    { id: "8_5_15", eng: "(to) mine sth.", phon: "[maɪn]", ger: "etwas abbauen, fördern (z. B. Bergbau)", ctx: "noun: mine = Bergwerk, Mine" },
    { id: "8_5_16", eng: "alert", phon: "[ə'lɜːt]", ger: "Warnung, Alarm; aufmerksam", ctx: "can be noun, adjective (alert to) or verb" },
    { id: "8_5_17", eng: "(to) frighten", phon: "['fraɪtn]", ger: "Angst einjagen, verängstigen; erschrecken", ctx: "frightening = beängstigend; frightened = Angst haben" },
    { id: "8_5_18", eng: "horn", phon: "[hɔːn]", ger: "Horn; Hupe (Auto)", ctx: "plural: horns" },
    { id: "8_5_19", eng: "(to) flash", phon: "[flæʃ]", ger: "blinken, leuchten", ctx: "flashing lights = Warnlicht / Blaulicht" },
    { id: "8_5_20", eng: "fear (of)", phon: "[fɪə]", ger: "Angst (vor)", ctx: "verb: (to) fear = fürchten" },
    { id: "8_5_21", eng: "migration", phon: "[maɪ'ɡreɪʃn]", ger: "Migration, Zu-/Aus-/Abwanderung", ctx: "verb: (to) migrate" },
    { id: "8_5_22", eng: "(to) weigh", phon: "[weɪ]", ger: "wiegen", ctx: "noun: weight = Gewicht" },
    { id: "8_5_23", eng: "kilo(gram)", phon: "['kiːləʊ]", ger: "Kilo(gramm)", ctx: "e.g., more than 30 kilos" },
    { id: "8_5_24", eng: "sense", phon: "[sens]", ger: "Sinn", ctx: "sense of smell/touch / (to) make sense = Sinn ergeben" },
    { id: "8_5_25", eng: "trap", phon: "[træp]", ger: "Falle", ctx: "verb: (to) trap = fangen, einschließen; (to) be trapped" },
    { id: "8_5_26", eng: "seal", phon: "[siːl]", ger: "Robbe, Seehund", ctx: "noun" },
    { id: "8_5_27", eng: "bay", phon: "[beɪ]", ger: "Bucht", ctx: "-" },
    { id: "8_5_28", eng: "autumn", phon: "['ɔːtəm]", ger: "Herbst", ctx: "💡 Merkhilfe: You say ['ɔːtəm] – you write autu*mn*!" },
    { id: "8_5_29", eng: "(to) terrify sb.", phon: "['terɪfaɪ]", ger: "jm. schreckliche Angst einjagen", ctx: "terrifying = erschreckend; terrified = schreckliche Angst haben" },
    { id: "8_5_30", eng: "(to) grab", phon: "[ɡræb]", ger: "packen, greifen (nach), ergreifen", ctx: "meaning: to take or hold sb./sth. suddenly" },
    { id: "8_5_31", eng: "scalp", phon: "[skælp]", ger: "Kopfhaut", ctx: "the skin on your head where your hair grows" },
    { id: "8_5_32", eng: "shovel", phon: "['ʃʌvl]", ger: "Schaufel", ctx: "noun" },
    { id: "8_5_33", eng: "local", phon: "['ləʊkl]", ger: "einheimisch, am/vom Ort", ctx: "Our kids go to the local school." },
    { id: "8_5_34", eng: "attitude (to/towards)", phon: "['ætɪtjuːd]", ger: "Einstellung, (Geistes-)Haltung (zu/gegenüber)", ctx: "What's your attitude?" },
    { id: "8_5_35", eng: "adventure", phon: "[əd'ventʃə]", ger: "Abenteuer", ctx: "What an adventure!" },
    { id: "8_5_36", eng: "outdoors", phon: "[aʊt'dɔːz]", ger: "im Freien, draußen", ctx: "adjective: outdoor / adverb: outdoors" },
    { id: "8_5_37", eng: "fishing", phon: "['fɪʃɪŋ]", ger: "Fischen, Angeln; Fischerei", ctx: "verb: (to) fish" },
    { id: "8_5_38", eng: "canoeing", phon: "['kə'nuːɪŋ]", ger: "Paddeln, Kanusport", ctx: "noun: canoe = Kanu, Paddelboot; verb: (to) canoe" },
    { id: "8_5_39", eng: "(to) confirm", phon: "[kən'fɜːm]", ger: "bestätigen", ctx: "noun: confirmation = Bestätigung" },
    { id: "8_5_40", eng: "suggestion", phon: "[sə'dʒestʃən]", ger: "Vorschlag", ctx: "verb: (to) suggest" },
    { id: "8_5_41", eng: "(to) make an excuse", phon: "[maɪk ən ɪk'skjuːs]", ger: "sich entschuldigen, eine Entschuldigung vorbringen", ctx: "noun: excuse [ɪk'skjuːs] / verb: (to) excuse [ɪk'skjuːz]" },
    { id: "8_5_42", eng: "follow-up", phon: "['fɒləʊ ʌp]", ger: "Anschluss-, Folge-", ctx: "e.g., follow-up questions" },
    { id: "8_5_43", eng: "(to) mention", phon: "['menʃn]", ger: "erwähnen", ctx: "verb" },
    { id: "8_5_44", eng: "general", phon: "['dʒenrəl]", ger: "allgemein", ctx: "in general = im Allgemeinen, generell" },
    { id: "8_5_45", eng: "legend", phon: "['ledʒənd]", ger: "Legende, Sage", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_5_46", eng: "(to) treat", phon: "[triːt]", ger: "behandeln", ctx: "noun: treatment = Behandlung" },
    { id: "8_5_47", eng: "(to) kiss", phon: "[kɪs]", ger: "(sich) küssen", ctx: "noun: kiss = Kuss" },
    { id: "8_5_48", eng: "marmot", phon: "['mɑːmət]", ger: "Murmeltier", ctx: "-" },
    { id: "8_5_49", eng: "subtitles (pl.)", phon: "['sʌbtaɪtlz]", ger: "Untertitel", ctx: "I watched the film with subtitles." },
    { id: "8_5_50", eng: "rodeo", phon: "['rəʊdiəʊ]", ger: "Rodeo", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_5_51", eng: "relay (race)", phon: "['riːleɪ]", ger: "Staffel(lauf)", ctx: "noun" },
    { id: "8_5_52", eng: "(to) injure", phon: "['ɪndʒə]", ger: "(sich) verletzen", ctx: "injured = verletzt; noun: injury = Verletzung" },
    { id: "8_5_53", eng: "helmet", phon: "['helmɪt]", ger: "Helm", ctx: "plural: helmets" },
    { id: "8_5_54", eng: "barrel", phon: "['bærəl]", ger: "Fass", ctx: "noun" },
    { id: "8_5_55", eng: "race", phon: "[reɪs]", ger: "(Wett-)Rennen", ctx: "person: racer; verb: (to) race" },
    { id: "8_5_56", eng: "saddle", phon: "['sædl]", ger: "Sattel", ctx: "verb: (to) saddle = satteln" },
    { id: "8_5_57", eng: "(to) be able to do sth.", phon: "[biː 'eɪbl]", ger: "etwas tun können, in der Lage sein etwas zu tun", ctx: "past: weren't able to / couldn't; noun: ability" },
    { id: "8_5_58", eng: "permission", phon: "[pə'mɪʃn]", ger: "Erlaubnis", ctx: "I was given permission to go." },
    { id: "8_5_59", eng: "possible", phon: "['pɒsəbl]", ger: "möglich", ctx: "as soon as possible = so bald wie möglich" },
    { id: "8_5_60", eng: "cruelty", phon: "['kruːəlti]", ger: "Grausamkeit", ctx: "adjective: cruel" },
    { id: "8_5_61", eng: "strap", phon: "[stræp]", ger: "Gurt, Riemen", ctx: "noun" },
    { id: "8_5_62", eng: "(to) buck", phon: "[bʌk]", ger: "bocken, buckeln (Pferd)", ctx: "When a horse bucks, it jumps around." },
    { id: "8_5_63", eng: "(to) publish", phon: "['pʌblɪʃ]", ger: "veröffentlichen, herausbringen", ctx: "verb" },
    { id: "8_5_64", eng: "Dear Sir or Madam", phon: "[dɪə sɜː ɔː 'mædəm]", ger: "Sehr geehrte Damen und Herren", ctx: "Briefanrede (Anschluss: Yours faithfully)" },
    { id: "8_5_65", eng: "finally", phon: "['faɪnəli]", ger: "schließlich, endlich", ctx: "synonym: at last" },
    { id: "8_5_66", eng: "Yours sincerely", phon: "[jɔːz sɪn'sɪəli]", ger: "Mit freundlichen Grüßen (Briefschluss bei bekanntem Namen)", ctx: "Briefschluss bei *unbekanntem* Namen = Yours faithfully" },
    { id: "8_5_67", eng: "Yours faithfully", phon: "[jɔːz 'feɪθfəli]", ger: "Mit freundlichen Grüßen (Briefschluss bei unbekanntem Namen)", ctx: "American English alternative: Sincerely yours" },
    { id: "8_5_68", eng: "bar chart", phon: "['bɑː tʃɑːt]", ger: "Balkendiagramm, Säulendiagramm", ctx: "-" },
    { id: "8_5_69", eng: "infographic", phon: "[ˌɪnfə'ɡræfɪk]", ger: "Infografik", ctx: "noun" },
    { id: "8_5_70", eng: "line chart", phon: "['laɪn tʃɑːt]", ger: "Liniendiagramm", ctx: "-" },
    { id: "8_5_71", eng: "development", phon: "[dɪ'veləpmənt]", ger: "Entwicklung; Erschließung (z. B. Gelände)", ctx: "verb: (to) develop" },
    { id: "8_5_72", eng: "five in 100", phon: "[faɪv ɪn hʌndrəd]", ger: "fünf von 100", ctx: "💡 structure: one in three kids has/have..." },
    { id: "8_5_73", eng: "alive", phon: "[ə'laɪv]", ger: "lebendig, am Leben", ctx: "meaning: living, not dead" },
    { id: "8_5_74", eng: "cabin", phon: "['kæbɪn]", ger: "Hütte; Kabine", ctx: "noun" },
    { id: "8_5_75", eng: "(to) set off", phon: "[set 'ɒf]", ger: "aufbrechen (sich auf den Weg machen)", ctx: "synonyms: (to) leave, (to) begin a journey" },
    { id: "8_5_76", eng: "either ... or ...", phon: "['aɪðə]", ger: "entweder ... oder ...", ctx: "opposite: neither ... nor ... (weder ... noch ...)" },
    { id: "8_5_77", eng: "jar", phon: "[dʒɑː]", ger: "Glasgefäß", ctx: "e.g., jars of mustard" },
    { id: "8_5_78", eng: "hatchet", phon: "['hætʃɪt]", ger: "Beil", ctx: "noun" },
    { id: "8_5_79", eng: "(to) stare (at)", phon: "[steə]", ger: "(an)starren", ctx: "noun: stare = das Starren" },
    { id: "8_5_80", eng: "shore", phon: "[ʃɔː]", ger: "Ufer; Küste", ctx: "noun" },
    { id: "8_5_81", eng: "(to) whistle", phon: "['wɪsl]", ger: "pfeifen", ctx: "noun: whistle = Pfiff, Pfeife" },
    { id: "8_5_82", eng: "edge", phon: "[edʒ]", ger: "Rand, Kante", ctx: "Don't stand near the edge!" },
    { id: "8_5_83", eng: "(to) trip", phon: "[trɪp]", ger: "stolpern", ctx: "(to) trip sb. up = jn. stolpern lassen" },
    { id: "8_5_84", eng: "branch", phon: "[brɑːntʃ]", ger: "Ast, Zweig, (Neben-)Arm", ctx: "parts of a tree where leaves grow" },
    { id: "8_5_85", eng: "(to) reach (sb./a place)", phon: "[riːtʃ]", ger: "(jn./einen Ort) erreichen", ctx: "reach for sth. = nach etwas greifen; reach out = Hand ausstrecken" },
    { id: "8_5_86", eng: "(to) slip", phon: "[slɪp]", ger: "(aus)rutschen", ctx: "I slipped on the wet grass." },
    { id: "8_5_87", eng: "apart", phon: "[ə'pɑːt]", ger: "auseinander, getrennt", ctx: "opposite: together / (to) come apart" },
    { id: "8_5_88", eng: "flesh", phon: "[fleʃ]", ger: "Fleisch; (von Menschen auch) Haut", ctx: "💡 UNTERSCHIED: meat = Fleisch von toten Tieren zum Essen; flesh = Gewebe bei Lebewesen/Früchten" },
    { id: "8_5_89", eng: "(to) dare", phon: "[deə]", ger: "wagen, sich trauen", ctx: "verb" },
    { id: "8_5_90", eng: "(to) turn off", phon: "[tɜːn 'ɒf]", ger: "abbiegen", ctx: "Where do we have to turn off?" },
    { id: "8_5_91", eng: "tail", phon: "[teɪl]", ger: "Schwanz", ctx: "The dog's tail was wagging." },
    { id: "8_5_92", eng: "(to) wag", phon: "[wæɡ]", ger: "wedeln (mit)", ctx: "The dog was wagging its tail." },
    { id: "8_5_93", eng: "thick", phon: "[θɪk]", ger: "dick; dicht", ctx: "opposite: thin / thick book / thick dark hair" },
    { id: "8_5_94", eng: "relief", phon: "[rɪ'liːf]", ger: "Erleichterung; Linderung", ctx: "What a relief!" },
    { id: "8_5_95", eng: "reluctant", phon: "[rɪ'lʌktənt]", ger: "zurückhaltend, zögernd; widerwillig", ctx: "adjective" },
    { id: "8_5_96", eng: "except (for)", phon: "[ɪk'sept]", ger: "außer, bis auf", ctx: "noun: exception = Ausnahme" },
    { id: "8_5_97", eng: "thought", phon: "[θɔːt]", ger: "Gedanke", ctx: "verb: (to) think, thought, thought" },
    { id: "8_5_98", eng: "(to) crush", phon: "[krʌʃ]", ger: "(zer)quetschen; (aus)pressen", ctx: "We crush apples to make juice." },
    { id: "8_5_99", eng: "fireplace", phon: "['faɪəpleɪs]", ger: "Kamin", ctx: "noun" },
    { id: "8_5_100", eng: "corn", phon: "[kɔːn]", ger: "(BE) Korn, Getreide; (AE) Mais", ctx: "-" },
    { id: "8_5_101", eng: "tongue", phon: "[tʌŋ]", ger: "Zunge; Sprache", ctx: "💡 Note pronunciation [tʌŋ]! (mother tongue = Muttersprache)" },
    { id: "8_5_102", eng: "(to) swallow", phon: "['swɒləʊ]", ger: "(ver)schlucken", ctx: "verb" },
    { id: "8_5_103", eng: "synonym", phon: "['sɪnənɪm]", ger: "Synonym (Wort mit gleicher Bedeutung)", ctx: "Betonung auf der 1. Silbe!" },
    { id: "8_5_104", eng: "logging", phon: "['lɒɡɪŋ]", ger: "Abholzung", ctx: "Stop the logging of the rainforests!" },
    { id: "8_5_105", eng: "(to) contain", phon: "[kən'teɪn]", ger: "enthalten", ctx: "This chocolate contains nuts." }
];