const e9u1_data = [
    { id: "9_1_1", eng: "(to) explore", phon: "[ɪk'splɔː]", ger: "erforschen, erkunden", ctx: "Let's go for a walk and explore this village." },
    { id: "9_1_2", eng: "parrot", phon: "['pærət]", ger: "Papagei", ctx: "noun" },
    { id: "9_1_3", eng: "kangaroo", phon: "[ˌkæŋɡə'ruː]", ger: "Känguru", ctx: "noun" },
    { id: "9_1_4", eng: "crocodile", phon: "['krɒkədaɪl]", ger: "Krokodil", ctx: "Betonung auf der 1. Silbe!" },
    { id: "9_1_5", eng: "Tasmanian devil", phon: "[tæzˌmeɪniən 'devl]", ger: "Beutelteufel (Tierart)", ctx: "devil = Teufel" },
    { id: "9_1_6", eng: "camel", phon: "['kæml]", ger: "Kamel", ctx: "Betonung auf der 1. Silbe!" },
    { id: "9_1_7", eng: "the outback", phon: "['aʊtbæk]", ger: "das Hinterland Australiens", ctx: "far away from the coast and the towns." },
    { id: "9_1_8", eng: "(to) bite, bit, bitten", phon: "[baɪt], [bɪt], ['bɪtn]", ger: "beißen; stechen (z. B. Insekten)", ctx: "noun: bite = Biss, (Insekten-)Stich" },
    { id: "9_1_9", eng: "insect repellent", phon: "['ɪnsekt rɪˌpelənt]", ger: "Insektenschutzmittel", ctx: "insect = Insekt; repellent = Schutzmittel" },
    { id: "9_1_10", eng: "continent", phon: "['kɒntɪnənt]", ger: "Kontinent", ctx: "Betonung auf der 1. Silbe!" },
    { id: "9_1_11", eng: "convict", phon: "['kɒnvɪkt]", ger: "Sträfling", ctx: "somebody who has been sent to prison" },
    { id: "9_1_12", eng: "scuba-diving", phon: "['skuːbəˌdaɪvɪŋ]", ger: "Sporttauchen", ctx: "noun" },
    { id: "9_1_13", eng: "snorkelling", phon: "['snɔːkəlɪŋ]", ger: "Schnorcheln", ctx: "noun" },
    { id: "9_1_14", eng: "coral", phon: "['kɒrəl]", ger: "Koralle/n", ctx: "coral reef = Korallenriff; reef = Riff" },
    { id: "9_1_15", eng: "testimony (to)", phon: "['testɪməni]", ger: "(Zeugen-)Aussage; Beweis (für), Zeugnis", ctx: "thousands of happy customers are testimony to the quality" },
    { id: "9_1_16", eng: "(to) identify", phon: "[aɪ'dentɪfaɪ]", ger: "erkennen; (sich) identifizieren", ctx: "(to) identify yourself (as) = sich zu erkennen geben (als)" },
    { id: "9_1_17", eng: "Aboriginal", phon: "[ˌæbə'rɪdʒənl]", ger: "Aborigine- (die Ureinwohner/innen Australiens betreffend)", ctx: "Aboriginal culture / Aboriginal Australian" },
    { id: "9_1_18", eng: "people (pl. peoples)", phon: "['piːpl]", ger: "Volk", ctx: "💡 people = 1. Menschen (pl.); 2. Volk (sing.), peoples = Urvölker" },
    { id: "9_1_19", eng: "(to) dream (of/about sth.)", phon: "[driːm]", ger: "träumen (von etwas)", ctx: "According to Aboriginal culture, the 'Dreamtime' is the period when life began." },
    { id: "9_1_20", eng: "plant", phon: "[plɑːnt]", ger: "Pflanze", ctx: "verb: (to) plant = pflanzen" },
    { id: "9_1_21", eng: "(to) pass sth. on (to sb.)", phon: "[pɑːs]", ger: "etwas weitergeben (an jn.)", ctx: "(to) pass sth. down = etwas weitergeben, überliefern" },
    { id: "9_1_22", eng: "present", phon: "['preznt]", ger: "Gegenwart", ctx: "the past – the present – the future / also: present = Geschenk" },
    { id: "9_1_23", eng: "fellow", phon: "['feləʊ]", ger: "Mit-", ctx: "fellow passengers = Mitreisende; fellow students = Mitschüler" },
    { id: "9_1_24", eng: "(to) integrate", phon: "['ɪntɪɡreɪt]", ger: "(sich) integrieren", ctx: "Betonung auf der 1. Silbe!" },
    { id: "9_1_25", eng: "community", phon: "[kə'mjuːnəti]", ger: "Gemeinschaft, Gemeinde", ctx: "e.g., a big community of fans" },
    { id: "9_1_26", eng: "(to) bring sb. up", phon: "[brɪŋ]", ger: "jd. aufziehen, großziehen", ctx: "brought up / well-brought-up child = gut erzogenes Kind" },
    { id: "9_1_27", eng: "generation", phon: "[ˌdʒenə'reɪʃn]", ger: "Generation", ctx: "Betonung auf der vorletzten Silbe!" },
    { id: "9_1_28", eng: "(to) apologize (to sb. for sth.)", phon: "[ə'pɒlədʒaɪz]", ger: "sich (bei jm. für etwas) entschuldigen", ctx: "noun: apology = Entschuldigung" },
    { id: "9_1_29", eng: "(to) suffer (from)", phon: "['sʌfə]", ger: "leiden (an), erleiden", ctx: "suffer from headaches / suffered a heart attack / noun: suffering = Leid" },
    { id: "9_1_30", eng: "hurt", phon: "[hɜːt]", ger: "Schmerz; Kränkung", ctx: "verb: (to) hurt" },
    { id: "9_1_31", eng: "(to) break sth. up", phon: "[breɪk]", ger: "etwas zerbrechen, zerstören; auflösen", ctx: "(to) break up (with sb.) = sich von jm. trennen" },
    { id: "9_1_32", eng: "indignity", phon: "[ɪn'dɪɡnəti]", ger: "Demütigung, Erniedrigung", ctx: "plural: indignities" },
    { id: "9_1_33", eng: "(to) inflict sth. on sb.", phon: "[ɪn'flɪkt]", ger: "jm. etwas zufügen, etwas bei jm. verursachen", ctx: "how much hurt your behaviour inflicts on black people" },
    { id: "9_1_34", eng: "proud (of)", phon: "[praʊd]", ger: "stolz (auf)", ctx: "noun: pride = Stolz" },
    { id: "9_1_35", eng: "prime minister", phon: "[ˌpraɪm 'mɪnɪstə]", ger: "Premierminister/in", ctx: "Betonung auf der 1. Silbe bei 'minister'!" },
    { id: "9_1_36", eng: "welfare", phon: "['welfeə]", ger: "Sozialhilfe; Wohlfahrt, Fürsorge; Wohl(ergehen)", ctx: "lives on welfare / social welfare programmes" },
    { id: "9_1_37", eng: "(to) separate", phon: "['sepəreɪt]", ger: "trennen", ctx: "adjective: separate ['sepərət] = getrennt, separat" },
    { id: "9_1_38", eng: "nursery", phon: "['nɜːsəri]", ger: "Kinderzimmer; Kinderkrippe", ctx: "1. room where young children play/sleep; 2. place for daycare" },
    { id: "9_1_39", eng: "(to) cut sth. out", phon: "[kʌt]", ger: "mit etwas aufhören", ctx: "informal synonym: to stop (doing) sth." },
    { id: "9_1_40", eng: "life expectancy", phon: "['laɪf ɪkˌspektənsi]", ger: "Lebenserwartung", ctx: "the time a person is likely to live" },
    { id: "9_1_41", eng: "unemployment", phon: "[ˌʌnɪm'plɔɪmənt]", ger: "Arbeitslosigkeit", ctx: "opposite: employment" },
    { id: "9_1_42", eng: "canvas", phon: "['kænvəs]", ger: "Leinwand; Segeltuch", ctx: "You can paint on canvas." },
    { id: "9_1_43", eng: "(tree) bark", phon: "[bɑːk]", ger: "Baumrinde", ctx: "...or on tree bark." },
    { id: "9_1_44", eng: "(back) then", phon: "[bæk ðen]", ger: "damals", ctx: "💡 then = 1. dann, danach; 2. damals" },
    { id: "9_1_45", eng: "(to) encourage", phon: "[ɪn'kʌrɪdʒ]", ger: "ermutigen, ermuntern; unterstützen", ctx: "noun: encouragement" },
    { id: "9_1_46", eng: "permanent", phon: "['pɜːmənənt]", ger: "dauerhaft, Dauer-; fest; (be)ständig", ctx: "opposite: temporary / permanent tattoo" },
    { id: "9_1_47", eng: "dot", phon: "[dɒt]", ger: "Punkt, Pünktchen", ctx: "dot painting = Punktmalerei" },
    { id: "9_1_48", eng: "bright", phon: "[braɪt]", ger: "hell, freundlich; leuchtend", ctx: "opposite: dark" },
    { id: "9_1_49", eng: "use", phon: "[juːs]", ger: "Gebrauch, Verwendung", ctx: "💡 Pronunciation: verb: (to) use [juːz] – noun: use [juːs]" },
    { id: "9_1_50", eng: "(to) be in progress", phon: "[biː ɪn 'prəʊɡres]", ger: "im Gange sein", ctx: "e.g., Recording in progress!" },
    { id: "9_1_51", eng: "regular", phon: "['reɡjələ]", ger: "regelmäßig; gewohnt, normal", ctx: "opposite: irregular; adverb: regularly" },
    { id: "9_1_52", eng: "(to) come of age", phon: "[kʌm əv 'eɪdʒ]", ger: "volljährig werden", ctx: "meaning: to become an adult by law" },
    { id: "9_1_53", eng: "(to) confirm", phon: "[kən'fɜːm]", ger: "konfirmieren; firmen; bestätigen", ctx: "💡 confirm = 1. bestätigen; 2. konfirmieren; noun: confirmation" },
    { id: "9_1_54", eng: "Jewish", phon: "['dʒuːɪʃ]", ger: "jüdisch", ctx: "noun: Jew = Jude/Jüdin" },
    { id: "9_1_55", eng: "Muslim", phon: "['mʊzlɪm]", ger: "Muslim/Muslima; muslimisch", ctx: "My religion is Islam." },
    { id: "9_1_56", eng: "ceremony", phon: "['serəməni]", ger: "Feier, Zeremonie", ctx: "Betonung auf der 1. Silbe!" },
    { id: "9_1_57", eng: "discipline", phon: "['dɪsəplɪn]", ger: "Disziplin", ctx: "Betonung auf der 1. Silbe! verb: (to) discipline = disziplinieren" },
    { id: "9_1_58", eng: "they used to make ...", phon: "[ðeɪ 'juːst tuː]", ger: "sie haben (früher) immer ... gemacht", ctx: "expresses a past habit (I used to do a lot of sport.)" },
    { id: "9_1_59", eng: "mark", phon: "[mɑːk]", ger: "Markierung; Zeichen", ctx: "verb: (to) mark = kennzeichnen, markieren" },
    { id: "9_1_60", eng: "(to) return", phon: "[rɪ'tɜːn]", ger: "zurückkehren, zurückkommen", ctx: "noun: return = Rückkehr" },
    { id: "9_1_61", eng: "venom", phon: "['venəm]", ger: "Gift", ctx: "adjective: venomous = giftig (bei Tieren; Gift für Pflanzen/Chemikalien = poison)" },
    { id: "9_1_62", eng: "creature", phon: "['kriːtʃə]", ger: "Geschöpf, (Lebe-)Wesen", ctx: "Betonung auf der 1. Silbe!" },
    { id: "9_1_63", eng: "snail", phon: "[sneɪl]", ger: "Schnecke", ctx: "noun" },
    { id: "9_1_64", eng: "backyard (AE)", phon: "[ˌbæk'jɑːd]", ger: "(Hinter-)Hof; Garten hinter dem Haus", ctx: "💡 AE yard/backyard vs. BE garden" },
    { id: "9_1_65", eng: "anti-", phon: "['ænti]", ger: "Anti-, Gegen-", ctx: "anti-discrimination laws / antivenom = Gegengift" },
    { id: "9_1_66", eng: "jellyfish (pl. jellyfish)", phon: "['dʒelɪfɪʃ]", ger: "Qualle", ctx: "💡 Plural form can stay the same!" },
    { id: "9_1_67", eng: "sting", phon: "[stɪŋ]", ger: "(Insekten-)Stich", ctx: "verb: (to) sting, stung, stung = stechen, brennen" },
    { id: "9_1_68", eng: "immediately", phon: "[ɪ'miːdiətli]", ger: "sofort, umgehend, unmittelbar", ctx: "adjective: immediate" },
    { id: "9_1_69", eng: "vinegar", phon: "['vɪnɪɡə]", ger: "Essig", ctx: "oil and vinegar for your salad" },
    { id: "9_1_70", eng: "octopus (pl. octopuses)", phon: "['ɒktəpəs]", ger: "Oktopus, Tintenfisch", ctx: "a sea creature with eight arms" },
    { id: "9_1_71", eng: "paralysis (pl. paralyses)", phon: "[pə'ræləsɪs], [pə'ræləsiːz]", ger: "Lähmung", ctx: "suffered paralysis in her legs" },
    { id: "9_1_72", eng: "tick", phon: "[tɪk]", ger: "Zecke", ctx: "noun" },
    { id: "9_1_73", eng: "oval", phon: "['əʊvl]", ger: "oval", ctx: "Betonung auf der 1. Silbe!" },
    { id: "9_1_74", eng: "(to) suck", phon: "[sʌk]", ger: "saugen", ctx: "Mosquitoes bite you and suck your blood." },
    { id: "9_1_75", eng: "tweezers (pl.)", phon: "['twiːzəz]", ger: "Pinzette", ctx: "plural noun" },
    { id: "9_1_76", eng: "friendliness", phon: "['frendlinəs]", ger: "Freundlichkeit", ctx: "adjective: friendly" },
    { id: "9_1_77", eng: "informal", phon: "[ɪn'fɔːml]", ger: "informell, locker", ctx: "opposite: formal" },
    { id: "9_1_78", eng: "(to) shorten", phon: "['ʃɔːtn]", ger: "(ver)kürzen", ctx: "adjective: short" },
    { id: "9_1_79", eng: "mate", phon: "[meɪt]", ger: "Freund/in, Kumpel", ctx: "informal" },
    { id: "9_1_80", eng: "cheers", phon: "[tʃɪəz]", ger: "tschüs; danke; prost", ctx: "informal (e.g., Cheers, mate!)" },
    { id: "9_1_81", eng: "cereal(s)", phon: "['sɪəriəlz]", ger: "Getreide-, Frühstücksflocken", ctx: "breakfast cereals" },
    { id: "9_1_82", eng: "detention centre", phon: "[dɪ'tenʃn ˌsentə]", ger: "Auffanglager, Haftanstalt (für Abschiebehaft)", ctx: "💡 detention = 1. Haft; 2. Nachsitzen (in der Schule); verb: (to) detain" },
    { id: "9_1_83", eng: "(to) criticize", phon: "['krɪtɪsaɪnz]", ger: "kritisieren", ctx: "Betonung auf der 1. Silbe!" },
    { id: "9_1_84", eng: "(to) drown", phon: "[draʊn]", ger: "ertrinken", ctx: "to die because you're underwater for too long" },
    { id: "9_1_85", eng: "conflict", phon: "['kɒnflɪkt]", ger: "Konflikt, Auseinandersetzung, Streit", ctx: "Betonung auf der 1. Silbe!" },
    { id: "9_1_86", eng: "corner", phon: "['kɔːnə]", ger: "Ecke", ctx: "e.g., the four corners of this room" },
    { id: "9_1_87", eng: "policy", phon: "['pɒləsi]", ger: "Politik, Richtlinie(n), Bestimmung(en)", ctx: "e.g., a 'no junk food'-policy" },
    { id: "9_1_88", eng: "whatever", phon: "[wɒt'evə]", ger: "was (auch) (immer)", ctx: "We will help you, whatever happens." },
    { id: "9_1_89", eng: "illegal", phon: "[ɪ'liːɡl]", ger: "illegal, verboten; Ilgale/r", ctx: "opposite: legal ['liːɡl]" },
    { id: "9_1_90", eng: "forever", phon: "[fər'evə]", ger: "für immer, ewig (lange)", ctx: "spelled forever or for ever" },
    { id: "9_1_91", eng: "difficulty", phon: "['dɪfɪkəlti]", ger: "Schwierigkeit(en)", ctx: "adjective: difficult" },
    { id: "9_1_92", eng: "hut", phon: "[hʌt]", ger: "Hütte", ctx: "meaning: a small and very simple house" },
    { id: "9_1_93", eng: "(to) dry", phon: "[draɪ]", ger: "(ab)trocknen", ctx: "adjective: dry = trocken" },
    { id: "9_1_94", eng: "expert", phon: "['ekspɜːt]", ger: "Experte, Expertin", ctx: "Betonung auf der 1. Silbe!" },
    { id: "9_1_95", eng: "operation", phon: "[ˌɒpə'reɪʃn]", ger: "Operation, Einsatz", ctx: "verb: (to) operate = bedienen, operieren" },
    { id: "9_1_96", eng: "(to) get id of sth.", phon: "[ɡet 'rɪd ɒv]", ger: "etwas loswerden", ctx: "I should get rid of my car." },
    { id: "9_1_97", eng: "textbook", phon: "['tekstbʊk]", ger: "Schulbuch, Lehrbuch", ctx: "noun" },
    { id: "9_1_98", eng: "(to) photocopy", phon: "['fəʊtəʊˌkɒpi]", ger: "fotokopieren", ctx: "noun: photocopy = Fotokopie" },
    { id: "9_1_99", eng: "current affairs (pl.)", phon: "[ˌkʌrənt ə'feəz]", ger: "Tagespolitik, aktuelle Ereignisse", ctx: "current = aktuell; affair = Angelegenheit" },
    { id: "9_1_100", eng: "course", phon: "[kɔːs]", ger: "Kurs(us)", ctx: "crash course = Intensivkurs" },
    { id: "9_1_101", eng: "(to) realize sth.", phon: "['rɪəlaɪz]", ger: "etwas erkennen, sich einer Sache bewusst werden", ctx: "noun: realization [ˌrɪəlaɪ'zeɪʃn]" },
    { id: "9_1_102", eng: "council", phon: "['kaʊnsl]", ger: "Ausschuss; Rat (z. B. Gemeinderat, Stadtrat)", ctx: "the town council = government of the town" },
    { id: "9_1_103", eng: "false", phon: "[fɔːls]", ger: "falsch, unrichtig", ctx: "meaning: not true, not real" },
    { id: "9_1_104", eng: "long-term", phon: "[ˌlɒŋ 'tɜːm]", ger: "langfristig, Langzeit-", ctx: "medium-term = mittelfristig; short-term = kurzfristig" },
    { id: "9_1_105", eng: "We recommend that you go ...", phon: "[rekə'mend]", ger: "Wir empfehlen, dass Sie ... gehen.", ctx: "💡 structure: recommend + that-clause / recommend + -ing" },
    { id: "9_1_106", eng: "authority", phon: "[ɔː'θɒrəti]", ger: "Behörde", ctx: "local authority = Gemeinde(behörde), Kommune" },
    { id: "9_1_107", eng: "a while", phon: "[ə waɪl]", ger: "eine Weile, einige Zeit", ctx: "💡 while = 1. während (conj.); 2. Weile (noun)" },
    { id: "9_1_108", eng: "(to) soak sth. up", phon: "[səʊk 'ʌp]", ger: "etwas aufsaugen, in sich aufnehmen", ctx: "they will soak up everything they hear" },
    { id: "9_1_109", eng: "(to) squint", phon: "[skwɪnt]", ger: "blinzeln, (die Augen) zusammenkneifen, spähen", ctx: "look with your eyes only half open" },
    { id: "9_1_110", eng: "campaign", phon: "[kæm'peɪn]", ger: "Aktion, Kampagne", ctx: "verb: (to) campaign (for/against) = sich einsetzen/kämpfen" },
    { id: "9_1_111", eng: "Lord Mayor", phon: "[ˌlɔːd 'meə]", ger: "Oberbürgermeister/in", ctx: "title of the mayor in some big cities" },
    { id: "9_1_112", eng: "(to) deny", phon: "[dɪ'naɪ]", ger: "leugnen, bestreiten", ctx: "noun: denial = Leugnen, Dementi" },
    { id: "9_1_113", eng: "(to) ignore", phon: "[ɪɡ'nɔː]", ger: "nicht beachten, ignorieren", ctx: "noun: ignorance (of/about sth.) = Unwissenheit" },
    { id: "9_1_114", eng: "accent", phon: "['æksənt]", ger: "Akzent", ctx: "Betonung auf der 1. Silbe!" },
    { id: "9_1_115", eng: "riddle", phon: "['rɪdl]", ger: "Rätsel", ctx: "These riddles are really difficult to solve." },
    { id: "9_1_116", eng: "direct", phon: "[də'rekt]", ger: "direkt, unmittelbar", ctx: "opposite: indirect [ˌɪndə'rekt]" },
    { id: "9_1_117", eng: "plains (pl.)", phon: "[pleɪnz]", ger: "Ebene", ctx: "noun" },
    { id: "9_1_118", eng: "(to) bear, bore, borne", phon: "[beə], [bɔː], [bɔːn]", ger: "ertragen, aushalten; tragen", ctx: "I can't bear this pain much longer. / Who bore the responsibility?" },
    { id: "9_1_119", eng: "perfect", phon: "['pɜːfɪkt]", ger: "perfekt", ctx: "Betonung auf der 1. Silbe! (perfectly still = völlig ruhig)" },
    { id: "9_1_120", eng: "calm", phon: "[kɑːm]", ger: "ruhig, besonnen", ctx: "verb: (to) calm (down) = sich beruhigen / jn. beruhigen" },
    { id: "9_1_121", eng: "point of view", phon: "[ˌpɔɪnt əv 'vjuː]", ger: "Standpunkt, Meinung; Perspektive", ctx: "meaning: way of seeing things, opinion" },
    { id: "9_1_122", eng: "tournament", phon: "['tʊənəmənt]", ger: "Turnier, Wettkampf", ctx: "a sports competition where teams take part" },
    { id: "9_1_123", eng: "congratulations (on sth.)", phon: "[kənˌɡrætʃu'leɪʃnz]", ger: "herzlichen Glückwunsch (zu etwas)", ctx: "verb: (to) congratulate sb. on sth." },
    { id: "9_1_124", eng: "anyway", phon: "['eniweɪ]", ger: "trotzdem; sowieso; jedenfalls", ctx: "💡 anyway = 1. trotzdem; 2. sowieso / jedenfalls" },
    { id: "9_1_125", eng: "collocation", phon: "[ˌkɒlə'keɪʃn]", ger: "Kollokation (inhaltlich kombinierbare sprachliche Einheiten)", ctx: "e.g., 'strong rain' vs. correct collocation 'heavy rain'" },
    { id: "9_1_126", eng: "athletics", phon: "[æθ'letɪks]", ger: "Leichtathletik", ctx: "sports such as running, jumping and throwing" },
    { id: "9_1_127", eng: "amateur", phon: "['æmətə]", ger: "Amateur/in; Amateur-, Hobby-", ctx: "Betonung auf der 1. Silbe! (opposite: professional)" },
    { id: "9_1_128", eng: "venue", phon: "['venjuː]", ger: "Veranstaltungsort, Veranstaltungsstätte", ctx: "place where concerts or sports events take place" },
    { id: "9_1_129", eng: "antonym", phon: "['æntənɪm]", ger: "Antonym, Gegenteil", ctx: "synonym vs. antonym" },
    { id: "9_1_130", eng: "idiom", phon: "['ɪdiəm]", ger: "Redewendung", ctx: "e.g., 'That's not my cup of tea' is a nice English idiom." },
    { id: "9_1_131", eng: "It's your turn.", phon: "[tɜːn]", ger: "Du bist dran. / Du bist an der Reihe.", ctx: "It was my turn to ask a question." },
    { id: "9_1_132", eng: "explanation", phon: "[ˌeksplə'neɪʃn]", ger: "Erklärung", ctx: "verb: (to) explain" },
    { id: "9_1_133", eng: "spectator", phon: "[spek'teɪtə]", ger: "Zuschauer/in", ctx: "somebody who watches a (sports) event" },
    { id: "9_1_134", eng: "goalpost", phon: "['ɡəʊlpəʊst]", ger: "Torfosten", ctx: "post = Pfosten, Pfahl" },
    { id: "9_1_135", eng: "mouthguard (AE)", phon: "['maʊθɡɑːd]", ger: "Mundschutz (Sport)", ctx: "British English: gumshield ['ɡʌmʃiːld]" },
    { id: "9_1_136", eng: "headguard", phon: "['hedɡɑːd]", ger: "Kopfschutz (Sport)", ctx: "noun" },
    { id: "9_1_137", eng: "(to) kick", phon: "[kɪk]", ger: "treten; (Sport) schießen", ctx: "noun: kick = Tritt, Stoß" },
    { id: "9_1_138", eng: "fist", phon: "[fɪst]", ger: "Faust", ctx: "noun" }
];