const e9u2_data = [
    { id: "9_2_1", eng: "part-time", phon: "[pɑːt 'taɪm]", ger: "Teilzeit-, Halbtags-", ctx: "He has a part-time job. (opposite: full-time)" },
    { id: "9_2_2", eng: "abroad", phon: "[ə'brɔːd]", ger: "im/ins Ausland", ctx: "meaning: in or to another country" },
    { id: "9_2_3", eng: "job advertisement", phon: "[dʒɒb əd'vɜːtɪsmənt]", ger: "Stellenanzeige", ctx: "short form: job advert" },
    { id: "9_2_4", eng: "CV (curriculum vitae)", phon: "[ˌsiː 'viː], [kəˌrɪkjʊləm 'viːtaɪ]", ger: "Lebenslauf", ctx: "At the age of 15, your CV is probably not very long." },
    { id: "9_2_5", eng: "cover letter", phon: "['kʌvə ˌletə]", ger: "Anschreiben, Begleitschreiben, Motivationsschreiben", ctx: "a letter that you send with your CV" },
    { id: "9_2_6", eng: "automation", phon: "[ˌɔːtə'meɪʃn]", ger: "Automatisierung", ctx: "The work he used to do is now done by a machine." },
    { id: "9_2_7", eng: "technique", phon: "[tek'niːk]", ger: "Methode, Technik", ctx: "💡 Achte auf die Betonung auf der 2. Silbe!" },
    { id: "9_2_8", eng: "work experience", phon: "['wɜːk ɪkˌspɪərɪəns]", ger: "Arbeitserfahrung(en), Praxiserfahrung(en); Praktikum", ctx: "to do some work experience" },
    { id: "9_2_9", eng: "high school (AE)", phon: "['haɪ skuːl]", ger: "(USA) Schule für 14- bis 18-Jährige", ctx: "school for young people between 14 and 18" },
    { id: "9_2_10", eng: "fee", phon: "[fiː]", ger: "Gebühr; Honorar; (Mitglieds-)Beitrag", ctx: "money you pay e.g. for club membership or services" },
    { id: "9_2_11", eng: "fund", phon: "[fʌnd]", ger: "Fonds; Geldmittel", ctx: "verb: (to) fund = finanzieren" },
    { id: "9_2_12", eng: "expenses (pl.)", phon: "[ɪk'spensɪz]", ger: "Kosten; Spesen", ctx: "living expenses = Lebenshaltungskosten; travelling expenses = Reisekosten" },
    { id: "9_2_13", eng: "loan", phon: "[ləʊn]", ger: "Darlehen, Kredit", ctx: "(to) take out a loan = einen Kredit aufnehmen" },
    { id: "9_2_14", eng: "training course", phon: "['treɪnɪŋ kɔːs]", ger: "Ausbildung(sgang)", ctx: "Do you want to go to university or start a training course?" },
    { id: "9_2_15", eng: "cashier", phon: "[kæ'ʃɪə]", ger: "Kassierer/in", ctx: "noun" },
    { id: "9_2_16", eng: "(to) walk a dog", phon: "[wɔːk]", ger: "mit einem Hund spazieren gehen", ctx: "dog walking = Hunde ausführen; dog walker = Hundeausführer/in" },
    { id: "9_2_17", eng: "secondary school", phon: "['sekəndri skuːl]", ger: "weiterführende Schule", ctx: "school for young people between the ages of 11 and 16 or 18" },
    { id: "9_2_18", eng: "childcare", phon: "['tʃaɪldkeə]", ger: "Kinderbetreuung", ctx: "Our company offers childcare for our children." },
    { id: "9_2_19", eng: "conservation", phon: "[ˌkɒnsə'veɪʃn]", ger: "(Natur-)Schutz; Erhaltung, Bewahrung", ctx: "verb: (to) conserve = schützen, erhalten" },
    { id: "9_2_20", eng: "internship", phon: "['ɪntɜːnʃɪp]", ger: "Praktikum", ctx: "synonym: work experience; person: intern = Praktikant/in" },
    { id: "9_2_21", eng: "apprenticeship", phon: "[ə'prentɪsʃɪp]", ger: "Ausbildung, Lehre", ctx: "person: apprentice = Lehrling, Auszubildende/r" },
    { id: "9_2_22", eng: "(to) jump at sth.", phon: "[dʒʌmp]", ger: "bei etwas sofort zugreifen, (Gelegenheit) sofort ergreifen", ctx: "e.g., jump at the offer" },
    { id: "9_2_23", eng: "accommodation", phon: "[əˌkɒmə'deɪʃn]", ger: "Unterkunft; Wohnung, Zimmer", ctx: "We need cheap accommodation in Paris." },
    { id: "9_2_24", eng: "host", phon: "[həʊst]", ger: "Gastgeber/in", ctx: "host family = Gastfamilie" },
    { id: "9_2_25", eng: "(to) get along (with sb.)", phon: "[ɡet ə'lɒŋ]", ger: "(gut) auskommen (mit jm.), sich (gut) verstehen (mit jm.)", ctx: "I get along well with my sister." },
    { id: "9_2_26", eng: "(to) get used to", phon: "[get 'juːst tuː]", ger: "sich gewöhnen an", ctx: "💡 structure: get used to + -ing (We got used to driving on the left.)" },
    { id: "9_2_27", eng: "(to) give (sth.) up", phon: "[ɡɪv 'ʌp]", ger: "(etwas) aufgeben, aufhören (mit etwas)", ctx: "give up buying things / give up your seat = für jn. aufstehen" },
    { id: "9_2_28", eng: "(to) keep / stay in contact (with)", phon: "[kɪːp], [steɪ]", ger: "in Kontakt bleiben (mit)", ctx: "We really wanted to stay in contact." },
    { id: "9_2_29", eng: "sloth", phon: "[sləʊθ]", ger: "Faultier", ctx: "noun" },
    { id: "9_2_30", eng: "deforestation", phon: "[ˌdiːˌfɒrɪ'steɪʃn]", ger: "Abholzung, Entwaldung", ctx: "There's a lot of deforestation in this area." },
    { id: "9_2_31", eng: "rainforest", phon: "['reɪnfɒrɪst]", ger: "Regenwald", ctx: "thick forests in hot parts of the world" },
    { id: "9_2_32", eng: "(to) convince", phon: "[kən'vɪns]", ger: "überzeugen", ctx: "adjective: convincing = überzeugend; convinced = überzeugt" },
    { id: "9_2_33", eng: "(to) let, let, let", phon: "[let]", ger: "lassen", ctx: "His parents let him go. = They allowed him to go." },
    { id: "9_2_34", eng: "even though", phon: "['iːvn ðəʊ]", ger: "auch wenn, obwohl (betont)", ctx: "He's world-famous, even though he isn't really an artist." },
    { id: "9_2_35", eng: "vaccination", phon: "[ˌvæksɪ'neɪʃn]", ger: "(Schutz-)Impfung", ctx: "Protect you against several dangerous diseases." },
    { id: "9_2_36", eng: "both ... and ...", phon: "[bəʊθ ... ænd]", ger: "sowohl ... als auch ...", ctx: "I like both Anne and Julia." },
    { id: "9_2_37", eng: "(to) check sb./sth. out", phon: "[tʃek 'aʊt]", ger: "sich etwas anschauen, anhören; etwas ausprobieren", ctx: "informal (e.g., I must check out the band.)" },
    { id: "9_2_38", eng: "scam", phon: "[skæm]", ger: "Schwindel, Betrug", ctx: "Sold online? Forget it. I'm sure it's a scam." },
    { id: "9_2_39", eng: "welcome", phon: "['welkəm]", ger: "Empfang; Willkommen", ctx: "to give sb. a warm welcome / verb: (to) welcome sb." },
    { id: "9_2_40", eng: "(to) carry on with sth. / doing sth.", phon: "['kæri ɒn]", ger: "weitermachen, fortfahren (mit etwas)", ctx: "I carried on with my work. / I carried on working." },
    { id: "9_2_41", eng: "occasional", phon: "[ə'keɪʒənl]", ger: "gelegentliche(r, s)", ctx: "adverb: occasionally (ab und zu); noun: occasion = Gelegenheit" },
    { id: "9_2_42", eng: "donkey", phon: "['dɒŋki]", ger: "Esel", ctx: "noun" },
    { id: "9_2_43", eng: "expat", phon: "['ekspæt]", ger: "im Ausland Lebende/r; im Ausland lebend", ctx: "informal for: expatriate [eks'pætriət]" },
    { id: "9_2_44", eng: "(to) attract", phon: "[ə'trækt]", ger: "anziehen, anlocken", ctx: "adjective: attractive; noun: attraction = Anziehungskraft" },
    { id: "9_2_45", eng: "certain", phon: "['sɜːtn]", ger: "gewiss, bestimmt; sicher", ctx: "It is certain that... / A certain Mr Miller... / adverb: certainly" },
    { id: "9_2_46", eng: "honest", phon: "['ɒnɪst]", ger: "ehrlich", ctx: "adverb: honestly; noun: honesty = Ehrlichkeit (The 'h' is silent!)" },
    { id: "9_2_47", eng: "punctual", phon: "['pʌŋktʃuəl]", ger: "pünktlich", ctx: "synonym: on time" },
    { id: "9_2_48", eng: "teabag", phon: "['tiːbæɡ]", ger: "Teebeutel", ctx: "noun" },
    { id: "9_2_49", eng: "habit", phon: "['hæbɪt]", ger: "(An-)Gewohnheit", ctx: "something you do regularly" },
    { id: "9_2_50", eng: "photography", phon: "[fə'tɒɡrəfi]", ger: "Fotografie (Hobby), (das) Fotografieren", ctx: "💡 Achte auf die Betonung auf der 2. Silbe!" },
    { id: "9_2_51", eng: "Good luck.", phon: "[ɡʊd 'lʌk]", ger: "Viel Glück!", ctx: "noun: luck; adjective: lucky; adverb: luckily" },
    { id: "9_2_52", eng: "prediction", phon: "[prɪ'dɪkʃn]", ger: "Vorhersage, Voraussage", ctx: "make a prediction / verb: (to) predict" },
    { id: "9_2_53", eng: "spontaneous", phon: "[spɒn'teɪniəs]", ger: "spontan", ctx: "adverb: spontaneously" },
    { id: "9_2_54", eng: "first aid", phon: "[ˌfɜːst 'eɪd]", ger: "Erste Hilfe", ctx: "💡 first-aid certificate = Erste-Hilfe-Schein" },
    { id: "9_2_55", eng: "foreign", phon: "['fɒrən]", ger: "ausländisch; fremd", ctx: "from another country / foreign language = Fremdsprache" },
    { id: "9_2_56", eng: "(to) deal with sb./sth., dealt, dealt", phon: "[diːl], [delt]", ger: "sich um jn./etwas kümmern, sich mit jm./einer Sache befassen", ctx: "The film deals with the life of John Lennon." },
    { id: "9_2_57", eng: "helpful", phon: "['helpfl]", ger: "hilfsbereit; hilfreich, nützlich", ctx: "She was really helpful." },
    { id: "9_2_58", eng: "organizational", phon: "[ˌɔːɡənaɪ'zeɪʃənl]", ger: "organisatorisch", ctx: "verb: (to) organize; noun: organization" },
    { id: "9_2_59", eng: "personal statement", phon: "['pɜːsənl 'steɪtmənt]", ger: "persönliche Beschreibung, Selbstbeschreibung", ctx: "statement = Aussage(satz)" },
    { id: "9_2_60", eng: "communication", phon: "[kəˌmjuːnɪ'keɪʃn]", ger: "Kommunikation, Verständigung", ctx: "verb: (to) communicate" },
    { id: "9_2_61", eng: "decision-making", phon: "['dɪsɪʒn ˌmeɪkɪŋ]", ger: "Entscheidungsfindung", ctx: "decision-making skills = Entscheidungsfähigkeit" },
    { id: "9_2_62", eng: "tool", phon: "[tuːl]", ger: "Werkzeug; (Hilfs-)Mittel", ctx: "noun" },
    { id: "9_2_63", eng: "strength", phon: "[streŋθ]", ger: "Stärke, Kraft", ctx: "opposite: weakness / strong vs. weak" },
    { id: "9_2_64", eng: "flexible", phon: "['fleksəbl]", ger: "flexibel", ctx: "💡 Achte auf die Betonung auf der 1. Silbe!" },
    { id: "9_2_65", eng: "working hours (pl.)", phon: "['wɜːkɪŋ ˌaʊəz]", ger: "Arbeitszeit(en)", ctx: "opening hours = Öffnungszeiten; work long hours = lange arbeiten" },
    { id: "9_2_66", eng: "reservation", phon: "[ˌrezə'veɪʃn]", ger: "Reservierung, Buchung", ctx: "verb: (to) reserve" },
    { id: "9_2_67", eng: "staff", phon: "[stɑːf]", ger: "Personal, Belegschaft; Kollegium (Schule)", ctx: "staff manager = Personalchef/in" },
    { id: "9_2_68", eng: "attn (= for the attention of)", phon: "[ə'tenʃn]", ger: "zu Händen / z. Hd.", ctx: "You can write to your local council, attn Ms Eve Miller." },
    { id: "9_2_69", eng: "(to) require", phon: "[rɪ'kwaɪə]", ger: "erfordern, benötigen", ctx: "noun: requirement = Voraussetzung, Anforderung" },
    { id: "9_2_70", eng: "patience", phon: "['peɪʃns]", ger: "Geduld", ctx: "adjective: patient" },
    { id: "9_2_71", eng: "(to) attach (to)", phon: "[ə'tætʃ]", ger: "anfügen; anhängen (an) (Brief, E-Mail)", ctx: "noun: attachment = Anhang" },
    { id: "9_2_72", eng: "(to) provide", phon: "[prə'vaɪd]", ger: "(an)bieten, zur Verfügung stellen", ctx: "Food and accommodation provided." },
    { id: "9_2_73", eng: "reference", phon: "['refrəns]", ger: "Referenz, Empfehlung; jd., der eine Referenz erteilt", ctx: "I gave my coach as a reference." },
    { id: "9_2_74", eng: "greeting", phon: "['ɡriːtɪŋ]", ger: "Gruß(formel), Begrüßung", ctx: "Greetings from Inverness!" },
    { id: "9_2_75", eng: "(to) sign", phon: "[saɪn]", ger: "unterschreiben", ctx: "💡 Achte auf den Unterschied zum Nomen: sign = Schild, Zeichen!" },
    { id: "9_2_76", eng: "introductory", phon: "[ˌɪntrə'dʌktəri]", ger: "einführend, einleitend", ctx: "noun: introduction; verb: (to) introduce" },
    { id: "9_2_77", eng: "available", phon: "[ə'veɪləbl]", ger: "verfügbar; erhältlich; (Stelle) frei", ctx: "to be available = zur Verfügung stehen, Zeit haben" },
    { id: "9_2_78", eng: "lifeguard", phon: "['laɪfɡɑːd]", ger: "Rettungsschwimmer/in; Bademeister/in", ctx: "The lifeguards watch people who are swimming." },
    { id: "9_2_79", eng: "life-saving", phon: "['laɪf ˌseɪvɪŋ]", ger: "Rettungsschwimmen", ctx: "the skills you need to save people from drowning" },
    { id: "9_2_80", eng: "(to) arrange", phon: "[ə'reɪndʒ]", ger: "arrangieren, planen; (an)ordnen", ctx: "noun: arrangement" },
    { id: "9_2_81", eng: "(job) interview", phon: "[dʒɒb 'ɪntəvjuː]", ger: "Vorstellungsgespräch", ctx: "💡 interview = 1. Interview; 2. Vorstellungsgespräch" },
    { id: "9_2_82", eng: "approximately", phon: "[ə'prɒksɪmətli]", ger: "ungefähr", ctx: "short form: approx" },
    { id: "9_2_83", eng: "(to) attend", phon: "[ə'tend]", ger: "(hin)gehen zu, teilnehmen (an); besuchen", ctx: "attend a school = to go to a school" },
    { id: "9_2_84", eng: "(to) ensure", phon: "[ɪn'ʃʊə]", ger: "sicherstellen, gewährleisten", ctx: "meaning: to make sure" },
    { id: "9_2_85", eng: "(to) inform sb. (about/of sth.)", phon: "[ɪn'fɔːm]", ger: "jn. (über etwas) informieren", ctx: "We'd like to inform you of some changes." },
    { id: "9_2_86", eng: "(to) receive", phon: "[rɪ'siːv]", ger: "erhalten, empfangen", ctx: "a more formal word for 'get'" },
    { id: "9_2_87", eng: "suitable (for)", phon: "['suːtəbl]", ger: "geeignet, passend (für)", ctx: "Shorts aren't suitable clothes for a job interview." },
    { id: "9_2_88", eng: "(to) catch sth.", phon: "[kætʃ]", ger: "verstehen (hören können), mitbekommen", ctx: "💡 catch = 1. verstehen, mitbekommen; 2. (ein)fangen; erwischen" },
    { id: "9_2_89", eng: "professor (of)", phon: "[prə'fesə]", ger: "Professor/in (für)", ctx: "She's a professor of medicine." },
    { id: "9_2_90", eng: "biochemistry", phon: "[ˌbaɪəʊ'kemɪstri]", ger: "Biochemie", ctx: "💡 Achte auf die Betonung auf der 3. Silbe! (adjective: biochemical)" },
    { id: "9_2_91", eng: "diary", phon: "['daɪəri]", ger: "Tagebuch; Kalender", ctx: "keep a diary = Tagebuch führen" },
    { id: "9_2_92", eng: "(to) turn (over) the page(s)", phon: "[tɜːn]", ger: "umblättern (in einem Buch)", ctx: "phrase" },
    { id: "9_2_93", eng: "crinkly", phon: "['krɪŋkli]", ger: "zerknittert; faltig (Haut)", ctx: "crinkly paper" },
    { id: "9_2_94", eng: "(to) be supposed to be/do sth.", phon: "[sə'pəʊzd]", ger: "etwas sein sollen / etwas tun sollen", ctx: "We're not supposed to eat in class." },
    { id: "9_2_95", eng: "waste", phon: "[weɪst]", ger: "Verschwendug", ctx: "This is a waste of time. / verb: (to) waste" },
    { id: "9_2_96", eng: "(to) guess", phon: "[ɡes]", ger: "(er)raten", ctx: "Guess what! = Rate mal, was... / Ich nehme an...; noun: guess = Vermutung" },
    { id: "9_2_97", eng: "television", phon: "['telɪvɪʒn]", ger: "Fernsehen", ctx: "short form: TV" },
    { id: "9_2_98", eng: "attic", phon: "['ætɪk]", ger: "Dachboden", ctx: "💡 Idiom-Unterschied: English: *in* the attic – German: *auf* dem Dachboden!" },
    { id: "9_2_99", eng: "more than ever", phon: "[mɔː ðæn 'evə]", ger: "mehr als jemals zuvor", ctx: "We need environment-friendly forms of transport more than ever!" },
    { id: "9_2_100", eng: "mechanical", phon: "[mɪ'kænɪkl]", ger: "mechanisch, Maschinen-", ctx: "The plane had mechanical problems." },
    { id: "9_2_101", eng: "inspector", phon: "[ɪn'spektə]", ger: "Inspektor/in, Kontrolleur/in", ctx: "The safety inspector checked the plane." },
    { id: "9_2_102", eng: "He knew how to put it together again all right.", phon: "[ɔːl raɪt]", ger: "Er wusste sehr wohl / zu gut, wie man es wieder zusammenbaut.", ctx: "all right = hier: sehr wohl, zu gut" },
    { id: "9_2_103", eng: "large", phon: "[lɑːdʒ]", ger: "groß", ctx: "💡 Nicht für Personen! People are tall (groß), big (dick) or great (bedeutend)." },
    { id: "9_2_104", eng: "ugly", phon: "['ʌɡli]", ger: "hässlich", ctx: "meaning: not nice to look at" },
    { id: "9_2_105", eng: "slot", phon: "[slɒt]", ger: "Schlitz, Öffnung; (Karten-)Einzug", ctx: "putting a card in a slot" },
    { id: "9_2_106", eng: "test paper", phon: "['test ˌpeɪpə]", ger: "Prüfungsarbeit", ctx: "The teacher collected all our test papers." },
    { id: "9_2_107", eng: "(to) write sth. out", phon: "[raɪt]", ger: "etwas ausstellen, (ins Reine) schreiben", ctx: "write out a confirmation for you" },
    { id: "9_2_108", eng: "(to) punch", phon: "[pʌntʃ]", ger: "lochen, stanzen", ctx: "punch code = Stanzcode" },
    { id: "9_2_109", eng: "(to) calculate", phon: "['kælkjʊleɪt]", ger: "berechnen, kalkulieren", ctx: "Let's calculate how much money we'll need." },
    { id: "9_2_110", eng: "mark", phon: "[mɑːk]", ger: "(Schul-)Note, Zensur", ctx: "💡 mark = 1. Schulnote; 2. Markierung, Zeichen; 3. verb: kennzeichnen" },
    { id: "9_2_111", eng: "sector", phon: "['sektə]", ger: "Sektor, Bereich", ctx: "meaning: a part, a (certain) area" },
    { id: "9_2_112", eng: "(to) slow sb./sth. down", phon: "[sləʊ]", ger: "jn./etwas langsamer machen, jn. aufhalten, etwas verlangsamen", ctx: "verb or adjective: slow" },
    { id: "9_2_113", eng: "satisfactory", phon: "[ˌsætɪs'fæktəri]", ger: "zufriedenstellend", ctx: "meaning: OK, good enough" },
    { id: "9_2_114", eng: "altogether", phon: "[ˌɔːltə'ɡeðə]", ger: "insgesamt", ctx: "e.g., £6 info altogether (macht zusammen...)" },
    { id: "9_2_115", eng: "superior (to sb./sth.)", phon: "[suː'pɪəriə]", ger: "(jm./einer Sache) überlegen; hervorragend", ctx: "superior apartments (Werbesprache) / superior to the older model" },
    { id: "9_2_116", eng: "(to) adjust (to)", phon: "[ə'dʒʌst]", ger: "(sich) einstellen (auf); (sich) anpassen (an)", ctx: "adjust to living without a car" },
    { id: "9_2_117", eng: "just the same / all the same", phon: "[dʒʌst ðə seɪm]", ger: "trotzdem", ctx: "It's raining, but I'll go by bike all the same." },
    { id: "9_2_118", eng: "this way / that way", phon: "[ðɪs weɪ]", ger: "so, auf diese/jene Art", ctx: "phrase" },
    { id: "9_2_119", eng: "right next to ...", phon: "[raɪt nekst tuː]", ger: "gleich/direkt neben ...", ctx: "💡 right = 1. richtig; 2. nach rechts; 3. das Recht; 4. gleich, direkt (Adverb)" },
    { id: "9_2_120", eng: "(to) be on", phon: "[biː ɒn]", ger: "an sein (eingeschaltet)", ctx: "The light is still on. (opposite: turn it off)" },
    { id: "9_2_121", eng: "(to) light, lit, lit", phon: "[laɪt], [lɪt]", ger: "anzünden", ctx: "light up = aufleuchten; light a fire = ein Feuer machen" },
    { id: "9_2_122", eng: "fraction", phon: "['frækʃn]", ger: "Bruch(zahl); Bruchteil", ctx: "Fractions like 1/2, 1/3, 1/4 or a fraction of what it costs." },
    { id: "9_2_123", eng: "sigh", phon: "[saɪ]", ger: "Seufzer", ctx: "verb: (to) sigh = seufzen" },
    { id: "9_2_124", eng: "schoolyard (AE)", phon: "['skuːljɑːd]", ger: "Schulhof", ctx: "British English alternative: (school) playground" },
    { id: "9_2_125", eng: "in the old days", phon: "[ɪn ðə 'əʊld deɪz]", ger: "früher", ctx: "In the old days there were no cars." },
    { id: "9_2_126", eng: "human", phon: "['hjuːmən]", ger: "menschlich; Mensch", ctx: "human rights = Menschenrechte" },
    { id: "9_2_127", eng: "(to) translate", phon: "[træns'leɪt]", ger: "übersetzen", ctx: "noun: translation [træns'leɪʃn]" },
    { id: "9_2_128", eng: "self-employed", phon: "[self ɪm'plɔɪd]", ger: "selbstständig, freiberuflich", ctx: "not employed by a company, but working for yourself" },
    { id: "9_2_129", eng: "graphic designer", phon: "['ɡræfɪk dɪˌzaɪnə]", ger: "Grafiker/in, Grafikdesigner/in", ctx: "Which graphic designer designed your brochures?" },
    { id: "9_2_130", eng: "(to) motivate", phon: "['məʊtɪveɪt]", ger: "motivieren", ctx: "noun: motivation [ˌməʊtɪ'veɪʃn]" },
    { id: "9_2_131", eng: "discussion", phon: "[dɪ'skʌʃn]", ger: "Diskussion", ctx: "verb: (to) discuss" },
    { id: "9_2_132", eng: "(to) get sb.'s attention", phon: "[ə'tenʃn]", ger: "js. Aufmerksamkeit erregen, gewinnen", ctx: "(to) keep sb.'s attention = js. Aufmerksamkeit aufrechterhalten" },
    { id: "9_2_133", eng: "audience", phon: "['ɔːdiəns]", ger: "Publikum; Zuschauer/innen, Zuhörer/innen", ctx: "At the end of the concert the audience stood up." },
    { id: "9_2_134", eng: "statistic", phon: "[stə'tɪstɪk]", ger: "statistische Tatsache, statistische Größe", ctx: "💡 plural: statistics = Statistik(en)" },
    { id: "9_2_135", eng: "unusual", phon: "[ʌn'juːʒuəl]", ger: "ungewöhnlich", ctx: "opposite: usual" },
    { id: "9_2_136", eng: "rhetorical question", phon: "[rɪˌtɒrɪkl 'kwestʃən]", ger: "rhetorische Frage", ctx: "a question to which no answer is expected" },
    { id: "9_2_137", eng: "(to) expect", phon: "[ɪk'spect]", ger: "erwarten", ctx: "I wouldn't have expected this result." },
    { id: "9_2_138", eng: "quote", phon: "[kwəʊt]", ger: "Zitat", ctx: "verb: (to) quote = zitieren" },
    { id: "9_2_139", eng: "pilot", phon: "['paɪlət]", ger: "Pilot/in", ctx: "💡 Achte auf die Betonung und Aussprache!" },
    { id: "9_2_140", eng: "(to) succeed", phon: "[sək'siːd]", ger: "Erfolg haben", ctx: "adjective: successful; (to) succeed in doing sth. = es schaffen, etwas zu tun" },
    { id: "9_2_141", eng: "anonymous", phon: "[ə'nɒnɪməs]", ger: "anonym", ctx: "💡 short form: anon. / Achte auf die Betonung auf der 2. Silbe!" },
    { id: "9_2_142", eng: "focus (on)", phon: "['fəʊkəs]", ger: "Mittelpunkt, Hauptpunkt, Schwerpunkt", ctx: "plural: focuses or foci; focus of attention = Zentrum der Aufmerksamkeit" },
    { id: "9_2_143", eng: "prop", phon: "[prɒp]", ger: "Requisite", ctx: "noun" },
    { id: "9_2_144", eng: "colleague", phon: "['kɒliːɡ]", ger: "Kollege/Kollegin", ctx: "💡 Achte auf die Betonung auf der 1. Silbe!" },
    { id: "9_2_145", eng: "sustainability", phon: "[səˌsteɪnə'bɪləti]", ger: "Nachhaltigkeit", ctx: "adjective: sustainable" }
];