const e9u3_data = [
    { id: "9_3_1", eng: "critical (of)", phon: "['krɪtɪkl]", ger: "kritisch (gegenüber)", ctx: "verb: (to) criticize; nouns: critic (Kritiker/in) / criticism (Kritik)" },
    { id: "9_3_2", eng: "(to) evaluate", phon: "[ɪ'væljueɪt]", ger: "beurteilten, bewerten, einschätzen", ctx: "noun: evaluation = Beurteilung" },
    { id: "9_3_3", eng: "device", phon: "[dɪ'vaɪs]", ger: "Gerät, Apparat", ctx: "A clock is a device that tells you the time." },
    { id: "9_3_4", eng: "irony", phon: "['aɪrəni]", ger: "Ironie", ctx: "💡 Betonung auf der 1. Silbe! adjective: ironic; adverb: ironically" },
    { id: "9_3_5", eng: "(to) address sth.", phon: "[ə'dres]", ger: "etwas angehen, sich mit etwas befassen; etwas zur Sprache bringen", ctx: "I really want to address this problem." },
    { id: "9_3_6", eng: "issue", phon: "['ɪʃuː]", ger: "Thema, Anliegen; Problem, (Streit-)Frage", ctx: "issue = 1. Thema/Problem; 2. Ausgabe (Dokument); 3. verb: ausgeben" },
    { id: "9_3_7", eng: "(to) log on/off", phon: "[lɒɡ 'ɒn], [lɒɡ 'ɒf]", ger: "(sich) ein-/ausloggen", ctx: "synonym: (to) log in(to)/out" },
    { id: "9_3_8", eng: "(to) exist", phon: "[ɪɡ'zɪst]", ger: "existieren", ctx: "noun: existence = Existenz" },
    { id: "9_3_9", eng: "detox", phon: "['diːtɒks]", ger: "Entzug(sprogramm)", ctx: "informal; short for detoxification" },
    { id: "9_3_10", eng: "(to) be tired of sth.", phon: "['taɪəd]", ger: "die Nase voll haben von etwas", ctx: "I'm really tired of your stupid excuses!" },
    { id: "9_3_11", eng: "version", phon: "['vɜːʃn]", ger: "Version", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "9_3_12", eng: "(to) get / be / feel fed up (with)", phon: "[fed 'ʌp]", ger: "genervt sein, die Nase voll haben (von)", ctx: "synonym: (to) be tired of sth." },
    { id: "9_3_13", eng: "(to) pop up", phon: "[pɒp 'ʌp]", ger: "aufpoppen (z. B. Computer-Fenster); (plötzlich) auftauchen", ctx: "Lots of ads pop up." },
    { id: "9_3_14", eng: "inappropriate", phon: "[ˌɪnə'prəʊpriət]", ger: "unangemessen, unpassend, ungeeignet", ctx: "opposite: appropriate = angemessen, passend" },
    { id: "9_3_15", eng: "(to) go to sleep", phon: "[ɡəʊ tuː sliːp]", ger: "einschlafen; schlafen gehen", ctx: "synonyms: (to) fall asleep; (to) go to bed" },
    { id: "9_3_16", eng: "(to) scroll (up/down)", phon: "[skrəʊl]", ger: "hoch-/runterscrollen", ctx: "Please scroll down to the bottom." },
    { id: "9_3_17", eng: "way more interesting", phon: "[weɪ]", ger: "viel interessanter, weit(aus) interessanter", ctx: "informal (e.g., way cooler)" },
    { id: "9_3_18", eng: "(to) lose touch (with sb./sth.)", phon: "[luːz tʌtʃ]", ger: "den Kontakt (zu jm./etwas) verlieren", ctx: "opposite: get/keep/stay in touch" },
    { id: "9_3_19", eng: "(to) go on", phon: "[ɡəʊ 'ɒn]", ger: "geschehen, vor sich gehen", ctx: "I didn't know what was going on." },
    { id: "9_3_20", eng: "membership", phon: "['membəʃɪp]", ger: "Mitgliedschaft", ctx: "when you're a member (e.g. of a club)" },
    { id: "9_3_21", eng: "(to) build up, built, built", phon: "[bɪld 'ʌp], [bɪlt]", ger: "(sich) aufbauen", ctx: "A storm built up. / My grandpa built up this company." },
    { id: "9_3_22", eng: "following", phon: "['fɒləʊɪŋ]", ger: "Anhängerschaft", ctx: "meaning: all the supporters / people who follow sb." },
    { id: "9_3_23", eng: "(to) hack", phon: "[hæk]", ger: "hacken", ctx: "(to) hack into a system / a computer" },
    { id: "9_3_24", eng: "sort (of)", phon: "[sɔːt]", ger: "Art (von)", ctx: "synonyms: kind (of); type (of); all sorts of things = lauter Dinge" },
    { id: "9_3_25", eng: "jealous (of)", phon: "['dʒeləs]", ger: "neidisch (auf); eifersüchtig", ctx: "She was jealous of her baby brother." },
    { id: "9_3_26", eng: "(to) shut, shut, shut", phon: "[ʃʌt]", ger: "schließen, verschließen", ctx: "(to) shut sth. down = etwas schließen, stilllegen" },
    { id: "9_3_27", eng: "(to) speak out", phon: "[spiːk 'aʊt]", ger: "sich äußern, seine Meinung äußern", ctx: "You can't change things if you don't speak out." },
    { id: "9_3_28", eng: "despite", phon: "[dɪ'spaɪt]", ger: "trotz", ctx: "despite the dangers = although/though it is dangerous" },
    { id: "9_3_29", eng: "(to) keep up with", phon: "[kiːp 'ʌp wɪð]", ger: "sich auf dem Laufenden halten über; Schritt halten mit", ctx: "He's too fast for me, I can't keep up with him." },
    { id: "9_3_30", eng: "It's me that tells her ...", phon: "[miː]", ger: "und (ausgerechnet/nur) ich sage ihr ...", ctx: "me betont (e.g., It's always me that helps Jim.)" },
    { id: "9_3_31", eng: "(to) sign in", phon: "[saɪn 'ɪn]", ger: "sich anmelden, sich eintragen", ctx: "opposite: (to) sign out = sich abmelden" },
    { id: "9_3_32", eng: "(to) sign out", phon: "[saɪn 'aʊt]", ger: "sich abmelden, sich austragen", ctx: "opposite: (to) sign in" },
    { id: "9_3_33", eng: "status", phon: "['steɪtəs]", ger: "Status", ctx: "e.g., relationship status on social media" },
    { id: "9_3_34", eng: "(to) influence", phon: "['ɪnfluəns]", ger: "beeinflussen", ctx: "noun: influence = Einfluss; person: influencer" },
    { id: "9_3_35", eng: "(to) promote", phon: "[prə'məʊt]", ger: "Werbung machen für; fördern, unterstützen; befördern", ctx: "promoted in online ads / promote interest / promoted to CEO" },
    { id: "9_3_36", eng: "(to) whisper", phon: "['wɪspə]", ger: "flüstern", ctx: "noun: whisper = ((das) Flüstern, Geflüster)" },
    { id: "9_3_37", eng: "whether", phon: "['weðə]", ger: "ob", ctx: "synonym: if (I don't know whether this is correct.)" },
    { id: "9_3_38", eng: "password", phon: "['pɑːswɜːd]", ger: "Passwort", ctx: "To sign in, please enter your password." },
    { id: "9_3_39", eng: "request", phon: "[rɪ'kwest]", ger: "Wunsch, Bitte; Anfrage", ctx: "noun or verb" },
    { id: "9_3_40", eng: "order", phon: "['ɔːdə]", ger: "Befehl; Bestellung", ctx: "💡 order = 1. Befehl; 2. Bestellung; verb: bestellen / befehlen" },
    { id: "9_3_41", eng: "(to) advise", phon: "[ə'vaɪz]", ger: "empfehlen; (be)raten; informieren", ctx: "noun: advice = Rat, Ratschlag" },
    { id: "9_3_42", eng: "sensible", phon: "['sensəbl]", ger: "vernünftig; praktisch, zweckmäßig", ctx: "sensible shoes / noun: sense = Sinn, Vernunft (NOT sensitive!)" },
    { id: "9_3_43", eng: "electronic", phon: "[ɪlek'trɒnɪk]", ger: "elektronisch", ctx: "adverb: electronically; noun: electronics" },
    { id: "9_3_44", eng: "(to) set sth. (to)", phon: "[set]", ger: "etwas einstellen (auf)", ctx: "set it to 'quiet'" },
    { id: "9_3_45", eng: "airplane", phon: "['eəpleɪn]", ger: "Flugzeug", ctx: "synonym: plane" },
    { id: "9_3_46", eng: "mode", phon: "[məʊd]", ger: "Modus; Art", ctx: "standby mode / mode of communication" },
    { id: "9_3_47", eng: "take-off", phon: "['teɪk ɒf]", ger: "Start (Flugzeug)", ctx: "opposite: landing" },
    { id: "9_3_48", eng: "20% off", phon: "[ɒf]", ger: "20% Preisnachlass", ctx: "Only today! 50% off all T-shirts! = zum halben Preis" },
    { id: "9_3_49", eng: "electronics", phon: "[ɪlek'trɒnɪks]", ger: "Elektronik; elektronische Geräte", ctx: "plural noun" },
    { id: "9_3_50", eng: "department", phon: "[dɪ'pɑːtmənt]", ger: "Abteilung", ctx: "A department store is a huge shop with many departments." },
    { id: "9_3_51", eng: "sale", phon: "[seɪl]", ger: "Verkauf; Schlussverkauf", ctx: "for sale = zu verkaufen" },
    { id: "9_3_52", eng: "coach", phon: "[kəʊtʃ]", ger: "(Eisenbahn-)Wagen; Reisebus; Trainer/in", ctx: "💡 coach = 1. Wagen; 2. Reisebus; 3. Trainer/in" },
    { id: "9_3_53", eng: "context", phon: "['kɒntekst]", ger: "Zusammenhang", ctx: "Show me the word in context." },
    { id: "9_3_54", eng: "(to) harness", phon: "['hɑːnɪs]", ger: "nutzen, nutzbar machen", ctx: "We can harness water, wind or sunlight." },
    { id: "9_3_55", eng: "official", phon: "[ə'fɪʃl]", ger: "offiziell", ctx: "official language = Amtssprache" },
    { id: "9_3_56", eng: "(to) be based on", phon: "[beɪst ɒn]", ger: "basieren auf, beruhen auf, sich stützen auf", ctx: "Is this statement based on facts?" },
    { id: "9_3_57", eng: "annual", phon: "['ænjuəl]", ger: "jährlich", ctx: "an annual fee = Gebühr, die man einmal im Jahr zahlt" },
    { id: "9_3_58", eng: "windmill", phon: "['wɪndmɪl]", ger: "Windmühle, Windrad", ctx: "mill = Mühle" },
    { id: "9_3_59", eng: "(to) pump", phon: "[pʌmp]", ger: "pumpen", ctx: "noun: pump = Pumpe" },
    { id: "9_3_60", eng: "scrapyard", phon: "['skræpjɑːd]", ger: "Schrottplatz", ctx: "noun" },
    { id: "9_3_61", eng: "bicycle", phon: "['baɪsɪkl]", ger: "Fahrrad", ctx: "synonym: bike" },
    { id: "9_3_62", eng: "clothes line", phon: "['kləʊðz laɪn]", ger: "Wäscheleine", ctx: "We hang washed clothes on the clothes line." },
    { id: "9_3_63", eng: "handle", phon: "['hændl]", ger: "Griff, Handgriff", ctx: "e.g., a door handle" },
    { id: "9_3_64", eng: "rung", phon: "[rʌŋ]", ger: "Sprosse (einer Leiter)", ctx: "noun" },
    { id: "9_3_65", eng: "ladder", phon: "['lædə]", ger: "(die) Leiter", ctx: "noun" },
    { id: "9_3_66", eng: "(to) guide", phon: "[ɡaɪd]", ger: "führen, leiten", ctx: "nouns: guide = 1. Reiseleiter/in; 2. Reiseführer (Buch)" },
    { id: "9_3_67", eng: "(to) reply (to)", phon: "[rɪ'plaɪ]", ger: "antworten (auf)", ctx: "synonym: (to) answer; noun: reply = Antwort" },
    { id: "9_3_68", eng: "(to) swing, swung, swung", phon: "[swɪŋ], [swʌŋ]", ger: "schwingen", ctx: "The plane swung from side to side." },
    { id: "9_3_69", eng: "blade", phon: "[bleɪd]", ger: "(Rotor-)Blatt, (Turbinen-)Schaufel", ctx: "Small planes have engines with blades." },
    { id: "9_3_70", eng: "close (to)", phon: "[kləʊs]", ger: "nahe (bei, an)", ctx: "💡 Aussprache: (to) close (Verb: schließen) [kləʊz] vs. close (Adjektiv: nahe) [kləʊs]!" },
    { id: "9_3_71", eng: "(to) secure sth.", phon: "[sɪ'kjʊə]", ger: "(sich) etwas sichern; sicherstellen", ctx: "adjective: secure = sicher, gesichert" },
    { id: "9_3_72", eng: "in place", phon: "[ɪn pleɪs]", ger: "an Ort und Stelle", ctx: "put a stone on top to keep it in place" },
    { id: "9_3_73", eng: "wooden", phon: "['wʊdn]", ger: "Holz-, hölzern", ctx: "meaning: made of wood" },
    { id: "9_3_74", eng: "(to) tighten", phon: "['taɪtn]", ger: "anziehen (z. B. Schraube), straff ziehen; verschärfen", ctx: "meaning: to make tighter; adjective: tight" },
    { id: "9_3_75", eng: "within", phon: "[wɪ'ðɪn]", ger: "innerhalb (von), in", ctx: "within two weeks / within walking distance = fußläufig erreichbar" },
    { id: "9_3_76", eng: "dozen (pl. dozen)", phon: "['dʌzn]", ger: "Dutzend", ctx: "💡 two dozen eggs (zwei Dutzend) vs. dozens of people (dutzende Leute)" },
    { id: "9_3_77", eng: "base", phon: "[beɪs]", ger: "Basis; Sockel, Fuß; Boden (Kuchen, Pizza)", ctx: "the bottom part of a lamp, ladder, cake" },
    { id: "9_3_78", eng: "electric", phon: "[ɪ'lektrɪk]", ger: "elektrisch, Elektro-", ctx: "I play the electric guitar." },
    { id: "9_3_79", eng: "impossible", phon: "[ɪm'pɒsəbl]", ger: "unmöglich", ctx: "opposite: possible" },
    { id: "9_3_80", eng: "stand back (from)", phon: "[stænd bæk]", ger: "zurücktreten (von) (Schritte nach hinten machen)", ctx: "Please stand back from the platform edge." },
    { id: "9_3_81", eng: "copper", phon: "['kɒpə]", ger: "Kupfer", ctx: "a pot made of copper" },
    { id: "9_3_82", eng: "socket", phon: "['sɒkɪt]", ger: "Steckdose, Anschluss(dose)", ctx: "a British power socket" },
    { id: "9_3_83", eng: "wide", phon: "[waɪd]", ger: "breit, weit; weit geöffnet (Augen)", ctx: "The river is too wide. / Her eyes were wide." },
    { id: "9_3_84", eng: "second", phon: "['sekənd]", ger: "Sekunde", ctx: "There are 60 seconds in a minute." },
    { id: "9_3_85", eng: "just as many children", phon: "[dʒʌst]", ger: "genauso viele Kinder", ctx: "You look just like your father. (genau wie...)" },
    { id: "9_3_86", eng: "(to) beg", phon: "[beɡ]", ger: "flehen, (eindringlich) bitten; betteln", ctx: "(to) beg sb. to do sth. = jn. anflehen / (to) beg for sth. = um etwas betteln" },
    { id: "9_3_87", eng: "(to) free", phon: "[friː]", ger: "befreien", ctx: "adjective: free; noun: freedom" },
    { id: "9_3_88", eng: "miracle", phon: "['mɪrəkl]", ger: "Wunder", ctx: "It's a miracle that nobody was seriously hurt." },
    { id: "9_3_89", eng: "(to) flicker", phon: "['flɪkə]", ger: "flackern, flimmern", ctx: "These lamps always flicker at first." },
    { id: "9_3_90", eng: "(to) burst, burst, burst", phon: "[bɜːst]", ger: "brechen, bersten, platzen", ctx: "The kids were frightened when the balloon burst." },
    { id: "9_3_91", eng: "dizzy", phon: "['dɪzi]", ger: "schwindelig", ctx: "I feel dizzy. = Mir ist schwindelig." },
    { id: "9_3_92", eng: "disbelief", phon: "[ˌdɪsbɪ'liːf]", ger: "Unglaube(n), Ungläubigkeit", ctx: "opposite: belief (Glaube) / verbs: (to) not believe vs. (to) believe" },
    { id: "9_3_93", eng: "(to) clap (your hands)", phon: "[klæp]", ger: "(in die Hände) klatschen", ctx: "At the end everyone clapped." },
    { id: "9_3_94", eng: "(to) doubt", phon: "[daʊt]", ger: "(be)zweifeln", ctx: "noun: doubt = Zweifel; No doubt = zweifellos (The 'b' is silent!)" },
    { id: "9_3_95", eng: "(to) go bigger", phon: "[ɡəʊ]", ger: "größer werden", ctx: "After a while their business went bigger. (= grew bigger)" },
    { id: "9_3_96", eng: "(to) turn (sth.) on/off", phon: "[tɜːn]", ger: "(etwas) ein-/ausschalten; sich ein-/ausschalten", ctx: "synonym: (to) switch (sth.) on/off" },
    { id: "9_3_97", eng: "(to) stream", phon: "[striːm]", ger: "streamen", ctx: "streaming service = Streamingdienst" },
    { id: "9_3_98", eng: "stereo", phon: "['steriəʊ]", ger: "Stereo-; Stereoanlage", ctx: "noun: a stereo" },
    { id: "9_3_99", eng: "(to) press", phon: "[pres]", ger: "drücken", ctx: "pressing a button" },
    { id: "9_3_100", eng: "button", phon: "['bʌtn]", ger: "Button; Schaltfläche; Knopf", ctx: "noun" },
    { id: "9_3_101", eng: "warranty", phon: "['wɒrənti]", ger: "Garantie, Gewährleistung", ctx: "The device has a one-year warranty." },
    { id: "9_3_102", eng: "(to) affect", phon: "[ə'fekt]", ger: "beeinflussen, betreffen, sich auswirken auf", ctx: "Climate change will affect all of us. / (to) be affected by = von etwas betroffen sein" },
    { id: "9_3_103", eng: "(to) consume", phon: "[kən'sjuːm]", ger: "verbrauchen, konsumieren", ctx: "noun: consumer = Konsument/in, Verbraucher/in" },
    { id: "9_3_104", eng: "(to) unplug sth.", phon: "[ʌn'plʌɡ]", ger: "den Stecker von etwas herausziehen, etwas ausstöpseln", ctx: "opposite: (to) plug sth. in" },
    { id: "9_3_105", eng: "(to) reset, reset, reset", phon: "[ˌriː'set]", ger: "zurücksetzen; resetten", ctx: "I'll delete all my data and reset my laptop." },
    { id: "9_3_106", eng: "(to) aim to do sth.", phon: "[eɪm]", ger: "bestrebt sein etwas zu tun, etwas tun wollen", ctx: "We aim to reply to all emails within 24 hours." },
    { id: "9_3_107", eng: "target", phon: "['tɑːɡɪt]", ger: "Ziel", ctx: "target group / target audience = Zielgruppe, Zielpublikum" },
    { id: "9_3_108", eng: "lemon", phon: "['lemən]", ger: "Zitrone", ctx: "noun" },
    { id: "9_3_109", eng: "(to) suggest", phon: "[sə'dʒest]", ger: "suggerieren; vorschlagen", ctx: "💡 (to) suggest = 1. vorschlagen; 2. suggerieren" },
    { id: "9_3_110", eng: "(to) appeal to sb.", phon: "[ə'piːl]", ger: "für jn. attraktiv sein, jn. ansprechen", ctx: "appealing = ansprechend; noun: appeal = Anziehungskraft, Reiz" },
    { id: "9_3_111", eng: "sb./sth. lacks sth.", phon: "[læks]", ger: "jm./einer Sache fehlt/mangelt es an etwas", ctx: "verb: (to) lack; noun: lack = Mangel; for lack of... = aus Mangel an..." },
    { id: "9_3_112", eng: "eye-catching", phon: "['aɪ ˌkætʃɪŋ]", ger: "auffallend, ins Auge springend", ctx: "I love clothes in bright, eye-catching colours." },
    { id: "9_3_113", eng: "concern", phon: "[kən'sɜːn]", ger: "Befürchtung, Bedenken, Sorge; Angelegenheit, Sache", ctx: "💡 noun: 1. Sorge; 2. Angelegenheit (none of your concern) / verb: beunruhigen" },
    { id: "9_3_114", eng: "luxury", phon: "['lʌkʃəri]", ger: "Luxus", ctx: "adjective: luxurious [lʌɡ'ʒʊəriəs] = luxuriös" },
    { id: "9_3_115", eng: "whereas", phon: "[weər'æz]", ger: "während, wohingegen", ctx: "Sam loves meat, whereas I'm a vegetarian." },
    { id: "9_3_116", eng: "ingredient", phon: "[ɪn'ɡriːdiənt]", ger: "Bestandteil, Inhaltsstoff; Zutat", ctx: "Look at the cake recipe and make sure you have all the ingredients." },
    { id: "9_3_117", eng: "basic", phon: "['beɪsɪk]", ger: "einfach, elementar", ctx: "adverb: basically = im Prinzip; noun: the basics = die Grundlagen" },
    { id: "9_3_118", eng: "Why pay ...?", phon: "[waɪ peɪ]", ger: "Warum sollte man ... bezahlen?", ctx: "Why pay more than necessary? / Why not buy from us?" },
    { id: "9_3_119", eng: "this good / that bad", phon: "[ðɪs ɡʊd]", ger: "so gut / so schlecht", ctx: "meaning: so good/bad; as good/bad as this/that" },
    { id: "9_3_120", eng: "firm", phon: "[fɜːm]", ger: "Firma", ctx: "synonym: company" },
    { id: "9_3_121", eng: "knowledge (of/about)", phon: "['nɒlɪdʒ]", ger: "Wissen (von/über), Kenntnis(se) (von/in)", ctx: "knowledge of art / knowledge of geography / verb: (to) know" },
    { id: "9_3_122", eng: "(to) analyze", phon: "['ænəlaɪz]", ger: "analysieren, untersuchen", ctx: "noun: analysis [ə'næləsɪs], plural: analyses [ə'næləsiːz]" }
];