const e9u4_data = [
    { id: "9_4_1", eng: "image", phon: "['ɪmɪdʒ]", ger: "Bild, Abbildung", ctx: "meaning: a picture or a photo" },
    { id: "9_4_2", eng: "contrast", phon: "['kɒntrɑːst]", ger: "Kontrast, Gegensatz", ctx: "💡 Noun: ['kɒntrɑːst] – Verb: (to) contrast [kən'trɑːst] (vergleichen, gegenüberstellen)" },
    { id: "9_4_3", eng: "currency", phon: "['kʌrənsi]", ger: "Währung", ctx: "Until 2001, the currency used in Germany was the Deutsche Mark." },
    { id: "9_4_4", eng: "Hinduism", phon: "['hɪnduːɪzəm]", ger: "Hinduismus", ctx: "💡 Person: Hindu (Hindu); language: Hindi (Hindi)" },
    { id: "9_4_5", eng: "cow", phon: "[kaʊ]", ger: "Kuh", ctx: "noun" },
    { id: "9_4_6", eng: "rule", phon: "[ruːl]", ger: "Herrschaft", ctx: "person: ruler = Herrscher/in; verb: (to) rule = herrschen (über)" },
    { id: "9_4_7", eng: "equality", phon: "[i'kwɒləti]", ger: "Gleichberechtigung, Gleichheit", ctx: "opposite: inequality; adjective: equal vs. unequal" },
    { id: "9_4_8", eng: "region", phon: "['riːdʒən]", ger: "Region", ctx: "💡 Betonung auf der 1. Silbe! adjective: regional" },
    { id: "9_4_9", eng: "middle class", phon: "[mɪdl 'klɑːs]", ger: "Mittelstand, Mittelschicht", ctx: "a middle-class family" },
    { id: "9_4_10", eng: "literacy", phon: "['lɪtərəsi]", ger: "Fähigkeit, lesen und schreiben zu können", ctx: "opposite: illiteracy; adjective: literate vs. illiterate" },
    { id: "9_4_11", eng: "caste", phon: "[kɑːst]", ger: "Kaste, Gesellschaftsklasse", ctx: "each of the traditional social classes in India" },
    { id: "9_4_12", eng: "warrior", phon: "['wɒriə]", ger: "Krieger/in", ctx: "someone who fights in a war" },
    { id: "9_4_13", eng: "labour", phon: "['leɪbə]", ger: "Arbeit, Arbeitskräfte", ctx: "labourer = Arbeiter/in; child labour = Kinderarbeit" },
    { id: "9_4_14", eng: "servant", phon: "['sɜːvənt]", ger: "Diener/in; Bedienstete/r", ctx: "someone who works in a richer person's house; verb: (to) serve" },
    { id: "9_4_15", eng: "(to) sweep, swept, swept", phon: "[swiːp], [swept]", ger: "fegen, kehren", ctx: "street sweeper = Straßenfeger/in; sweeping the floor" },
    { id: "9_4_16", eng: "sewer", phon: "['suːə]", ger: "Abwasserkanal", ctx: "💡 plural: sewers = Kanalisation(ssystem)" },
    { id: "9_4_17", eng: "constitution", phon: "[ˌkɒnstɪ'tjuːʃn]", ger: "Verfassung", ctx: "adjective: constitutional = verfassungsgemäß" },
    { id: "9_4_18", eng: "marriage", phon: "['mærɪdʒ]", ger: "Hochzeit, Ehe", ctx: "verb: (to) marry; phrase: to get married to / be married to sb." },
    { id: "9_4_19", eng: "waste", phon: "[weɪst]", ger: "Müll; Abfall; Fäkalien", ctx: "💡 animal/human waste = tierische/menschliche Fäkalien; also: Verschwendung / verschwenden" },
    { id: "9_4_20", eng: "(to) avoid", phon: "[ə'vɔɪd]", ger: "(ver)meiden; verhindern", ctx: "💡 structure: avoid + -ing (I'd like to avoid waiting for hours.)" },
    { id: "9_4_21", eng: "well", phon: "[wel]", ger: "Quelle, Brunnen", ctx: "Centuries ago people had to get water from wells." },
    { id: "9_4_22", eng: "quota", phon: "['kwəʊtə]", ger: "Quote", ctx: "e.g., female quotas" },
    { id: "9_4_23", eng: "salary", phon: "['sæləri]", ger: "Gehalt", ctx: "money that your employer pays you every month for doing your job" },
    { id: "9_4_24", eng: "pharmaceutical", phon: "[ˌfɑːmə'suːtɪkl]", ger: "Pharma-, pharmazeutisch", ctx: "💡 Das Substantiv steht meist im Plural: pharmaceuticals = Arzneimittel" },
    { id: "9_4_25", eng: "biotechnology", phon: "[ˌbaɪəʊtek'nɒlədʒi]", ger: "Biotechnologie", ctx: "product of biotechnology" },
    { id: "9_4_26", eng: "multinational", phon: "[ˌmʌlti'næʃnəl]", ger: "multinational", ctx: "noun: multinational = multinationaler Konzern, Multi" },
    { id: "9_4_27", eng: "positive discrimination", phon: "['pɒzətɪv dɪˌskrɪmɪ'neɪʃn]", ger: "positive Diskriminierung", ctx: "socio-political policy to treat disadvantaged groups more fairly" },
    { id: "9_4_28", eng: "among", phon: "[ə'mʌŋ]", ger: "unter, zwischen (mehreren Personen oder Dingen)", ctx: "💡 unter mehreren = among / zwischen genau zweien = between" },
    { id: "9_4_29", eng: "position", phon: "[pə'zɪʃn]", ger: "Position, Standort; Stellung; (Arbeits-)Stelle", ctx: "💡 Achte auf die Betonung auf der 2. Silbe!" },
    { id: "9_4_30", eng: "almost", phon: "['ɔːlməʊst]", ger: "fast, nahezu, beinahe", ctx: "synonym: nearly" },
    { id: "9_4_31", eng: "employee", phon: "[ɪm'plɔɪiː]", ger: "Arbeitnehmer/in", ctx: "employer = Arbeitgeber/in; employment vs. unemployment; self-employed" },
    { id: "9_4_32", eng: "majority", phon: "[mə'dʒɒrəti]", ger: "Mehrheit, Mehrzahl", ctx: "opposite: minority [maɪ'nɒrəti] = Minderheit" },
    { id: "9_4_33", eng: "ahead", phon: "[ə'hed]", ger: "voran; voraus", ctx: "accident ahead! / (to) get ahead = vorankommen, weiterkommen" },
    { id: "9_4_34", eng: "stall", phon: "[stɔːl]", ger: "(Markt-)Stand, Bude", ctx: "person: stallholder = Standinhaber/in" },
    { id: "9_4_35", eng: "sensitive", phon: "['sensətɪv]", ger: "einfühlsam, sensibel; heikel (z. B. Thema)", ctx: "💡 False Friend! sensitive = sensibel / sensible = vernünftig" },
    { id: "9_4_36", eng: "religious", phon: "[rɪ'lɪdʒəs]", ger: "religiös", ctx: "💡 Achte auf die Betonung auf der 2. Silbe!" },
    { id: "9_4_37", eng: "opportunity", phon: "[ˌɒpə'tjuːnəti]", ger: "Gelegenheit, Möglichkeit, Chance", ctx: "💡 Möglichkeit/Chance = opportunity / zeitlicher Anlass = occasion" },
    { id: "9_4_38", eng: "rate", phon: "[reɪt]", ger: "Rate, Quote, Anteil; Tarif, Preis", ctx: "unemployment rate = Arbeitslosenquote / group rate = Gruppenpreis" },
    { id: "9_4_39", eng: "blend", phon: "[blend]", ger: "Mischung", ctx: "verb: (to) blend ((sich) vermischen)" },
    { id: "9_4_40", eng: "role", phon: "[rəʊl]", ger: "Rolle (Film, Theater)", ctx: "The coach plays a key role." },
    { id: "9_4_41", eng: "romantic", phon: "[rəʊ'mæntɪk]", ger: "romantisch", ctx: "adverb: romantically [rəʊ'mæntɪkli]" },
    { id: "9_4_42", eng: "tax", phon: "[tæks]", ger: "(die) Steuer", ctx: "e.g., a high tax on alcohol" },
    { id: "9_4_43", eng: "wonderful", phon: "['wʌndəfl]", ger: "wunderbar", ctx: "synonyms: very good, great, amazing, awesome" },
    { id: "9_4_44", eng: "(to) have sth. done (by sb.)", phon: "[hæv ... dʌn]", ger: "etwas (von jm.) machen lassen (erledigen lassen)", ctx: "Causative structure: Did you cut your hair yourself or did you have it cut?" },
    { id: "9_4_45", eng: "It is said to be ...", phon: "[ɪz sed tuː biː]", ger: "Man sagt, es sei ...", ctx: "Passive report structures: She is said to be rich. / He is known to get up early." },
    { id: "9_4_46", eng: "sin", phon: "[sɪn]", ger: "Sünde", ctx: "In our religion this is a sin." },
    { id: "9_4_47", eng: "pilgrim", phon: "['pɪlɡrɪm]", ger: "Pilger/in", ctx: "somebody who travels to a holy place for religious reasons" },
    { id: "9_4_48", eng: "(to) bathe", phon: "[beɪð]", ger: "baden (in einem Fluss / dem Meer)", ctx: "💡 verb: bathe [beɪð] (im Fluss/Meer) vs. noun: bath [bɑːθ] (Zuhause in der Wanne)" },
    { id: "9_4_49", eng: "(to) pollute", phon: "[pə'luːt]", ger: "(die Umwelt) verschmutzen", ctx: "noun: pollution = Air pollution is a serious problem." },
    { id: "9_4_50", eng: "sewage", phon: "['suːɪdʒ]", ger: "Abwasser", ctx: "meaning: dirty water from the sewers" },
    { id: "9_4_51", eng: "(to) cremate", phon: "[krə'meɪt]", ger: "einäschern", ctx: "noun: cremation = Einäscherung" },
    { id: "9_4_52", eng: "So do I.", phon: "[səʊ duː aɪ]", ger: "Ich auch. / Das tue ich auch. / Das gilt auch für mich.", ctx: "Used to agree with a positive statement (I hate coffee. – So do I.)" },
    { id: "9_4_53", eng: "Neither do I.", phon: "['naɪðə], ['niːðə]", ger: "Ich auch nicht.", ctx: "Used to agree with a negative statement. Alternative: Nor do I. / I don't either." },
    { id: "9_4_54", eng: "by the way", phon: "[baɪ ðə weɪ]", ger: "übrigens", ctx: "Oh, by the way, Grandma called this morning." },
    { id: "9_4_55", eng: "This goes for ... (too).", phon: "[ɡəʊz fɔː]", ger: "Dies gilt (auch) für ...", ctx: "Please be quiet now! This goes for all of you!" },
    { id: "9_4_56", eng: "(to) interrupt", phon: "[ˌɪntə'rʌpt]", ger: "unterbrechen", ctx: "noun: interruption = Unterbrechung" },
    { id: "9_4_57", eng: "(to) force sb. to do sth.", phon: "[fɔːs]", ger: "jn. zwingen, etwas zu tun", ctx: "forced marriage = Zwangsheirat; noun: force = Zwang, Gewalt" },
    { id: "9_4_58", eng: "old-fashioned", phon: "[ˌəʊld'fæʃnd]", ger: "altmodisch", ctx: "opposite: modern" },
    { id: "9_4_59", eng: "(to) date sb.", phon: "[deɪt]", ger: "mit jm. gehen, eine Beziehung haben", ctx: "💡 date = 1. Datum; 2. Verabredung, Date; 3. verb: eine Beziehung haben" },
    { id: "9_4_60", eng: "(to) have sth. in common", phon: "[ɪn 'kɒmən]", ger: "etwas gemeinsam haben", ctx: "We're the same age, but we don't have much in common." },
    { id: "9_4_61", eng: "horoscope", phon: "['hɒrəskəʊp]", ger: "Horoskop", ctx: "💡 Achte auf die Betonung auf der 1. Silbe!" },
    { id: "9_4_62", eng: "(to) match (sth.)", phon: "[mætʃ]", ger: "zueinander passen; übereinstimmen mit; zusammenfügen", ctx: "These socks don't match. / noun: match = passendes Paar" },
    { id: "9_4_63", eng: "personality", phon: "[ˌpɜːsə'næləti]", ger: "Persönlichkeit; Charakter", ctx: "Ann has the perfect personality to be captain." },
    { id: "9_4_64", eng: "bride", phon: "[braɪd]", ger: "Braut", ctx: "noun" },
    { id: "9_4_65", eng: "groom", phon: "[ɡruːm]", ger: "Bräutigam", ctx: "noun" },
    { id: "9_4_66", eng: "divorce", phon: "[dɪ'vɔːs]", ger: "(Ehe-)Scheidung", ctx: "(to) get a divorce / to get divorced (from) / to divorce sb." },
    { id: "9_4_67", eng: "eventually", phon: "[ɪ'ventʃuəli]", ger: "letztendlich, schließlich", ctx: "💡 temporal: after a long time. In the end = am Ende; at last = endlich" },
    { id: "9_4_68", eng: "possibly", phon: "['pɒsəbli]", ger: "möglicherweise", ctx: "synonym: maybe" },
    { id: "9_4_69", eng: "logical", phon: "['lɒdʒɪkl]", ger: "logisch", ctx: "noun: logic = Logik" },
    { id: "9_4_70", eng: "(to) adopt", phon: "[ə'dɒpt]", ger: "adoptieren; (Tier) bei sich aufnehmen", ctx: "noun: adoption" },
    { id: "9_4_71", eng: "harsh", phon: "[hɑːʃ]", ger: "hart, rau; brutal, harsch", ctx: "Life is often harsh for servants. / a harsh winter" },
    { id: "9_4_72", eng: "reasonable", phon: "['riːznəbl]", ger: "vernünftig, angemessen", ctx: "adverb: reasonably (ziemlich/durchaus)" },
    { id: "9_4_73", eng: "railway", phon: "['reɪlwei]", ger: "Eisenbahn", ctx: "railway station = Bahnhof; railway line = Bahnstrecke" },
    { id: "9_4_74", eng: "(to) pass sb./sth.", phon: "[pɑːs]", ger: "an jm./etwas vorbeigehen, vorbeifahren; vergehen (Zeit)", ctx: "I pass 14 shops every morning. / Time passes so quickly." },
    { id: "9_4_75", eng: "tonight", phon: "[tə'naɪt]", ger: "heute Nacht, heute Abend", ctx: "We can sit in the garden tonight." },
    { id: "9_4_76", eng: "perhaps", phon: "[pə'hæps]", ger: "vielleicht", ctx: "synonyms: maybe, possibly" },
    { id: "9_4_77", eng: "thrilled", phon: "[θrɪld]", ger: "fasziniert, begeistert", ctx: "meaning: very excited" },
    { id: "9_4_78", eng: "(to) hire", phon: "['haɪə]", ger: "mieten, leihen; (Person:) einstellen", ctx: "noun: hire = Verleih, Vermietung" },
    { id: "9_4_79", eng: "bar", phon: "[bɑː]", ger: "Stange, Balken, Gitterstab; Riegel; Tafel (Schokolade)", ctx: "bicycle handlebars = Lenkstange; verb: (to) bar = absperren" },
    { id: "9_4_80", eng: "(to) rest", phon: "[rest]", ger: "ruhen; sich (auf)stützen; sich ausruhen", ctx: "Sit down and rest your feet. / noun: rest = Ruhe, Pause" },
    { id: "9_4_81", eng: "bumpy", phon: "['bʌmpi]", ger: "holprig, (Flug/Schifffahrt) unruhig", ctx: "bumpy country road / bumpy flight" },
    { id: "9_4_82", eng: "bush", phon: "[bʊʃ]", ger: "Busch", ctx: "💡 Aussprache beachten! plural: bushes" },
    { id: "9_4_83", eng: "by the time", phon: "[baɪ]", ger: "als; wenn", ctx: "By the time we arrived, the concert had already started." },
    { id: "9_4_84", eng: "sleepy", phon: "['sliːpi]", ger: "müde; verschlafen", ctx: "meaning: a bit tired; needing sleep" },
    { id: "9_4_85", eng: "exhausted", phon: "[ɪɡ'zɔːstɪd]", ger: "erschöpft", ctx: "meaning: very tired" },
    { id: "9_4_86", eng: "bench", phon: "[bentʃ]", ger: "Bank (zum Sitzen)", ctx: "💡 Sitzgelegenheit = bench / Geldinstitut = bank" },
    { id: "9_4_87", eng: "straightaway", phon: "[ˌstreɪtə'weɪ]", ger: "sofort", ctx: "synonym: immediately" },
    { id: "9_4_88", eng: "carriage", phon: "['kærɪdʒ]", ger: "(Eisenbahn-)Wagen", ctx: "an old train carriage" },
    { id: "9_4_89", eng: "(to) wonder", phon: "['wʌndə]", ger: "sich fragen", ctx: "💡 Kein Reflexivpronomen im Englischen! I wonder who she is. (Ich frage mich...)" },
    { id: "9_4_90", eng: "stairs (pl.)", phon: "[steəz]", ger: "Treppe; (Treppen-)Stufen", ctx: "💡 Plural-Verb-Anschluss im Englischen: Those stairs *are* dangerous." },
    { id: "9_4_91", eng: "case", phon: "[keɪs]", ger: "Fall", ctx: "In the case of fire... / just in case = für den Fall, dass... (nur für alle Fälle)" },
    { id: "9_4_92", eng: "conductor", phon: "[kən'dʌktə]", ger: "Schaffner/in, Zugbegleiter/in", ctx: "noun" },
    { id: "9_4_93", eng: "(to) shine, shone, shone", phon: "[ʃaɪn], [ʃɒn]", ger: "scheinen (Sonne); leuchten, strahlen", ctx: "The sun is shining." },
    { id: "9_4_94", eng: "panic", phon: "['pænɪk]", ger: "Panik", ctx: "verb: (to) panic (in Panik geraten); Don't panic!" },
    { id: "9_4_95", eng: "(to) curse", phon: "[kɜːs]", ger: "fluchen", ctx: "He cursed as he arrived. / noun: curse = Fluch" },
    { id: "9_4_96", eng: "keep (on) doing sth.", phon: "[kiːp]", ger: "etwas immer wieder / immer weiter tun; etwas ständig tun", ctx: "He kept interrupting me. / Keep on smiling!" },
    { id: "9_4_97", eng: "golden", phon: "['ɡəʊldən]", ger: "golden, aus Gold", ctx: "adjective; noun: gold" },
    { id: "9_4_98", eng: "triangle", phon: "['traɪæŋɡl]", ger: "Dreieck", ctx: "noun" },
    { id: "9_4_99", eng: "architecture", phon: "['ɑːkɪtektʃə]", ger: "Architektur", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "9_4_100", eng: "fabulous", phon: "['fæbjʊləs]", ger: "sagenhaft, fabelhaft", ctx: "synonyms: extremely good, fantastic, awesome" },
    { id: "9_4_101", eng: "landmark", phon: "['lændmɑːk]", ger: "Wahrzeichen", ctx: "The Eiffel Tower is a landmark of Paris." },
    { id: "9_4_102", eng: "palace", phon: "['pæləs]", ger: "Palast, Schloss", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "9_4_103", eng: "sunrise", phon: "['sʌnraɪz]", ger: "Sonnenaufgang", ctx: "opposite: sunset = Sonnenuntergang" },
    { id: "9_4_104", eng: "(to) impress", phon: "[ɪm'pres]", ger: "beeindrucken", ctx: "noun: impression" },
    { id: "9_4_105", eng: "decoration", phon: "[ˌdekə'reɪʃn]", ger: "Dekoration, Schmuck, Verzierung", ctx: "verb: (to) decorate" },
    { id: "9_4_106", eng: "neutral", phon: "['njuːtrəl]", ger: "neutral", ctx: "💡 Achte auf die englische Aussprache!" },
    { id: "9_4_107", eng: "reliable", phon: "[rɪ'laɪəbl]", ger: "verlässlich, zuverlässig", ctx: "She's a very reliable person." },
    { id: "9_4_108", eng: "plantation", phon: "[plæn'teɪʃn]", ger: "Plantage; Anpflanzung", ctx: "sugar plantation" },
    { id: "9_4_109", eng: "production", phon: "[prə'dʌkʃn]", ger: "Produktion", ctx: "💡 Betonung auf der 2. Silbe! verb: (to) produce; noun: product" },
    { id: "9_4_110", eng: "encyclopedia", phon: "[ɪnˌsaɪklə'piːdiə]", ger: "Enzyklopädie, Lexikon", ctx: "💡 Achte auf Betonung und Aussprache!" },
    { id: "9_4_111", eng: "item", phon: "['aɪtəm]", ger: "Artikel, Gegenstand, Punkt (auf einer Liste)", ctx: "news item = Nachrichtenmeldung" },
    { id: "9_4_112", eng: "medical", phon: "['medɪkl]", ger: "ärztlich, medizinisch; gesundheitlich", ctx: "💡 Betonung auf der 1. Silbe! medical insurance = Krankenversicherung" },
    { id: "9_4_113", eng: "decent", phon: "['diːsnt]", ger: "anständig, ordentlich, annehmbar", ctx: "meaning: good enough, satisfactory (e.g., decent pay)" },
    { id: "9_4_114", eng: "wage", phon: "[weɪdʒ]", ger: "Lohn", ctx: "💡 oft im Plural: wages. Regelmäßiger (oft wöchentlicher) Lohn für Arbeit / minimum wage = Mindestlohn" },
    { id: "9_4_115", eng: "benefit", phon: "['benɪfɪt]", ger: "Nutzen, Vorteil", ctx: "verb: (to) benefit from = profitieren von; It benefits you = Es nützt dir." },
    { id: "9_4_116", eng: "caffeine", phon: "['kæfiːn]", ger: "Koffein", ctx: "💡 Betonung auf der 1. Silbe!" },
    { id: "9_4_117", eng: "cancer", phon: "['kænsə]", ger: "Krebs (Erkrankung)", ctx: "He got cancer." },
    { id: "9_4_118", eng: "(to) claim", phon: "[kleɪm]", ger: "angeben, behaupten", ctx: "He claims he's 18. / noun: claim = Behauptung" },
    { id: "9_4_119", eng: "herbal", phon: "['hɜːbl]", ger: "Kräuter-", ctx: "herbal tea = Tee aus echten Kräutern (herbs)" },
    { id: "9_4_120", eng: "mint", phon: "[mɪnt]", ger: "(Pfeffer-)Minze", ctx: "mint leaves" },
    { id: "9_4_121", eng: "significant", phon: "[sɪɡ'nɪfɪkənt]", ger: "deutlich, spürbar, erheblich, signifikant", ctx: "opposite: insignificant = unbedeutend, geringfügig" },
    { id: "9_4_122", eng: "study", phon: "['stʌdi]", ger: "Untersuchung, Studie", ctx: "verb: (to) study = untersuchen; studieren, lernen" },
    { id: "9_4_123", eng: "recent", phon: "['riːsnt]", ger: "aktuell, jüngst", ctx: "recent history = jüngere Geschichte / in recent years = in den letzten Jahren" },
    { id: "9_4_124", eng: "strike", phon: "[straɪk]", ger: "Streik", ctx: "Workers went on strike. / verb: (to) strike, struck, struck = streiken; schlagen" },
    { id: "9_4_125", eng: "miserable", phon: "['mɪzrəbl]", ger: "erbärmlich, jämmerlich, trostlos", ctx: "I felt miserable. / What miserable weather! (= horrible)" },
    { id: "9_4_126", eng: "tourism", phon: "['tʊərɪzəm]", ger: "Tourismus", ctx: "💡 Betonung auf der 1. Silbe!" }
];